### PR TITLE
Detect typos in Markdown documents

### PR DESCRIPTION
**Pull request by electrocucaracha**
#### Problem
Typos and grammar errors are not easy to detect, specially when documentation is created with standard editors. This becomes harder for non-native English speakers.

Documentation changes trigger build CI actions which are not needed reducing the number of concurrent jobs available. 

#### Change overview
This change fixes some of the current existing typos in the markdown documents as well as provides a set of GitHub actions for reviewing new changes and/or additions in documents.

It also configures the GitHub workflows to avoid unnecessary executions.

#### Testing
The GitHub actions will only be triggered when changes on markdown are detected.

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]
There's a little more change in here than described, but I like it. Thank you!

**Review by saurabhst — APPROVED** [review]

**Review by jmeg-sfy — APPROVED** [review]
Can we use this is in the spec ?

**Review by msandstedt — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Review by mspang — APPROVED** [review]

**Comment by andy31415** [comment]
Restyler fails because of changes to .github folder. Will force-push this one.

**Comment by andy31415** [comment]
#9340 reverts this merge - it seems this completely disabled CI.

I would suggest to merge the markdown fixes separately from the github workflow changes, to have smaller deltas and debugging.

**Pull request merged**
