### PR TITLE
[InetLayer] handle source address for transport layer

### PR DESCRIPTION
**Pull request by kghost**
#### Problem
#11120 

This is the first step to solve referred issue, after this PR, we need another PR to put source address into the session matching tuple.

#### Change overview
[InetLayer] handle source address for transport layer
* When `SendMessage` take an extra argument of local address, send via this local address
* When `OnMessageReceived`, pass an extra argument of local address to the delegate object (the `SessionManager`)

#### Testing
WIP

### CODE REVIEW

**Comment by bzbarsky-apple** [comment]
I thought we had decided to handle this via including some sort of identifiers in unencrypted messages so we don't have to rely on the ip/interface bits?  Or do I misunderstand the point of this PR?

@tcarmelveilleux

**Comment by kghost** [comment]
@bzbarsky-apple  Even we decide to use other identifiers to solve this problem, we still prefer avoiding asymmetric path.

Because asymmetric path can cause lots of problems, like:
* unicast flood
* firewall deny
* NAT block

So this PR is needed for better network adaptability.

**Comment by bzbarsky-apple** [comment]
Is there a description somewhere of the exact behavior that you are proposing implementing?

@msandstedt

**Comment by msandstedt** [comment]
> Is there a description somewhere of the exact behavior that you are proposing implementing?
> 
> @msandstedt

All captured here: https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/4674

**Comment by msandstedt** [comment]
This is essentially the 'individually bind to all addresses', 'locate and use previously bound address:port for outbound reply'.

That is the portable solution.  However, it's difficult to achieve.  For this to work, you would need to bind to all addresses on the given interface.  But there might be many, and they might change.  I don't think our stack is going to be easily adapted to this.

**Comment by msandstedt** [comment]
> @bzbarsky-apple Even we decide to use other identifiers to solve this problem, we still prefer avoiding asymmetric path.
> 
> Because asymmetric path can cause lots of problems, like:
> 
>     * unicast flood
>     * firewall deny
>     * NAT block
> 
> 
> So this PR is needed for better network adaptability.

@kghost ,

I don't personally have a lot of expertise to evaluate the seriousness of these problems.  But maybe we can discuss them in turn.

>     * unicast flood

How do we experience this problem here?  The difficulty we are facing in the sdk is that the source address may be new / unknown.  I assumed a unicast flood would only be related to unknown destination addresses.

>     * firewall deny

I can see this being a problem.  What is the usual configuration?  Are rules usually dynamically created mapping the full <protocol, src IP, src port, dst IP, dst port> quintuple, or just opening the outbound source IP and port for replies from anywhere?

>     * NAT block

The difficulty in sending from the correct source address is most pronounced with IPv6, where there will almost always be multiple IPv6 addresses for a given adapter.  So then to NAT: this problem of sending from the correct source address is more easily solvable for IPv4, so we could fix it for IPv4.  Or we could decide that we don't care about IPv4 NAT.  As to NAT64 and NAT66, I think we might just say we don't care about 64.  And many have concluded that NAT66 is a fundamentally crappy idea; we might also not care about this.

Thoughts?

**Comment by kghost** [comment]
> unicast flood

It also caused by L2 mac learning (NOT arp learning). When you always respond packets via another route, the L2 bridge may forget your mac entry (most switches have a default timer of 300 seconds), so every packet send to you are flooded over the L2 domain.

firewall deny and NAT block is self-explained.

Never underestimate the complexity of a user's home network. It is pretty common that a user's device in his home network go through several NAT devices until it reaches his carrier network.

I'd like to make our design adapt to the most common usage, rather than introduce any dependency to specific network configuration and get lost into debugging the user's network environment.

**Comment by msandstedt** [comment]
> It is caused by L2 mac learning (NOT arp learning). When you always respond packets via another interface, the L2 bridge may forget your mac entry (most switches have a default timer of 300 seconds), so every packet send to you are flooded over the L2 domain.

I see.  Understood.

> firewall deny and NAT block is self-explained.

Fair enough.  Yes, if we want Matter to easily and reliably cross all NATs and firewalls, we should make sure the full <protocol, src IP, src port, dst IP, dst port> quintuple is simply src/dst reversed for responses to given requests.

If this is doable, we obviously should.

**Comment by msandstedt** [comment]
Actually, we have gone off the rails here.

This problem only surfaced for unauthenticated session matching when using UDP, and we have no plans that I'm aware of to mandate a source IP/ port rule for secure channel communication.  Thus, ensuring a particular source IP/port here doesn't "fix matter" for the named cases.  These purported problems (unicast flood, firewalls, NAT) would still entirely exist.

I question whether my own NAT+firewall actually operates in a way that would require this (some particular source IP/port for inbound traffic when rules are opened by outbound traffic).  I don't know what additional security this would confer.  I'm curious enough to do some manual hole-punching and see.

However, that doesn't matter.  We need to fix this in the spec with the originally discussed plan, which does not rely upon source IP/port in incoming packets to identify peers in unauthenticated sessions.  The only rubric we need to know this is the right thing to do is that this is how all other Matter UDP communication works.

**Pull request closed without merging**
