### PR TITLE
[cluster] Add TestUnknownCommand command to test cluster[TE3]

### PR DESCRIPTION
**Pull request by erjiaqing**
#### Problem
* We need a suitable case for test device behavior of unsupported command on a supported cluster.

#### Change overview
* Add TestUnknownCommand, this command should not be added / implemented by server.

#### Testing
- Tested locally with chip-device-ctrl with all-cluster-apps
- `zcl TestCluster TestUnknownCommand 1 1 0`
- Verify device controller output and server output.
  - Server prints `CHIP:ZCL: Unknown command 3 for cluster 50f  `
  - Controller prints 
  ```
  CHIP:DMG:               CommandDataElement =
  CHIP:DMG:               {
  CHIP:DMG:                       CommandPath =
  CHIP:DMG:                       {
  CHIP:DMG:                               EndpointId = 0x1,
  CHIP:DMG:                               ClusterId = 0x50f,
  CHIP:DMG:                               CommandId = 0x3,
  CHIP:DMG:                       },
  CHIP:DMG: 
  CHIP:DMG:                       StatusElement =
  CHIP:DMG:                       {
  CHIP:DMG:                               GeneralCode = 0xd,
  CHIP:DMG:                               ProtocolId = 0x0,
  CHIP:DMG:                               protocolCode = 0xffff,
  CHIP:DMG:                       },
  CHIP:DMG: 
  CHIP:DMG:               },
  ```

### CODE REVIEW

**Review by msandstedt — APPROVED** [review]

**Review by yunhanw-google — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]
Is there CI exercising this?  If not, can we add some, so we don't have to do manual testing?

**Comment by yunhanw-google** [comment]
> Is there CI exercising this? If not, can we add some, so we don't have to do manual testing?

Create this https://github.com/project-chip/connectedhomeip/issues/7293 for tracking

**Comment by woody-apple** [comment]
@andy31415 @Damian-Nordic @LuDuda ?

**Review by jmartinez-silabs — APPROVED** [review]

**Pull request merged**
