### PR TITLE
[Android] Clean up both success and failure cluster callbacks

### PR DESCRIPTION
**Pull request by austinh0**
#### Problem
* In Android cluster code, only the success or the failure callback will be cleaned up after the command/read/etc returns, not both.

#### Change overview
* Similar to #8889
* Create `CHIPCallbackWrapper.h` base class which wraps success and failure callbacks, takes in a `CHIPActionBlock` for the command to execute, and also handles creating/cleaning up a global reference to the Java callback object.
* In ZAP template, make all callbacks extend `CHIPCallbackWrapper`. `CHIPDefaultFailureCallback` is no longer needed.
  * For each JNI method, create a lambda for the read/write/etc (`CHIPActionBlock`), and pass that to the callback.
* Refactor exception creating/return code into `AndroidClusterExceptions.cpp` for code reuse.
* While I'm here, remove remaining `VerifyOrExit` pattern in generated JNI code.

#### Testing
* Manual test command, read, write, subscribe, and report, with both DefaultSuccessCallback and custom callback types.
* Verified CHIPCallbackWrapper is deleted with some logs

### CODE REVIEW

**Comment by austinh0** [comment]
@andy31415 @bzbarsky-apple @chrisdecenzo @Damian-Nordic @jelderton @jmartinez-silabs @saurabhst ?

**Review by bzbarsky-apple — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
@austinh0 - conflicts.

**Review by woody-apple — APPROVED** [review]

**Review by msandstedt — APPROVED** [review]

**Review by chulspro — APPROVED** [review]
Great ~ Looks good to me.

**Review by jmeg-sfy — APPROVED** [review]
@austinh0 conflicts!

**Comment by austinh0** [comment]
I need to put up a separate PR splitting up the clusters code before this will pass the CI (currently running into compiler OOM), so not updating this until then.

**Review by mrjerryjohns — APPROVED** [review]

**Comment by andy31415** [comment]
@austinh0 any updates on this one? has been open for a very long time and  stalebot complains.

**Comment by austinh0** [comment]
Sorry, no bandwidth at the moment...and the CI was still OOM'ing even after splitting the reads out, so probably even more refactoring required here.

**Comment by woody-apple** [comment]
@austinh0 ?

**Pull request closed without merging**
