### PR TITLE
Add GitHub workflow to verify Mbed OS image build process.

### PR DESCRIPTION
**Pull request by lukgni**
#### Problem
Some way to verify proposed Mbed OS docker image is needed.
Related issue: #4653

 #### Summary of Changes
Add new GitHub workflow which builds mbed-os image and verify that all tools which we need are in the place.
Added workflow has to be triggered manually (workflow_dispatch) and should be used on PR #4620 branch

### CODE REVIEW

**Comment by lukgni** [comment]
I updated workflow to work with PR #4657 - I guess @woody-apple change will land on master first.

**Review by bzbarsky-apple — APPROVED** [review]

**Review by jelderton — APPROVED** [review]

**Review by mspang — APPROVED** [review]

**Review by msandstedt — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
@lukgni CI failures?

**Review by jelderton — APPROVED** [review]
Need to address the CI build failure

**Comment by lukgni** [comment]
In our team we decided to close this PR and return with mbed integration when we will have more complete solution.

**Pull request closed without merging**
