### PR TITLE
[Android] Refactor address update UI into common fragment

### PR DESCRIPTION
**Pull request by austinh0**
#### Problem
* In the Android CHIPTool, UI/logic for updating device address is duplicated across the OnOff, Basic, OpCred, MultiAdmin, and Cluster Interaction fragments.

#### Change overview
* Refactor into `AddressUpdateFragment`, and directly embed this fragment into the XML of other fragments.
* Delete unused `on_off_fragment.xml` and `root_fragment.xml` while I'm here

#### Testing
* Commissioned and controlled all-clusters-app

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

**Review by Damian-Nordic — APPROVED** [review]
Another approach that could be considered is starting the update automatically when the device ID text box is modified (or when a fragment shows up). I did something like that for the sensor clusters screen on our fork: https://github.com/Damian-Nordic/sdk-connectedhomeip/blob/9bfa2f6e49b77e098c686c7d68186834805f18b3/src/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/clusterclient/SensorClientFragment.kt#L46, but if you think it would be useful, I can upstream it.

**Review by LuDuda — APPROVED** [review]
I would suggest the same as Damian to make the CASE session establishment and Resolve automatically.

**Comment by austinh0** [comment]
> Another approach that could be considered is starting the update automatically when the device ID text box is modified (or when a fragment shows up). I did something like that for the sensor clusters screen on our fork: https://github.com/Damian-Nordic/sdk-connectedhomeip/blob/9bfa2f6e49b77e098c686c7d68186834805f18b3/src/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/clusterclient/SensorClientFragment.kt#L46, but if you think it would be useful, I can upstream it.

I would actually prefer to keep the update address button. I don't think it's obvious that entering the OnOff, MultiAdmin, etc. fragment should immediately update the address of the last device ID from preferences. But if you want to upstream your change just for the SensorClientFragment, I have no problem with that.

**Comment by austinh0** [comment]
@bzbarsky-apple @chrisdecenzo @jelderton @jmartinez-silabs @saurabhst?

**Review by jmartinez-silabs — APPROVED** [review]

**Pull request merged**
