### PR TITLE
Add C++ wrappers for ZCL Clusters

### PR DESCRIPTION
**Pull request by vivien-apple**
#### Problem

In #3879, an `OnOffCluster` class has been introduced. This class has been handrolled to have a base template.
    
This PR generates C++ wrappers for the ZCL clusters from the `all-clusters-app`, which is what has been used to generate the code inside `chip-tool` and `src/app`.
    
Included in this PR are the templates used for generating the wrappers.

One thing I don't like in the code/template is the repetition of:
```
CHIP_ERROR err         = CHIP_NO_ERROR;
    uint16_t payloadLength = 0;

    System::PacketBufferHandle buffer = System::PacketBuffer::NewWithAvailableSize(kMaxMessageLength);
    VerifyOrExit(!buffer.IsNull(), err = CHIP_ERROR_NO_MEMORY);

    payloadLength = encode{{asCamelCased parent.name false}}ClusterWrite{{asCamelCased name false}}Attribute(buffer->Start(), kMaxMessageLength, mEndpoint, value);
    VerifyOrExit(payloadLength != 0, err = CHIP_ERROR_INVALID_MESSAGE_LENGTH);
    VerifyOrExit(payloadLength <= kMaxMessageLength, err = CHIP_ERROR_INTERNAL);

    buffer->SetDataLength(payloadLength);
    VerifyOrExit(buffer->DataLength() >= payloadLength, err = CHIP_ERROR_NO_MEMORY);

    err = SendCommand(buffer, onCompletion);
```

This is something I would like to fix in a followup, by solving https://github.com/project-chip/connectedhomeip/issues/965

### CODE REVIEW

**Comment by vivien-apple** [comment]
Ah. I guess CI is all red because I did this one from a `all-clusters-app` configuration containing the changes for #4127...
It should not really matters for review, though. So I will rebase this one depending on which one is ready first to land.

**Comment by rwalker-apple** [comment]
> One thing I don't like in the code/template is the repetition of:
> 
> ```
> CHIP_ERROR err         = CHIP_NO_ERROR;
>     uint16_t payloadLength = 0;
> 
>     System::PacketBufferHandle buffer = System::PacketBuffer::NewWithAvailableSize(kMaxMessageLength);
>     VerifyOrExit(!buffer.IsNull(), err = CHIP_ERROR_NO_MEMORY);
> 
>     payloadLength = encode{{asCamelCased parent.name false}}ClusterWrite{{asCamelCased name false}}Attribute(buffer->Start(), kMaxMessageLength, mEndpoint, value);
>     VerifyOrExit(payloadLength != 0, err = CHIP_ERROR_INVALID_MESSAGE_LENGTH);
>     VerifyOrExit(payloadLength <= kMaxMessageLength, err = CHIP_ERROR_INTERNAL);
> 
>     buffer->SetDataLength(payloadLength);
>     VerifyOrExit(buffer->DataLength() >= payloadLength, err = CHIP_ERROR_NO_MEMORY);
> 
>     err = SendCommand(buffer, onCompletion);
> ```


can the boilerplate can be put in a single function that takes the encode function as an argument?

**Comment by vivien-apple** [comment]
> can the boilerplate can be put in a single function that takes the encode function as an argument?

What I want to do is to have the various `encode{{asCamelCased parent.name false}}Cluster*` methods to do all the `PacketBufferHandle` related work directly. 

So the signatures of the methods may be something like:
```
CHIP_ERROR encodeOnOffClusterOnCommand(chip::System::PacketBufferHandle & buffer, chip::EndpointId endpointId);
```
And so the embedding calling site may be something like:
```
System::PacketBufferHandle buffer;
ReturnErrorOnFailure(encodeOnOffClusterOnCommand(buffer, mEndpoint));
ReturnErrorOnFailure(SendCommand(buffer, onCompletion));
return CHIP_NO_ERROR;
```

Or maybe the `PacketBufferHandle` could be returned by the `encode*` method. The signature could then be:
```
chip::System::PacketBufferHandle encodeOnOffClusterOnCommand(chip::EndpointId endpointId);
```


 In this case the calling site could be:
```
return SendCommand(encodeOnOffClusterOnCommand(mEndpoint), onCompletion);
```

The reason why I'm not doing it in this patch is because it just because of timing.

Cleaning `src/app/chip-zcl-zpro-codec-api.h` and `src/app/encoder.cpp`, as well as the current calling sites will take a few days,  and in the meantime people won't be able to use those C++ wrappers.
While If I land the C++ wrappers first, then more work can be added on top of them while their internal code is being rewritten.

**Comment by vivien-apple** [comment]
> Cleaning `src/app/chip-zcl-zpro-codec-api.h` and `src/app/encoder.cpp`, as well as the current calling sites will take a few days, and in the meantime people won't be able to use those C++ wrappers.
> While If I land the C++ wrappers first, then more work can be added on top of them while their internal code is being rewritten.

I end up opening #4181 for that finally.

**Review by rwalker-apple — APPROVED** [review]

**Review by mspang — APPROVED** [review]

**Comment by vivien-apple** [comment]
I pushed an update using the changes from #4181, so using a `PacketBufferHandle` value returned by the ZCL API instead of building it manually.

**Review by BroderickCarlin — APPROVED** [review]

**Pull request merged**
