### PR TITLE
Add rpc builds to python build scripts

### PR DESCRIPTION
**Pull request by rgoliver**
#### Problem
The build scripts can't build the application with the RPC debug interface enabled for testing.

#### Change overview
Add --rpc option which builds applications with the rpc debug interface enabled.

#### Testing
Used scripts to build the following app/board versions with RPC enabled, flashed and verified RPCs worked with console.
- esp all-clusters
- efr lighting
- nrf lighting

### CODE REVIEW

**Comment by mspang** [comment]
Should we support building both cases?

I think these should have distinct filenames in the output to avoid confusion.

**Comment by rgoliver** [comment]
> Should we support building both cases?
> 
> I think these should have distinct filenames in the output to avoid confusion.

Are you suggesting building both versions as part of "platform all"?

Currently the RPC build folders are named differently, with -rpc appended but the actual build artifacts aren't changed.

**Comment by mspang** [comment]
> > Should we support building both cases?
> > I think these should have distinct filenames in the output to avoid confusion.
> 
> Are you suggesting building both versions as part of "platform all"?
> 
> Currently the RPC build folders are named differently, with -rpc appended but the actual build artifacts aren't changed.

Would the archive be named differently?

**Comment by mspang** [comment]
> > > Should we support building both cases?
> > > I think these should have distinct filenames in the output to avoid confusion.
> > 
> > 
> > Are you suggesting building both versions as part of "platform all"?

Sure... but this is another dimension entirely.. "config all" ?

All of {debug, release} x {rpc_enabled, rpc_disabled} are possible and really I think we should provide artifacts for at least release and debug+rpc

> > Currently the RPC build folders are named differently, with -rpc appended but the actual build artifacts aren't changed.
> 
> Would the archive be named differently?

**Comment by rgoliver** [comment]
> > > Should we support building both cases?
> > > I think these should have distinct filenames in the output to avoid confusion.
> > 
> > 
> > Are you suggesting building both versions as part of "platform all"?
> > Currently the RPC build folders are named differently, with -rpc appended but the actual build artifacts aren't changed.
> 
> Would the archive be named differently?

Yes the archive uses this name for the archive name so they show up differently, for example: 
```
$ ls archive
efr32-brd4161a-light-rpc.tar.gz  efr32-brd4161a-light.tar.gz
```

**Comment by mspang** [comment]
> > > > Should we support building both cases?
> > > > I think these should have distinct filenames in the output to avoid confusion.
> > > 
> > > 
> > > Are you suggesting building both versions as part of "platform all"?
> > > Currently the RPC build folders are named differently, with -rpc appended but the actual build artifacts aren't changed.
> > 
> > 
> > Would the archive be named differently?
> 
> Yes the archive uses this name for the archive name so they show up differently, for example:
> 
> ```
> $ ls archive
> efr32-brd4161a-light-rpc.tar.gz  efr32-brd4161a-light.tar.gz
> ```

Ok sounds good. Sounds like the only possible issue is that we can't generate all the configs we want artifacts for in one go.

**Review by woody-apple — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
It would be ideal to have the ability to generate all configurations in one build if desirable. I would imagine we would want some sort of 'build configurations' option where I can say `--configurations rpc` to only build RPC, or `--configurations default,rpc` to get evertyhing and we can keep adding (e.g. clang, debug/release,  ipv6-only etc).

Currently we have an automated build controlled by https://github.com/project-chip/connectedhomeip/blob/master/integrations/cloudbuild/build-all.yaml that tries to compile everything possible and we probably want to add RPCs to those.

Generally however, this  change is a step forward and shows how builders can compile an RPC version of things, so approving.

**Comment by andy31415** [comment]
Also thinking aloud, I believe the current `--platform` and `--board` and such arguments are not ideal. I would prefer to have a list of all possible things that can be generated  and use globbing to select, so that I can do things like:

```
build_examples.py --target '*'
build_examples.py --target 'efr32-*-light-rpc' 
build_examples.py --target '{efr32,esp32}*light-rpc-ipv6_only'
```

and have them do the 'obvious thing'. Also have `build_examples.py list-targets` to build a list of possible targets for me to see what is available.

I think this is well beyond the scope of  this PR, but thinking aloud about the path to take.

**Pull request merged**
