### PR TITLE
[nRF Connect] Provide a way to build examples with no debugging features

### LINKED ISSUE #3657: [nRF Connect] Provide a way to build examples with no debugging features
#### Problem
nRF Connect examples are built with diagnostic features like shell, application logs, network statistics etc. They pretty useful for development, but there should also be a way to build the examples with "release" settings.

 #### Proposed Solution
* Add configuration overlay with release settings that disable diagnostic features like shell/application logs
* Add instruction how to you the release config

### PR DESCRIPTION
**Pull request by Damian-Nordic**
#### Problem
nRF Connect examples are built with diagnostic features like shell, application logs, network statistics etc. They pretty useful for development, but there should also be a way to build the examples with "release" settings.

 #### Summary of Changes
* Add configuration overlay with release settings that disable diagnostic features like shell/application logs
* Add instruction how to you the release config
* Turn overlay-sample-defaults.conf into sample-defaults.conf and apply it before a project-specific config so that every project may override the default settings.

 Fixes #3657

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

**Review by rwalker-apple — APPROVED** [review]

**Comment by mspang** [comment]
Where are we setting `is_debug=false` in GN args ?

**Comment by Damian-Nordic** [comment]
> Where are we setting `is_debug=false` in GN args ?

@mspang Apparently we are not. We do pass optimizations flags from zephyr to GN, so it doesn't change much, but there is some small size reduction when I set it, so I'll fix that.

**Comment by mspang** [comment]
> > Where are we setting `is_debug=false` in GN args ?
> 
> @mspang Apparently we are not. We do pass optimizations flags from zephyr to GN, so it doesn't change much, but there is some small size reduction when I set it, so I'll fix that.

Yes, please prefer to communicate using the build system using its actual interface not by setting CFLAGS directly.

**Comment by Damian-Nordic** [comment]
> > > Where are we setting `is_debug=false` in GN args ?
> > 
> > 
> > @mspang Apparently we are not. We do pass optimizations flags from zephyr to GN, so it doesn't change much, but there is some small size reduction when I set it, so I'll fix that.
> 
> Yes, please prefer to communicate with the build system using its actual interface not by setting CFLAGS directly.

That may not be easy. Zephyr not only sets compilation flags, but also injects macros definitions via `-imacros` etc. which we need also while building CHIP. We would have to filter-out some flags and pass remaining ones which is a bit hard to maintain between subsequent Zephyr releases. But I agree that in most obvious cases we should let CHIP decide which flags it is built with.

**Comment by mspang** [comment]
> > > > Where are we setting `is_debug=false` in GN args ?
> > > 
> > > 
> > > @mspang Apparently we are not. We do pass optimizations flags from zephyr to GN, so it doesn't change much, but there is some small size reduction when I set it, so I'll fix that.
> > 
> > 
> > Yes, please prefer to communicate with the build system using its actual interface not by setting CFLAGS directly.
> 
> That may not be easy. Zephyr not only sets compilation flags, but also injects macros definitions via `-imacros` etc. which we need also while building CHIP. We would have to filter-out some flags and pass remaining ones which is a bit hard to maintain between subsequent Zephyr releases. But I agree that in most obvious cases we should let CHIP decide which flags it is built with.

I think CHIP likely should provide a centralized script that maps CFLAGS back onto GN args. That way we avoid duplicated arguments, and avoid wrong branches in build files due to options set behind our back.

**Comment by Damian-Nordic** [comment]
> I think CHIP likely should provide a centralized script that maps CFLAGS back onto GN args. That way we avoid duplicated arguments, and avoid wrong branches in build files due to options set behind our back.

Agreed. Filed an issue for that: #3685

**Review by mspang — APPROVED** [review]

**Review by LuDuda — APPROVED** [review]
LGTM :+1:

**Review by bukepo — APPROVED** [review]
LGTM:+1:

**Comment by bzbarsky-apple** [comment]
@saurabhst @jelderton @hawk248 @BroderickCarlin @chrisdecenzo Please take a look?

**Review by shana-apple — APPROVED** [review]

**Comment by Damian-Nordic** [comment]
@saurabhst @jelderton @hawk248 @BroderickCarlin @chrisdecenzo do you have any comments?

**Review by saurabhst — APPROVED** [review]
Resolve merge conflicts pls

**Comment by Damian-Nordic** [comment]
> Resolve merge conflicts pls

OK, done.

**Pull request merged**
