### PR TITLE
[Telink]: Use docker image 0.5.74

### PR DESCRIPTION
**Pull request by s07641069**
#### Problem
* Issue with plic_set_priority under irq_connect_dynamic.
#### Change overview
* Use docker image 0.5.74

#### Testing
Tested manually with chip-tool.
Steps:

Run: $ chip-tool pairing ble-thread <...>
Wait till success
Run: $ chip-tool accesscontrol write acl <...>
Wait till success
Run: $ chip-tool binding write binding <...>
Wait till success
Press manually switch button
Check if end device perform command

### CODE REVIEW

**Review by Damian-Nordic — APPROVED** [review]

**Review by arkq — APPROVED** [review]

**Review by andy31415 — CHANGES_REQUESTED** [review]
Lets make the change across the board. Using a single docker image for all builds seems more consistent than each platform using a separate build.

I believe only o.5.75 compiled fully on all platforms.

**Comment by s07641069** [comment]
> Lets make the change across the board. Using a single docker image for all builds seems more consistent than each platform using a separate build.
> 
> I believe only o.5.75 compiled fully on all platforms.

@andy31415 
Do you mean switch our platform from chip-build-telink into chip-build-vscode?

**Comment by andy31415** [comment]
> @andy31415 Do you mean switch our platform from chip-build-telink into chip-build-vscode?

I mean update all references in yaml files to updated versions: instead of just changing telink, also change linux/efr/esp/ameba/qpg/etc. Also vscode default and cloudbuild.

Something like:

```
rg --no-ignore --hidden ':0\.5\.\d\d' | cut -f1 -d: | uniq | xargs sd ':0\.5\...' ':0.5.75'
```

**Comment by s07641069** [comment]
Done in #18673

**Pull request closed without merging**
