### PR TITLE
Change default setup pin code from 12345678 to 20202021

### LINKED ISSUE #6058: invalid passcode in source file(s)
#### Problem
File examples/lock-app/nrfconnect/main/include/CHIPProjectConfig.h:38 contains
`#define CHIP_DEVICE_CONFIG_USE_TEST_SETUP_PIN_CODE 12345678`
Looking at spec section 5.1.6.1, this is one of the **invalid** passcodes.

#### Proposed Solution
Suggest to change it to another value (e.g. `20202021`).
Note - I expect there are other source files (e.g. the other example files) with the same invalid value. Please check and fix.

 
Triggered from slack discussion ([link](https://zigbeeiot.slack.com/archives/C01RATGFSJD/p1617953391126700))

### PR DESCRIPTION
**Pull request by lucicop**
Problem:
The default setup pin code (12345678) does not comply with test case 6.1.1 QR Code Onboarding Payload Verification - it is an invalid value according to that test case. 

Proposed solution:
Replace the default code by 20202021.

Closing #6058

### CODE REVIEW

**Comment by vivien-apple** [comment]
I'm not against changing that code, but if it is an invalid passcode I would expect the SDK to fail the pairing process. Can we open a followup to not forget to implement properly ` 6.1.1 QR Code Onboarding Payload Verification` ?

**Review by Damian-Nordic — APPROVED** [review]

**Comment by Damian-Nordic** [comment]
> I'm not against changing that code, but if it is an invalid passcode I would expect the SDK to fail the pairing process. Can we open a followup to not forget to implement properly ` 6.1.1 QR Code Onboarding Payload Verification` ?

I believe the SDK fails the process in case of not matching PIN code, but here the issue is that the default PIN code is one of the examples of forbidden PIN codes listed in the spec, which looks bad :).

**Review by andy31415 — APPROVED** [review]

**Comment by vivien-apple** [comment]
> > I'm not against changing that code, but if it is an invalid passcode I would expect the SDK to fail the pairing process. Can we open a followup to not forget to implement properly ` 6.1.1 QR Code Onboarding Payload Verification` ?
> 
> I believe the SDK fails the process in case of not matching PIN code, but here the issue is that the default PIN code is one of the examples of forbidden PIN codes listed in the spec, which looks bad :).

Sure. What I'm saying is: if `12345678` is invalid per spec, why do we not throw at startup on the accessory side ?

**Review by vivien-apple — APPROVED** [review]

**Comment by lucicop** [comment]
@vivien-apple : I have opened issue https://github.com/project-chip/connectedhomeip/issues/6144 to track supplemental checks.

**Review by LuDuda — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]

**Review by mspang — APPROVED** [review]

**Pull request merged**
