### PR TITLE
Import LwIP code to CHIP

### PR DESCRIPTION
**Pull request by pan-apple**
This PR imports LwIP code to CHIP codebase.

* update copyright notice where applicable
* update reference to Weave and Nest Labs
* introduce a build system that builds, lints, and runs unit tests. Also, run code coverage and valgrind on code under test.

### CODE REVIEW

**Review by woody-apple — CHANGES_REQUESTED** [review]
Can we update the build flows to uncomment the main 'make' - so this runs?
.github/workflows/build-main.yml

**Review by gerickson — APPROVED** [review]

**Review by bhaskar-apple — APPROVED** [review]

**Review by woody-apple — CHANGES_REQUESTED** [review]
Looks like you have a missing space there, run needs to be two spaces in to be valid yaml. Can we make sure this runs on your branch before committing?
    - name: Run Build
    run: make

**Review by woody-apple — APPROVED** [review]
Thank you!

**Review by robszewczyk — APPROVED** [review]

**Review by hawk248 — APPROVED** [review]
Approved.

**Pull request merged**
