### PR TITLE
Revert "Move CHIPClusters.* to gen/ folders (#6284)"

### PR DESCRIPTION
**Pull request by erjiaqing**
Reverts project-chip/connectedhomeip#6284

When taking look at the generated files, the generated files in python device controller is empty.

We need to take some look at the template / zap files and fix the PR so we can still work with the python device controller.

### CODE REVIEW

**Comment by mspang** [comment]
solved by #6313 ?

**Comment by woody-apple** [comment]
Appears so

**Comment by woody-apple** [comment]
(Still working on k32w build)

**Comment by erjiaqing** [comment]
> solved by #6313 ?

Seems so, close now

**Comment by erjiaqing** [comment]
> (Still working on k32w build)

Checked that cirque test is passed.

**Pull request closed without merging**
