### PR TITLE
Updated StateChange Events of the Boolean State Cluster as Optional to Match the Spec

### LINKED ISSUE #24959: [BUG] Update Boolean State Cluster XML to Match The Spec
### Reproduction steps

StateChange event should be marked as optional (not mandatory).

### Bug prevalence

100% of the time

### GitHub hash of the SDK that was being used

1f8138495a3bc85d2539779c8284ea0f848bc080

### Platform

core

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by emargolis**
Fixes #24959

### CODE REVIEW

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]
This looks like a bug in the spec to me.  The spec has a non-optional normative requirement that the event be generated, no?

**Comment by emargolis** [comment]
> This looks like a bug in the spec to me. The spec has a non-optional normative requirement that the event be generated, no?

@bzbarsky-apple Do you suggest that we fix the spec to make this event Mandatory (M) for the Boolean State cluster?

**Comment by bzbarsky-apple** [comment]
> Do you suggest that we fix the spec to make this event Mandatory (M) for the Boolean State cluster?

I would like to at least get the spec clarified as to whether it's meant to be mandatory or optional before we change the XML.

**Comment by emargolis** [comment]
> I would like to at least get the spec clarified as to whether it's meant to be mandatory or optional before we change the XML.

I didn't find Boolean State cluster description in the generated spec but I found it's description here:
  `src/app_clusters/BooleanState.adoc`
According to the text the `StateChange` event is meant to be optional.

**Comment by bzbarsky-apple** [comment]
Please see https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/6270

**Comment by emargolis** [comment]
> Please see [CHIP-Specifications/connectedhomeip-spec#6270](https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/6270)

My interpretation of the comment from `Leo Rozendaal` is that this event is Optional:
`If this event is supported, then this event ....`

**Comment by bzbarsky-apple** [comment]
That's Leo's interpretation, yes.  It's not clear to me that that is the intent of the people who wrote the cluster spec.

**Comment by andy31415** [comment]
Assuming stale. Closing

**Comment by bzbarsky-apple** [comment]
Reopening.  This needs to actually merge; the spec says this event is optional.

**Comment by bzbarsky-apple** [comment]
We need to either change the SDK here or the spec.  Just pretending the problem does not exist is not helping anything.

**Comment by andy31415** [comment]
I re-opened the underlying issue, however this PR has been open for almost 2 years now and is in changes requested state without developer followup. Closing as stale.

**Pull request closed without merging**
