### PR TITLE
Revert "Fix issue 13075"

### PR DESCRIPTION
**Pull request by woody-apple**
Reverts project-chip/connectedhomeip#15683

### CODE REVIEW

**Comment by andy31415** [comment]
Revert reason seems to be build failures (is this right @woody-apple )?

https://github.com/project-chip/connectedhomeip/runs/5396525003?check_suite_focus=true

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
The issue seems to be an overload though - casting to specific sized values.

**Comment by andy31415** [comment]
https://github.com/project-chip/connectedhomeip/pull/15747 may be better.

**Comment by yunhanw-google** [comment]
yes, let's merge https://github.com/project-chip/connectedhomeip/pull/15747, thanks

**Pull request closed without merging**
