### PR TITLE
Modified scripts JUNE 01

### LINKED ISSUE #27421: [Build] test failed: The test expectation "value == 1" is false
### Build issue(s)

https://github.com/project-chip/connectedhomeip/actions/runs/5349369366/jobs/9700494331

```
ERROR   20:39:42.950 - APP  OUT  : [1687466382949] [43734:331988] [EM] Rxd Ack; Removing MessageCounter:95909991 from Retrans Table on exchange 4673r
ERROR   20:39:42.950 - TEST OUT  : 		    Expected: [
ERROR   20:39:42.950 - TEST OUT  : 		                {
ERROR   20:39:42.950 - TEST OUT  : 		                  "values": [
ERROR   20:39:42.950 - TEST OUT  : 		                    {
ERROR   20:39:42.950 - TEST OUT  : 		                      "value": 1
ERROR   20:39:42.950 - TEST OUT  : 		                    }
ERROR   20:39:42.950 - TEST OUT  : 		                  ]
ERROR   20:39:42.950 - TEST OUT  : 		                }
ERROR   20:39:42.950 - TEST OUT  : 		              ]
ERROR   20:39:42.950 - TEST OUT  : 		    Received: [
ERROR   20:39:42.950 - TEST OUT  : 		                 {
ERROR   20:39:42.950 - TEST OUT  : 		                   "attribute": "LockState",
ERROR   20:39:42.950 - TEST OUT  : 		                   "cluster": "DoorLock",
ERROR   20:39:42.950 - TEST OUT  : 		                   "dataVersion": 3671656477,
ERROR   20:39:42.950 - TEST OUT  : 		                   "endpoint": 1,
ERROR   20:39:42.950 - TEST OUT  : 		                   "value": 2
ERROR   20:39:42.950 - TEST OUT  : 		                 }
ERROR   20:39:42.950 - TEST OUT  : 		               ]
ERROR   20:39:42.950 - TEST OUT  : 		***** Test Failure : The test expectation "value == 1" is false
ERROR   20:39:42.950 - TEST OUT  : ✗ Test finished in 56580ms with 27 success, 1 errors and 0 warnings
ERROR   ================ CAPTURED LOG END ====================
ERROR   Test_TC_DRLK_2_4               - FAILED in 70.72 seconds
Traceback (most recent call last):
  File "/Users/runner/work/connectedhomeip/connectedhomeip/./scripts/tests/run_test_suite.py", line 344, in cmd_run
    test.Run(
  File "/Users/runner/work/connectedhomeip/connectedhomeip/scripts/tests/chiptest/test_definition.py", line 340, in Run
    runner.RunSubprocess(
  File "/Users/runner/work/connectedhomeip/connectedhomeip/scripts/tests/chiptest/runner.py", line 167, in RunSubprocess
    raise Exception('Command %r failed: %d' % (cmd, s.returncode))
Exception: Command ['stdbuf', '-o0', '-i0', 'python3', '/Users/runner/work/connectedhomeip/connectedhomeip/scripts/tests/yaml/chiptool.py', 'tests', 'Test_TC_DRLK_2_4', '--PICS', 'src/app/tests/suites/certification/ci-pics-values', '--server_path', './out/darwin-x64-chip-tool-no-ble-tsan-clang/chip-tool', '--server_arguments', 'interactive server --storage-directory /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpb9l01tio'] failed: 1
Error: Process completed with exit code 2.
```

### Platform

darwin

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by manjunath-grl**
Fixes issue:  [555](https://github.com/CHIP-Specifications/chip-test-scripts/issues/555), [556](https://github.com/CHIP-Specifications/chip-test-scripts/issues/556), [557](https://github.com/CHIP-Specifications/chip-test-scripts/issues/557), [558](https://github.com/CHIP-Specifications/chip-test-scripts/issues/558), [559](https://github.com/CHIP-Specifications/chip-test-scripts/issues/559), [560](https://github.com/CHIP-Specifications/chip-test-scripts/issues/560), [561](https://github.com/CHIP-Specifications/chip-test-scripts/issues/561), [562](https://github.com/CHIP-Specifications/chip-test-scripts/issues/562), [565](https://github.com/CHIP-Specifications/chip-test-scripts/issues/565), [567](https://github.com/CHIP-Specifications/chip-test-scripts/issues/567),[851](https://github.com/CHIP-Specifications/chip-certification-tool/issues/851), [847](https://github.com/CHIP-Specifications/chip-certification-tool/issues/847), [27087](https://github.com/project-chip/connectedhomeip/issues/27087)
Modified scripts:
ci-pics-values
ciTests.json
app1/ciTests.json
app1/config.zap
app2/config.zap
manualTests.json
PICS.yaml
TC_AUDIOOUTPUT_7_2
TC_BINFO_2_1
TC_BRBINFO_2_1
TC_CHANNEL_5_2
TC_CHANNEL_5_3
TC_DGTHREAD_3_2_Simulated
TC_MEDIAINPUT_3_11
TC_MEDIAINPUT_3_13
TC_MOD_1_2
TC_MOD_2_1
TC_MOD_2_3
TC_MOD_3_1
TC_MOD_3_2
TC_MOD_3_4
TC_PRS_2_1
TC_PS_1_1
TC_TMP_2_1

Semi-Automated tests:
TC-DRLK-2.1
TC-DRLK-2.9
Simulated:
TC-DGTHREAD-3.1
TC-DRLK-3.1
TC-CC-2.2
Automated tests:
TC-WNCV-2.2
TC-WNCV-2.4
TC-DRLK-2.8
TC_CC_6_5

Added auto generated files

Tested

Execution logs:
[exe_log.txt](https://github.com/project-chip/connectedhomeip/files/11626620/exe_log.txt)
[CC_2_2_Simulated.zip](https://github.com/project-chip/connectedhomeip/files/11626630/CC_2_2_Simulated.zip)
[WNCV_22_24_DRLK_22_Logs.zip](https://github.com/project-chip/connectedhomeip/files/11736898/WNCV_22_24_DRLK_22_Logs.zip)

### CODE REVIEW

**Review by raju-apple — APPROVED** [review]

**Comment by manjunath-grl** [comment]
@vivien-apple @bzbarsky-apple  Test Suites - Linux (no-ble-tsan-clang) check is failing for test DRLK-2.8 for step 5 and the expected outcome is Occupied (cluster error: 0x3) script check for it and locally also it worked fine but failing for this check. Please take a look at it.
image
image
image
Local execution logs:
[DRLK_2_8.zip](https://github.com/project-chip/connectedhomeip/files/11760245/DRLK_2_8.zip)

**Comment by bzbarsky-apple** [comment]
@manjunath-grl It's failing only with chip-repl, right?  Please check with @tehampson or @andy31415

**Comment by tehampson** [comment]
I am OOO today so I will not be able to take a closer look at the moment. If there is a rush to get this in we could add that test to the list here https://github.com/project-chip/connectedhomeip/blob/master/scripts/tests/chiptest/__init__.py#L130 along with an issue to resolve it ASAP

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
@manjunath-grl can you please fix the merge conflicts?

**Comment by manjunath-grl** [comment]
> @manjunath-grl can you please fix the merge conflicts?

@woody-apple Done rebase.

**Pull request merged**
