### PR TITLE
Fix broken link in to Cirque documentation

### PR DESCRIPTION
**Pull request by neonsoftware**
#### Problem
The user, when cliicking on the link to the Cirque's README documentation page, was landing on a 404 Github page, due to an invalid relative link.

#### Summary of Changes
The link is fixes, and the documentation navigation is now working correctly.

### CODE REVIEW

**Review by saurabhst — APPROVED** [review]

**Review by LuDuda — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]

**Review by jelderton — APPROVED** [review]

**Comment by neonsoftware** [comment]
**Status**
The GIthub doxygen workflow reported the following issue:
`/home/runner/work/connectedhomeip/connectedhomeip/docs/README.md:9: error: unexpected token TK_EOF as the argument of ref (warning treated as error, aborting now)`

Although launching locally `./scripts/helpers/doxygen.sh` the doxignen generation was successful and the link working. 

**Action**
Investigating why the doxygen is failing on the Github workflow (and not locally). I have re-uploaded the commit with a freshly re-modified line, in case it was an issue with encoding.

**Comment by bzbarsky-apple** [comment]
> Investigating why the doxygen is failing on the Github workflow (and not locally)

What version of doxygen are you running locally?  This looks a lot like https://github.com/doxygen/doxygen/issues/8130 which was just fixed a few months ago.  Fix is in doxygen 1.9.0, but our containers are running doxygen 1.8.17, afaict.

**Comment by neonsoftware** [comment]
Hi @bzbarsky-apple, 
Spot on. I run 1.9.1 locally. 
And, yes, Github offers up to Ubuntu 20-04 on workflows, while 1.9.x is only from ubuntu 21-04.
It might be that.

Before I make any correction, what do you think, or any other of the project of course, would be the best way forward ?

- option A: in the Github workflow, I will add a temporary step, with bash doing if(doxygen version < 1.9.x) { install doxygen from ubuntu 21-04 }, marking such workflow step with a comment, capital letters, "this step can be removed once default doxygen version will be 1.9.x"
- option B: as option A, still manually upgrading doxygen in the workflow, but better, looking forward any idea or suggestion
- option C: asking the doxygen project a backport of the fix to  1.8.17+ and putting this issue on hold until available
- option D: none of the above and deleting this issue
- option E: any other option that I might have not considered yet, let me know

Considering that with option C and D the documentation has broken links in this phase of adoption.

Let me know, cheers, have an outstanding week, F

**Comment by bzbarsky-apple** [comment]
My gut feeling is that if we can do the doxygen update in our container in general, not on a per-workflow basis, that would be ideal.  I guess that's option B, right?

@woody-apple How feasible is that?

**Comment by electrocucaracha** [comment]
I have created this [PR](https://github.com/project-chip/connectedhomeip/pull/7105) to automate the validation of broken links, hopefully that helps to early detect these issues.

**Comment by neonsoftware** [comment]
@electrocucaracha great.

**Review by jmartinez-silabs — APPROVED** [review]

**Pull request closed without merging**
