### PR TITLE
Csg/feature/qr code validation

### PR DESCRIPTION
**Pull request by Xiole-KKE**
#### Problem
Expose QR code parsing from RPC server.

 #### Summary of Changes
 One function that return the parsed QR code information with a dictionary object.
 Exposed API added for RPC server

 Fixes  https://github.com/chip-csg/chip-certification-tool/issues/160

image
image

### CODE REVIEW

**Comment by woody-apple** [comment]
Thank you for this change!

@Xiole-KKE and @wahajsyed can you please sign the CLA?

**Review by woody-apple — APPROVED** [review]

**Comment by wahajsyed** [comment]
Sorry for the noise @woody-apple 
PR should have been set to merge on te2.2 [branch](https://github.com/chip-csg/connectedhomeip/tree/csg/test_event_2.2) of the CSG fork

**Comment by Xiole-KKE** [comment]
Wrong branch, sorry for confusion.

**Pull request closed without merging**
