### PR TITLE
Fix Doxygen errors

### PR DESCRIPTION
**Pull request by harsha-rajendran**
#### Problem
Fixed Doxygen errors

Re-enabling the "Doxygen workflow" for all PRs should prevent such issues from being introduced. Unless there's a different reason for disabling the Doxygen workflow that I am not aware of... :-)

#### Change overview
Updated comments that were causing Doxygen generation from succeeding.

#### Testing
Tested by successfully generating Doxygen HTML docs on my local machine, i.e. the following commands now work.
```
doxygen docs/Doxyfile
```

```
./scripts/helpers/doxygen.sh 
```

### CODE REVIEW

**Review by saurabhst — APPROVED** [review]

**Comment by hrajendran** [comment]
Re-enabling the "Doxygen workflow" for all PRs should prevent such issues from being introduced. Unless there's a different reason for disabling the Doxygen workflow that I am not aware of... :-)

**Review by electrocucaracha — APPROVED** [review]
@woody-apple @andy31415 The size of this image has been reduced so maybe after merging this we can re-enable this workflow

**Comment by andy31415** [comment]
@electrocucaracha - I believe the 'deploy doxygen' workflow was disabled because it created very large commits (maybe due to images? I am not sure) and there was no evidence that the doxygen output was actually used by anyone.

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
I would propose to enable the doxygen run to validate generation (i.e. make sure our comments are reasonably formatted) however without actually deploying just yet. There may be value in having one single 'doxygen' periodically, however one per merged PR seems not as useful.

**Comment by electrocucaracha** [comment]
> I would propose to enable the doxygen run to validate generation (i.e. make sure our comments are reasonably formatted) however without actually deploying just yet. There may be value in having one single 'doxygen' periodically, however one per merged PR seems not as useful.

Another option is just run when a [supported doxygen](https://www.doxygen.nl/manual/starting.html#step1) files are modified using [GH paths](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onpushpull_requestpaths)

**Pull request merged**
