### PR TITLE
[IM] Encode error status code during command dispatch.

### PR DESCRIPTION
**Pull request by erjiaqing**
#### Problem

We does not encode error code during dispatching commands.

 #### Summary of Changes

Add code for encoding command responses.

The second commit is generated by

```
./scripts/tools/zap_regen_all.py && for x in $(gd --name-only | grep -ve '(.zap$)|(.py$)|(.gn$)'); do clang-format -i $x; done && git add examples/ src/ && gc -m "Run codegen"
```

### CODE REVIEW

**Review by jmartinez-silabs — APPROVED** [review]

**Comment by erjiaqing** [comment]
@bzbarsky-apple @mspang PTAL

**Review by LuDuda — APPROVED** [review]
LGTM :+1:

**Comment by yunhanw-google** [comment]
@mspang ?

**Review by mspang — APPROVED** [review]

**Comment by erjiaqing** [comment]
@mspang @bzbarsky-apple conflict resolved, PTAL.

**Pull request merged**
