### PR TITLE
[fix] ReadAttribute should put UTF8String type for Char String attributes

### LINKED ISSUE #8096: zclread Basic VendorName should return string instead of byte array
#### Problem
zclread Basic VendorName should return string instead of byte array

curent output is
[1625259924.667724][977736] CHIP:DMG: ReportData =
[1625259924.667750][977736] CHIP:DMG: {
[1625259924.667769][977736] CHIP:DMG: 	AttributeDataList =
[1625259924.667793][977736] CHIP:DMG: 	[
[1625259924.667814][977736] CHIP:DMG: 		AttributeDataElement =
[1625259924.667845][977736] CHIP:DMG: 		{
[1625259924.667873][977736] CHIP:DMG: 			AttributePath =
[1625259924.667907][977736] CHIP:DMG: 			{
[1625259924.667940][977736] CHIP:DMG: 				NodeId = 0xbc5c01,
[1625259924.667973][977736] CHIP:DMG: 				EndpointId = 0x0,
[1625259924.668007][977736] CHIP:DMG: 				ClusterId = 0x28,
[1625259924.668040][977736] CHIP:DMG: 				FieldTag = 0x1,
[1625259924.668070][977736] CHIP:DMG: 			}
[1625259924.668102][977736] CHIP:DMG: 				
[1625259924.668134][977736] CHIP:DMG: 			Data = [
[1625259924.668167][977736] CHIP:DMG: 				0x54, 0x45, 0x53, 0x54, 0x5f, 0x56, 0x45, 0x4e, 0x44, 0x4f, 0x52, 
[1625259924.668200][977736] CHIP:DMG: 			]
[1625259924.668231][977736] CHIP:DMG: 			DataElementVersion = 0x0,
[1625259924.668260][977736] CHIP:DMG: 		},
[1625259924.668289][977736] CHIP:DMG: 		
[1625259924.668309][977736] CHIP:DMG: 	],
[1625259924.668334][977736] CHIP:DMG:

### PR DESCRIPTION
**Pull request by erjiaqing**
#### Problem
- Fixes #8096

#### Change overview
- Put UTF8String (by `PutString`) when encoding TLV data for ReadAttribute
- Includes "Data buffer to numeric types convert" in #7937

#### Testing
- Added CHAR_STRING attribute in TestCluster

### CODE REVIEW

**Review by jmartinez-silabs — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Comment by erjiaqing** [comment]
@bzbarsky-apple @vivien-apple PTAL.

**Comment by vivien-apple** [comment]
I think I have fixed the same issue with #8134 that has been cherry-picked already. And I did something very similar to the rest of your patch with https://github.com/project-chip/connectedhomeip/pull/8167

I should have checked more properly the PR list :(

**Comment by bzbarsky-apple** [comment]
@erjiaqing Please rebase on ToT so it's clearer what the actual changes being made here (after #8134, and ideally after #8167, which is just waiting on CI to merge) are?

**Comment by erjiaqing** [comment]
> @erjiaqing Please rebase on ToT so it's clearer what the actual changes being made here (after #8134, and ideally after #8167, which is just waiting on CI to merge) are?

Seems this PR is already covered by #8167, close now.

**Pull request closed without merging**
