### PR TITLE
[K32W] Enable Thread Joining

### PR DESCRIPTION
**Pull request by doru91**
[K32W] Enable Thread Joining
    
    Using the SW4 button on the Expansion board, the user can initiate a
    Thread session to a Border Router. Thread Commissioning parameters are
    hard-coded for the moment but in a future PR these parameters will be
    sent via BLE.
   

    [K32W] Code refactor
    
    * remove invalid reference to IPAddress;
    * fix typos.

### CODE REVIEW

**Review by mspang — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]
This could use a better commit message (explaining why the changes from OTA to JOIN, not just "Code refactor") and the restyle results being merged in...  lgtm with that.

**Review by rwalker-apple — APPROVED** [review]

**Comment by mspang** [comment]
@saurabhst

**Comment by doru91** [comment]
> This could use a better commit message (explaining why the changes from OTA to JOIN, not just "Code refactor") and the restyle results being merged in... lgtm with that.

Added a more descriptive commit message and also solved the "restyled" problems.

**Comment by mspang** [comment]
@saurabhst

**Review by saurabhst — APPROVED** [review]

**Pull request merged**
