### PR TITLE
[Linux] Run only one GLib main event loop

### PR DESCRIPTION
**Pull request by arkq**
### Problem

When Linux platform uses WiFi (wpa_supplicant) and BLE (BlueZ) it runs one GLib main event loop per remote D-Bus service (one for wpa_supplicant and one for BlueZ). It is possible to handle all D-Bus related processing in one event loop - it's not required to start new thread for every D-Bus connection (D-Bus socket messages are handled in only one context any way - D-Bus connection is shared). Also, new WiFi address changer thread is started every time the `PlatformManagerImpl::_InitChipStack()` is called, but previous one is not terminated when calling `PlatformManagerImpl::_Shutdown()` - thread leakage can be seen when running `./tests/TestPlatformMgr` test.

### Changes

- run only one GLib main event loop per Matter SDK
- stop GLib main event loop thread when calling `PlatformManagerImpl::_Shutdown()`
- added workaround for TSAN false positive when initializing CHIP stack (fix related to #14710)
- run WiFi IP address change listener in GLib main loop
- remove unused functions/defines

### Testing

Tested locally with chip-tool and lighting-app.
CI should also check correctness of this PR.

### CODE REVIEW

**Review by andy31415 — COMMENTED** [review]
From the history in MainLoop.cpp, it was added for python support.

Can we confirm that this does not break pychip.ble.adapter ?

**Comment by Arkq** [comment]
> From the history in MainLoop.cpp, it was added for python support.

OK, thanks for info. I'll check that.

**Review by andy31415 — APPROVED** [review]

**Comment by msandstedt** [comment]
> ### Problem
> When Linux platform uses WiFi (wpa_supplicant) and BLE (BlueZ) it runs one GLib main event loop per remote D-Bus service (one for wpa_supplicant and one for BlueZ). It is possible to handle all D-Bus related processing in one event loop - it's not required to start new thread for every D-Bus connection (D-Bus socket messages are handled in only one context any way - D-Bus connection is shared). Also, new WiFi address changer thread is started every time the `PlatformManagerImpl::_InitChipStack()` is called, but previous one is not terminated when calling `PlatformManagerImpl::_Shutdown()` - thread leakage can be seen when running `./tests/TestPlatformMgr` test.

@Arkq ,

I suspect this fixes https://github.com/project-chip/connectedhomeip/issues/9214.  Can you confirm?

**Comment by Arkq** [comment]
@msandstedt It will definitely "fix" that issue, because the `MainLoop::EnsureStarted()` is gone :D

Right now there will be only one thread started and it's joined in the `PlatformManagerImpl::_Shutdown()` so there should be no leakage (as long as `_Shutdown()` will be called before calling `_InitChipStack()` again, but I assume that calling `_InitChipStack()` twice or more should be treated as programmer error).

**Comment by Arkq** [comment]
Yes, such pattern is possible. Twice or trice *in a row* I should say :)

**Comment by yzm157** [comment]
If using glib main loop, can't initChipStack in GUI application, such as Qt/Gtk

**Comment by arkq** [comment]
@yzm157 what do you mean "can't initChipStack in GUI application"? There is a deadlock, segfault, etc. Do you got any logs?

**Comment by yzm157** [comment]
> @yzm157 what do you mean "can't initChipStack in GUI application"? There is a deadlock, segfault, etc. Do you got any logs?

I created an application using pyqt5,
failed to exit after calling chip.native.Init(0), it seems to be deadlocked.
This issue was not found on the v1.0-branch branch

**Comment by arkq** [comment]
Can you attach to deadlocked process with gdb and dump backtraces of all threads `gdb -p <PID> -ex 'thread apply all bt'` ?

**Comment by yzm157** [comment]
@arkq 

Looks like it's caused by mutex lock, could removing the lock cause other problems?

```
CHIP_ERROR PlatformManagerImpl::_InitChipStack()
{
#if CHIP_DEVICE_CONFIG_WITH_GLIB_MAIN_LOOP

    mGLibMainLoop       = g_main_loop_new(nullptr, FALSE);
    mGLibMainLoopThread = g_thread_new("gmain-matter", GLibMainLoopThread, mGLibMainLoop);

//    {
//        std::unique_lock<std::mutex> lock(mGLibMainLoopCallbackIndirectionMutex);
//        CallbackIndirection startedInd([](void *) { return G_SOURCE_REMOVE; }, nullptr);
//        g_idle_add(G_SOURCE_FUNC(&CallbackIndirection::Callback), &startedInd);
//        startedInd.Wait(lock);
//    }

#endif

#if CHIP_DEVICE_CONFIG_ENABLE_WIFI
    ReturnErrorOnFailure(RunWiFiIPChangeListener());
#endif

    // Initialize the configuration system.
    ReturnErrorOnFailure(Internal::PosixConfig::Init());

    // Call _InitChipStack() on the generic implementation base class
    // to finish the initialization process.
    ReturnErrorOnFailure(Internal::GenericPlatformManagerImpl_POSIX<PlatformManagerImpl>::_InitChipStack());

    // Now set up our device instance info provider.  We couldn't do that
    // earlier, because the generic implementation sets a generic one.
    SetDeviceInstanceInfoProvider(&DeviceInstanceInfoProviderMgrImpl());

    mStartTime = System::SystemClock().GetMonotonicTimestamp();

    return CHIP_NO_ERROR;
}

```

**Comment by arkq** [comment]
Yes, however, this block of code is more or less required. Right now I've got some other important work to do, but I'll try to investigate this issue tomorrow. Sorry for inconvenience.

One thing you can check is whether the `[](void *) { return G_SOURCE_REMOVE; }` is executed, and if yes, on which thread - simply add `ChipLogError` into that lambda.

**Comment by yzm157** [comment]
> One thing you can check is whether the `[](void *) { return G_SOURCE_REMOVE; }` is executed, and if yes, on which thread - simply add `ChipLogError` into that lambda.

No, not executed

**Pull request merged**
