### PR TITLE
Allocate ChipCertificateData on a Stack Rather than on Heap

### PR DESCRIPTION
**Pull request by emargolis**
#### Change overview
Allocate ChipCertificateData on a Stack Rather than on Heap

#### Testing
Unit tests

### CODE REVIEW

**Review by tcarmelveilleux — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Comment by andy31415** [comment]
@emargolis : how much of stack is needed for this object? Certificates sound big, not sure if this is the case here. The PR description does not seem to explain why we think we have sufficient stack space.

**Comment by emargolis** [comment]
> @emargolis : how much of stack is needed for this object? Certificates sound big, not sure if this is the case here. The PR description does not seem to explain why we think we have sufficient stack space.

@andy31415 The size of `ChipCertificateData` struct is ~424 bytes.

**Comment by andy31415** [comment]
> > @emargolis : how much of stack is needed for this object? Certificates sound big, not sure if this is the case here. The PR description does not seem to explain why we think we have sufficient stack space.
> 
> @andy31415 The size of `ChipCertificateData` struct is ~424 bytes.

How about 'why do we think we have sufficient stack space' part? How deep is this called in our stack and how about other variables?

I have not checked what various apps use as stack size, however at least a quick grep for stack + size showed configPOSIX_STACK_SIZE for a device to be 1024 bytes. 424 is a very large percentage of that.

**Comment by andy31415** [comment]
Chatted offline with Tennessee: this is supposed to move from heap due to running out of heap. Chip main stack is likely much larger than defaults and stack does not  suffer from fragmentation.

**Review by andy31415 — APPROVED** [review]

**Pull request merged**
