### PR TITLE
ask and send credentials during the Rendezvous phase on iOS

### LINKED ISSUE #3233: Use CHIPDevicePairingDelegate to prompt user for WiFi credentials in iOS CHIP tool app
#### Problem
CHIPTool iOS application currently prompts the user to share the WiFi credentials (with device/accessory) when it receives Rendezvous message from the device. The `RendezvousSession` is currently bubbling up this message to the application layer.

`CHIPDevicePairingDelegate` callback mechanism was recently introduced to CHIP stack, using which `RendezvousSession` calls into upper layers to request WiFi network provisioning. The delegate is plumbed all the way to CHIPTool application, but the [function](https://github.com/project-chip/connectedhomeip/blob/382008c7cf8af44fc59fcb5f078757db62baa800/src/darwin/CHIPTool/CHIPTool/View%20Controllers/QRCode/QRCodeViewController.m#L288) is currently a no-op (it just prints a log message).

The application code needs to be changed to use this function to prompt the user for the network credentials, and send it to `RendezvousSession` using the included handler callback (passed as a parameter to the function). 

 #### Proposed Solution
Update the application code to use [this function](https://github.com/project-chip/connectedhomeip/blob/382008c7cf8af44fc59fcb5f078757db62baa800/src/darwin/CHIPTool/CHIPTool/View%20Controllers/QRCode/QRCodeViewController.m#L288) to prompt the user for the network credentials
Also, update [this function](https://github.com/project-chip/connectedhomeip/blob/382008c7cf8af44fc59fcb5f078757db62baa800/src/darwin/CHIPTool/CHIPTool/View%20Controllers/QRCode/QRCodeViewController.m#L270) to *not* prompt the user for the network credentials.

### PR DESCRIPTION
**Pull request by andy31415**
#### Problem
Need a Rendezvous implementation in iOS.

 #### Summary of Changes
Prompts the user for ssid/pwd and sends it to the device.

 Fixes #3233

### CODE REVIEW

**Review by saurabhst — APPROVED** [review]

**Review by rwalker-apple — APPROVED** [review]

**Comment by pan-apple** [comment]
This PR is dependent on a fix for this issue: https://github.com/project-chip/connectedhomeip/issues/3177
If it's merged prior to fixing #3177, it'll break the iOS CHIPTool app. Please hold off on merging it for time being.

The changes look good to me. Thanks @andy31415

**Comment by andy31415** [comment]
I added a esp32 woraround (not sure if full 3177 fix, but at least if will not break iOS).
@mspang thos should be mergeable now.

**Comment by pan-apple** [comment]
> I added a esp32 woraround (not sure if full 3177 fix, but at least if will not break iOS).
> @mspang thos should be mergeable now.

Thanks @andy31415, a similar change is needed here: https://github.com/project-chip/connectedhomeip/blob/a663039b40caacc90c7ff1be6a363b2bb818f0b0/examples/temperature-measurement-app/esp32/main/DeviceNetworkProvisioningDelegate.cpp#L25

**Review by pan-apple — APPROVED** [review]

**Comment by andy31415** [comment]
Discussed offline: we need mores tuff in temperature measurement (the wifi code is not yet there) so we will do it as a separate PR.

**Review by mspang — APPROVED** [review]

**Pull request merged**
