### PR TITLE
Add headers required to build CHIP for Android apps.

### PR DESCRIPTION
**Pull request by vidhis88**

### CODE REVIEW

**Review by gerickson — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Comment by pan-apple** [comment]
@vidhis88 are these files part of some existing public Git project? Can we use `repos.conf` or `git submodules` to pull them in?

**Comment by gerickson** [comment]
> @vidhis88 are these files part of some existing public Git project? Can we use `repos.conf` or `git submodules` to pull them in?

The largely entirety of the Android NDK could be pulled in; however, that takes it from a few thousand, to tens to hundreds of thousands of files amounting in many MiB to GiB. In openweave-core, for tracking, we sliced this to a single Android sub-directory/-project that could be easily versioned and tracked. If we wanted to further winnow down the file set, we could manually pare from there.

**Review by woody-apple — CHANGES_REQUESTED** [review]
@pan-apple? You mentioned offline that maybe this should be submodule?

**Comment by pan-apple** [comment]
I think it should be a separate Git project which could be pulled in via repos.conf or submodules. The extra size of Android NDK would manifest as disc space in dev/build machines. But it won't impact the resulting binaries. Also, it'll allow us to test CHIP with different versions/releases of the NDK.

If space is a concern, we can still move these files to a separate Git repo and pull them in from there.

**Comment by sagar-apple** [comment]
Just to add to this…in my opinion, we don't need to check-in Android SDK/NDK pieces right. We should just expect to find it at compile time from a local SDK/NDK install.
We follow a similar model for each of the supported platforms and all the Darwin bits as well. 
Unless I’m missing the point, that should be doable, no?

**Comment by gerickson** [comment]
> Just to add to this…in my opinion, we don't need to check-in Android SDK/NDK pieces. We should just expect to find it at compile time from a local SDK/NDK install.
> We follow a similar model for each of the supported platforms and all the Darwin bits as well.
> Unless I’m missing the point, that should be doable, no?

This is a bit different than the SDK/NDK. What we are providing here is essentially the moral equivalent of a *compat/strdup.c* (for example, from libopt) but, in this case, for getifaddrs. What's being included is an arbitrary **later** snapshot of Android that has this compat functionality, provided to **earlier** versions of the Andriod NDK that do not have this required functionality.

Effectively, CHIP wants a consistent *getifaddrs* API on the appropriate platforms it intends to support, so CHIP is providing this *compat* shim to ensure that compatibility on those platforms.

**Comment by randyrossi** [comment]
It's not clear to me why all these files are being brought in.  It should be assumed (as sagar-apple pointed out) that the build environment has the Android NDK installed.  I don't think all this is required for getifaddrs.  Is it not just a couple files to get that dependency satisfied?

**Comment by gerickson** [comment]
> It's not clear to me why all these files are being brought in. It should be assumed (as sagar-apple pointed out) that the build environment has the Android NDK installed. I don't think all this is required for getifaddrs. Is it not just a couple files to get that dependency satisfied?

@randyrossi, yes, as I noted above, there's a full spectrum of options here. With openweave-core, for the ease of tracking, we historically chose to snapshot on a single .tgz we could curl/wget out of an Android NDK rather than pulling in a whole NDK for backward compatibility. We can, if desired, further prune that .tgz to exclusively those files that satisfy the *getifaddrs* dependency which cuts the file list from four figures to single digits.

**Comment by andy31415** [comment]
> > Just to add to this…in my opinion, we don't need to check-in Android SDK/NDK pieces. We should just expect to find it at compile time from a local SDK/NDK install.
> > We follow a similar model for each of the supported platforms and all the Darwin bits as well.
> > Unless I’m missing the point, that should be doable, no?
> 
> This is a bit different than the SDK/NDK. What we are providing here is essentially the moral equivalent of a _compat/strdup.c_ (for example, from libopt) but, in this case, for getifaddrs. What's being included is an arbitrary **later** snapshot of Android that has this compat functionality, provided to **earlier** versions of the Andriod NDK that do not have this required functionality.
> 
> Effectively, CHIP wants a consistent _getifaddrs_ API on the appropriate platforms it intends to support, so CHIP is providing this _compat_ shim to ensure that compatibility on those platforms.

Is this shim code written by us or part of NDK in future versions? I am thinking that if it is part of a future NDK, we could require it at build time: either you use a new NDK and dont need shims or you use an old one but then a new one should also be available so we copy over the shims at build time.

**Comment by gerickson** [comment]
> > > Just to add to this…in my opinion, we don't need to check-in Android SDK/NDK pieces. We should just expect to find it at compile time from a local SDK/NDK install.
> > > We follow a similar model for each of the supported platforms and all the Darwin bits as well.
> > > Unless I’m missing the point, that should be doable, no?
> > 
> > 
> > This is a bit different than the SDK/NDK. What we are providing here is essentially the moral equivalent of a _compat/strdup.c_ (for example, from libopt) but, in this case, for getifaddrs. What's being included is an arbitrary **later** snapshot of Android that has this compat functionality, provided to **earlier** versions of the Andriod NDK that do not have this required functionality.
> > Effectively, CHIP wants a consistent _getifaddrs_ API on the appropriate platforms it intends to support, so CHIP is providing this _compat_ shim to ensure that compatibility on those platforms.
> 
> Is this shim code written by us or part of NDK in future versions? I am thinking that if it is part of a future NDK, we could require it at build time: either you use a new NDK and dont need shims or you use an old one but then a new one should also be available so we copy over the shims at build time.

I'm open to counter proposals. Landing something that works and then optimizing it is preferable to spending a ton of time on optimizing this up front.

I'd suggest:

1. Land this as-is, do a fast-follow to strip out only those files that are truly needed; long-term follow up with a more optimized approach.
a. Downside: git history is forever polluted with files we don't need.
2. Land this with the files winnowed down to only those files that are truly needed; long-term follow up with a more optimized approach.

**Comment by sagar-apple** [comment]
>I'm open to counter proposals. Landing something that works and then optimizing it is preferable to spending a ton of time on optimizing this up front.
>
> I'd suggest:
>
>Land this as-is, do a fast-follow to strip out only those files that are truly needed; long-term follow up with a more optimized approach.
a. Downside: git history is forever polluted with files we don't need.
Land this with the files winnowed down to only those files that are truly needed; long-term follow up with a more optimized approach.

How do you feel about putting this in a separate repo?

**Comment by pan-apple** [comment]
> > > > Just to add to this…in my opinion, we don't need to check-in Android SDK/NDK pieces. We should just expect to find it at compile time from a local SDK/NDK install.
> > > > We follow a similar model for each of the supported platforms and all the Darwin bits as well.
> > > > Unless I’m missing the point, that should be doable, no?
> > > 
> > > 
> > > This is a bit different than the SDK/NDK. What we are providing here is essentially the moral equivalent of a _compat/strdup.c_ (for example, from libopt) but, in this case, for getifaddrs. What's being included is an arbitrary **later** snapshot of Android that has this compat functionality, provided to **earlier** versions of the Andriod NDK that do not have this required functionality.
> > > Effectively, CHIP wants a consistent _getifaddrs_ API on the appropriate platforms it intends to support, so CHIP is providing this _compat_ shim to ensure that compatibility on those platforms.
> > 
> > 
> > Is this shim code written by us or part of NDK in future versions? I am thinking that if it is part of a future NDK, we could require it at build time: either you use a new NDK and dont need shims or you use an old one but then a new one should also be available so we copy over the shims at build time.
> 
> I'm open to counter proposals. Landing something that works and then optimizing it is preferable to spending a ton of time on optimizing this up front.
> 
> I'd suggest:
> 
> 1. Land this as-is, do a fast-follow to strip out only those files that are truly needed; long-term follow up with a more optimized approach.
>    a. Downside: git history is forever polluted with files we don't need.
> 2. Land this with the files winnowed down to only those files that are truly needed; long-term follow up with a more optimized approach.

Option 2 sounds better to me. Do we have an estimate on how many files we are going to pull in with that option?

**Comment by gerickson** [comment]
> Option 2 sounds better to me. Do we have an estimate on how many files we are going to pull in with that option?

Less than 10 I suspect.

**Comment by woody-apple** [comment]
@vidhis88 Any update here?

**Comment by gerickson** [comment]
As far as I can see, the following three (3) headers would get us there:

- ./third_party/android/platform-libcore/android-platform-libcore/luni/src/main/native/ifaddrs-android.h
- ./third_party/android/platform-libcore/android-platform-libcore/include/LocalArray.h 
- ./third_party/android/platform-libcore/android-platform-libcore/include/ScopedFd.h

**Comment by vidhis88** [comment]
Done. Have brought in only the 3 header files required to build CHIP for Android.
PTAL.

**Review by woody-apple — APPROVED** [review]

**Review by gerickson — APPROVED** [review]

**Review by BroderickCarlin — APPROVED** [review]

**Comment by woody-apple** [comment]
@robszewczyk @jelderton @hawk248 @andy31415 ?

**Review by andy31415 — APPROVED** [review]

**Pull request merged**
