### PR TITLE
[YAML] Generates write attribute methods for non writeable attributes

### PR DESCRIPTION
**Pull request by vivien-apple**
#### Problem

Some tests are trying to write to attributes that are not writeable. 
This PR expose a test interface wrapping the normal cluster interface but with methods for writing to such attributes.

For example `OnOffCluster` is the base class for `OnOffClusterTest`:
 ```
class DLL_EXPORT OnOffClusterTest : public OnOffCluster
{
public:
    OnOffClusterTest() : OnOffCluster() {}
    ~OnOffClusterTest() {}

    CHIP_ERROR WriteAttributeOnOff(Callback::Cancelable * onSuccessCallback, Callback::Cancelable * onFailureCallback, bool value);
    CHIP_ERROR WriteAttributeGlobalSceneControl(Callback::Cancelable * onSuccessCallback, Callback::Cancelable * onFailureCallback,
                                                bool value);
    CHIP_ERROR WriteAttributeFeatureMap(Callback::Cancelable * onSuccessCallback, Callback::Cancelable * onFailureCallback,
                                        uint32_t value);
    CHIP_ERROR WriteAttributeClusterRevision(Callback::Cancelable * onSuccessCallback, Callback::Cancelable * onFailureCallback,
                                             uint16_t value);
};
```

All those methods should results into the controller returning an error when they are received. They are not useful for regular operations, but it is useful to check that the controllee implements those attributes properly.

#### Change overview
* Add wrapper test interfaces
* Remove some of the disabled flags into some yaml tests, notably those trying to write to global attributes
* Update the generated content for tests

#### Testing
 I have enabled more yaml tests.

### CODE REVIEW

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
@vivien-apple The Linux compile failures seem unrelated to your changes... needs a rebase?

**Comment by bzbarsky-apple** [comment]
Yes, needs to be rebased on top of #9560.

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
@saurabhst @andy31415 ?

**Review by saurabhst — APPROVED** [review]

**Review by msandstedt — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
@vivien-apple - conflicts

**Pull request merged**
