### PR TITLE
Compile android in build_examples.py and move android compilation outside of Github CI

### PR DESCRIPTION
**Pull request by andy31415**
#### Problem
Android chiptool example is not built by build_examples.py

#### Change overview
Add android libraries and App support in build_examples.py
Disable Github Action for 'android.yaml' and leave it to run in GCP only

#### Testing
Ran compilation manually in vscode environment
Unit test
GCP CI will run this.

### CODE REVIEW

**Review by msandstedt — APPROVED** [review]

**Comment by andy31415** [comment]
vscode does not seem to allow license accepting. This will only pass after https://github.com/project-chip/connectedhomeip/pull/8864

**Review by austinh0 — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Review by woody-apple — CHANGES_REQUESTED** [review]
Doesn't seem needed post additional jobs? @andy31415 ?

**Comment by andy31415** [comment]
> Doesn't seem needed post additional jobs? @andy31415 ?

The android movement is not needed, I would roll that back once we have more capacity.

The 'ability to compile android' is still useful to have in the build_examples.py as a single entry point.

**Review by woody-apple — APPROVED** [review]

**Review by mspang — CHANGES_REQUESTED** [review]
Please don't use directory listings in build scripts.

**Comment by mspang** [comment]
> Please don't use directory listings in build scripts.

(very few build systems delete files, they only replace them. Doing this invariably leads to broken outputs and confused engineers)

**Comment by andy31415** [comment]
> > Please don't use directory listings in build scripts.
> 
> (very few build systems delete files, they only replace them. Doing this invariably leads to broken outputs and confused engineers)

Updated to not use rsync/path walk equivalents.
Unfortunately the 'copy to source' is still needed for gradle and cound not remove it in this PR. sideffect is that the APK instead of supporting only one platform, would 'support' everything that gets copied into jnilibs.

**Comment by mspang** [comment]
> > > Please don't use directory listings in build scripts.
> > 
> > 
> > (very few build systems delete files, they only replace them. Doing this invariably leads to broken outputs and confused engineers)
> 
> Updated to not use rsync/path walk equivalents.
> Unfortunately the 'copy to source' is still needed for gradle and cound not remove it in this PR. sideffect is that the APK instead of supporting only one platform, would 'support' everything that gets copied into jnilibs.

Ok, that's broken, and is exactly the kind of unfortunate issue that globbing causes.

**Review by mspang — APPROVED** [review]

**Pull request merged**
