### PR TITLE
Fix broken image link in lightning-app README

### PR DESCRIPTION
**Pull request by balloob**
#### Problem
The image link in the introduction of the [lighting-app README](https://github.com/project-chip/connectedhomeip/tree/master/examples/lighting-app/nrf5#introduction) is broken

#### Summary of Changes

Fix the image path

### CODE REVIEW

**Review by mspang — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by rwalker-apple** [comment]
@saurabhst @hawk248 @jelderton ?

**Review by rwalker-apple — APPROVED** [review]

**Comment by mspang** [comment]
@saurabhst

**Review by saurabhst — APPROVED** [review]

**Comment by rwalker-apple** [comment]
@balloob need conflicts resolved

**Comment by balloob** [comment]
This PR has been fixed in #2488 🤷

**Pull request closed without merging**
