### PR TITLE
[shell] Adds a generic, portable shell library.

### PR DESCRIPTION
**Pull request by turon**
- Command line interface (cli) registration, parsing, and dispatch.
- Retargetable streamer object for input / output.
- Stdio-based streamer implementation for posix platforms.
- Default commands: help, echo, version.
- Sample app that adds some more example commands: rand, 

 #### Problem
This shell app framework is designed to be portable, testable, and extensible.

 #### Summary of Changes
Implements an initial cli framework to allow for fast prototyping and functional testing.

fixes #743

### CODE REVIEW

**Review by gerickson — CHANGES_REQUESTED** [review]
This should be using the CHIP argument parsing library that's already in tree.

**Review by jwhui — COMMENTED** [review]
The code in this PR seems very similar (if not identical in some cases) to https://github.com/apache/mynewt-core/tree/master/sys/shell/src 

Should we provide attribution? Possibly include the Apache Mynewt copyright?

**Review by gerickson — COMMENTED** [review]
At a high-level a few additional observations:

1) Why isn't streamer in third_party? If you need examples of how to handle this, check out OWC and the Android code included there.
2) Why isn't the shell in C++, at the very least, namespaced as `namespace chip { ... };`?
3) Why ins't the shell in src/lib? It seems library-ish.
4) All public interfaces need to be Doxygenated.

**Review by gerickson — CHANGES_REQUESTED** [review]
A few minor changes requested: see comments.

**Review by gerickson — APPROVED** [review]

**Review by BroderickCarlin — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Pull request merged**
