### PR TITLE
Added disabling BLE advertisement after Thread is provisioned.

### LINKED ISSUE #3196: Is IsMemberOfFabric() check necessary to consider device as fully provisioned?
#### Problem
I'm trying to disable BLE advertisment after having Thread provisioned and I found that similar functionality is already implemented in the BLEManagerImpl.cpp, but it checks output of the IsFullyProvisioned() method. Inside of this method implementation there are few checks depending on the definitions values (including the one I'm interested in - IsThreadProvisioned) and one mandatory condition IsMemberOfFabric(), which cannot be disabled by any definition. As far as I understand this condition will always fail for the device, which is not a final product and doesn't have many settings filled (like for example Development Kit in sample application). I would like to get an answer on following questions:
* Is having the fabric ID value set necessary to consider device as fully provisioned?
* Is the disabling BLE advertisment functionality important only for final product devices or some additional implementation is needed to support it also on devices not having fabric ID set? 

 #### Proposed Solution
Adding some definition (e.g. CHIP_DEVICE_CONFIG_ENABLE_FABRIC_MEMBER) to make IsMemberOfFabric() check dependent on the definition's value.

### PR DESCRIPTION
**Pull request by kkasperczyk-no**
#### Problem
BLE advertisement after having Thread provisioned should be disabled. Disabling is already implemented using CHIP_DEVICE_CONFIG_CHIPOBLE_DISABLE_ADVERTISING_WHEN_PROVISIONED and isFullyProvisioned()
method, but cannot be used for non-production devices, which are not fabric members.

 #### Summary of Changes
* Added posting kServiceProvisioningChange event after Thread provisioning to handle itin BLEManager's 
OnPlatformEvent and disable advertisement.
* Removed checks of fabric membership and account pairing conditions from isFullyProvisioned method,
as those functionalities are not yet implemented.
* Added Kconfig option for nrfconnect platform to set value of CHIP_DISABLE_CHIPOBLE_ADVERTISING_WHEN_PROVISIONED definition.

 Fixes #3196

### CODE REVIEW

**Review by rwalker-apple — APPROVED** [review]

**Review by mspang — CHANGES_REQUESTED** [review]
Please apply this fix more broadly, not just to nRF Connect.

**Comment by mspang** [comment]
> Please apply this fix more broadly, not just to nRF Connect.

(you don't need to go change other examples, but we don't need to add a new config option that is wrong for everyone except nRF connect)

**Comment by kkasperczyk-no** [comment]
> > Please apply this fix more broadly, not just to nRF Connect.
> 
> (you don't need to go change other examples, but we don't need to add a new config option that is wrong for everyone except nRF connect)

@mspang ok, but could you try to explain more precisely what changes do you expect? I don't quite understand why do you think it is only for nRF connect. The added CHIP_DEVICE_CONFIG_DISABLE_FABRIC_MEMBER define might be set in CHIPDevicePlatformConfig.h file for every platform and in the default state it doesn't change anything from the current version. Kconfig options for nRF connect are created just to avoid editing header file and to make setting more comfortable, so it doesn't have any impact on the other platforms.

**Comment by mspang** [comment]
> > > Please apply this fix more broadly, not just to nRF Connect.
> > 
> > 
> > (you don't need to go change other examples, but we don't need to add a new config option that is wrong for everyone except nRF connect)
> 
> @mspang ok, but could you try to explain more precisely what changes do you expect? I don't quite understand why do you think it is only for nRF connect. The added CHIP_DEVICE_CONFIG_DISABLE_FABRIC_MEMBER define might be set in CHIPDevicePlatformConfig.h file for every platform and in the default state it doesn't change anything from the current version. Kconfig options for nRF connect are created just to avoid editing header file and to make setting more comfortable, so it doesn't have any impact on the other platforms.

I object to the change on the basis that it;s effectively adding

`CHIP_CONFIG_SKIP_BROKEN_CODE`

and sets `CHIP_CONFIG_SKIP_BROKEN_CODE` for nRF Connect. Why leave the broken code for everyone else?

We don't need a `CHIP_CONFIG_SKIP_BROKEN_CODE` in the first place.

Remove the broken code, or replace it with a TODO.

**Comment by mspang** [comment]
> > > > Please apply this fix more broadly, not just to nRF Connect.
> > > 
> > > 
> > > (you don't need to go change other examples, but we don't need to add a new config option that is wrong for everyone except nRF connect)
> > 
> > 
> > @mspang ok, but could you try to explain more precisely what changes do you expect? I don't quite understand why do you think it is only for nRF connect. The added CHIP_DEVICE_CONFIG_DISABLE_FABRIC_MEMBER define might be set in CHIPDevicePlatformConfig.h file for every platform and in the default state it doesn't change anything from the current version. Kconfig options for nRF connect are created just to avoid editing header file and to make setting more comfortable, so it doesn't have any impact on the other platforms.
> 
> I object to the change on the basis that it's effectively adding
> 
> `CHIP_CONFIG_SKIP_BROKEN_CODE`
> 
> and sets `CHIP_CONFIG_SKIP_BROKEN_CODE` for nRF Connect. Why leave the broken code for everyone else?
> 
> We don't need a `CHIP_CONFIG_SKIP_BROKEN_CODE` in the first place.
> 
> Remove the broken code, or replace it with a TODO.

Specifically, I wouldn't add either of these options:
- CHIP_DEVICE_CONFIG_DISABLE_ACCOUNT_PAIRING
- CHIP_DEVICE_CONFIG_DISABLE_FABRIC_MEMBER

We don't have fabric membership (yet). We don't have account pairing. It's not necessary to consult the configuration to know that we don't have those things.

These options add complexity, and will be effectively gotchas for porters.

**Comment by kkasperczyk-no** [comment]
> > > > > Please apply this fix more broadly, not just to nRF Connect.
> > > > 
> > > > 
> > > > (you don't need to go change other examples, but we don't need to add a new config option that is wrong for everyone except nRF connect)
> > > 
> > > 
> > > @mspang ok, but could you try to explain more precisely what changes do you expect? I don't quite understand why do you think it is only for nRF connect. The added CHIP_DEVICE_CONFIG_DISABLE_FABRIC_MEMBER define might be set in CHIPDevicePlatformConfig.h file for every platform and in the default state it doesn't change anything from the current version. Kconfig options for nRF connect are created just to avoid editing header file and to make setting more comfortable, so it doesn't have any impact on the other platforms.
> > 
> > 
> > I object to the change on the basis that it's effectively adding
> > `CHIP_CONFIG_SKIP_BROKEN_CODE`
> > and sets `CHIP_CONFIG_SKIP_BROKEN_CODE` for nRF Connect. Why leave the broken code for everyone else?
> > We don't need a `CHIP_CONFIG_SKIP_BROKEN_CODE` in the first place.
> > Remove the broken code, or replace it with a TODO.
> 
> Specifically, I wouldn't add either of these options:
> 
>     * CHIP_DEVICE_CONFIG_DISABLE_ACCOUNT_PAIRING
> 
>     * CHIP_DEVICE_CONFIG_DISABLE_FABRIC_MEMBER
> 
> 
> We don't have fabric membership (yet). We don't have account pairing. It's not necessary to consult the configuration to know that we don't have those things.
> 
> These options add complexity, and will be effectively gotchas for porters.

Ok, thanks for clarification, now I understand your stand. I just didn't consider it as a broken code, so I didn't want to skip it for other platforms. I fixed it following your instructions.

**Comment by kkasperczyk-no** [comment]
@rwalker-apple could I ask for your re-review, as solution changed after discussions?

**Review by mspang — APPROVED** [review]

**Review by BroderickCarlin — APPROVED** [review]

**Review by rwalker-apple — APPROVED** [review]

**Pull request merged**
