### PR TITLE
[ember] Remove not used call-command-handler.cpp

### PR DESCRIPTION
**Pull request by erjiaqing**
#### Problem
What is being fixed?  Examples:
* After IM landed, some code from ember library for dispatching commands can be removed.

#### Change overview
Remove them

#### Testing
- Code cleanup, no tests

### CODE REVIEW

**Review by Damian-Nordic — APPROVED** [review]

**Review by msandstedt — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]

**Review by msandstedt — APPROVED** [review]

**Review by woody-apple — CHANGES_REQUESTED** [review]
Per the updated template, can you update the PR here?

```
#### Problem
What is being fixed?  Examples:
* Fix crash on startup
* Fixes #12345 12345 Frobnozzle is leaky (exactly like that, so GitHub will auto-close the issue).

#### Change overview
What's in this PR

#### Testing
How was this tested? (at least one bullet point required)
    • If unit tests were added, how do they cover this issue?
    • If unit tests existed, how were they fixed/modified to prevent this in future?
    • If integration tests were added, how do they verify this change?
    • If manually tested, what platforms controller and device platforms were manually tested, and how?
    • If no testing is required, why not?
```

**Review by vivien-apple — APPROVED** [review]
Approving assuming that the `command_handler_cluster_commands` partial will be removed too. It would also have been nice to dig into the methods of `src/app/zap-templates/templates/app/helper.js` and ensure that unused methods are removed too.

**Comment by erjiaqing** [comment]
> Approving assuming that the `command_handler_cluster_commands` partial will be removed too. It would also have been nice to dig into the methods of `src/app/zap-templates/templates/app/helper.js` and ensure that unused methods are removed too.

Removed command_handler_cluster_commands, @woody-apple PR description updated, PTAL.

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
@erjiaqing Sorry, conflict now :(

**Pull request merged**
