### PR TITLE
Decouple transport from session management.

### LINKED ISSUE #1339: Add support for multiple transports
#### Problem
Sessions should support compile-time transport selection, including support for multiple transports.

Even with only UDP, ESP32 and others already have IPv6 and IPv4 UDP (we may eventually only support v6, but having both in parallel makes for a nice testing environment) and eventually we will have BLE and may also have TCP.

 #### Proposed Solution
SessionManager transports should be compile time. Possible solutions would be #ifdeffing, templating, subclassing etc.

Templates would be prefferable (compiletime, typesafe) as long as generated code size is not negatively impacted.

### PR DESCRIPTION
**Pull request by andy31415**
#### Problem
Currently a separate session manager is created for every transport (e.g. ESP creates 2: one for ipv4 and one for ipv6). There should be a central session and encryption management rather than per protocol.

 #### Summary of Changes
Decouples transport from session management.

fixes #1339

### CODE REVIEW

**Review by gerickson — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Review by woody-apple — CHANGES_REQUESTED** [review]
Requesting changes, per @pan-apple 's comment

**Review by gerickson — CHANGES_REQUESTED** [review]
At minimum, this needs a *lot* more documentation.

**Comment by andy31415** [comment]
> @andy31415 this seems to expose a `UDPTransport` directly to the applications. So far, we have been avoiding giving a non-secure endpoint to apps. This will enable apps to bypass security layer (intentionally, or by mistake).

Discussed with @pan-apple offiline - the intent is to balance not asking the app to explicitly create transports while also allowing the app to manage memory (i.e. cannot dynamically allocate transports in Init calls, which would be the easiest approach).

For now, we settled on deriving the session manager and having an object that combines both transports and session manager into one, so that the user never creates the actual transport object.

If we have other ideas in time, we can iterate. I can see it going in 2 separate directions:
   - We start having more transports (tcp, ble) and then we finalize the interface, eventually making the API even clearer
   - Thread completely abstracts away any transport and only IP remains plus chip is requring IPv6, so we may end up only needing UDP and even then only one. In that case, we can start taking out transports to not be as generic.

**Comment by andy31415** [comment]
Created #1424 after CLA check required me to refork the project

**Pull request closed without merging**
