### PR TITLE
Move OnOff cluster to match the spec

### PR DESCRIPTION
**Pull request by andy31415**
Changed type of variable from uint8 to enum8 (since it is an enum according to the spec).

Updated to revision 6 (added OffOnly feature)

https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/7776 matched the usage of Behavior/Behaviour.

### CODE REVIEW

**Review by bzbarsky-apple — DISMISSED** [review]
We should fix the spelling of Behavior in the spec instead.

More to the point: this already got renamed once; we can't easily rename it again.

**Comment by bzbarsky-apple** [comment]
Note also that the spec is already inconsistent: it calls it "Behavior" some places and "Behaviour" in others...

**Comment by ReneJosefsen** [comment]
To add to that, as far as I know, the proposed Vale rule would suggest "behavior".

Kind of agree with Boris here that it might be better to adjust spec in this specific case.

**Comment by ReneJosefsen** [comment]
Almost sounds like we should just do a mass fix of this one and get it aligned on "behavior" 🤷🏼

**Review by jmeg-sfy — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]

**Pull request merged**
