### PR TITLE
Update Pigweed to e2bcc03c

### PR DESCRIPTION
**Pull request by rgoliver**
#### Problem
Need to periodically update Pigweed.

#### Change overview
Update Pigweed repo to e2bcc03c
- The updated Pigweed includes some improvements to the RPC console, including copy-paste support.

#### Testing
Clean bootstrap, built EFR32 RPC example, tested RPCs with console.

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
@rgoliver looks like maybe a real error in:

```
../../examples/lighting-app/linux/third_party/connectedhomeip/third_party/pigweed/repo/pw_stream/socket_stream.cc:35:54: error: 'strerror' is not a member of 'std'
```

Maybe pigweed does not like our C++14 environment?

**Comment by rgoliver** [comment]
> @rgoliver looks like maybe a real error in:
> 
> ```
> ../../examples/lighting-app/linux/third_party/connectedhomeip/third_party/pigweed/repo/pw_stream/socket_stream.cc:35:54: error: 'strerror' is not a member of 'std'
> ```
> 
> Maybe pigweed does not like our C++14 environmen

I think your right, I'll look into it.

**Review by msandstedt — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]

**Review by mspang — APPROVED** [review]

**Comment by rgoliver** [comment]
> > @rgoliver looks like maybe a real error in:
> > ```
> > ../../examples/lighting-app/linux/third_party/connectedhomeip/third_party/pigweed/repo/pw_stream/socket_stream.cc:35:54: error: 'strerror' is not a member of 'std'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Maybe pigweed does not like our C++14 environmen
> 
> I think your right, I'll look into it.

Pushed a fix in Pigweed and updated the CL to include it.

**Comment by rgoliver** [comment]
It seems like the EFR32 build is sometimes missing it's timeout, created a separate PR to fix: https://github.com/project-chip/connectedhomeip/pull/9002

**Review by jelderton — APPROVED** [review]

**Pull request merged**
