### PR TITLE
Add UI for temperature sensor in CHIPTool iOS app

### LINKED ISSUE #2983: Add UI for temperature sensor in CHIPTool iOS app
Add UI for temperature sensor in CHIPTool iOS app

### PR DESCRIPTION
**Pull request by shana-apple**
IMG_0836
Adds UI to control the temperature sensor app.
Add UI to send reporting controls 

Call CHIPTemperatureMeasurement methods (although they currently do not return a value but an NSError pending @vivien-apple 's patch.)

Fixes #2983

### CODE REVIEW

**Comment by andy31415** [comment]
Some code here seems to be shared with wifi-echo example. Could we somehow reuse things instead of duplicating? This would help any refactoring that is expected, since we are still developing some API and message layer bits.

**Comment by shana-apple** [comment]
> Some code here seems to be shared with wifi-echo example. Could we somehow reuse things instead of duplicating? This would help any refactoring that is expected, since we are still developing some API and message layer bits.

Actually the shared code is from the commit of the other PR that this PR is blocked on. This specific UI does not add any shared code. I do have an issue tracking removing duplicated code from the esp32 example apps.

**Comment by vivien-apple** [comment]
@shana-apple Now that #3053 has landed can you update this PR ? That will make it easier to see the relevant diff.

**Comment by andy31415** [comment]
@shana-apple - dependency seems to have been merged, however this PR became stale.

Should we update or drop?

**Comment by shana-apple** [comment]
> @shana-apple - dependency seems to have been merged, however this PR became stale.
> 
> Should we update or drop?

I'll update :)

**Comment by woody-apple** [comment]
ping @shana-apple :)

**Comment by shana-apple** [comment]
@woody-apple was waiting on the callback APIs, which I have adopted in their first version pending @vivien-apple's changes. But this can go in as is

**Review by woody-apple — APPROVED** [review]

**Review by saurabhst — APPROVED** [review]

**Review by mspang — APPROVED** [review]

**Pull request merged**
