### PR TITLE
[tools] update west to 0.9.0

### PR DESCRIPTION
**Pull request by LuDuda**
#### Problem
New nRF Connect SDK requires the newest version of west.

#### Summary of Changes
Bump up west version.

### CODE REVIEW

**Comment by woody-apple** [comment]
@LuDuda - looks like this isn't new, but this looks like a primary file in the tree is platform specific, rather than being in the SDK for that platform. Most of the ESP32 stuff is in the docker/build container for it. Can we do something like this with Zephyr? (Note: I'm concerned about mixing all the platforms into one single SDK, as it inevitably will cause conflicts as other platforms have conflicting requirements).

**Comment by LuDuda** [comment]
@woody-apple I agree with the comment. West was introduced with #3540.

I changed the version from 0.8.0, to 0.9.0 so that pigweed does not override version to one that is not supported, but frankly i don't see a reason of including only west in requirements.txt since our SDK requires much more dependencies anyway (which are present in Docker).

@Damian-Nordic can we then simply remove the west, what was the motivation of adding only west to pigweed?

**Review by saurabhst — APPROVED** [review]

**Comment by woody-apple** [comment]
> @Damian-Nordic can we simply remove the west from the requirements and move responsibility of installing west to the user?
Looking at the container: connectedhomeip/chip-build-nrf-platform:0.4.18

Can we just include the right python environment in there?

**Comment by mspang** [comment]
> @LuDuda - looks like this isn't new, but this looks like a primary file in the tree is platform specific, rather than being in the SDK for that platform. Most of the ESP32 stuff is in the docker/build container for it. Can we do something like this with Zephyr? (Note: I'm concerned about mixing all the platforms into one single SDK, as it inevitably will cause conflicts as other platforms have conflicting requirements).

We have that, too. Both docker and non-docker builds are supported right now for both nRF Connect & ESP-IDF.

I'm not sold on requiring docker for local development. There are some significant problems with that such as USB/BT access from the container, divergence from documented upstream workflows, increased duplication of dependencies, non-native shell environment, VS Code images that are huge and slow to update, etc.

I think an SDK having conflicts with another vendor's SDK is generally just a bug, and one that will need to be addressed in order for us to be able to support your platform in an ordinary [non-dockerized] way. We don't actually have that problem with nRF Connect currently - west is an unintrusive python package that we can provide in the default build environment in case you find it useful (I do).

**Comment by mspang** [comment]
> @woody-apple I agree with the comment. West was introduced with #3540.
> 
> I changed the version from 0.8.0, to 0.9.0 so that pigweed does not override version to one that is not supported, but frankly i don't see a reason of including only west in requirements.txt since our SDK requires much more dependencies anyway (which are present in Docker).
> 
> @Damian-Nordic can we simply remove the west from the requirements and move responsibility of installing west to the user?

Why would we do that? If contributors need to have west 0.9.0 in order to contribute to CHIP, why would prefer to make that their problem rather than just providing it?

Managing dependencies is tedious and a waste of our manpower, we need to keep this automated.

**Review by mspang — APPROVED** [review]

**Comment by woody-apple** [comment]
> > @LuDuda - looks like this isn't new, but this looks like a primary file in the tree is platform specific, rather than being in the SDK for that platform. Most of the ESP32 stuff is in the docker/build container for it. Can we do something like this with Zephyr? (Note: I'm concerned about mixing all the platforms into one single SDK, as it inevitably will cause conflicts as other platforms have conflicting requirements).
> 
> We have that, too. Both docker and non-docker builds are supported right now for both nRF Connect & ESP-IDF.
> 
> I'm not sold on requiring docker for local development. There are some significant problems with that such as USB/BT access from the container, divergence from documented upstream workflows, increased duplication of dependencies, non-native shell environment, VS Code images that are huge and slow to update, etc.


It also allows us to contain development flows and make them reliable without crazy cross dependencies. I understand some people don't like them, and it's fine to have local tools and instructions to develop natively - but let's not pollute the whole tree with the dependencies of **all**of the SDKs/platforms out there.


> I think an SDK having conflicts with another vendor's SDK is generally just a bug, and one that will need to be addressed in order for us to be able to support your platform in an ordinary [non-dockerized] way. 

I think this is incorrect. Relying on all SDK vendors to play nice in the same pool seems unlikely to succeed, not because of Mal-intent, but just from the scope of the problem.

> We don't actually have that problem with nRF Connect currently - west is an unintrusive python package that we can provide in the default build environment in case you find it useful (I do).

I'm fine having a python package being required, but tying this to zephyr seems quite wrong long term wise.


Filed:
https://github.com/project-chip/connectedhomeip/issues/4649

**Review by woody-apple — APPROVED** [review]

**Comment by mspang** [comment]
> > > @LuDuda - looks like this isn't new, but this looks like a primary file in the tree is platform specific, rather than being in the SDK for that platform. Most of the ESP32 stuff is in the docker/build container for it. Can we do something like this with Zephyr? (Note: I'm concerned about mixing all the platforms into one single SDK, as it inevitably will cause conflicts as other platforms have conflicting requirements).
> > 
> > 
> > We have that, too. Both docker and non-docker builds are supported right now for both nRF Connect & ESP-IDF.
> > I'm not sold on requiring docker for local development. There are some significant problems with that such as USB/BT access from the container, divergence from documented upstream workflows, increased duplication of dependencies, non-native shell environment, VS Code images that are huge and slow to update, etc.
> 
> It also allows us to contain development flows and make them reliable without crazy cross dependencies. I understand some people don't like them, and it's fine to have local tools and instructions to develop natively - but let's not pollute the whole tree with the dependencies of **all**of the SDKs/platforms out there.

Not all dependencies, only ones that must compile to submit to this repo. They are dependencies of this project, whether or not those dependencies come in the form of a docker image.

docker is nothing special, it's just a delivery vehicle and contained runtime environment for Linux software. But nRF Connect / Zephyr isn't Linux, and the SDK doesn't even require a particular Linux host to build, or even any Linux host - you can build it on Windows. The kind of tight host OS-coupling that would require something like docker to work isn't there.

We can deliver SDK tools via git, tarballs, pip, or similar, with exact versioning, and achieve the necessary separation by just putting the dependencies in different directories, rather than different virtual filesystems. It's feasible to have robust flows this way and it can be portable to Windows and Mac natively (without resorting to virtual machines).

I'd definitely agree we it would be helpful to separate dependencies by platform and deliver them based on platform interest. This is something that we're missing in the current python requirements file. It's also missing for VS Code even though VS Code uses docker - the VS Code docker image is currently the sum of the other images.

So far, sharing the python environment has worked OK , but if we need to, having a separate virtualenv for different platforms (e.g. nRF Connect & esp-idf) is possible. We had that with esp-idf at the beginning, and it was pretty painful. Separate environments isn't free; it increases the level of complexity that contributors have to work with, and regresses on disk usage & build performance.

> 
> > I think an SDK having conflicts with another vendor's SDK is generally just a bug, and one that will need to be addressed in order for us to be able to support your platform in an ordinary [non-dockerized] way.
> 
> I think this is incorrect. Relying on all SDK vendors to play nice in the same pool seems unlikely to succeed, not because of Mal-intent, but just from the scope of the problem.
> 
> > We don't actually have that problem with nRF Connect currently - west is an unintrusive python package that we can provide in the default build environment in case you find it useful (I do).
> 
> I'm fine having a python package being required, but tying this to zephyr seems quite wrong long term wise.
> 
> Filed:
> #4649

**Pull request merged**
