### PR TITLE
Replace bsdtar with libarchive-tools in Dockerfile

### LINKED ISSUE #1563: Package 'bsdtar' has no installation candidate
#### Problem
Trying to build the image in VSCode with the docker container.

Reading package lists...
Building dependency tree...
Reading state information...
Package bsdtar is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libarchive-tools

E: Package 'bsdtar' has no installation candidate
The command '/bin/sh -c apt-get -fy install git vim emacs sudo     apt-utils dialog zsh     iproute2 procps lsb-release     bash-completion     build-essential cmake cppcheck valgrind     wget curl telnet bsdtar     docker.io' returned a non-zero code: 100
[2175 ms] Command failed: docker build -f /Users/pierred/connectedhomeip/.devcontainer/Dockerfile -t vsc-connectedhomeip-6920a15c44cb93d412e70ead49596b09 --build-arg BUILD_VERSION=0.3.0 /Users/pierred/connectedhomeip/.devcontainer

 #### Proposed Solution
In Dockerfile, replace bsdtar with libarchive-tools:

wget curl telnet libarchive-tools \

### PR DESCRIPTION
**Pull request by markus-becker-tridonic-com**
bsdtar package is unavailable

fixes #1563

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
@markus-becker-tridonic-com - looks good to me. Please sign the CLA so that this can be merged once we gather all required approvals. Thank you for the contribution!

**Comment by markus-becker-tridonic-com** [comment]
> @markus-becker-tridonic-com - looks good to me. Please sign the CLA so that this can be merged once we gather all required approvals. Thank you for the contribution!

working on it with our management.

**Review by turon — APPROVED** [review]
LGTM :+1:

**Review by saurabhst — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Comment by rwalker-apple** [comment]
#1598

**Comment by andy31415** [comment]
@markus-becker-tridonic-com #1598 removed the bsdtar alltogether. Should we keep this around to add libarchive-tools or are those not needed?

**Comment by markus-becker-tridonic-com** [comment]
not required AFAIK.

**Pull request closed without merging**
