### PR TITLE
Dispatch IO thread work to the main dispatch_queue for darwin

### PR DESCRIPTION
**Pull request by vivien-apple**
#### Problem

This PR dispatch the IO thread work to the main dispatch queue introduced in #6207.

#### Summary of Changes
* Call `dispatch_sync(mWorkQueue, ^{..}` into `SysProcess`

### CODE REVIEW

**Comment by vivien-apple** [comment]
I have turned it into a draft at the moment. It works for most things but it end ups into a deadlock when one calls: 
`CHIPDeviceController::Shutdown` is called. This is likely due some some of the other `dispatch_sync` calls from `src/darwin`.

Furthermore I dig a bit more into it and looking at the code of `src/platform/MdnsImpl.cpp` it does not really makes sense to call `dispatch_sync` on it. I will do a separate patch to use `DNSServiceSetDispatchQueue`...

**Comment by vivien-apple** [comment]
> I have turned it into a draft at the moment. It works for most things but it end ups into a deadlock when one calls:
> `CHIPDeviceController::Shutdown` is called. This is likely due some some of the other `dispatch_sync` calls from `src/darwin`.
> 
> Furthermore I dig a bit more into it and looking at the code of `src/platform/MdnsImpl.cpp` it does not really makes sense to call `dispatch_sync` on it. I will do a separate patch to use `DNSServiceSetDispatchQueue`...

I did #6414 for the Mdns callbacks bits.

**Review by jmartinez-silabs — APPROVED** [review]

**Comment by woody-apple** [comment]
Approving given this fixes this: https://github.com/project-chip/connectedhomeip/pull/6427

**Comment by vivien-apple** [comment]
The code has been updated to `dispatch_async` work from the `SystemLayer` and `InetLayer`.

**Comment by vivien-apple** [comment]
There is still something wrong. Keeping it as a draft still..

**Comment by vivien-apple** [comment]
Updated again. No deadlock and no semaphore.

**Review by andy31415 — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Pull request merged**
