### PR TITLE
[nRF Connect] Add github workflow to verify build of the lock example

### LINKED ISSUE #1893: [nRF Connect] Add github workflow to verify build of the lock example
#### Problem
Build status of the nRF Connect SDK platform layer along with the door-lock example is not verified in CI

 #### Proposed Solution
Add github workflow to build the door-lock app for nRF Connect SDK platform

### PR DESCRIPTION
**Pull request by Damian-Nordic**
#### Problem
Build status of the nRF Connect SDK platform layer along with the door-lock example is not verified in CI

 #### Summary of Changes
* Add github workflow to build the door-lock app for nRF Connect SDK platform
* Fix existing build errors (commit shared with #1678)

fixes #1893

### CODE REVIEW

**Review by saurabhst — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Review by BroderickCarlin — APPROVED** [review]

**Comment by Damian-Nordic** [comment]
FYI, I noticed I wasn't quick enough and nRF Connect build fails after today's openthread-related changes :). I'll fix that tomorrow.

**Review by woody-apple — APPROVED** [review]

**Comment by andy31415** [comment]
> FYI, I noticed I wasn't quick enough and nRF Connect build fails after today's openthread-related changes :). I'll fix that tomorrow.

Please ping when this is ready to merge.

**Comment by Damian-Nordic** [comment]
> Please ping when this is ready to merge.

Ok, thanks. Turns out we had to update openthread in our SDK to fix the build and thus we now have to wait till #1907 is merged and the docker image updated until this PR can be merged, too.

**Comment by Damian-Nordic** [comment]
@andy31415 looks like it's ready to merge now

**Pull request merged**
