### PR TITLE
[nrfconnect] Bump nRF Connect SDK version to 1.7.0

### PR DESCRIPTION
**Pull request by Damian-Nordic**
#### Problem
New SDK version has been released.

#### Change overview
Update the supported nRF Connect SDK version in CHIP.
Tune the examples' configuration, for example take advatange of Bluetooth driver optimizations in the new release.
Enable DFU over BLE for nRF5340 board family.

#### Testing
Tested manually on various Nordic boards.

### CODE REVIEW

**Review by msandstedt — APPROVED** [review]

**Review by saurabhst — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
Any opinions on this change making it in for TE6? 

Background: I pushed new docker images and `:latest` now points to tthis new code, but TE6 relies on previous SDK .... so at least on some internal builds a `check ncs` fails on the latest docker images ... rendering te6 branch unbuildable with `build_examples.py`

**Comment by Damian-Nordic** [comment]
In general, I have an impression that when we branch off, we should stick to the fixed Docker image version instead of using `:latest`.

But in this case, it should be fine to cherry-pick the change to the TE6 branch.

**Comment by Damian-Nordic** [comment]
@andreilitvin I added the TE6 cherrypick label as some users also experienced some difficulties with switching between TE6 and master branches due to this change.

**Comment by andy31415** [comment]
Confirmed CP with Chaitanya and performed it.

**Pull request merged**
