### PR TITLE
Adds BOOT button as switch to toggle LED

### PR DESCRIPTION
**Pull request by jmarcelomb**
#### Change overview
This pull request adds the the App Task module and the ESP32 boot button ISR to toggle the LED.

#### Testing
How was this tested? 
* If manually tested, what platforms controller and device platforms were manually tested, and how?
It was tested in a ESP32 C3. It was compiled and tested using the Python REPL. When it was changed in the REPL it changed the LED and when the button was pressed it was reported the LED state change.

### CODE REVIEW

**Comment by bzbarsky-apple** [comment]
@jmmb13 restyle failures...

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
Fast tracking, given this has had enough time, >3 days for review.

**Review by andy31415 — APPROVED** [review]

**Comment by jmmb13** [comment]
Failed the unit tests duo timeout of bootstrap. How can I solve that?

**Comment by bzbarsky-apple** [comment]
> How can I solve that?

I retriggered the test job....

**Pull request merged**
