### PR TITLE
[nrfconnect] Update nRF Connect SDK version

### PR DESCRIPTION
**Pull request by Damian-Nordic**
#### Problem
Currently supported nRF Connect SDK version includes an outdated OpenThread version which is incompatible with the latest OpenThread Border Router - hence the SRP doesn't work correctly.

#### Change overview
1. Update the supported nRF Connect SDK version to the most recent one which includes OpenThread changes
   needed to fix compatibility with the latest OpenThread Border Router (changes in advertising the SRP server).
2. Use Xoroshiro algorithm for random number generation to workaround potential hangs on calling the cryptocell library (to be fixed in the upcoming SDK release).
3. Check the current nRF Connect SDK version also in the CMake configuration phase to early let users know that they should update the version.

The change is necessary to align with other Thread-based platforms and create a single instruction for TE3.

#### Testing
Tested the commissioning flow, DNS-SD/SRP and sending ZCL messages using Python CHIP controller and lighting-app on nRF52840 DK and nRF5340 DK.

### CODE REVIEW

**Review by LuDuda — APPROVED** [review]

**Comment by Damian-Nordic** [comment]
Note: the change includes https://github.com/project-chip/connectedhomeip/pull/7275.

**Review by bzbarsky-apple — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
@Damian-Nordic conflict :(

**Comment by Damian-Nordic** [comment]
@woody-apple resolved

**Review by saurabhst — APPROVED** [review]

**Review by msandstedt — APPROVED** [review]

**Comment by andy31415** [comment]
Cherry-pick creates conflicts for this one - otcli updates.

**Pull request merged**
