### PR TITLE
Revert "[Telink] Move SetRouterPromotion(false) at the end of OpenCom…

### PR DESCRIPTION
**Pull request by woody-apple**
This set of changes was placed in as a workaround for an OpenThread issue in #25517. This has since been fixed. 

Removing this, as at this point it's actually causing pairing failures for some device configurations.

### CODE REVIEW

**Comment by woody-apple** [comment]
@LuDuda FYI

**Comment by woody-apple** [comment]
FYI: OpenThread issue is here: https://github.com/openthread/openthread/pull/7745

**Review by jtung-apple — APPROVED** [review]

**Comment by andy31415** [comment]
@s07641069

**Comment by woody-apple** [comment]
Also note: This spec change was rejected, so this is also technically non spec compliant.

**Review by LuDuda — APPROVED** [review]

**Comment by s07641069** [comment]
> @s07641069 

Next week will do additional test of old issue.

**Pull request merged**
