### PR TITLE
Improve error reporting in chip-tool when the wrong quotes are used.

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
In interactive mode, arguments are delimited by single quotes.  If our argument init fails, and we have arguments that include mismatched double quotes, there's a good chance the wrong quotes were used in the command, and we should log that.

### CODE REVIEW

**Review by mmb-davidsmith — APPROVED** [review]
Thanks Boris. This is helpful for people coming in new.

**Review by vivien-apple — APPROVED** [review]
I guess it may help

**Comment by vivien-apple** [comment]
A small nit, it would have been probably better to have a dedicated method for this task. Something like `DetectMissingDoubleQuotes` just in case we end up adding more methods there.

**Comment by bzbarsky-apple** [comment]
> A small nit, it would have been probably better to have a dedicated method for this task. Something like DetectMissingDoubleQuotes just in case we end up adding more methods there.

Done.

**Review by andy31415 — APPROVED** [review]

**Review by yufengwangca — APPROVED** [review]

**Pull request merged**
