### PR TITLE
Revert "Implement Message Counter Synchronization Protocol part (#4712)"

### PR DESCRIPTION
**Pull request by msandstedt**
This reverts commit a9497739cf6ca41acc98900c0c0ca5c9c4cf7555.

 #### Problem

The NewPairing API changed since CI checks were run against #4712, resulting in build breakages.  This removes the offending code until it can be updated to support the new API.

### CODE REVIEW

**Comment by yufengwangca** [comment]
it seems #4712 need to be updated to the latest API, lets me check the error

**Review by woody-apple — APPROVED** [review]

**Review by LuDuda — APPROVED** [review]
Confirm building issue :+1:

**Comment by yufengwangca** [comment]
It seems #4712 and #4885 are almost merge at the same time which cause the conflict.

I just post the fix https://github.com/project-chip/connectedhomeip/pull/4913

**Comment by yufengwangca** [comment]
> It seems #4712 and #4885 are almost merged at the same time which cause the conflict.
> 
> I just post the fix #4913

**Comment by msandstedt** [comment]
> It seems #4712 and #4885 are almost merge at the same time which cause the conflict.
> 
> I just post the fix #4913

I'm open to #4913 instead.  I think that only fixes 2 of 5 errors though.

**Comment by bzbarsky-apple** [comment]
Looks like #4913 will fix this by actually fixing the code.  I'll give it another 5-10 mins, and if it passes CI merge it, else merge this....

**Comment by yufengwangca** [comment]
https://github.com/project-chip/connectedhomeip/pull/4913 passed. I was wondering how can we capture the last minute conflict automatically in the future.  One solution I can think of is "merge" action could trigger the sanity check against the tip of the branch.

**Pull request closed without merging**
