### PR TITLE
Updated TV example app to align with latest spec changes

### PR DESCRIPTION
**Pull request by lazarkov**
#### Problem
TV example app clusters are not up to date with latest spec changes
https://github.com/CHIP-Specifications/connectedhomeip-spec/releases/tag/0.7-app-cluster-ballot-2

#### Change overview
- Updated the `tv.zap`
- Updated the `controller.zap`
- Renamed Content Launch to Content Launcher cluster per spec
- Added missing command `ChangeStatus` to the Application Basic cluster
- Moved Media clusters to the Media section from General section, by changing their XML

#### Testing
How was this tested? (at least one bullet point required)
- Used the `./gn_build.sh` to verify the building is successful
- Run tv example app locally on Mac OS
` ./out/debug/chip-tv-app `
- Sent pairing command from chip tool to tv example app and got success response
`./out/debug/standalone/chip-tool pairing onnetwork  0 20202021 3840 ::1 11097`
- Sent get tv channel list command from chip-tool to tv example app and got success response
`./out/debug/standalone/chip-tool applicationbasic change-status 3 2`

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]

**Review by chrisdecenzo — APPROVED** [review]
mostly auto-generated files

**Comment by lazarkov** [comment]
Fixed the conflicts.

**Comment by woody-apple** [comment]
@lazarkov 
```
/Users/runner/work/connectedhomeip/connectedhomeip/src/credentials/CHIPCert.h:649:11: note: did you mean 'chipCertBufLen'?
1990
 * @param chipCertBufLen[out]  The length of the converted certificates.
1991
          ^~~~~~~~~~~~~~~~~~~
1992
          chipCertBufLen
1993
```

Still looks like real failures...

**Comment by lazarkov** [comment]
Fixed the conflicts. #again

**Comment by lazarkov** [comment]
> @lazarkov
> 
> ```
> /Users/runner/work/connectedhomeip/connectedhomeip/src/credentials/CHIPCert.h:649:11: note: did you mean 'chipCertBufLen'?
> 1990
>  * @param chipCertBufLen[out]  The length of the converted certificates.
> 1991
>           ^~~~~~~~~~~~~~~~~~~
> 1992
>           chipCertBufLen
> 1993
> ```
> 
> Still looks like real failures...

I've fixed this as well, but it's due to wrong named code docs. They are not matching the coded params.

**Comment by lazarkov** [comment]
Fixed the conflicts.

**Review by msandstedt — APPROVED** [review]

**Pull request merged**
