### PR TITLE
Allow piecemeal migration from EmberAf non-enum-class enums to cluster-objects enum classes

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
#### Problem
No real plausible path to migrate to strongly typed cluster-objects enums.

#### Change overview
Introduce such a path, so it can be done on a per-enum basis, not for everything at once (which seems hard to imagine happening).

#### Testing
Tree compiles.  No expected behavior changes.

### CODE REVIEW

**Review by yunhanw-google — APPROVED** [review]

**Comment by mrjerryjohns** [comment]
What is the expectation for clusters to move over for TE7.5? Do we need to document the process by which they would do so? Is this work tracked somewhere?

**Comment by bzbarsky-apple** [comment]
> What is the expectation for clusters to move over for TE7.5? Do we need to document the process by which they would do so? Is this work tracked somewhere?

I don't think this is work that needs to be done for TE7.5.  It's mostly SDK-internal cleanup, except insofar as we expose cluster-objects as our API surface.  The enum values are not changing; just how you name them and whether they are enum class.

The process to move an enum over is to remove its entry from the list, then fix all the compile errors.  It's not documented, really, but I could add a comment in the JS.

This is not tracked anywhere, because we are not really tracking "code cleanliness/sanity" work, as far as I can tell.

**Review by mrjerryjohns — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
@carol-apple @pan-apple @msandstedt @saurabhst @LuDuda @Damian-Nordic @jepenven-silabs @jmartinez-silabs Please review?

**Review by jmartinez-silabs — APPROVED** [review]

**Review by jmeg-sfy — APPROVED** [review]

**Review by vivien-apple — APPROVED** [review]
That sounds pretty reasonable. I like the patch that allows what is currently in use, but do not let us introduce new weakly typed enum.

**Pull request merged**
