### PR TITLE
Use DataModelHandler from examples/common/chip-app-server in ESP32 wi…

### PR DESCRIPTION
**Pull request by vivien-apple**
…fi-echo demo app instead of its own copy

 #### Problem
 DataModelHandler.cpp is duplicated between `examples/wifi-echo` and `examples/common` 

 #### Summary of Changes
 * Removes the version that lives in `examples/wifi-echo`

### CODE REVIEW

**Review by saurabhst — APPROVED** [review]

**Review by BroderickCarlin — APPROVED** [review]

**Comment by vivien-apple** [comment]
I pushed an update to remove the duplicate instance from `examples/temperature-measurement-app` too.

**Review by rwalker-apple — APPROVED** [review]

**Comment by rwalker-apple** [comment]
would be nice to see files that only depend on CHIP from examples/common moved into CHIP...

**Comment by vivien-apple** [comment]
> would be nice to see files that only depend on CHIP from examples/common moved into CHIP...

Agreed 100%. But until we can reach this point, I'm happy to remove some duplicates.

To move this file down into the stack for example, we first need to merge `EchoServer` from `wifi-echo` and the `Server` from `examples/common`. I believe the only thing that prevent us to do that at the moment is the fact that the 'EchoServer' is doing specific things for doing an echo while 'Server' does not.  Having #3020 would remove the specific `echo` code and let us merge those files, and then the Server/HandleDataModel down into the stack.

That's the underlying reason why I was bugging you with #3020 a few weeks ago ;)

**Comment by vivien-apple** [comment]
force-pushing again since `restyled` has not runned for some reasons...

**Review by andy31415 — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
I had been avoiding doing this to avoid having the unnecessary `Server.cpp` compiled into wifi-echo....  But yes, it doesn't seem to hurt anything to do that.  It's just lucky to not have name collisions with `EchoServer`.

I'm also not sure what the setup is now with both Rendezvous impls compiled in....

**Pull request merged**
