### PR TITLE
Integrated examples/common/chip-app-server to the CHIP src/app/server.

### PR DESCRIPTION
**Pull request by kkasperczyk-no**
#### Problem
examples/common/chip-app-server should is not a part of CHIP,
while is needed by most of CHIP devices and is based on CHIP API.

 #### Summary of Changes
* Created src/app/server directory to store all CHIP accessory device specific files.
* Moved examples/common/chip-app-server content to the src/app/server.
* Removed examples/common/chip-app-server.
* Aligned READMEs to describe directories content.

 Fixes #2927

### CODE REVIEW

**Review by rwalker-apple — DISMISSED** [review]
this is great!  but would you put these in src/app instead of src/accessory?

**Comment by kkasperczyk-no** [comment]
> this is great! but would you put these in src/app instead of src/accessory?

I mentioned why I did this in #2927, but we can also discuss it here. The thing is that to compile chip-app-server files, we need to have compiled src/transport and src/platform modules. Src/platform needs in indirect way through the src/lib to have src/app compiled before it can be compiled, so at the moment it's kind of impossible to compile src/platform before src/app. And that means that we can't compile files from chip-app-server inside of the src/app module. That's why I proposed creating new src/accessory module. Maybe it's not the only solution, but src modules already have some dependencies and chip-app-server was previously compiled after CHIP library, so now it's not so easy to find out how to integrate it in some of the existing modules to fulfill all dependencies.

**Comment by mspang** [comment]
> > this is great! but would you put these in src/app instead of src/accessory?
> 
> I mentioned why I did this in #2927, but we can also discuss it here. The thing is that to compile chip-app-server files, we need to have compiled src/transport and src/platform modules. Src/platform needs in indirect way through the src/lib to have src/app compiled before it can be compiled, so at the moment it's kind of impossible to compile src/platform before src/app. And that means that we can't compile files from chip-app-server inside of the src/app module. That's why I proposed creating new src/accessory module. Maybe it's not the only solution, but src modules already have some dependencies and chip-app-server was previously compiled after CHIP library, so now it's not so easy to find out how to integrate it in some of the existing modules to fulfill all dependencies.

You could potentially put it at `src/app/server` or `src/app:server` while we think about how to untangle this.

**Comment by kkasperczyk-no** [comment]
> > > this is great! but would you put these in src/app instead of src/accessory?
> > 
> > 
> > I mentioned why I did this in #2927, but we can also discuss it here. The thing is that to compile chip-app-server files, we need to have compiled src/transport and src/platform modules. Src/platform needs in indirect way through the src/lib to have src/app compiled before it can be compiled, so at the moment it's kind of impossible to compile src/platform before src/app. And that means that we can't compile files from chip-app-server inside of the src/app module. That's why I proposed creating new src/accessory module. Maybe it's not the only solution, but src modules already have some dependencies and chip-app-server was previously compiled after CHIP library, so now it's not so easy to find out how to integrate it in some of the existing modules to fulfill all dependencies.
> 
> You could potentially put it at `src/app/server` or `src/app:server` while we think about how to untangle this.

@mspang that was first thing I tried, but I realized `src/app/server` files can't be compiled in the `app` static library, because of the reason described above. I have two ideas how to implement your suggestion:

- do it similar to the `src/app/util`, so place files in the `src/app/server` and add it to sources in the external BUILD.gn (e.g. in lighting-common etc), but actually those server files still won't be integrated in the CHIP library, but only located in `src/app`.

- place files in the `src/app/server` and create separate library from `app`, like `app-server`, having all dependencies set to the way to allow building it after src/platform and src/transport. That would allow integrating server to the CHIP lib.

I think that second option would be better, as using compiled CHIP library in the external projects would be much easier (currently I'm interested in doing it) without need of adding some sources manually outside of the library.

Another question is why would you like to place rendezvous server in the src/app, which contains data model specific files? I'm not claiming it is wrong, but it's quite confusing for me, as I can't find relation between those two. Is it some kind of intermediate step before finding out final shape?

**Comment by mspang** [comment]
> > > > this is great! but would you put these in src/app instead of src/accessory?
> > > 
> > > 
> > > I mentioned why I did this in #2927, but we can also discuss it here. The thing is that to compile chip-app-server files, we need to have compiled src/transport and src/platform modules. Src/platform needs in indirect way through the src/lib to have src/app compiled before it can be compiled, so at the moment it's kind of impossible to compile src/platform before src/app. And that means that we can't compile files from chip-app-server inside of the src/app module. That's why I proposed creating new src/accessory module. Maybe it's not the only solution, but src modules already have some dependencies and chip-app-server was previously compiled after CHIP library, so now it's not so easy to find out how to integrate it in some of the existing modules to fulfill all dependencies.
> > 
> > 
> > You could potentially put it at `src/app/server` or `src/app:server` while we think about how to untangle this.
> 
> @mspang that was first thing I tried, but I realized `src/app/server` files can't be compiled in the `app` static library, because of the reason described above. I have two ideas how to implement your suggestion:
> 
> * do it similar to the `src/app/util`, so place files in the `src/app/server` and add it to sources in the external BUILD.gn (e.g. in lighting-common etc), but actually those server files still won't be integrated in the CHIP library, but only located in `src/app`.
> * place files in the `src/app/server` and create separate library from `app`, like `app-server`, having all dependencies set to the way to allow building it after src/platform and src/transport. That would allow integrating server to the CHIP lib.
> 
> I think that second option would be better, as using compiled CHIP library in the external projects would be much easier (currently I'm interested in doing it) without need of adding some sources manually outside of the library.
> 
> Another question is why would you like to place rendezvous server in the src/app, which contains data model specific files? I'm not claiming it is wrong, but it's quite confusing for me, as I can't find relation between those two. Is it some kind of intermediate step before finding out final shape?

To be honest neither app nor accessory make very much sense to me.


> > > > this is great! but would you put these in src/app instead of src/accessory?
> > > 
> > > 
> > > I mentioned why I did this in #2927, but we can also discuss it here. The thing is that to compile chip-app-server files, we need to have compiled src/transport and src/platform modules. Src/platform needs in indirect way through the src/lib to have src/app compiled before it can be compiled, so at the moment it's kind of impossible to compile src/platform before src/app. And that means that we can't compile files from chip-app-server inside of the src/app module. That's why I proposed creating new src/accessory module. Maybe it's not the only solution, but src modules already have some dependencies and chip-app-server was previously compiled after CHIP library, so now it's not so easy to find out how to integrate it in some of the existing modules to fulfill all dependencies.
> > 
> > 
> > You could potentially put it at `src/app/server` or `src/app:server` while we think about how to untangle this.
> 
> @mspang that was first thing I tried, but I realized `src/app/server` files can't be compiled in the `app` static library, because of the reason described above. I have two ideas how to implement your suggestion:
> 
> * do it similar to the `src/app/util`, so place files in the `src/app/server` and add it to sources in the external BUILD.gn (e.g. in lighting-common etc), but actually those server files still won't be integrated in the CHIP library, but only located in `src/app`.
> * place files in the `src/app/server` and create separate library from `app`, like `app-server`, having all dependencies set to the way to allow building it after src/platform and src/transport. That would allow integrating server to the CHIP lib.
> 
> I think that second option would be better, as using compiled CHIP library in the external projects would be much easier (currently I'm interested in doing it) without need of adding some sources manually outside of the library.
> 
> Another question is why would you like to place rendezvous server in the src/app, which contains data model specific files? I'm not claiming it is wrong, but it's quite confusing for me, as I can't find relation between those two. Is it some kind of intermediate step before finding out final shape?

Not sure. App server would seem to belong with "app", but I'd agree the naming of the app directory seems a bit off. Maybe that should be called data_model.

I think CHIP speak for "accessory" is just "device".

**Comment by mspang** [comment]
> > > > > this is great! but would you put these in src/app instead of src/accessory?
> > > > 
> > > > 
> > > > I mentioned why I did this in #2927, but we can also discuss it here. The thing is that to compile chip-app-server files, we need to have compiled src/transport and src/platform modules. Src/platform needs in indirect way through the src/lib to have src/app compiled before it can be compiled, so at the moment it's kind of impossible to compile src/platform before src/app. And that means that we can't compile files from chip-app-server inside of the src/app module. That's why I proposed creating new src/accessory module. Maybe it's not the only solution, but src modules already have some dependencies and chip-app-server was previously compiled after CHIP library, so now it's not so easy to find out how to integrate it in some of the existing modules to fulfill all dependencies.
> > > 
> > > 
> > > You could potentially put it at `src/app/server` or `src/app:server` while we think about how to untangle this.
> > 
> > 
> > @mspang that was first thing I tried, but I realized `src/app/server` files can't be compiled in the `app` static library, because of the reason described above. I have two ideas how to implement your suggestion:
> > 
> > * do it similar to the `src/app/util`, so place files in the `src/app/server` and add it to sources in the external BUILD.gn (e.g. in lighting-common etc), but actually those server files still won't be integrated in the CHIP library, but only located in `src/app`.
> > * place files in the `src/app/server` and create separate library from `app`, like `app-server`, having all dependencies set to the way to allow building it after src/platform and src/transport. That would allow integrating server to the CHIP lib.
> > 
> > I think that second option would be better, as using compiled CHIP library in the external projects would be much easier (currently I'm interested in doing it) without need of adding some sources manually outside of the library.
> > Another question is why would you like to place rendezvous server in the src/app, which contains data model specific files? I'm not claiming it is wrong, but it's quite confusing for me, as I can't find relation between those two. Is it some kind of intermediate step before finding out final shape?
> 
> To be honest neither app nor accessory make very much sense to me.
> 
> > > > > this is great! but would you put these in src/app instead of src/accessory?
> > > > 
> > > > 
> > > > I mentioned why I did this in #2927, but we can also discuss it here. The thing is that to compile chip-app-server files, we need to have compiled src/transport and src/platform modules. Src/platform needs in indirect way through the src/lib to have src/app compiled before it can be compiled, so at the moment it's kind of impossible to compile src/platform before src/app. And that means that we can't compile files from chip-app-server inside of the src/app module. That's why I proposed creating new src/accessory module. Maybe it's not the only solution, but src modules already have some dependencies and chip-app-server was previously compiled after CHIP library, so now it's not so easy to find out how to integrate it in some of the existing modules to fulfill all dependencies.
> > > 
> > > 
> > > You could potentially put it at `src/app/server` or `src/app:server` while we think about how to untangle this.
> > 
> > 
> > @mspang that was first thing I tried, but I realized `src/app/server` files can't be compiled in the `app` static library, because of the reason described above. I have two ideas how to implement your suggestion:

Sure, I meant put it in its own library, but in the app/server/BUILD.gn or app/BUILD.gn build files. There is no restriction that there be only one library per build file. It's more tidy to do that, but not required.

> > 
> > * do it similar to the `src/app/util`, so place files in the `src/app/server` and add it to sources in the external BUILD.gn (e.g. in lighting-common etc), but actually those server files still won't be integrated in the CHIP library, but only located in `src/app`.
> > * place files in the `src/app/server` and create separate library from `app`, like `app-server`, having all dependencies set to the way to allow building it after src/platform and src/transport. That would allow integrating server to the CHIP lib.
> > 
> > I think that second option would be better, as using compiled CHIP library in the external projects would be much easier (currently I'm interested in doing it) without need of adding some sources manually outside of the library.
> > Another question is why would you like to place rendezvous server in the src/app, which contains data model specific files? I'm not claiming it is wrong, but it's quite confusing for me, as I can't find relation between those two. Is it some kind of intermediate step before finding out final shape?
> 
> Not sure. App server would seem to belong with "app", but I'd agree the naming of the app directory seems a bit off. Maybe that should be called data_model.
> 
> I think CHIP speak for "accessory" is just "device".
> > > > this is great! but would you put these in src/app instead of src/accessory?
> > > 
> > > 
> > > I mentioned why I did this in #2927, but we can also discuss it here. The thing is that to compile chip-app-server files, we need to have compiled src/transport and src/platform modules. Src/platform needs in indirect way through the src/lib to have src/app compiled before it can be compiled, so at the moment it's kind of impossible to compile src/platform before src/app. And that means that we can't compile files from chip-app-server inside of the src/app module. That's why I proposed creating new src/accessory module. Maybe it's not the only solution, but src modules already have some dependencies and chip-app-server was previously compiled after CHIP library, so now it's not so easy to find out how to integrate it in some of the existing modules to fulfill all dependencies.
> > 
> > 
> > You could potentially put it at `src/app/server` or `src/app:server` while we think about how to untangle this.
> 
> @mspang that was first thing I tried, but I realized `src/app/server` files can't be compiled in the `app` static library, because of the reason described above. I have two ideas how to implement your suggestion:
> 
> * do it similar to the `src/app/util`, so place files in the `src/app/server` and add it to sources in the external BUILD.gn (e.g. in lighting-common etc), but actually those server files still won't be integrated in the CHIP library, but only located in `src/app`.
> * place files in the `src/app/server` and create separate library from `app`, like `app-server`, having all dependencies set to the way to allow building it after src/platform and src/transport. That would allow integrating server to the CHIP lib.
> 
> I think that second option would be better, as using compiled CHIP library in the external projects would be much easier (currently I'm interested in doing it) without need of adding some sources manually outside of the library.
> 
> Another question is why would you like to place rendezvous server in the src/app, which contains data model specific files? I'm not claiming it is wrong, but it's quite confusing for me, as I can't find relation between those two. Is it some kind of intermediate step before finding out final shape?

**Comment by kkasperczyk-no** [comment]
@mspang @rwalker-apple thanks for comments and remarks. I aligned structure according to your suggestions.

**Review by mspang — APPROVED** [review]

**Comment by kkasperczyk-no** [comment]
@rwalker-apple could you re-review it to verify if requested changes were done? If there is nothing else to fix I would be glad to push this PR forward.

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
@saurabhst @jelderton @BroderickCarlin @chrisdecenzo @hawk248 could you please take a look?

**Review by saurabhst — APPROVED** [review]

**Pull request merged**
