### PR TITLE
[Ameba] Update yaml file to 0.5.43

### PR DESCRIPTION
**Pull request by pankore**
#### Problem
Update yaml file to adapt the docker update in #13406

#### Change overview
Update yaml file to 0.5.43

#### Testing
N.A.

### CODE REVIEW

**Comment by pankore** [comment]
The prerequisite of this PR is #13409.

**Review by Damian-Nordic — APPROVED** [review]

**Comment by andy31415** [comment]
@pankore - how about updating all of them?
Also building the image will take a few hours (starting it now).

**Comment by pankore** [comment]
> @pankore - how about updating all of them? Also building the image will take a few hours (starting it now).

Hi @andy31415,
I have seen that PR#13406 has been merged. Now I rebase the PR to let the auto-check re-run. Thanks!

**Comment by pankore** [comment]
> @pankore - how about updating all of them? Also building the image will take a few hours (starting it now).

Hi @andy31415 ,
I have also updated the yaml files for other platforms with the reference of your pervious commit #13055 . Please help to review, thanks!

**Review by andy31415 — APPROVED** [review]

**Pull request merged**
