### PR TITLE
Update builds to docker version 65

### PR DESCRIPTION
**Pull request by s07641069**
Change overview

- Update builds to latest docker version

https://github.com/project-chip/connectedhomeip/pull/33637

### CODE REVIEW

**Comment by andy31415** [comment]
@s07641069 I think we have to update this gradually ... we switched docker to 24.04 and still need to fix some individual failures.

**Review by Damian-Nordic — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by s07641069** [comment]
> @s07641069 I think we have to update this gradually ... we switched docker to 24.04 and still need to fix some individual failures.

We can use this PR as parent to check and switch all build into latest version as soon as all vendors will apply their fixes.
Will be good to mention all vendor responsible persons which builds fails with ubuntu 24.04.

**Comment by s07641069** [comment]
https://github.com/project-chip/connectedhomeip/pull/33637

**Comment by jlatusek** [comment]
Hi, I've created a similar PR #33979. I had a problem with the current versions of the python packages so I've updated them. As far as I know, EFR32 still needs updates in the SDK to make it work on images newer than 54.

**Comment by kkasperczyk-no** [comment]
I think that updating docker version to 65 will result in pulling in the new nRF Connect SDK 2.7.0 version of nrfconnect platform. This change requires a big number of alignments in nrfconnect platform and examples. I pushed a PR that addresses it and updates all workflows to use docker version 65: https://github.com/project-chip/connectedhomeip/pull/34403. @s07641069 do you think we could agree to close this PR and pull docker version update in my PR?

**Comment by kkasperczyk-no** [comment]
> I think that updating docker version to 65 will result in pulling in the new nRF Connect SDK 2.7.0 version of nrfconnect platform. This change requires a big number of alignments in nrfconnect platform and examples. I pushed a PR that addresses it and updates all workflows to use docker version 65: #34403. @s07641069 do you think we could agree to close this PR and pull docker version update in my PR?

After having a talk with @andy31415 it seems it will be much more reasonable to update only docker version on nrf platform in my PR, so I will remove updating docker image for other platforms.

**Pull request closed without merging**
