### PR TITLE
Added Command Line Tool to Generate Attestation Certificates

### PR DESCRIPTION
**Pull request by emargolis**
#### Problem
CHIP SDK is missing command line tool to generate attestation certificate for testing or could be for real use purposes. 

#### Change overview
Tool is added

#### Testing
Validated tool outputs using openssl commands.

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
@saurabhst @msandstedt @mspang @jmartinez-silabs @Damian-Nordic ?

**Comment by woody-apple** [comment]
@mspang @Damian-Nordic @LuDuda @jmartinez-silabs ?

**Review by jmartinez-silabs — APPROVED** [review]

**Review by msandstedt — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by andy31415** [comment]
@emargolis - merge conflicts

**Comment by emargolis** [comment]
> @emargolis - merge conflicts

conflict resolved

**Pull request merged**
