### PR TITLE
[ASR] add more examples

### PR DESCRIPTION
**Pull request by tx2rx**
1、add examples

   - all-clusters-app
   - all-clusters-minimal-app
   - light-switch-app
   - lock-app
   - ota-requestor-app
   - temperature-measurement-app
   - bridge-app
   - thermostat

all examples test pass by chip-tool

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

**Comment by tx2rx** [comment]
@bzbarsky-apple hi, can you help review this PR? Thanks a lot :)

**Comment by bzbarsky-apple** [comment]
@tx2rx Given the size of this PR, I don't expect a single chunk of time big enough to review this in the next several days.

**Comment by tx2rx** [comment]
rebase and squash to master

**Comment by tx2rx** [comment]
@bzbarsky-apple @andy31415 hi,  can this PR be merged ?  It needs another review ...

**Comment by bzbarsky-apple** [comment]
@tx2rx Do you have access to the CSA Slack?  If so, I would strongly suggest asking some folks there for reviews....

**Pull request merged**
