### PR TITLE
bump efr32_sdk submodule

### PR DESCRIPTION
**Pull request by jmartinez-silabs**
#### Problem
no issue is been fix

#### Change overview
bump efr32_sdk submodule commit hash for wifi boards support and ground work for a silabs matter wifi platform.

#### Testing
no change for existing/used code

### CODE REVIEW

**Comment by jmartinez-silabs** [comment]
I labelled as fast track as it is only a EFR32 submodule bump

**Review by yufengwangca — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Review by saurabhst — APPROVED** [review]

**Comment by woody-apple** [comment]
> I labelled as fast track as it is only a EFR32 submodule bump

@jmartinez-silabs Please don't label things fast track, this is meant to be only applied by @andy31415 and myself. We're trying to keep up as best as we can!

**Comment by jmartinez-silabs** [comment]
@woody-apple all right

**Pull request merged**
