### PR TITLE
Modified YAML Test Cases - Jan 17th

### PR DESCRIPTION
**Pull request by ghost**
Modified following testcases
1. TC-BI-1.1
2. TC-BOOL-1.1
3.  TC-CC-1.1
4.  TC-DIAGTH-1.1
5.  TC-EMR-1.1
6.  TC-LVL-1.1
7.  TC-ILL-1.1
8.  TC-TM-1.1
9.  TC-TSUIC-1.1
10.  TC-TSTAT-1.1
11.  TC-WNCV-1.1
12.  TC-MC-1.1
13.  TC-OCC-1.1
14.  TC-OO-1.1
15.  TC-PCC-1.1
16.  TC-PRS-1.1
17.  TC-RH-1.1
18.  TC-FLW-1.1
19.  TC-SWDIAG-3.1

Executed all YAML test scripts, attached logs for reference:
[Execution_log.zip](https://github.com/project-chip/connectedhomeip/files/7880721/Execution_log.zip)

### CODE REVIEW

**Review by bzbarsky-apple — APPROVED** [review]

**Review by jmeg-sfy — APPROVED** [review]

**Comment by woody-apple** [comment]
Fast tracking, given adding tests.

**Review by andy31415 — APPROVED** [review]

**Pull request merged**
