### PR TITLE
Fix circular dependency issue when linking message layer

### PR DESCRIPTION
**Pull request by yufengwangca**
Problem
PlatformLayer is responsible for initilizing the CHIP stack, it should depend on the libcore which is the dependent of most of CHIP Core stack components. 

Summary of Changes
We should remove platform from libcore as the dependent to make message layer link.

### CODE REVIEW

**Review by saurabhst — APPROVED** [review]

**Comment by mspang** [comment]
Note there's still a cycle between src/lib/support and src/platform:

```
src/lib/support/PersistedCounter.cpp:#include <platform/PersistedStorage.h>
src/lib/support/PersistedCounter.h:#include <platform/PersistedStorage.h>
src/lib/support/tests/TestPersistedCounter.cpp:#include <platform/PersistedStorage.h>
src/lib/support/tests/TestPersistedStorageImplementation.cpp:#include <platform/PersistedStorage.h>
```

**Review by mspang — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by rwalker-apple** [comment]
is this just a gn circularity, or is there an underlying core->platform dep?

**Comment by mspang** [comment]
> is this just a gn circularity, or is there an underlying core->platform dep?

Judging by the broken build, it looks like there is one issue to untangle (although indirect).

**Comment by rwalker-apple** [comment]
@yufengwangca are you working on the CI failure?

**Comment by yufengwangca** [comment]
> @yufengwangca are you working on the CI failure?

Yes, need to setup the nRF environment to repo this error

**Pull request merged**
