### PR TITLE
Power Source cluster support

### PR DESCRIPTION
**Pull request by fessehaeve**
#### Problem
* Current SDK lacks support for Power Source cluster 
 
#### Change overview
Added SDK support for Power Source cluster 

#### Testing
* This was tested on Nordic nrf52840dk kit

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]

**Review by jmeg-sfy — APPROVED** [review]

**Review by jmeg-sfy — CHANGES_REQUESTED** [review]
Please look at comments regarding CamelCase

**Review by jmeg-sfy — APPROVED** [review]

**Review by msandstedt — APPROVED** [review]

**Review by jelderton — APPROVED** [review]

**Comment by fessehaeve** [comment]
@bzbarsky-apple thanks for the hint. But the cluster is on endpoint 1. Further investigation revealed that the tests are generated based on controller-clusters.zap and some of the attributes from there are not enabled in all-clusters-app.zap. Who would have known how to deal with this ...

**Comment by andy31415** [comment]
Merged into TE6, with manual zap regen. ZAP seemed somewhat flaky in changing some CHIPClusters.h/cpp

**Pull request merged**
