### PR TITLE
Change storage type of Ethernet diagnostic attributes to RAM

### PR DESCRIPTION
**Pull request by yufengwangca**
#### Problem
What is being fixed?  Examples:

With https://github.com/project-chip/connectedhomeip/pull/9667 merged, Ethernet diagnostic attributes are retrieved by a new mechanism with SDK-internal logic run to produce attribute values, in TLV form only.

So now, we have three mechanisms to manage the attributes
1. Internal attributes handled by the "global" attribute store directly.
2. External attributes handled by application-level callback.
3. Platform attributes handled by SDK-internal logic run to produce attribute values, 

For Ethernet diagnostic attributes, we should not mark them as 'external' any more since they are no longer handled by the application-level callback.

#### Change overview
Change storage type of Ethernet diagnostic attributes to RAM

#### Testing
How was this tested? (at least one bullet point required)
* ./chip-tool ethernetnetworkdiagnostics read packet-rx-count 0

```
[1632260951.084713][454525:454532] CHIP:EM: Removed CHIP MessageCounter:00000000 from RetransTable
[1632260951.084721][454525:454532] CHIP:DMG: ReportData =
[1632260951.084725][454525:454532] CHIP:DMG: {
[1632260951.084728][454525:454532] CHIP:DMG: 	AttributeDataList =
[1632260951.084732][454525:454532] CHIP:DMG: 	[
[1632260951.084735][454525:454532] CHIP:DMG: 		AttributeDataElement =
[1632260951.084738][454525:454532] CHIP:DMG: 		{
[1632260951.084742][454525:454532] CHIP:DMG: 			AttributePath =
[1632260951.084748][454525:454532] CHIP:DMG: 			{
[1632260951.084753][454525:454532] CHIP:DMG: 				NodeId = 0xd0aa20ffc084c442,
[1632260951.084758][454525:454532] CHIP:DMG: 				EndpointId = 0x0,
[1632260951.084762][454525:454532] CHIP:DMG: 				ClusterId = 0x37,
[1632260951.084767][454525:454532] CHIP:DMG: 				FieldTag = 0x2,
[1632260951.084771][454525:454532] CHIP:DMG: 			}
[1632260951.084776][454525:454532] CHIP:DMG: 				
[1632260951.084781][454525:454532] CHIP:DMG: 			Data = 0, 
[1632260951.084785][454525:454532] CHIP:DMG: 			DataElementVersion = 0x0,
[1632260951.084789][454525:454532] CHIP:DMG: 		},
[1632260951.084795][454525:454532] CHIP:DMG: 		
[1632260951.084798][454525:454532] CHIP:DMG: 	],
[1632260951.084804][454525:454532] CHIP:DMG: 	
[1632260951.084807][454525:454532] CHIP:DMG: }
[1632260951.084825][454525:454532] CHIP:ZCL: ReadAttributesResponse:
[1632260951.084828][454525:454532] CHIP:ZCL:   ClusterId: 0x0000_0037
[1632260951.084832][454525:454532] CHIP:ZCL:   attributeId: 0x0000_0002
[1632260951.084836][454525:454532] CHIP:ZCL:   status: Success                (0x0000)
[1632260951.084839][454525:454532] CHIP:ZCL:   attribute TLV Type: 0x04
```

### CODE REVIEW

**Comment by bzbarsky-apple** [comment]
The thing is, we don't want to allocate (unused) RAM storage for these things.

What we really need is either a new storage type or some way of forcing things to have the "external" storage type (possibly without triggering the app callbacks).

@vivien-apple @tecimovic

**Review by yunhanw-google — APPROVED** [review]

**Comment by yufengwangca** [comment]
> The thing is, we don't want to allocate (unused) RAM storage for these things.
> 
> What we really need is either a new storage type or some way of forcing things to have the "external" storage type (possibly without triggering the app callbacks).
> 
> @vivien-apple @tecimovic

Yes. we need a new type for this. If we set 'External' type here and the SDK-internal logic fail to produce attribute values, then we will call into the external attribute machinery, but we don't have application callback logic implemented for those attributes now.

**Comment by mrjerryjohns** [comment]
> What we really need is either a new storage type or some way of forcing things to have the "external" storage type (possibly without triggering the app callbacks).

Why wouldn't marking it as 'external' be sufficient? That would ensure no storage gets allocated, while at the same time, due to the way the logic is structured in `ReadSingleClusterData`, the attribute accessor would get called first (if one is registered) _before_ it decides to hit up `emberAfReadAttribute` and ultimately, route the request to the application.

**Comment by yufengwangca** [comment]
> > What we really need is either a new storage type or some way of forcing things to have the "external" storage type (possibly without triggering the app callbacks).
> 
> Why wouldn't marking it as 'external' be sufficient? That would ensure no storage gets allocated, while at the same time, due to the way the logic is structured in `ReadSingleClusterData`, the attribute accessor would get called first (if one is registered) _before_ it decides to hit up `emberAfReadAttribute` and ultimately, prevent routing the request to the application.

Because we expect the application implement the external logic to handle those attributes if we mark them as 'external', if attribute accessor fail to produce values for those attributes, then it will call into the external attribute machinery.

**Review by msandstedt — APPROVED** [review]

**Comment by mrjerryjohns** [comment]
> Because we expect the application implement the external logic to handle those attributes if we mark them as 'external', if attribute accessor fail to produce values for those attributes, then it will call into the external attribute machinery.

I always thought 'external' as viewed relative to the Ember stack itself, i.e that the data is coming from outside the global store. In that regard, whether that is provided by the application itself, or from a logic-backed cluster handler feels like they are synonymous with the definition.

From an ordering standpoint, it also feels nice - if there isn't a registered over-ride, it falls back to asking it from the application.

**Comment by yufengwangca** [comment]
> > Because we expect the application implement the external logic to handle those attributes if we mark them as 'external', if attribute accessor fail to produce values for those attributes, then it will call into the external attribute machinery.
> 
> I always thought 'external' as viewed relative to the Ember stack itself, i.e that the data is coming from outside the global store. In that regard, whether that is provided by the application itself, or from a logic-backed cluster handler feels like they are synonymous with the definition.
> 
> From an ordering standpoint, it also feels nice - if there isn't a registered over-ride, it falls back to asking it from the application.

We don't have any implementation on the application side to handle those attributes. it either hit stub or crash in this case. If mark them as RAM, at least it will be handled by the attribute store in case of fall back.

**Review by saurabhst — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
@yufengwangca FYI Conflicts

**Review by jmartinez-silabs — APPROVED** [review]

**Pull request merged**
