### PR TITLE
chip-cert: Added Support for All Possible SubjectDN Attributes in Operational Certificates

### PR DESCRIPTION
**Pull request by emargolis**
#### Problem
Need to support all possible attributes in the subjectDN of the operational certificates.

#### Change overview
Implemented.

#### Testing
Manual tool testing

### CODE REVIEW

**Comment by andy31415** [comment]
@emargolis what is the 1.0 justification here? What is the sideffect of NOT having this in the 1.0 branch?

**Review by andy31415 — DISMISSED** [review]
Request changes: need 1.0 justification.

All PRs created after Aug 22 should be linked to an issue (except hotfixes or trivial changes) and provide solid justification for 1.0 (fixing crash, fixing a blocker issue, etc.).

The bar is higher than "safe change" or "good/useful change".

**Comment by emargolis** [comment]
> Request changes: need 1.0 justification.
> 
> All PRs created after Aug 22 should be linked to an issue (except hotfixes or trivial changes) and provide solid justification for 1.0 (fixing crash, fixing a blocker issue, etc.).
> 
> The bar is higher than "safe change" or "good/useful change".

This tool enhancement will enable new test vectors creation, which were not possible before. As a result we will be able to increate code test coverage by testing new operational certificates with new fields (RDNs) in the SubjectDN.

**Review by tcarmelveilleux — APPROVED** [review]

**Comment by emargolis** [comment]
Added ticket: #22442

**Comment by andy31415** [comment]
Accepting for 1.0: this changes `/tools` which is equivalent to examples: this does not change core SDK behavior.

**Review by turon — APPROVED** [review]

**Pull request merged**
