### PR TITLE
[3rd-party] update openthread and ot-br-posix

### PR DESCRIPTION
**Pull request by wgtdkp**
#### Summary of Changes
Update OpenThread and ot-br-posix to include the latest SRP and Thread Duckhorn Border Router changes.

Depends-On:
- [x] https://github.com/openthread/openthread/issues/6218 (the issue is fixed within CHIP).
- [x] https://github.com/openthread/ot-br-posix/pull/713

### CODE REVIEW

**Comment by mspang** [comment]
Need to figure out the EFR32 update. @jepenven-silabs

**Comment by mspang** [comment]
Also, build is broken on VerifyOrDie conflict.

**Comment by wgtdkp** [comment]
> Need to figure out the EFR32 update. @jepenven-silabs

@mspang @jepenven-silabs I submitted the issue in openthread: https://github.com/openthread/openthread/issues/6218

**Comment by wgtdkp** [comment]
> Also, build is broken on VerifyOrDie conflict.

I created https://github.com/openthread/ot-br-posix/pull/713 for this.

**Comment by jepenven-silabs** [comment]
> > Need to figure out the EFR32 update. @jepenven-silabs
> 
> @mspang @jepenven-silabs I submitted the issue in openthread: [openthread/openthread#6218](https://github.com/openthread/openthread/issues/6218)

The failure on the CHIP side of things seems to be related to some headers files missing inside the sdk gn config. I'll take a quick look at this later today.

**Comment by jepenven-silabs** [comment]
@wgtdkp @mspang Currently working on a fix for the EFR32. I'll post the commit once the fix is complete so you can cherry-pick it on top of your branch

**Comment by wgtdkp** [comment]
> @wgtdkp @mspang Currently working on a fix for the EFR32. I'll post the commit once the fix is complete so you can cherry-pick it on top of your branch

:+1:  Thanks!

**Comment by jepenven-silabs** [comment]
@wgtdkp https://github.com/project-chip/connectedhomeip/commit/a1b9b524d3b39fc3607359af7d2d524ed5a21872

This should do the trick.

**Comment by wgtdkp** [comment]
@jepenven-silabs Thanks! It works.

@mspang Seems the CI failures have been resolved, PTAL.

(There are several commits, please do squash merge.

**Review by andy31415 — APPROVED** [review]

**Review by jwhui — APPROVED** [review]

**Review by jelderton — APPROVED** [review]

**Review by saurabhst — APPROVED** [review]

**Review by mspang — APPROVED** [review]

**Pull request merged**
