### PR TITLE
[Ameba] SoftwareDiagnostic update

### PR DESCRIPTION
**Pull request by pankore**
#### Problem
Ameba doesn't have method to get thread metrics and reset watermark

#### Change overview
Implement GetThreadMetrics and ResetWatermarks

#### Testing
`./chip-tool softwarediagnostics read thread-metrics 1234 0`
`./chip-tool softwarediagnostics reset-watermarks 1234 0`

### CODE REVIEW

**Review by bzbarsky-apple — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]
Fast tracking platform changes

**Comment by woody-apple** [comment]
@pankore FYI, real build failure here in Ameba platform

**Comment by pankore** [comment]
I have updated ThreadMetrics to fix build error. This PR also requires #19223 to be merged for build to be successful.

**Review by woody-apple — APPROVED** [review]
Fast tracking platform changes.

**Pull request merged**
