### PR TITLE
Remove ExchangeMessageDispatch.h (Fix #6456)

### LINKED ISSUE #6456: Sort out interaction of exchange lifetime and CRMP in the SDK
#### Problem
Consider a simple message flow:
1. A sends an unsolicited message to B
2. B sends a response to A, does not expect any more messages

At what point does B call `Close` on the `ExchangeContext` that it created to handle the unsolicited message?  My expectation as an API consumer would be "right after calling SendMessage" with the response.  But if we do that, CRMP will fail to retransmit that message, because CRMP retransmit needs state from the exchange context's delegate, but `Close` nulls the delegate out.

If we don't null the delegate out during `Close` but just use it when we need to retransmit, it's not clear how a consumer is supposed to know when it's safe to deallocate the delegate.

We could have some sort of delegate callback that indicates "All message sends have completed (do not need ack, got ack, or timed out waiting for ack)" or something like that, which would then allow the consumer to close the exchange.  But this is slightly annoying to use and exposes transport-level state to the higher-level API...

 #### Proposed Solution
Don't have a good one yet, see above.  Ideally we would not need anything caller-allocated to do CRMP retransmits and could just `Close` right after `SendMessage` and move on, but that's not the setup we seem to have.

@pan-apple @tcarmelveilleux @yufengwangca @erjiaqing @kghost @mrjerryjohns @vivien-apple

### PR DESCRIPTION
**Pull request by kghost**
#### Problem
 #6456 

 #### Summary of Changes
 * ExchangeManager and ExchangeContext will handle both secure and unsecure messages
 * ExchangeContext will be explicitly flagged as secure or unsecure
    * Secure context will only handle secure messages
    * Unsecure context will only handle Unsecure messages
 * Add a simple Variant (src/lib/support/Variant.h)
    * Secure and unsecure context have diffent member fields. Use Variant to manage these fields.
 * Use RAII for ExchangeContext contruction and destruction.
    * Use contructor and destructor of ExchangeContext instread of Alloc/Free.
 * Remove ExchangeMessageDispatch base class and all its derived classes
    * Remove ApplicationExchangeDispatch
    * Remove SessionEstablishmentExchangeDispatch

 #### Test
 Verified using linux echo-requester/responder and im-requester/responder
 Verified using linux chip-tool pairing

 #### Future works:
 * Enforce secure or unsecure exchange creation by solicited message handler. (Add secure or unsecure flag in the handler)
 * Enable CRMP for unsecure exchanges.

 Fixes #6456

### CODE REVIEW

**Comment by kghost** [comment]
This PR is written on top of #5389, because there are several conflicts. It contains all changes from #5389, please focus on the  last patch.

**Comment by gerickson** [comment]
Regarding:

> Use RAII for ExchangeContext construction and destruction.
> Use constructor and destructor of ExchangeContext instead of Alloc/Free.

Is there ever a case when the allocation of an ExchangeContext can fail?

If so, RAII and con/destructors for initialization are not a good pattern to follow (and is generally why you don't see that pattern prevalently in constrained-system C++ code such as CHIP). In C++, the problem of "constructors have no return value" is addressed by exceptions as an error handling mechanism. As you are likely aware, one of the challenges of C++ in an embedded environment is that when you ban the use of exceptions due to code size increases, then the only way to handle initialization failures is to use explicit error status-returning initializers.

**Comment by kghost** [comment]
@gerickson 

There can be 3 steps to create a object:

 1. Alloc memory from the pool: Can fail, when it fails, the pool will return a nullptr.
 2. Call constructor: Never fails, just initialize all its members.
 3. Call `Init`: Can fail, an return the corresponding error code.

Most of CHIP codes defer the initialization codes which can fail into the `Init` function, leaving the constructor only to initialize all its member fiends, and it never fails.

> Is there ever a case when the allocation of an ExchangeContext can fail?
Fortunately, `ExchangeContext::Alloc` never fails, so it doesn't require `ExchangeContext::Init` function.

BTW, The pool will handle object allocation, ensures that constructor and destructor are calls corresponding to the lifecycle of the object. Currently code managing the lifecycle of ExchangeContext using manually calls to `Alloc`, `Free` along with `Reset`, also call its constructor to try to reset all its fields, but it is error probe.

There are several benefits of using constructor and destructor.
 1. They are called from pool manage, or else `Alloc` and `Free` is manually called, you may forget to call them
 2. Constructor and destructor calls are propagated to all member fields. otherwise you may forget to call them when adding a new field.

**Comment by woody-apple** [comment]
@bzbarsky-apple ?

**Comment by kghost** [comment]
Make it draft until message counter PR has been merged.

**Comment by yufengwangca** [comment]
> @gerickson
> 
> There can be 3 steps to create a object:
> 
> 1. Alloc memory from the pool: Can fail, when it fails, the pool will return a nullptr.
> 2. Call constructor: Never fails, just initialize all its members.
> 3. Call `Init`: Can fail, an return the corresponding error code.
> 
> Most of CHIP codes defer the initialization codes which can fail into the `Init` function, leaving the constructor only to initialize all its member fiends, and it never fails.
> 
> > Is there ever a case when the allocation of an ExchangeContext can fail?
> 
> Fortunately, `ExchangeContext::Alloc` never fails, so it doesn't require `ExchangeContext::Init` function.
> 
> BTW, The pool will handle object allocation, ensures that constructor and destructor are calls corresponding to the lifecycle of the object. Currently code managing the lifecycle of ExchangeContext using manually calls to `Alloc`, `Free` along with `Reset`, also call its constructor to try to reset all its fields, but it is error probe.
> 
> There are several benefits of using constructor and destructor.
> 
> 1. They are called from pool manage, or else `Alloc` and `Free` is manually called, you may forget to call them
> 2. Constructor and destructor calls are propagated to all member fields. otherwise you may forget to call them when adding a new field.

The exchange is designed to represent "conversation" defined in the protocol, which allows devices to have multiple "conversations" simultaneously.  Currently, each protocol needs to define the begin message and end message of each conversation, and the protocol need to create the exchange to start the conversation and close the exchange at the end of the conversation.

Only the protocol has the knowledge of the semantics of each conversation, how the exchange life-cycle can be managed via RAII pattern? How do you know when the conversation start and end?

**Comment by bzbarsky-apple** [comment]
Is the switch to BitMapObjectPool actually semantically meaninful here, or is it just a somewhat unrelated change?  I ask because:

1. It makes it harder to see what the actual behavior changes are.
2. It's not clear to me that we want to make that change, since there's some overhead to a BitMapObjectPool and we don't really need its out-of-band tracking of which objects are live, because we can use internal ExchangeContext state to track that.

**Comment by kghost** [comment]
> Is the switch to BitMapObjectPool actually semantically meaninful here, or is it just a somewhat unrelated change? I ask because:

Yes it is meaninful. It depends on the constructor and destructor of the `ExchangeContext` to correctly adjust the session variant type, and destroy the session variant. Without using `BitMapObjectPool`, constructor and destructor of the `ExchangeContext` object is not called at all. So, we need to manually calling the constructor and destructor on the `SessionVariant`, it is very error prone.

**Comment by kghost** [comment]
@yufengwangca 

> how the exchange life-cycle can be managed via RAII pattern? How do you know when the conversation start and end?

When the conversation starts, an `ExchangeContext` is allocated from the pool, and it constructor will be call via the pool manager.

When the conversation ends, the `ExchangeContext` is returned to the pool, and it destructor will be call via the pool manager.

**Comment by yufengwangca** [comment]
> @yufengwangca
> 
> > how the exchange life-cycle can be managed via RAII pattern? How do you know when the conversation start and end?
> 
> When the conversation starts, an `ExchangeContext` is allocated from the pool, and it constructor will be call via the pool manager.
> 
> When the conversation ends, the `ExchangeContext` is returned to the pool, and it destructor will be call via the pool manager.

So the ExchangeContext is still allocated/returned from/to pool by the upper layer protocol who has the knowledge of start and end of the conversation, right? If so, will current allocation and closing of an ExchangeContext can fail?

**Comment by kghost** [comment]
> So the ExchangeContext is still allocated/returned from/to pool by the upper layer protocol who has the knowledge of start and end of the conversation, right? If so, will current allocation and closing of an ExchangeContext can fail?

@yufengwangca It will fail when the pool is full.

I have a separate PR about this #6808, we can continue the discussion on that PR.

**Comment by yufengwangca** [comment]
> > So the ExchangeContext is still allocated/returned from/to pool by the upper layer protocol who has the knowledge of start and end of the conversation, right? If so, will current allocation and closing of an ExchangeContext can fail?
> 
> @yufengwangca It will fail when the pool is full.
> 
> I have a separate PR about this #6808, we can continue the discussion on that PR.

I think the allocation will fail when pool is full is by design. I don't think we have blocked by this design until now. Lets continue the discussion in #6808

**Comment by yufengwangca** [comment]
> > > So the ExchangeContext is still allocated/returned from/to pool by the upper layer protocol who has the knowledge of start and end of the conversation, right? If so, will current allocation and closing of an ExchangeContext can fail?
> > 
> > 
> > @yufengwangca It will fail when the pool is full.
> > I have a separate PR about this #6808, we can continue the discussion on that PR.
> 
> I think the allocation will fail when pool is full is by design. I don't think we have blocked by this design until now. Lets continue the discussion in #6808

I don't think we can address allocation fail on pool full case by switching to BitMapObjectPool since the pool also have the maximum size restriction.

BitMapObjectPool<ExchangeContext, CHIP_CONFIG_MAX_EXCHANGE_CONTEXTS> mContextPool;

**Comment by kghost** [comment]
> don't think we can address allocation fail on pool full case by switching to BitMapObjectPool since the pool also have the maximum size restriction.

The way we handle allocation failure is exactly same as before.

Before: ExchangeManager::AllocContext returns nullptr on failure.
Now: mContextPool.CreateObject returns nullptr on failure.

I can't sense any difference.

**Review by woody-apple — CHANGES_REQUESTED** [review]
A few comments here.

• CRMP already works over unencrypted communications, per @pan-apple 's change a while back to refactor this. Please sync him up on having this better fit into the tree.
• What feature is this enabling?
• Allowing for unencrypted exchanges sounds like a security problem and we shouldn't supply API for this
• We should be focusing on not exposing more of the inner guts of Exchange/IM to the upper layers - in fact the opposite

**Comment by kghost** [comment]
> • CRMP already works over unencrypted communications, per @pan-apple 's change a while back to refactor this. Please sync him up on having this better fit into the tree.

https://github.com/project-chip/connectedhomeip/blob/f72e0b7abfaa1cc4fc0b83c4ae4832887ff359ca/src/messaging/ExchangeMessageDispatch.h#L50-L54

`ResendMessage` is not implemented. Here `SessionEstablishmentExchangeDispatch` derived from the `ExchangeMessageDispatch` doesn't override `ResendMessage`
https://github.com/project-chip/connectedhomeip/blob/f72e0b7abfaa1cc4fc0b83c4ae4832887ff359ca/src/protocols/secure_channel/SessionEstablishmentExchangeDispatch.h#L32

Without `ResendMessage` being implemented. I can hardly believe that CRMP works.

> • What feature is this enabling?

This PR fixes issue #6456.

> • Allowing for unencrypted exchanges sounds like a security problem and we shouldn't supply API for this

In fact we are already doing this, the PASE/CASE session is running over exchanges, and they are unsecure,

So I'm marking it unsecure explicitly, Introducing a separate API to create an unsecure exchange, trying to avoid possible security problems, in this PR.

> • We should be focusing on not exposing more of the inner guts of Exchange/IM to the upper layers - in fact the opposite

All API introduced by this PR won't exposing to upper layers, they will be hidden behind channel API. The way to create a exchange is responsibility of channel API.

**Review by woody-apple — CHANGES_REQUESTED** [review]
Pending approval and security review from @pan-apple

**Review by woody-apple — CHANGES_REQUESTED** [review]
Per the updated template, can you update the PR here?

```
#### Problem
What is being fixed?  Examples:
* Fix crash on startup
* Fixes #12345 12345 Frobnozzle is leaky (exactly like that, so GitHub will auto-close the issue).

#### Change overview
What's in this PR

#### Testing
How was this tested? (at least one bullet point required)
    • If unit tests were added, how do they cover this issue?
    • If unit tests existed, how were they fixed/modified to prevent this in future?
    • If integration tests were added, how do they verify this change?
    • If manually tested, what platforms controller and device platforms were manually tested, and how?
    • If no testing is required, why not?
```

**Pull request closed without merging**
