### PR TITLE
use docker image 0.5.73

### PR DESCRIPTION
**Pull request by pankore**
#### Problem
Move forward to the latest docker images.

#### Change overview
Change all images to 0.5.73

#### Testing
CI will validate this

### CODE REVIEW

**Comment by pankore** [comment]
Hi @andy31415 ,
This PR requires an update on dockerhub.
Current chip-build/version => 0.5.73
Current Dockerhub TAG => 0.5.72
Thanks!

**Review by bzbarsky-apple — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]

**Pull request merged**
