### PR TITLE
[linux] Linux Device Layer needs ConfigurationMgr. (#738)

### PR DESCRIPTION
**Pull request by yufengwangca**
#### Summary of Changes
* Add initial Linux platform DeviceLayer ConfigurationMgr module.

* Implement ChipStorage using inipp for both durable and ephemeral settings.

* Add unit tests

fixes #<#738>

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Review by rwalker-apple — CHANGES_REQUESTED** [review]
looks like inipp is coming in the way nlbuild-autotools is coming in?  I think it should only be in repos.conf, right?

**Review by rwalker-apple — CHANGES_REQUESTED** [review]
I think there are 2 too-many layers, which has introduced some copy-paste bugs, e.g. it looks like reading a string value goes down the binaryblob path?

**Review by turon — CHANGES_REQUESTED** [review]
Still reviewing, but posting this initial set of comments.

**Review by turon — APPROVED** [review]
Looks good.  Thanks @yufengwangca!

**Review by BroderickCarlin — APPROVED** [review]

**Pull request merged**
