### PR TITLE
Enable setting command timeout for chip-tool pairing open-commissioning-window.

### LINKED ISSUE #14490: TE7.5 [TC-MF-1.x] open-commissioning-window command timeout on slow device
branch: TE7.5
device: ESP32 WiFi LED light blub (ESP32 single core 80MHz)

problem:
While testing TC-MF-1.x test case, open-commissioning-window command will timeout and fail.
```
[1643005362.786203][3333:3333] CHIP:-: ../../examples/chip-tool/commands/common/CHIPCommand.cpp:232: CHIP Error 0x00000032: Timeout at ../../examples/chip-tool/commands/common/CHIPCommand.cpp:59
[1643005362.786302][3333:3333] CHIP:TOO: Run command failure: ../../examples/chip-tool/commands/common/CHIPCommand.cpp:232: CHIP Error 0x00000032: Timeout
[1643005362.792823][3333:3333] CHIP:SPT: VerifyOrDie failure at ../../src/inet/InetLayer.h:121: sEndPointPool.Allocated() == 0
Aborted (core dumped)
```

I run the device at 80MHz single core. If ESP32 is run at 240MHz, the command will pass.

It looks similar to issue [#13929](https://github.com/project-chip/connectedhomeip/issues/13929)

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
Specific changes:

* Allow doing --timeout to set the command timeout.
* Bump the default timeout from 5 seconds to 20 seconds.
* Document the arguments to open-commissioning-window, especially
  because some of them are a bit cryptic.
* Fix an issue with the command field description setup, where for
  some arg types the "flags" had to be specified when specifying the
  description.  The flags are internal bookkeeping, and should never
  be specified explicitly by normal AddArgument callers, so
  Command.h/Command.cpp were modified to put the flags last again,
  after the (optional) description.

Fixes https://github.com/project-chip/connectedhomeip/issues/14490

#### Problem
See above.

#### Change overview
See above.

#### Testing
Made sure that the command does not time out until 20 seconds pass by default and that I can use `--timeout 2` to make it time out after 2 seconds.

### CODE REVIEW

**Comment by bzbarsky-apple** [comment]
Oh, and the new help output looks something like this:
```
[1652938749834] [4874:51150541] CHIP: [TOO] InitArgs: Wrong arguments number: 0 instead of 5
Usage:
  ./out/debug/standalone/chip-tool pairing open-commissioning-window node-id option window-timeout iteration discriminator [--paa-trust-store-path] [--commissioner-name] [--commissioner-nodeid] [--trace_file] [--trace_log] [--ble-adapter] [--timeout]

node-id:
  Node to send command to.

option:
  1 to use Enhanced Commissioning Method.
  0 to use Basic Commissioning Method.

window-timeout:
  Time, in seconds, before the commissioning window closes.

iteration:
  Number of PBKDF iterations to use to derive the verifier.  Ignored if 'option' is 0.

discriminator:
  Discriminator to use for advertising.  Ignored if 'option' is 0.

[--timeout]:
  Time, in seconds, before this command is considered to have timed out.
```

**Review by arkq — APPROVED** [review]
Maybe for completeness you could add help messages for arguments defined in CHIPCommand?

**Comment by bzbarsky-apple** [comment]
> Maybe for completeness you could add help messages for arguments defined in CHIPCommand?

Yes, but as a separate PR.

**Review by tcarmelveilleux — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
https://github.com/project-chip/connectedhomeip/pull/18612 documents the args in CHIPCommand that I understand.

**Pull request merged**
