### PR TITLE
[Telink] Handle building Lighting app with RPC feature by CI

### PR DESCRIPTION
**Pull request by TelinkKrystian**
Enable RPC feature for Telink builder.
Handle building Lighting App with RPC feature by CI

### CODE REVIEW

**Review by bzbarsky-apple — APPROVED** [review]

**Review by s07641069 — APPROVED** [review]

**Review by andy31415 — CHANGES_REQUESTED** [review]
Please add a rpc variant instead. See how other platforms support this:

https://github.com/project-chip/connectedhomeip/blob/master/scripts/build/build/targets.py#L271

https://github.com/project-chip/connectedhomeip/blob/master/scripts/build/build/targets.py#L183

https://github.com/project-chip/connectedhomeip/blob/master/scripts/build/builders/nrf.py#L184

**Comment by TelinkKrystian** [comment]
> Please add a rpc variant instead. See how other platforms support this:
> 
> https://github.com/project-chip/connectedhomeip/blob/master/scripts/build/build/targets.py#L271
> 
> https://github.com/project-chip/connectedhomeip/blob/master/scripts/build/build/targets.py#L183
> 
> https://github.com/project-chip/connectedhomeip/blob/master/scripts/build/builders/nrf.py#L184

You mean to remove all my changes and replace them with rpc variant you mentioned or add this variant to my changes too?

**Comment by TelinkKrystian** [comment]
> Please add a rpc variant instead. See how other platforms support this:
> 
> https://github.com/project-chip/connectedhomeip/blob/master/scripts/build/build/targets.py#L271
> 
> https://github.com/project-chip/connectedhomeip/blob/master/scripts/build/build/targets.py#L183
> 
> https://github.com/project-chip/connectedhomeip/blob/master/scripts/build/builders/nrf.py#L184

@andy31415 Sorry I don't catch this solution for NRF. It seems like (self.enable_rpcs) is redundant feature in this case, since in examples-nrfconnect.yaml file -D flags are included into executed path. What is more NRF uses its own script to build apps (scripts/examples/nrfconnect_example.sh) that allows passing -D flags, in contrast to general build script (build_examples.py), that I'm using and which doesn't allow to do so.

I would expect, that when I'm using enable_rpcs feature I should pass "--enable_rpcs" in executed path, like "./scripts/build/build_examples.py --target 'telink-tlsr9518adk80d-light' --enable_rpcs build" and this make the RPC build, am I right or I mixed something? Should I create own telink_example.sh script for it?

**Comment by TelinkKrystian** [comment]
Moved to rpc_build branch. Another PR will be created.

**Pull request closed without merging**
