### PR TITLE
EVSE update zap xml to reflect latest spec (ChargingTargetStruct) and removed 2 attributes

### LINKED ISSUE #30997: [1.3] Complete EVSE delegate implementation
### Reproduction steps

This issue is to track the outstanding work in the EVSE Delegate

Implemented in PR: https://github.com/project-chip/connectedhomeip/pull/30999/
- [x] - [x] Add Callback to HW to inform it of MaxCurrentLimit
- [x] Add Callback to HW to inform it of Change in Charging Enabled / Disable state

Implemented in PR: https://github.com/project-chip/connectedhomeip/pull/31200/
- [x] Add PluggedIn / Unplugged Events
- [x] Add EnergyTransferStarted Event
- [x] Add EnergyTransferStopped Event
- [x] Add Session support (Requires EEM cluster integration)
- [x] Add Persisted Storage support for some attributes

- [x] Add Timer expiry checking to automatically stop charging/discharging

Implemented in PR 
https://github.com/project-chip/connectedhomeip/pull/31406

-[x] Update XML for EVSE to support new charging preference structures

To do:
- [ ] Implement Persisting of helper data which allows session duration, session energy charged etc to be computed

- [ ] Add Charging Preferences Support (GetTargets/SetTargets/ClearTargets) (see PR https://github.com/project-chip/connectedhomeip/pull/31407)
- [ ] Add RPC handlers into example energy management app

### Bug prevalence

N/A

### GitHub hash of the SDK that was being used

N/A

### Platform

core

### Platform Version(s)

1.3

### Type

Core SDK Performance Improvement

### Anything else?

This is an issue to track EVSE implementation for 1.3

### PR DESCRIPTION
**Pull request by jamesharrow**
This PR changes the energy-evse-cluster.xml to reflect the latest EnergyEVSE.adoc

- https://github.com/CHIP-Specifications/connectedhomeip-spec/commit/43d5437f427fa0befff1c58980e9137055e9c1b9

Updated energy-evse-cluster.xml to use latest EnergyEVSE.adoc which removes numberOfWeeklyTargets, numberOfDailyTargets, and adds new ChargingTargetScheduleStruct in Get/Set/Clear Target commands.

Also changes to CamelCase in DayOfWeekForSequence (was a lowercase `for`)

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
Checked against my copy of the spec, .matter file updates looked right.

**Comment by andy31415** [comment]
Fast track - no review in 5 days and I validated the changes match the spec.

**Comment by michaelleecowan** [comment]
Approve, not on approval list so a 'grey check'

**Review by michaelleecowan — COMMENTED** [review]
Approve, looks good

**Pull request merged**
