### PR TITLE
Adding Darwin focused CI. Resolves: #506

### LINKED ISSUE #506: Add CI for macOS / iOS / watchOS / tvOS
#### Problem
The project has extensive CI for Linux; however, none yet for macOS / OS X.

#### Proposed Solution
Add explicit, non-Docker-based CI for macOS / OS X (since Travis CI does not support Docker on macOS / OS X).

### PR DESCRIPTION
**Pull request by woody-apple**
#### Problem
Adding some simple Darwin CI to verify builds to resolve:
https://github.com/project-chip/connectedhomeip/issues/506

 #### Summary of Changes
Added a GitHub workflow that builds the Darwin platform

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

**Comment by woody-apple** [comment]
@saurabhst @msandstedt @bzbarsky-apple ?

**Review by mspang — APPROVED** [review]

**Review by saurabhst — APPROVED** [review]

**Comment by mspang** [comment]
I believe we should get all these -Wdocumentation errors fixed up and then turn on -Werror for this build.

**Comment by woody-apple** [comment]
@mspang From a Darwin perspective, -Werror isn't something that is prioritized or prioritized  from this platform, however can't disagree from a -Wdocumentation perspective. 

Filed this to cover doxygen: https://github.com/project-chip/connectedhomeip/issues/6184

That said, given this is setting up CI, I don't think this should block warnings for existing issues in the tree. Thoughts?

**Comment by mspang** [comment]
> @mspang From a Darwin perspective, -Werror isn't something that is prioritized or generally used for this platform, however can't disagree from a -Wdocumentation perspective.
> 
> Filed this to cover doxygen: #6184
> 
> That said, given this is setting up CI, I don't think this should block warnings for existing issues in the tree. Thoughts?

Agree it should be a followup. This is already a huge improvement, I wouldn't block on it.

Unfixed warnings are distracting, and my position is our CI should be kept warnings clean across all platforms (possibly by disabling warnings that we truly do not care to fix).

**Review by jelderton — APPROVED** [review]

**Pull request merged**
