### PR TITLE
[WiFi Diagnostics Cluster] Enable WiFi Network Diagnostics cluster on the controllers 

### PR DESCRIPTION
**Pull request by yufengwangca**
#### Problem
What is being fixed?
WiFi Network Diagnostics cluster is not enabled on the controllers.

#### Change overview
1. Enable Wifi diagnostics cluster in controller-clusters.zap

#### Testing
How was this tested? (at least one bullet point required)
Run ./scripts/tools/zap_regen_all.py and conform codegen can re-generate the code without error.
Run ./chip-tool and confirm wifinetworkdiagnostics is in the cluster list.

### CODE REVIEW

**Comment by bzbarsky-apple** [comment]
> Currently, codegen does not generate code for the items if we set optional to 'true' in the cluster xml definition file.

Even if the .zap file says they are enabled?  @vivien-apple that sounds odd....

**Comment by yufengwangca** [comment]
> > Currently, codegen does not generate code for the items if we set optional to 'true' in the cluster xml definition file.
> 
> Even if the .zap file says they are enabled? @vivien-apple that sounds odd....

This is because the ZAP UI tools does not mark those items as enabled if optional is set to 'true' in xml definition file. With latest version of ZAP UI tools, we can manually enable those items and update the .zap file.

**Comment by bzbarsky-apple** [comment]
That sounds like a better approach: the XML should say what the spec says (ideally not just optional but what feature enables it), the UI should expose the toggling ability, we should turn on which things we want in the UI, and the zap file should capture those decisions.

**Comment by yufengwangca** [comment]
> That sounds like a better approach: the XML should say what the spec says (ideally not just optional but what feature enables it), the UI should expose the toggling ability, we should turn on which things we want in the UI, and the zap file should capture those decisions.

Yes, the XML does not fully match with the spec, that is the cause of current confusion.

**Review by mspang — APPROVED** [review]

**Review by msandstedt — APPROVED** [review]

**Comment by yufengwangca** [comment]
@jepenven-silabs @bzbarsky-apple @Damian-Nordic ?

**Comment by bzbarsky-apple** [comment]
@yufengwangca This is still changing the XML to mark optional things as non-optional, instead of enabling them in the ZAP UI if we want them enabled.  Why are we doing that?  

That is, why are we not doing the thing https://github.com/project-chip/connectedhomeip/pull/7365#issuecomment-854158666 proposed doing?

**Review by Damian-Nordic — APPROVED** [review]

**Comment by yufengwangca** [comment]
> @yufengwangca This is still changing the XML to mark optional things as non-optional, instead of enabling them in the ZAP UI if we want them enabled. Why are we doing that?
> 
> That is, why are we not doing the thing [#7365 (comment)](https://github.com/project-chip/connectedhomeip/pull/7365#issuecomment-854158666) proposed doing?

@bzbarsky-apple I am confused, which optional item is marked as non-optional? This is only one item "Current MaxRate" is optional in the spec, this PR marked the items whose Conformance level not set to 'O' as non-optional to align with other XMLs.

**Comment by woody-apple** [comment]
@yufengwangca conflicts :(

**Comment by yufengwangca** [comment]
> > @yufengwangca This is still changing the XML to mark optional things as non-optional, instead of enabling them in the ZAP UI if we want them enabled. Why are we doing that?
> > That is, why are we not doing the thing [#7365 (comment)](https://github.com/project-chip/connectedhomeip/pull/7365#issuecomment-854158666) proposed doing?
> 
> @bzbarsky-apple I am confused, which optional item is marked as non-optional? This is only one item "Current MaxRate" is optional in the spec, this PR marked the items whose Conformance level not set to 'O' as non-optional to align with other XMLs.

Synced offline, decided to leave items whose Conformance level not set to 'O' nor 'M' optional in XML and enable those items only in ZAP.

**Review by saurabhst — APPROVED** [review]

**Pull request merged**
