### PR TITLE
add SLAAC configuration for CC2652R7

### LINKED ISSUE #5554: [TE1] Commissioning lock-app example device (cc13x2x7_26x2x7 platform) did not complete
#### Problem
When commissioning the lock-app example device using the TI CC2652R7 platform, the process did not end with success. The `chip-device-ctrl` tool ended up just "spinning" at the final stage, thereby not finalizing the process. The communication timed out and emitted an error:
```
OnRendezvousError: Ble Error 6024 (0x00001788): Message fragment acknowledgement timed out
Releasing end point's BLE connection back to application.
```

 #### Proposed Solution
Enable the SLAAC feature in the `OpenThreadConfig.h` header file:
`#define OPENTHREAD_CONFIG_IP6_SLAAC_ENABLE 1`

### PR DESCRIPTION
**Pull request by srickardti**
The provisioning process through BLE will hang until a GUA is reported
back. This won't happen until either SLAAC or DHCPv6 configure an
address for the prefix associated with the border router.

#### Problem

BLE provisioning will hang until a GUA is reported. This address won't be assigned to the Thread device without SLAAC or DHCPv6 enabled.

#### Summary of Changes

Enables SLAAC address generation in the lock-app reference example.

Fixes #5554

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
Do we need this fix in master?

**Comment by srickardti** [comment]
@andy31415 yes, but one of the other PRs broke `master` for the CC2652R7 so I was going to include it in that update.

I had assumed that `test_event_1` would eventually be merged back to `master`. But I could be wrong.

**Comment by andy31415** [comment]
testevent1 will not be merged in master - we only cherrypick from master into te1.

**Comment by srickardti** [comment]
I was under the assumption that it was a development branch, my bad. Would it make more sense to have this on master? I can rework the branch.

**Review by mspang — APPROVED** [review]

**Comment by mspang** [comment]
Please reopen this against master.

**Pull request merged**
