### PR TITLE
[YAML] Use a common list for tests with an explicit method to disable some tests

### PR DESCRIPTION
**Pull request by vivien-apple**
#### Problem

The list of yaml tests to generates is specified in `examples/*/templates/tests/tests.js` files.
This is nice because applications can specify which tests they want to build but it makes it hard spot which tests are disabled for a given example.

#### Change overview
 * Use a common list of YAML tests to build
 * Add an explicit method to disable some tests

### CODE REVIEW

**Review by bzbarsky-apple — APPROVED** [review]
Thank you; this will make it much simpler to keep things in sync...

That said, we should really do some re-evaluating of whether tests belong in manual tests or not, clearly.

**Comment by vivien-apple** [comment]
> That said, we should really do some re-evaluating of whether tests belong in manual tests or not, clearly.

At the moment the test harness team is sort of using that for their own purposes - in theory most of those should be automated...

**Comment by bzbarsky-apple** [comment]
Fast-tracking test infra change that only affects chip-tool-darwin.

**Review by woody-apple — APPROVED** [review]
Fast tracking tests

**Review by krypton36 — APPROVED** [review]
Nice!

**Review by woody-apple — APPROVED** [review]
Fast tracking test updates

**Pull request merged**
