### PR TITLE
improve PS and PSCFG test scripts

### PR DESCRIPTION
**Pull request by fessehaeve**
#### Problem
- Cluster names are not correct in few instances
- Power source and power source configuration cluster tests are mostly manual

#### Change overview
Improvements 

#### Testing
chip-tool and nrf based DUT

### CODE REVIEW

**Review by bzbarsky-apple — APPROVED** [review]
Are any of these manual right now?  Can they move out of the manual list?

**Comment by fessehaeve** [comment]
@bzbarsky-apple yes, some of these tests are manual right now. I don't know what the workflow is to update these things.

**Comment by bzbarsky-apple** [comment]
@fessehaeve You move the test from the "getManualTests()" section in tests.js to the "getTests()" section.

**Comment by woody-apple** [comment]
@fessehaeve Please restyle :)

**Comment by woody-apple** [comment]
> @fessehaeve Please restyle :)

Done

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
@fessehaeve FYI, this has conflicts.

**Review by andy31415 — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
@fessehaeve Please address the conflicts?

**Review by andy31415 — CHANGES_REQUESTED** [review]
Not updated in 15 days. This has to be re-reviewed for 1.0 suitability

**Comment by jmeg-sfy** [comment]
This PR @fessehaeve still need to go ?

**Pull request closed without merging**
