### PR TITLE
Move controller cluster files from python dir.

### LINKED ISSUE #6740: Give device controller access to generated cluster files
#### Problem
device controller will need access to cluster for commissioning. These are currently located in the python subdir, but will be required by the base code.

 #### Proposed Solution
Move.

### PR DESCRIPTION
**Pull request by cecille**
To perform commissioing, the controller will need to make calls to
device clusters, which means it needs gen files for the clusters.
Moving this out of python to give the commissioner code acccess.

 #### Problem
device controller will need access to cluster for commissioning. These are currently located in the python subdir, but will be required by the base code.

 #### Summary of Changes
Moves cluster generated files from src/controller/python/gen to src/controller/controller_clusters/gen

 Fixes #6740

### CODE REVIEW

**Comment by vivien-apple** [comment]
Can you elaborate ? Ideally I would like the controller to not depends on gen/ files. 
Also, the files generated for the Python Device controller, contains a lot of clusters that are not needed for commissioning.

**Comment by cecille** [comment]
The clusters will be needed for commissioning, so will need to be available to the controller.

**Comment by woody-apple** [comment]
@cecille Conflicts as well

**Comment by vivien-apple** [comment]
> The clusters will be needed for commissioning, so will need to be available to the controller. Right now I'm not too worried about the extra clusters - I'm just trying to get something working in time for TE3 without angering zap. If you don't want the controller to depend on the gen files, how will it get cluster information?

There are probably ways to get the controller to delegate the commissioning work to something that is generated. I would like to avoid tying too much `DeviceCommissioner` to the code that is currently generated as it will require extra work and manual editing if we change it.

For example I can imagine that `DeviceCommissioner` delegates some of the work to an other object that implements the spec'ed commissioning part and who contains generated code to send commands/receive responses.

`DeviceCommissioner` could just sit here and expose an API that this object will use to feed it with the bits it needs to know of. All of this without having to know anything `clusters` by itself, since the `CommissioningProcess` class (or whatever name) is a generated c++  file into the gen/ folder of the app itself and will take care of that.

About creating a `zap` file that enable the set of required clusters and use it directly into `src/controller`, I would assume that in the future the set of "required" clusters will just be enabled by zap by default and so this is redundant as it will already be part of the `gen/` folder of the app.

**Comment by cecille** [comment]
Is that necessary though? What would an extra layer do for us? The commands the controller needs to send aren't going to change - they're locked by the spec.

**Review by woody-apple — CHANGES_REQUESTED** [review]
Pending approval from @vivien-apple for cluster changes like this

**Comment by cecille** [comment]
Superseded by https://github.com/project-chip/connectedhomeip/pull/6941

**Pull request closed without merging**
