### PR TITLE
Reduce number of replies on MinMds query processing.

### PR DESCRIPTION
**Pull request by andy31415**
UDP packets are received on every listening interface, resulting in single queries being multipled by the interface count and this causes more packets than expected being generated.

This change will only process queries that are originating from the same interface that the mdns endpoint is bound to.

### CODE REVIEW

**Comment by andy31415** [comment]
Marking as ready for review as this reduces number of replies in minmdns.

I am still wondering if maybe there is an update potential for minmdns to use less udp sockets and listening ports as I would expect addr_any to cover listening over more interfaces (the existing behavior seems to cover that).

**Review by tcarmelveilleux — APPROVED** [review]

**Comment by andy31415** [comment]
obsolete after #27219

**Comment by andy31415** [comment]
Re-opened as the other PR seems to have issues on OpenIOT. The error of `Failed to reply to query` that I get there is not helpful, so I am unsure on how long this will take to debug. Maybe once we have better tracing/logging piped through we can actually see what queries and answers are seen.

**Comment by PSONALl** [comment]
can we cherry pick this PR on v1.1-branch ?

**Pull request merged**
