### PR TITLE
Enable CRMP on the client

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
#### Problem
We don't currently send commands as reliable messages from controllers to servers.

#### Change overview
Send commands as reliable messages.

#### Testing
Manually verified that if the server is unreachable we now do several retransmits.  Haven't figured out a good way to do an automated test for this yet.  The existing TestCommandInteraction tests don't seem to do any actual sending/receiving of commands, unfortunately.

### CODE REVIEW

**Comment by yunhanw-google** [comment]
For automation testing, we can validate it using ping/echo from python device controller (https://github.com/project-chip/connectedhomeip/pull/7432) in cirque, where cirque traffic control module can block traffic and test this situation.
Please file the ticket, we would try to add this test case on it

**Review by yunhanw-google — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
Thanks, I filed https://github.com/project-chip/connectedhomeip/issues/7691

**Review by yufengwangca — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Comment by woody-apple** [comment]
@Damian-Nordic @LuDuda @jepenven-silabs .

**Comment by bzbarsky-apple** [comment]
@jmartinez-silabs @saurabhst @msandstedt Please take a look?

**Review by saurabhst — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]

**Pull request merged**
