### PR TITLE
Increase the number of read/write client/handler to 4

### PR DESCRIPTION
**Pull request by yunhanw-google**
#### Problem
Similar to Command, we also need increase the number of read/write client/handler to 4 for multiple read/write situations

#### Change overview
increase the number of read/write client/handler to 4

#### Testing
Manual compilation and run device controller test with song's IM read with ember integration

### CODE REVIEW

**Comment by woody-apple** [comment]
Why did we choose 4? Is there a better path forward here for constrained devices? @bzbarsky-apple ?

**Comment by yunhanw-google** [comment]
> Why did we choose 4? Is there a better path forward here for constrained devices? @bzbarsky-apple ?

@bzbarsky-apple @woody-apple I think we have clear TODO "Make number of command/read/write client/handler configurable"

**Comment by yunhanw-google** [comment]
> Why did we choose 4? Is there a better path forward here for constrained devices? @bzbarsky-apple ?

https://github.com/project-chip/connectedhomeip/issues/8006

**Review by bzbarsky-apple — APPROVED** [review]

**Review by bzbarsky-apple — COMMENTED** [review]
And just to be clear: 4 clients is totally inadequate for any sort of resident/hub/etc device.  We need a better allocation strategy here.

On the other hand, having 4 _handlers_ is total overkill because all of our handlers return sychronously afaict, so I don't think we ever use more than 1.

**Comment by bzbarsky-apple** [comment]
> Is there a better path forward here for constrained devices?

The right numbers are something like:

* ReadHandler/WriteHandler/CommandHandler: 1, possibly allocated on the stack, not living in bss.  Questionable whether these objects should even exist in their current form, especially CommandHandler (which has a bunch of unused members, etc).
* Constrained device ReadClient/WriteClient/CommandClient: Depends on the device, between 0 and 1.
* Unconstrained device ReadClient/WriteClient/CommandClient: infinite, bounded by available RAM (and maybe not even that, for devices with swap).

This PR is sort of no worse than the state before; Sagar's attempts to use this on iOS will still be broken and he will need to bump these numbers to much larger values to get anything usable, our CI will still work because it does one thing at a time....  But it's not really any better than the state before either.  We should stop wasting our time twiddling these constants and actually solve the real problems.

**Review by jmartinez-silabs — APPROVED** [review]

**Comment by woody-apple** [comment]
@saurabhst @msandstedt @mspang @Damian-Nordic ?

**Review by woody-apple — APPROVED** [review]

**Review by jelderton — APPROVED** [review]

**Pull request merged**
