### PR TITLE
[Tizen] Update tizen docker image for thread

### PR DESCRIPTION
**Pull request by ay-agarwal**
Update Tizen docker file to download Tizen thread stack.

Signed-off-by: Abhay Agarwal <ay.agarwal@samsung.com>

#### Problem
Tizen platform's thread stack manager requires the tizen thread library.

#### Change overview
Update Tizen docker file to download Tizen thread stack.

#### Testing
Tizen docker image build.

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]

**Review by dh79pyun — APPROVED** [review]
Looks good

**Review by arkq — CHANGES_REQUESTED** [review]
I think that you should bump [version file](https://github.com/project-chip/connectedhomeip/blob/master/integrations/docker/images/chip-build/version) as well.

**Review by Damian-Nordic — APPROVED** [review]

**Review by hyunuktak — APPROVED** [review]
Looks good to me.

**Comment by ay-agarwal** [comment]
> I think that you should bump [version file](https://github.com/project-chip/connectedhomeip/blob/master/integrations/docker/images/chip-build/version) as well.

updated the version file, Thanks

**Review by arkq — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Pull request merged**
