### PR TITLE
Introducing ble adaptation for webOS

### PR DESCRIPTION
**Pull request by sungho1shin**
#### Problem
What is being fixed?  Examples:
* There is no support for ble-wifi commissioning on webOS.

#### Change overview
* Implement base function regarding ble behavior using webOS ble API
* Implement ble central functionality for webOS

#### Testing
How was this tested? (at least one bullet point required)
* If unit tests were added, how do they cover this issue?
* If unit tests existed, how were they fixed/modified to prevent this in future?
* If new unit tests are not added, why not?
* If integration tests were added, how do they verify this change?
* If new integration tests are not added, why not?
* If manually tested, what platforms controller and device platforms were manually tested, and how?
Controller: webOS OSE on rapsberrypi4
Controlee: ubuntu on rapsberrypi4 where connectedhomeip is compiled
It has been verified that ble-wifi commissioning works as expected between webOS (raspberrypi4) and ubuntu (rapsberrypi4)
* If no testing is required, why not?

### CODE REVIEW

**Comment by cabin15** [comment]
Dear reviewers,
This PR was re-created since the last one (https://github.com/project-chip/connectedhomeip/pull/17305) was staled.

Could you plz review this PR?
Also it would be so kind if someone with authorization could run the CI for this.

Thank you so much.

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
@sungho1shin - please update to fix merge conflicts. I added the checkmark and this should be mergeable now after that.

**Comment by sungho1shin** [comment]
@andy31415 
I really appreciate your effort for reviewing this PR.
According to your review, I just fetched the latest upstream, and resolved the merge conflict.

Could you plz consider merging this?
Thank you.

**Comment by sungho1shin** [comment]
@andy31415 
Gentle reminder for considering to merge this.

**Comment by bzbarsky-apple** [comment]
@sungho1shin Failing code lints: https://github.com/project-chip/connectedhomeip/runs/6561767526?check_suite_focus=true

**Pull request merged**
