### PR TITLE
Move the QR code link to the project-chip gh-pages branch

### LINKED ISSUE #3266: Need to display the QR code using the Github pages of CHIP repository
#### Problem
With PR #3242 we have added the support of displaying the QR code on a webpage. This will be helpful for devices that do not have a physical display (to scan/print the QR code). Currently, the page is under the Github pages of my personal Github fork. We need to move this to CHIP repository.

 #### Proposed Solution
I think, the CHIP maintainers should enable Github pages (gh-pages) for the CHIP repository. Once that is done, we can merge the changes through a PR.

### PR DESCRIPTION
**Pull request by dhrishi**
#### Problem
Fixes #3266

#### Change overview
Replace all occurrences with of the QR code link with the one in the chip repository

#### Testing
NA

### CODE REVIEW

**Comment by dhrishi** [comment]
This depends on #19874

**Comment by woody-apple** [comment]
Thank you!

**Review by woody-apple — APPROVED** [review]
Fast tracking documentation changes

**Comment by woody-apple** [comment]
@dhrishi Page is deployed, please mark as ready for review whenever you're ready!

**Review by woody-apple — APPROVED** [review]

**Comment by dhrishi** [comment]
@woody-apple Done!

**Pull request merged**
