### PR TITLE
Fix ble connect error in Temperature Measurement app

### LINKED ISSUE #7680: chip-device-ctrl failed to establish secure session to device using temperature-measurement-app on mac
#### Problem
chip-device-ctrl failed to establish secure session to device using temperature-measurement-app on mac
 * expected behavior : establish secure session over ble after command
 `connect -ble 3840 20202021 135246` 
 * actual behavior:
      chip-device-ctrl failed to establish secure session over ble 
 * system configuration
     - platform - macOS
     - kit - ESP32 devkit
 * logs
      - device side: [device-side-logs.txt](https://github.com/project-chip/connectedhomeip/files/6660638/device-side-logs.txt)

      - chip-device-ctrl side: [chip-device-ctrl-logs.txt](https://github.com/project-chip/connectedhomeip/files/6660635/chip-device-ctrl-logs.txt)

### PR DESCRIPTION
**Pull request by PSONALl**
#### Problem

1. chip-device-ctrl failed to establish a secure session to the device using temperature-measurement-app on mac
   - Fixes #7680 
 2. resolve command hangs in chip-device-ctrl with temperature-measurement-app 
    - Fix for: https://github.com/project-chip/connectedhomeip/pull/7723#issuecomment-863349153 

#### Change overview

1. Fix ble-connect error in temperature measurement app
    -  Added two separate endpoints (Endpoint 0, Endpoint 1) in endpoint_config.h
    - One for Operational Credentials and other for Temperature Measurement
    - Earlier there was only Endpoint 1

2. Fix resolve mdns hang in temperature measurement app
   -  added mdns server start at connectivity change

#### Testing
* Tested commissioning with chip-device-ctrl

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]

**Review by msandstedt — APPROVED** [review]

**Review by saurabhst — APPROVED** [review]

**Comment by dhrishi** [comment]
@andy31415  @bzbarsky-apple Any idea why the ZAP templates generation has failed?

**Review by yunhanw-google — APPROVED** [review]

**Comment by PSONALl** [comment]
> /rebase

Done!

**Comment by bzbarsky-apple** [comment]
> Any idea why the ZAP templates generation has failed?

Bad tip merge.  That's why woody-apple was rebasing things (/rebase in a comment like that when he does it triggers a workflow which automatically rebases the PR).

**Comment by bzbarsky-apple** [comment]
>  Any idea why the ZAP templates generation has failed?

Probably because it's catching that `endpoint_config.h` (a generated file) was hand-edited without actually modifying the data it's generated from, so the next thing to come along and regenerate things will clobber the hand-changes.

Probably what should happen here is changing `examples/temperature-measurement-app/esp32/main/temperature-measurement.zap` (by hand or via the ZAP ui) to set up the right endpoint configuration, then running `./scripts/tools/zap/generate.py  examples/temperature-measurement-app/esp32/main/temperature-measurement.zap` to regenerate `endpoint_config.h`.

**Comment by PSONALl** [comment]
> Probably what should happen here is changing `examples/temperature-measurement-app/esp32/main/temperature-measurement.zap` (by hand or via the ZAP ui) to set up the right endpoint configuration, then running `./scripts/tools/zap/generate.py examples/temperature-measurement-app/esp32/main/temperature-measurement.zap` to regenerate `endpoint_config.h`.

Added this change.

**Review by bzbarsky-apple — COMMENTED** [review]
Two questions:
1. Why is this adding Thread Network Diagnostics?
2. This is putting Temperature Measurement on endpoint 0.  What's the point of the (empty, no clusters enabled for it) endpoint 1?

**Review by woody-apple — CHANGES_REQUESTED** [review]
Requesting changes per @bzbarsky-apple

**Comment by PSONALl** [comment]
> Requesting changes per @bzbarsky-apple

Added this change. cc: @bzbarsky-apple @woody-apple

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
@Damian-Nordic @andy31415 @jepenven-silabs ?

**Review by Damian-Nordic — APPROVED** [review]

**Comment by dhrishi** [comment]
Approving for the 2nd commit you have added in this PR.

**Review by dhrishi — APPROVED** [review]

**Review by mspang — APPROVED** [review]

**Pull request merged**
