### PR TITLE
[BouffaloLab] Update BouffaloLab platform requirements

### PR DESCRIPTION
**Pull request by shchen-Lab**
bflb-iot-tool need to specify serial module  and signature module and encryption module, this is used to signature and encrypt firmware.

### CODE REVIEW

**Review by andy31415 — CHANGES_REQUESTED** [review]
@shchen-Lab please update the summary of the PR to help reviewers undestand what requirements were updated and why. It says right  there: `!!!!!!!!!! Please delete the instructions below and replace with PR description`

**Comment by shchen-Lab** [comment]
Thanks, updated.

**Comment by shchen-Lab** [comment]
>  
bflb-iot-tool need to specify some module version, like pyserial module.

**Comment by shchen-Lab** [comment]
> bflb-iot-tool need to specify some module version, like pyserial module.

**Comment by andy31415** [comment]
> > bflb-iot-tool need to specify some module version, like pyserial module.

This description seems incomplete - you seem to be adding module not just specifying versions. Given that boufallolab examples already compile could you explain the change?

As a reviewer I would like to understand where this is heading because for now we share pip modules across all platforms (our fault: we use the free version of buildjet so we cache only one build environment) so any modules interacts with all other platforms: fixing versions has higher chances of conflicts and more dependencies will cause images to become slightly larger (probably not much, but would still like to understand and ensure the images are minimal).

**Review by jmartinez-silabs — APPROVED** [review]

**Review by andy31415 — CHANGES_REQUESTED** [review]
I unpacked https://pypi.org/project/bflb-iot-tool/1.8.6/#files and I see:

```
    install_requires=[
        'ecdsa>=0.15',
        'pycryptodome==3.9.8',
        'bflb-crypto-plus==1.0',
        'pycklink>=0.1.1',
        'pyserial==3.5',
        'pylink-square==0.5.0',
        'portalocker==2.0.0'
    ],
```

in setup.py

So you do not need these requirements here.

**Comment by shchen-Lab** [comment]
> I unpacked https://pypi.org/project/bflb-iot-tool/1.8.6/#files and I see:
> 
> ```
>     install_requires=[
>         'ecdsa>=0.15',
>         'pycryptodome==3.9.8',
>         'bflb-crypto-plus==1.0',
>         'pycklink>=0.1.1',
>         'pyserial==3.5',
>         'pylink-square==0.5.0',
>         'portalocker==2.0.0'
>     ],
> ```
> 
> in setup.py
> 
> So you do not need these requirements here.

You are right， but use  "source ./scripts/activate.sh -p bouffalolab" to install bflb-iot-tool will appear dependency conflicts. I have contact bflb-iot -tool developer try reslove this issue.

**Pull request closed without merging**
