### PR TITLE
[groups] Remove NDEBUG from GroupSession.h

### PR DESCRIPTION
**Pull request by Damian-Nordic**
#### Problem
Using NDEBUG to change public structure layouts is problematic since it may introduce hard to debug bugs when integrating the CHIP library with external components that are built with different compiler options.

#### Change overview
Use the same memory layout for group sessions regardless of NDEBUG presence.
Move functionality that depends on NDEBUG to .cpp file.

#### Testing
Did smoke tests with group communication on nRF Connect hardware.

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
@kghost

**Comment by mspang** [comment]
I think this is too confusing. The type isn't managed via refcounting, and provides a no-op Release. Arguably that doesn't fulfill the contract implied by RefCounted<>.

**Comment by Damian-Nordic** [comment]
> I think this is too confusing. The type isn't managed via refcounting, and provides a no-op Release. Arguably that doesn't fulfill the contract implied by RefCounted<>.

Do you think I should replace `ReferenceCounted` with a simple `uint32_t` to check the number of `SessionHandle`s referencing a given group session?

**Comment by mspang** [comment]
> > I think this is too confusing. The type isn't managed via refcounting, and provides a no-op Release. Arguably that doesn't fulfill the contract implied by RefCounted<>.
> 
> Do you think I should replace `ReferenceCounted` with a simple `uint32_t` to check the number of `SessionHandle`s referencing a given group session?

Sure, that would avoid the confusion.

**Comment by Damian-Nordic** [comment]
> Sure, that would avoid the confusion.

Ok, done.

**Comment by kghost** [comment]
The counter is only used for debugging, I'd suggest remove it completely.

**Comment by Damian-Nordic** [comment]
> The counter is only used for debugging, I'd suggest remove it completely.

Ok, I did as you suggested.

**Review by jepenven-silabs — APPROVED** [review]

**Pull request merged**
