### PR TITLE
Add Mode Select Cluster

### PR DESCRIPTION
**Pull request by du48s03**
*Problem

Implementation for Mode Select Cluster is missing.

Speicification for the Mode Select Cluster can be found at

https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/ModeSelect.adoc

*Change overview

Add the the implementation for the mode select cluster's server.

Add SupportedOptionsManager to help initializing the supported options
and retriving the options.

Changes the all-cluster-all and chip-tool's zap files to include the
mode select cluster.

#### Problem
Add the implementation for Mode Select Cluster. The specification for
    Mode Select Cluster can be found at https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/ModeSelect.adoc

#### Change overview
    * Add src/app/zap-templates/zcl/data-model/chip/mode-select-cluster.xml
    * Add the ModeSelectCluster to the all-cluster-app
    * Add the ModeSelectCluster to the chip-tool
    * Add src/app/clusters/mode-select-server/mode-select-server.cpp, the
    main logic for the server of the ModeSelectCluster
    * Add src/app/clusters/mode-select-server/supported-modes-manager.h,
    which contains helper method for managing the supported options.
    * Generate code for Mode Select Cluster

#### Testing
How was this tested? (at least one bullet point required)
* If manually tested, what platforms controller and device platforms were manually tested, and how?
  Manually tested with chip-tool built on MacOs. Tested by issuing the read command and the "change-to-mode" command, and verified that all the attributes can be read, and "change-to-mode" correctly changes the "current-mode" attribute. 
* `./scripts/test/test_suites.sh` passed on a iOS machine.

### CODE REVIEW

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]
There should probably be some tests being added here, no?  As in a YAML that exercises this cluster in the all-clusters-app.

**Review by chrisdecenzo — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]

**Review by lazarkov — APPROVED** [review]

**Review by mrjerryjohns — COMMENTED** [review]
On the whole, this PR has a number of concerning items that can be changed to improve it signifcantly:
1. The use of 'std::map' makes it a non-starter for use on constrained devices. By the description of the cluster, it seems like this is targeted for a fairly broad class of devices.
2. Over-designed interfaces and iterators that have a lot of virtuals on them, that are not necessary. This results in 24K increase in flash alone, **without** any of the application bits at all involved here. That is concerning.
3. Went through a lot of work to design a `SupportedModesManager` interface, yet the cluster impl only permits a specific concrete realization of that interface, which defeats the point of that interface.

I think this can be done much simpler - creation of a fairly simple 'data provider' interface that hides away the actual list of modes, as well as the methods to interact with that data feels like the appropriate solution here. This would hide away the storage specifics of that data (letting the application decide it), making it more flexible, as well as reducing the complexity of the overall solution.

A suggested provider interface (that would be registered with the cluster impl) could look like this:

```
class ModeDataProvider {
public:
    class ModeChangeListener {
    public:
        enum ModeOperation {
            kModeAdded = 0,
            kModeDeleted = 1,
            kModeModified = 2
        };

        virtual void OnModeChange(uint16_t modeIndex, ModeOperation modeOperation) = 0;
    };

    virtual CHIP_ERROR GetNumSupportedModes() = 0;

    virtual CHIP_ERROR GetMode(uint16_t modeIndex, Structs::ModeOptionsStruct::Type &mode, EndpointId &associatedEndpointId) = 0;
    virtual CHIP_ERROR SetMode(uint16_t modeIndex, Structs::ModeOptionStruct::Type &mode) = 0;

    virtual CHIP_ERROR RegisterModeChangeListener(ModeChangeListener *modeChangeListener) = 0;
};
```

This approximates very closely existing provider interfaces (like `GroupDataProvider`).

**Review by mrjerryjohns — APPROVED** [review]
Approved, given the requisite issues have been filed, and will be worked on shortly after this PR merges.

**Review by jmartinez-silabs — APPROVED** [review]

**Pull request merged**
