### PR TITLE
Add Bridged Device Basic information and Fixed Label clusters for bridge support

### PR DESCRIPTION
**Pull request by jrhees-cae**
#### Problem

Bridge support requires the following mandatory clusters:
1. Bridged Device Basic
2. Fixed Label

#### Change overview

1. Added templates for Bridged Device Basic and Fixed Label clusters.
2. Add new clusters to .zap's for:
     - all-clusters example
     - chip-tool
     - controller-clusters
     - python controller
     - darwin controller

#### Testing

1. Manually tested reading/writing new clusters using chip-tool and all-clusters-app (both on Linux platform)

Notes:
Part of issue #1874 
zap-generated files to be pushed separately

Replaces #6934

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]
@saurabhst @msandstedt @andy31415 @jepenven-silabs ?

**Review by saurabhst — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]

**Review by msandstedt — APPROVED** [review]

**Comment by jrhees-cae** [comment]
@woody-apple Do I need to wait for more reviewers before adding the generated files to this PR?

**Comment by bzbarsky-apple** [comment]
Would be good to have @andy31415 or @mspang or @jmartinez-silabs or @Damian-Nordic review.

You could also just add it as a separate commit; reviewing should still be easy enough....

**Review by chrisdecenzo — APPROVED** [review]

**Comment by jrhees-cae** [comment]
> You could also just add it as a separate commit; reviewing should still be easy enough....

@bzbarsky-apple will a new commit (with the generated files) erase the 'review-approved' tag?

**Comment by bzbarsky-apple** [comment]
> @bzbarsky-apple will a new commit (with the generated files) erase the 'review-approved' tag?

No, it will not.  Unfortunately (but fortunately in this case, I guess), arbitrary changes to the PR after review has been granted don't reset the review state.

**Comment by bzbarsky-apple** [comment]
To be clear, I meant add another commit on the branch that this is developed on and then push that branch, so the PR consists of two commits.

**Review by mspang — APPROVED** [review]

**Pull request merged**
