### PR TITLE
WindowCovering: Add missing Basic cluster attributes to zap demo config

### PR DESCRIPTION
**Pull request by jmeg-sfy**
#### Problem
What is being fixed?  Examples:
* Few Versioning and informative attributes from the Basic Cluster were not present 
* This PR add those attributes to be at the level of the all-cluster + Lightning demos

#### Change overview
No logic code change 
Just Zap config + autogen endpoint config

#### Testing
How was this tested? (at least one bullet point required)
* Test via chip-tool reading a commissioned EFR32 demo WindowCovering

### CODE REVIEW

**Review by ReneJosefsen — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]

**Review by vivien-apple — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
Fast tracking given this has been in review for a while.

**Comment by jmeg-sfy** [comment]
@woody-apple @andreilitvin ready for merge

**Comment by andy31415** [comment]
@jmeg-sfy - still have some zap generation conflicts

**Comment by woody-apple** [comment]
@jmeg-sfy ?

**Comment by jmeg-sfy** [comment]
> @jmeg-sfy ?

Rebase / Regen

**Pull request merged**
