### PR TITLE
Darwin: Deprecate MTRAsyncCallbackQueue and clone into MTRAsyncWorkQueue

### PR DESCRIPTION
**Pull request by ksperling-apple**
MTRAsyncCallbackQueue was accidentally made part of the public API, which is now constraining our ability to refactor its API. This change "renames" the class to MTRAsyncWorkQueue (and similar renames for related types), but leaves the existing MTRAsyncCallbackQueue class in place. (More precisely, only the parts of it that were public are retained.)

Also disable TAPI for Debug builds so we can easily unit-test internal parts of the framework.

### CODE REVIEW

**Review by bzbarsky-apple — APPROVED** [review]
Note: I mostly reviewed by diffing the new files against the pre-rename versions.  I wish git had better support for explicit copy-and-modify....

**Comment by ksperling-apple** [comment]
> Note: I mostly reviewed by diffing the new files against the pre-rename versions. I wish git had better support for explicit copy-and-modify....

Yeah I was hoping git would recognize this as a rename since I made effectively no changes to the copied versions, but doesn't look like it does.

**Comment by ksperling-apple** [comment]
Fast-tracking Darwin-only change.

**Comment by bzbarsky-apple** [comment]
> I was hoping git would recognize this as a rename since I made effectively no changes to the copied versions

The problem was the old file was still there...

**Pull request merged**
