### PR TITLE
Adding YAML Test Cases - Dec 17th

### PR DESCRIPTION
**Pull request by ghost**
Adding following cluster testcases:
1.TC-MC-5.1
2.TC-MC-5.2
3.TC-MC-5.3
4.TC-MC-6.1
5.TC-MC-6.2
6.TC-MC-6.3
7.TC-MC-6.4
8.TC-MC-7.1
9.TC-MC-7.2
10.TC-MC-8.1
11.TC-MC-9.1
12.TC-LVL-2.2
13.TC-LVL-6.1
Modified following Testcases:
1.TC-LVL-2.1
2.TC-LVL-3.1
3.TC-LVL-4.1
4.TC-LVL-5.1

Executed all YAML test scripts, attached logs for reference:
[Execution_log.zip](https://github.com/project-chip/connectedhomeip/files/7737221/Execution_log.zip)

### CODE REVIEW

**Review by bzbarsky-apple — APPROVED** [review]
This needs a merge to tip and regen of common bits via:
```
./scripts/tools/zap/generate.py -t src/app/common/templates/templates.json -o zzz_generated/app-common/app-common/zap-generated src/controller/data_model/controller-clusters.zap 
```

**Comment by manjunathambiger23** [comment]
Rebased it

**Comment by bzbarsky-apple** [comment]
@manjunathambiger23 should this be reopened again?

**Pull request closed without merging**
