### PR TITLE
Adding YAML Test Cases - Dec 13th

### PR DESCRIPTION
**Pull request by ghost**
Adding manual checking test cases

1. Test_TC_DD_1_2
2. Test_TC_DD_1_6
3. Test_TC_DD_1_7
4. Test_TC_DD_1_9
Testing
Executed all YAML test scripts, attached logs for reference :
[Execution_log.zip](https://github.com/project-chip/connectedhomeip/files/7703082/Execution_log.zip)

### CODE REVIEW

**Review by jmeg-sfy — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Comment by kvikrambhat** [comment]
Opened up a new PR with updates to the test cases, will close this once @manjunathambiger23 is back from vacation.
New PR Link: https://github.com/project-chip/connectedhomeip/pull/12984

**Comment by andy31415** [comment]
@vivien-apple @bzbarsky-apple - these seem to also be examples where the darwin zap generation does not quote strings.

**Comment by kvikrambhat** [comment]
@andy31415 PR#12984 contains all these test cases with updates so this PR can be closed.

**Comment by manjunathambiger23** [comment]
closing this PR as the new PR #12984 is opened

**Pull request closed without merging**
