### PR TITLE
Simplify ExchangeMessageDispatch, preventing it from dangling

### PR DESCRIPTION
**Pull request by kghost**
#### Problem
`ExchangeMessageDispatch` in `ExchangeContext` is dangling if CASE/PASE session is release before exchange context

#### Change overview
the message dispatch for case/pase is allocated inside case/pase session, but sometime the ExchangeContext holding a pointer to the dispatch can live longer than the case/pase session, due to some refer is holding by the retrans table. Causing another dangling pointer. Where triggers another crash when disposing the ExchangeContext

* Make the `ExchangeMessageDispatch` an empty virtual object. `ApplicationExchangeDispatch` and `SessionEstablishmentExchangeDispatch` are global singleton now, and it doesn't contain any data field.
  * `ExchangeMessageDispatch` is no longer reference counted.
  * `mDispatch` inside `ExchangeContext` becomes a reference, which always hold a valid dispatcher.
  * Inline `PrepareMessage` and `SendPreparedMessage`, the implementation is same in all derived classes
  * Make `OnMessageReceived` non-virtual, the implementation is same in all derived classes

#### Testing
Verified using unit-tests

### CODE REVIEW

**Comment by andy31415** [comment]
@kghost - Ameba seems to be failing and is a legitimate compile error rater than flake.

**Review by andy31415 — APPROVED** [review]

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]
I asked @pan-apple to take a look, since he knows this code best.  He should be able to do that on Monday...  Marking changes requested pending that.

**Comment by kghost** [comment]
@pan-apple Please take a look

**Review by pan-apple — COMMENTED** [review]
@kghost I am unable to find where we are initializing ExchangeContext with the specific dispatch (e.g. for `SessionEstablishmentExchangeDispatch` object). Could you point me to it?

The mDispatch object is initialized with `ApplicationExchangeDispatch` by default. Is it using this object even for exchanges created for PASE and CASE messages?

**Comment by kghost** [comment]
@pan-apple In the constructor of `ExchangeContext`, we grab message dispatcher from the `ExchangeDelegate`

``
ExchangeContext::ExchangeContext(ExchangeManager * em, uint16_t ExchangeId, SessionHandle session, bool Initiator,
                                 ExchangeDelegate * delegate) :
    mDispatch((delegate != nullptr) ? delegate->GetMessageDispatch() : ApplicationExchangeDispatch::Instance())
{
...
```

The `ExchangeDelegate` returns `ApplicationExchangeDispatch` by default, but for CASE/PASE session, it is overrided to return a `SessionEstablishmentExchangeDispatch`

```
    Messaging::ExchangeMessageDispatch & GetMessageDispatch() override { return SessionEstablishmentExchangeDispatch::Instance(); }
```

**Review by pan-apple — APPROVED** [review]

**Review by msandstedt — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]

**Pull request merged**
