### PR TITLE
Bump OpenThread repo to 009dba9 and ot-qorvo, ot-nxp and ot-efr32 to e8b085e

### PR DESCRIPTION
**Pull request by lucicop**
#### Problem
PR 8252 (https://github.com/project-chip/connectedhomeip/pull/8252) is adding support for service subtypes on Thread devices and some functionality needs a newer API version. For Nordic this is coming via Zephyr, but for Qorvo, NXP and EFR32 platforms the repos need to be updated.

#### Change overview
This PR is updating OpenThread versions in Matter to more recent versions.

#### Testing
Testing via CI.

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

**Review by msandstedt — APPROVED** [review]

**Review by saurabhst — APPROVED** [review]

**Comment by andy31415** [comment]
CI failure seems legitimate

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
@lucicop the K32W failure looks like a real failure?

**Comment by lucicop** [comment]
Yes, will take with NXP to solve the failing compilation.

**Comment by tima-q** [comment]
> Yes, will take with NXP to solve the failing compilation.

@doru91 Could you take a look ?

**Review by mspang — APPROVED** [review]

**Comment by doru91** [comment]
> > Yes, will take with NXP to solve the failing compilation.
> 
> @doru91 Could you take a look ?

Yes, I am looking into this right now.

**Review by jmartinez-silabs — APPROVED** [review]

**Pull request merged**
