### PR TITLE
[zap] automate application zap code generation in build stage

### PR DESCRIPTION
**Pull request by gjc13**
#### Problem

We are now manually generating the ZCL c++ code and shipping the generated code in the repository.

This leads to:
* Out of date generated files.
* Difficulty in understanding the ZCL applications.
* Extra repo size.

#### Change overview

* Automate code generation in `chip_data_model` gn template.
* Integrate zap code genration with ESP32 build.

The generated files are not removed since ESP and NRF platforms are using them in CMake. Since these two platforms share a very similar CMake based build system, I'll discuss with the Nordic developers about the solution in CMake.

#### Testing

Build and run `chip-tool` `chip-all-cluster-app` `chip-light-app` and everything is still fine.

### CODE REVIEW

**Comment by Damian-Nordic** [comment]
Although there are indisputable advantages of the change, adding another large dependency such as nodejs can cause some problems with integration of Matter with other projects. Therefore, I would prefer the generation of ZCL files on the fly to be an option while still being able to use the old approach. 

For instance, could we keep the `zap_regen_all.py` script and rework it in a way that it only takes into account ZAP files located in directories that contain `gen/` subdirectory?

**Comment by gjc13** [comment]
We need to update the CI docker to pull in zap's npm dependencies. @andy31415

**Comment by gjc13** [comment]
> Although there are indisputable advantages of the change, adding another large dependency such as nodejs can cause some problems with integration of Matter with other projects. Therefore, I would prefer the generation of ZCL files on the fly to be an option while still being able to use the old approach. At least for now.
> 
> For instance, could we keep the `zap_regen_all.py` script and rework it in a way that it only takes into account ZAP files located in directories that contain `gen/` subdirectory?

I revisted the generated code and found we are also generating ObjC/Python and othet C/C++ code with the zap templates so adding the script back is necessary. I'll do my best to automate them as well in future PRs.

I still believe generating on-the-fly is the best way to implement ZCL callbacks. Would you name the difficulties this approach may encounter in your integrations if it's convenient for you?

**Comment by andy31415** [comment]
@gjc13 - will updated docker images as needed, let me know. I did a build to add telink just this morning so docker hub images currently match tip of tree.

Regarding generation, aguments exist for both approaches:

- "do not check in generated code" makes sense as a general concept:
   - does not require reviewing generated code (always a pain)
   - smaller codebase, less likely to "grep" into something generated
- "check in gen files" makes sense given the large zap/nodejs requirement:
  - zap is an electron app and large, which pulls in nodejs and also requires a "display" to run, which is often impractical
    for stand alone build machines
  - needing nodejs for compiling an embedded C++ library seems odd, it is much more convenient for library users to be able to just "checkout and compile with a C++ compiler"
  
Anything that moves us towards simpler builds would be great. I believe the current approach has flaws (and I feel the pain on every review updating generated code, which only seems to have the potential to grow with things like automated test case generation)

**Comment by Damian-Nordic** [comment]
> I still believe generating on-the-fly is the best way to implement ZCL callbacks. Would you name the difficulties this approach may encounter in your integrations if it's convenient for you?

For example, we have a tool called "Toolchain Manager" for installing nRF Connect SDK with all possible dependencies. If we make ZAP a mandatory dependency of Matter then all nRF Connect users,  even those who are not interested in Matter at all, will need to additionally install `node JS`, `npm` + `node JS modules` which will quite significantly impact time to install the SDK and required disk space:
 - size of nodejs on my system is about 120MB
 - size of npm is 3MB
 - size of node modules is rather significant (is there a way to install only those required by the code generation?)
 ```
$ du -sh ~/src/chip/third_party/zap/repo/node_modules/
956M	/home/damian/src/chip/third_party/zap/repo/node_modules/
```
We can of course think how to optimize the process and select only necessary nodejs modules, but at least for now we would like to have an option to decide on a sample basis if the code generation on the fly is necessary.

**Review by jmartinez-silabs — APPROVED** [review]

**Comment by gjc13** [comment]
> @gjc13 - will updated docker images as needed, let me know. I did a build to add telink just this morning so docker hub images currently match tip of tree.
> 
> Regarding generation, aguments exist for both approaches:
> 
> * "do not check in generated code" makes sense as a general concept:
>   
>   * does not require reviewing generated code (always a pain)
>   * smaller codebase, less likely to "grep" into something generated
> * "check in gen files" makes sense given the large zap/nodejs requirement:
>   
>   * zap is an electron app and large, which pulls in nodejs and also requires a "display" to run, which is often impractical
>     for stand alone build machines
>   * needing nodejs for compiling an embedded C++ library seems odd, it is much more convenient for library users to be able to just "checkout and compile with a C++ compiler"
> 
> Anything that moves us towards simpler builds would be great. I believe the current approach has flaws (and I feel the pain on every review updating generated code, which only seems to have the potential to grow with things like automated test case generation)

For the CI to run, we need to update the docker containers with the `chip-build` Dockerfile modified in this PR.

**Comment by woody-apple** [comment]
@vivien-apple ?

**Comment by vivien-apple** [comment]
> Size increase report for "esp32-example-build" from [a87bc4f](https://github.com/project-chip/connectedhomeip/commit/a87bc4f06eff6088c86551197044656fbd57bf47)
> 
> File	Section	File	VM
> chip-all-clusters-app.elf	.dram0.bss	0	-40
> chip-all-clusters-app.elf	.dram0.data	-184	-184
> chip-all-clusters-app.elf	.flash.rodata	-968	-968
> chip-all-clusters-app.elf	.flash.text	-3104	-3104
> Full report output

Why is there some size changes ?

**Review by mspang — CHANGES_REQUESTED** [review]
While automating this is a good idea, I believe we need to do it without making building significantly harder. Scripting this in the linux docker image does not seem enough; we need to adopt an approach that will also work on other platforms.

Proposed requirements for any tooling run inline in the build -
- P0) Tested on Linux & Mac, can work on Windows with some additional work
- P1) Updates are automated (i.e., extend bootstrap process to manage the install)
- P1) Installs within the checkout so multiple checkout versions (of CHIP) don't interfere with one another
- P2) Ideally has prebuilts on key platforms as this will amortize build costs & reduce build dependencies

That just for managing the install. I'd also propose requirements for tool behavior:

- P0) Has predictable inputs and tracks them so outputs can be invalidated as needed 
- P1) Does not write files outside the output directory
  - e.g., rm -rf out/ should be sufficient to get to a clean state,
  - concurrent builds should be possible without stomping on shared outputs, and
  - running something like rm -rf ~/.zap should not be required

It may be a worthwhile tradeoff leaving some of these as a TODO in the short term, however we need clear documentation about how to manage it and ideally a reminder to 
developers every time there is an update.

Finally, I would like to reiterate my initial concerns about pulling in a large dependency like this into the build. So far the cost has been borne by a handful of developers, but with this PR it will be borne by everyone. It is extremely concerning that installing this tool brings along with it a complete copy of the chrome browser and more than 3000 NPM modules.

**Comment by gjc13** [comment]
> > Size increase report for "esp32-example-build" from [a87bc4f](https://github.com/project-chip/connectedhomeip/commit/a87bc4f06eff6088c86551197044656fbd57bf47)
> > File	Section	File	VM
> > chip-all-clusters-app.elf	.dram0.bss	0	-40
> > chip-all-clusters-app.elf	.dram0.data	-184	-184
> > chip-all-clusters-app.elf	.flash.rodata	-968	-968
> > chip-all-clusters-app.elf	.flash.text	-3104	-3104
> > Full report output
> 
> Why is there some size changes ?

It turned out to be caused by the file `af-gen-event.h` which is placed in the `gen/` directory but is not really automatically  generated. I removed the include of this file and everything looks still fine. Maybe we need to silab guys to shed some light on the history of this file and how it's supposed to be generated.

**Comment by gjc13** [comment]
> While automating this is a good idea, I believe we need to do it without making building significantly harder. Scripting this in the linux docker image does not seem enough; we need to adopt an approach that will also work on other platforms.
> 
> Proposed requirements for any tooling run inline in the build -
> 
> * P0) Tested on Linux & Mac, can work on Windows with some additional work
> * P1) Updates are automated (i.e., extend bootstrap process to manage the install)
> * P1) Installs within the checkout so multiple checkout versions (of CHIP) don't interfere with one another
> * P2) Ideally has prebuilts on key platforms as this will amortize build costs & reduce build dependencies
> 
> That just for managing the install. I'd also propose requirements for tool behavior:
> 
> * P0) Has predictable inputs and tracks them so outputs can be invalidated as needed
> * P1) Does not write files outside the output directory
>   
>   * e.g., rm -rf out/ should be sufficient to get to a clean state,
>   * concurrent builds should be possible without stomping on shared outputs, and
>   * running something like rm -rf ~/.zap should not be required
> 
> It may be a worthwhile tradeoff leaving some of these as a TODO in the short term, however we need clear documentation about how to manage it and ideally a reminder to
> developers every time there is an update.
> 
> Finally, I would like to reiterate my initial concerns about pulling in a large dependency like this into the build. So far the cost has been borne by a handful of developers, but with this PR it will be borne by everyone. It is extremely concerning that installing this tool brings along with it a complete copy of the chrome browser and more than 3000 NPM modules.

Currently the generated files are limited to the output directory so that won't be a concern.
As to pulling the npm modules into the dependency: While checking in the generated code suffices for the sdk development, it doesn't suffice for the sdk's final users. They will inevitablly write their own zap file and re-generate these c++ code. Forcing them to use a two-stage build will be quite awkward and becomes the motivation of this PR.
During the discussion we've found that there are quite some tricky issues in the whole generation process such as the `af-gen-event.h` left behind and the xml file dependency. I believe we need a further discussion with the ZAP team and the app team about how we would like our users to define a device and write ZCL callbacks. Where do you think is the right place to discuss this issue?

**Comment by mspang** [comment]
> > While automating this is a good idea, I believe we need to do it without making building significantly harder. Scripting this in the linux docker image does not seem enough; we need to adopt an approach that will also work on other platforms.
> > Proposed requirements for any tooling run inline in the build -
> > 
> > * P0) Tested on Linux & Mac, can work on Windows with some additional work
> > * P1) Updates are automated (i.e., extend bootstrap process to manage the install)
> > * P1) Installs within the checkout so multiple checkout versions (of CHIP) don't interfere with one another
> > * P2) Ideally has prebuilts on key platforms as this will amortize build costs & reduce build dependencies
> > 
> > That just for managing the install. I'd also propose requirements for tool behavior:
> > 
> > * P0) Has predictable inputs and tracks them so outputs can be invalidated as needed
> > * P1) Does not write files outside the output directory
> >   
> >   * e.g., rm -rf out/ should be sufficient to get to a clean state,
> >   * concurrent builds should be possible without stomping on shared outputs, and
> >   * running something like rm -rf ~/.zap should not be required
> > 
> > It may be a worthwhile tradeoff leaving some of these as a TODO in the short term, however we need clear documentation about how to manage it and ideally a reminder to
> > developers every time there is an update.
> > Finally, I would like to reiterate my initial concerns about pulling in a large dependency like this into the build. So far the cost has been borne by a handful of developers, but with this PR it will be borne by everyone. It is extremely concerning that installing this tool brings along with it a complete copy of the chrome browser and more than 3000 NPM modules.
> 
> Currently the generated files are limited to the output directory so that won't be a concern.
> As to pulling the npm modules into the dependency: While checking in the generated code suffices for the sdk development, it doesn't suffice for the sdk's final users. They will inevitablly write their own zap file and re-generate these c++ code. Forcing them to use a two-stage build will be quite awkward and becomes the motivation of this PR.
> During the discussion we've found that there are quite some tricky issues in the whole generation process such as the `af-gen-event.h` left behind and the xml file dependency. I believe we need a further discussion with the ZAP team and the app team about how we would like our users to define a device and write ZCL callbacks. Where do you think is the right place to discuss this issue? Maybe a slack room?

ZAP writes a database to ~/.zap which is the reason for bringing this up. This opens the door to concurrency problems between different builds.

The software or data model room on slack are probably the right places to discuss.

**Comment by mspang** [comment]
> As to pulling the npm modules into the dependency: While checking in the generated code suffices for the sdk development, it doesn't suffice for the sdk's final users. They will inevitablly write their own zap file and re-generate these c++ code. Forcing them to use a two-stage build will be quite awkward and becomes the motivation of this PR.

BTW, I agree it is awkward and the generated files has been an massive source of problems such as outdated files, merge conflicts, and code review noise.

I'm not saying "don't do this" and acknowledge that proceeding with this and leave those open as TODO items may be the lesser evil. What we should definitely not do, however, is proceed with this without providing clear documentation. As-is, once this lands, the documented build workflow(s) will not work anymore.

Furthermore I probably would not remove the option of using pregenerated files. This can be an escape hatch for environments where cannot get ZAP working in the build environment.

**Pull request closed without merging**
