### PR TITLE
Add Android tv server

### PR DESCRIPTION
**Pull request by xylophone21**
#### Problem
* Old Tv app is for Linux, not android, but for all android tv, tv features those be controlled are in android word

#### Change overview
Added a tv app for android

#### Testing
* Baisc test by chip-device-ctrl python

### CODE REVIEW

**Comment by xylophone21** [comment]
Any one cloud help to have a look at the 2 CI issues? Thanks
1. Zap issue. I know I should modify examples/tv-app/tv-common/tv-app.zap instead of zzz_generated/tv-app/zap-generated/CHIPClusters.cpp, but I do not know how to do it. I added 2 empty functions in CHIPClusters.cpp to fix link issue. I found that zzz_generated/tv-app/zap-generated deps src/controller, while src/controller deps zzz_generated/controller-clusters, so I have to add some controller-clusters functions to pass the linke
2. Test Suites issue. Seems it is because I changed the placed to init mChipStackLock and added some status check code at GenericPlatformManagerImpl_POSIX.cpp, but I do know why this check caused error. I added these code here because I found that some _LockChipStack is called before _InitChipStack, and some unlock is called when is not locked. ( revert these change doest not effect my PR, but I do not think hide a issue is a good idea )

**Comment by bzbarsky-apple** [comment]
> I should modify examples/tv-app/tv-common/tv-app.zap instead of zzz_generated/tv-app/zap-generated/CHIPClusters.cpp, but I do not know how to do it.

The simplest way, but takes some time to run, is `./scripts/tools/zap_regen_all.py`.

To just rerun the `CHIPClusters.cpp` and `CHIPClusters.h` in `zzz_generated/tv-app/zap-generated`, you can run:
```
./scripts/tools/zap/generate.py -t src/app/zap-templates/app-templates.json -o zzz_generated/tv-app/zap-generated examples/tv-app/tv-common/tv-app.zap
```
and generally speaking you can find out which template (`-t` argument) to use by doing `git grep CHIPClusters.cpp | grep json` or equivalent for the filename you want to regenerate and seeing which template file is involved.  The `.zap` file to use varies depending on which app you need to generate for, and the `-o` value depends on where you want things to land in the tree.

You will also want to rebase on tip to fix the `ClusterInfoMapping.java` bit in the ZAP job.

**Comment by bzbarsky-apple** [comment]
> but I do know why this check caused error

Did you read the TSan output in the CI job?  Your code is reading mChipStackIsLocked while not holding the lock, which ends up with a data race: one thread is reading the boolean (not holding the lock) at the same time as another thread is writing the boolean (while holding the lock).  Which means that the answer you will get from the read will be random depending on how the threads race against each other.

In general, I don't understand what those changes are trying to do.  Obviously `mChipStackIsLocked` could be true when `_LockChipStack` is called!  That would indicate that some other thread is holding the lock, which is why we need a lock in the first place.

Now unlocking when not locked is in fact weird, and the check in `_UnlockChipStack` makes sense to add.  But the checks being added in `_TryLockChipStack` and `_LockChipStack` make no sense.

> I found that some _LockChipStack is called before _InitChipStack

So the thing we should really be checking in `_LockChipStack` and `_TryLockChipStack` is that the stack is initialized, right?

> and some unlock is called when is not locked.

Stack trace?
, and some unlock is called when is not locked.

**Comment by xylophone21** [comment]
> > but I do know why this check caused error
> 
> Did you read the TSan output in the CI job? Your code is reading mChipStackIsLocked while not holding the lock, which ends up with a data race: one thread is reading the boolean (not holding the lock) at the same time as another thread is writing the boolean (while holding the lock). Which means that the answer you will get from the read will be random depending on how the threads race against each other.
> 
> In general, I don't understand what those changes are trying to do. Obviously `mChipStackIsLocked` could be true when `_LockChipStack` is called! That would indicate that some other thread is holding the lock, which is why we need a lock in the first place.
> 
> Now unlocking when not locked is in fact weird, and the check in `_UnlockChipStack` makes sense to add. But the checks being added in `_TryLockChipStack` and `_LockChipStack` make no sense.
> 
> > I found that some _LockChipStack is called before _InitChipStack
> 
> So the thing we should really be checking in `_LockChipStack` and `_TryLockChipStack` is that the stack is initialized, right?
> 
> > and some unlock is called when is not locked.
> 
> Stack trace? And steps to reproduce? Please file an issue with this information and @-mention me in it.

Yes, that make sense, I debuged into this today, and found that 'unlock is called when is not locked' is in my pre code which is fixed now, so it is no problem now, thanks.

**Comment by xylophone21** [comment]
> > I should modify examples/tv-app/tv-common/tv-app.zap instead of zzz_generated/tv-app/zap-generated/CHIPClusters.cpp, but I do not know how to do it.
> 
> The simplest way, but takes some time to run, is `./scripts/tools/zap_regen_all.py`.
> 
> To just regenerate the `CHIPClusters.cpp` and `CHIPClusters.h` and other bits in `zzz_generated/tv-app/zap-generated`, you can run:
> 
> ```
> ./scripts/tools/zap/generate.py -t src/app/zap-templates/app-templates.json -o zzz_generated/tv-app/zap-generated examples/tv-app/tv-common/tv-app.zap
> ```
> 
> and generally speaking you can find out which template (`-t` argument) to use by doing `git grep CHIPClusters.cpp | grep json` or equivalent for the filename you want to regenerate and seeing which template file is involved. The `.zap` file to use varies depending on which app you need to generate for, and the `-o` value depends on where you want things to land in the tree.
> 
> You will also want to rebase on tip to fix the `ClusterInfoMapping.java` bit in the ZAP job.

Yes, I know it is from tv-app.zap and app-templates.json, but any document about zap format? Or I need to read its code?

While I debuged on this issue today and found that:
1. Why I need to added AdministratorCommissioningCluster in tv-app/CHIPClusters.h is not because I need it, but because of tv-zap -> src/controller/CHIPDevice.cpp::Device::OpenPairingWindow --> OpenCommissioningWindow --> cluster.OpenCommissioningWindow. Without it I met link issues
2. I tried to comment Device::OpenPairingWindow and Device::OpenCommissioningWindow, them the link issue is fixed. It means that in fact no one are using these function, but '--gc-sections'  seems does not work. I think it is the root case, and the right way is fix here. But I checked a lot, '--gc-sections'  and '-ffunction-sections -fdata-sections' are all included in commands. Am I missed anything?

**Comment by bzbarsky-apple** [comment]
> Yes, I know it is from tv-app.zap and app-templates.json, but any document about zap format? Or I need to read its code?

The .zap file is representing whatever was selected in the UI.  You can run the UI as:
```
./scripts/tools/zap/run_zaptool.sh examples/tv-app/tv-common/tv-app.zap
```
Presumably you would want to enable the client side of the administrator commissioning cluster there, and enable these commands.

> Without it I met link issues

Right, so your real issue is that Device::OpenPairingWindow is linked in and then pulls in all this other stuff.

> but '--gc-sections' seems does not work.

This is on Android?  Is that doing a static link or dynamic link?  `--gc-sections` is effectively a no-op for dynamic linking; it only does something useful if you do static linking..

**Comment by xylophone21** [comment]
> dynamic

Yes, it is android.

> > Yes, I know it is from tv-app.zap and app-templates.json, but any document about zap format? Or I need to read its code?
> 
> The .zap file is representing whatever was selected in the UI. You can run the UI as:
> 
> ```
> ./scripts/tools/zap/run_zaptool.sh examples/tv-app/tv-common/tv-app.zap
> ```
> 
> Presumably you would want to enable the client side of the administrator commissioning cluster there, and enable these commands.
> 
> > Without it I met link issues
> 
> Right, so your real issue is that Device::OpenPairingWindow is linked in and then pulls in all this other stuff.
> 
> > but '--gc-sections' seems does not work.
> 
> This is on Android? Is that doing a static link or dynamic link? `--gc-sections` is effectively a no-op for dynamic linking; it only does something useful if you do static linking..

Yes, android, I am doing some test on `--gc-sections`, looks you are right, it is not work on dynamic linking.

**Comment by xylophone21** [comment]
> > Yes, I know it is from tv-app.zap and app-templates.json, but any document about zap format? Or I need to read its code?
> 
> The .zap file is representing whatever was selected in the UI. You can run the UI as:
> 
> ```
> ./scripts/tools/zap/run_zaptool.sh examples/tv-app/tv-common/tv-app.zap
> ```

wow, it is amazing, thanks.

**Comment by xylophone21** [comment]
> > Yes, I know it is from tv-app.zap and app-templates.json, but any document about zap format? Or I need to read its code?
> 
> The .zap file is representing whatever was selected in the UI. You can run the UI as:
> 
> ```
> ./scripts/tools/zap/run_zaptool.sh examples/tv-app/tv-common/tv-app.zap
> ```
> 
> Presumably you would want to enable the client side of the administrator commissioning cluster there, and enable these commands.
> 
> > Without it I met link issues
> 
> Right, so your real issue is that Device::OpenPairingWindow is linked in and then pulls in all this other stuff.
> 
> > but '--gc-sections' seems does not work.
> 
> This is on Android? Is that doing a static link or dynamic link? `--gc-sections` is effectively a no-op for dynamic linking; it only does something useful if you do static linking..

I think I found some way to fix it, I added '-fvisibility=hidden' to all symbols and declare jni functions to JNIEXPORT (visibility=default)

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
Fast tracking, given platform specific code.

**Pull request merged**
