### PR TITLE
Use new (std::nothrow) instead of new where the result is checked aga…

### PR DESCRIPTION
**Pull request by vivien-apple**
…inst nullptr

#### Problem

Some code is expecting new to return `nullptr` without using `std::nothrow`

#### Change overview
 * Use `std::nothrow` 

#### Testing
I have just compiles it as it is not super convenient to test a failing new.

### CODE REVIEW

**Comment by andy31415** [comment]
@vivien-apple is this required for 1.0?

Please add 1.0 justification and link to an issue if applicable (generally changes after Aug 22 should have an issue unless hotfix or very small delta)

Do we really expect and will handle well new to fail? What happens if new fails currently?
My instinct would be to postpone this one after 1.0

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
> What happens if new fails currently?

If not using std::nothrow it will try to throw.   If the code is compiled with exceptions disabled (as Matter is), that will crash.

**Comment by vivien-apple** [comment]
> @vivien-apple is this required for 1.0?
> 
> Please add 1.0 justification and link to an issue if applicable (generally changes after Aug 22 should have an issue unless hotfix or very small delta)
> 
> Do we really expect and will handle well new to fail? What happens if new fails currently? My instinct would be to postpone this one after 1.0

As Boris says, the current code is making expectations about the behaviour of `new` that are wrong. `new` will not return `nullptr` unless `std::nothrow` is used so instead of failing with an error, the code will crash.

That said I agree that I don't know under which conditions this can happens unless there is no memory left on the device but since this is not a behaviour change but only making the SDK works as it was supposed to I would think it makes sense to add it into v1.0.
@andy31415 ^^

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
Approved for 1.0 with the logic of "fixes a crash" (throw crashing instead of nullptr).

it is a bit at the edge of approving: platforms which compile this code are extremely unlikely to run out of memory (most code is assuming embedded so should be reasonably low on resource consumption for android/darwin/linux/etc.

**Pull request merged**
