### PR TITLE
Ignore resolved interface IDs for non-LinkLocal IPv6 Addresses

### PR DESCRIPTION
**Pull request by sagar-apple**
#### Problem
We rely on the mDNS resolution to tell us what the peer node's address is. 

We also pickup the interface ID of the mDNS resolution and then use that interface ID for communicating with that node. This seems to have been added to support IPv6 LLAs which require us to specify which interface to use when communicating with a node's ULA.

For bridged networks like Thread, the mDNS advertisement might not be visible on the same interface the peer is reachable on. 

We should avoid setting the interface ID for non-LLA addresses because the sender's routing table should be able to figure out the interface ID correctly. 

#### Change overview
Ignore the interface ID of the mDNS resolution if the resolved address is not an IPv6 LLA. 

#### Testing
How was this tested? (at least one bullet point required)
* If manually tested, what platforms controller and device platforms were manually tested, and how?
Tested pairing and control with the CHIP Tool CLI and an m5 stack + nRF5.

### CODE REVIEW

**Review by tcarmelveilleux — APPROVED** [review]

**Review by mspang — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
@saurabhst ?

**Review by saurabhst — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]
This seems fine, though I wonder whether we should be doing this in the mdns impl instead of at just this consumer....

**Comment by sagar-apple** [comment]
> This seems fine, though I wonder whether we should be doing this in the mdns impl instead of at just this consumer....

mDNS isn't doing anything wrong here, we're just misusing the information that comes off of it.

**Comment by bzbarsky-apple** [comment]
> mDNS isn't doing anything wrong here, we're just misusing the information that comes off of it.

Yes, but this is a fixup all consumers will need to do....

**Comment by woody-apple** [comment]
Yes, I would expect most platforms have a stream of mDNS information coming back to them, assuming you know it all after X seconds, in one block seems... like a bad assumption.

**Pull request merged**
