### PR TITLE
Copy shared libstdc++ as part of the build step for android.

### PR DESCRIPTION
**Pull request by andy31415**
#### Problem
Android libs require a copy of libc++-shared.so

 #### Summary of Changes
Copy over the relevant library as part of the build.

### CODE REVIEW

**Review by saurabhst — APPROVED** [review]

**Review by mspang — CHANGES_REQUESTED** [review]
There's more to this, see #2680 (static libc++ has caveats that must be accounted for, see NDK documentation)

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by mspang** [comment]
> see NDK documentation

https://developer.android.com/ndk/guides/cpp-support

**Review by vidhis88 — APPROVED** [review]
Thank you!

**Comment by andy31415** [comment]
> There's more to this, see #2680 (static libc++ has caveats that must be accounted for, see NDK documentation)

Ah, I was only going after the readme comment of 'automake needs fixing' .... and I changed the build system.

Will see what can be done about the rest.

**Review by rwalker-apple — APPROVED** [review]

**Review by wgtdkp — APPROVED** [review]

**Comment by andy31415** [comment]
> > There's more to this, see #2680 (static libc++ has caveats that must be accounted for, see NDK documentation)
> 
> Ah, I was only going after the readme comment of 'automake needs fixing' .... and I changed the build system.
> 
> Will see what can be done about the rest.

The NDK docs say:

```
In general, you can only use a static variant of the C++ runtime if you have one and only one shared library in your application.
```

This may be reasonably hard. We currently have: setuppayload, controller and ot-commisioner. We can probably merge controller and setuppayload (GN built) but openthread merge may be hard.

We may be better of by just copying the share so for now.

**Comment by andy31415** [comment]
Ready for re-review: after seeing NDK limitations, we have more than one SO so it is not practical to statically link :(

**Comment by andy31415** [comment]
I cleared all the code reviews: this is brand new code, just reused the branch.

**Review by rwalker-apple — APPROVED** [review]

**Review by mspang — APPROVED** [review]

**Comment by mspang** [comment]
> Ready for re-review: after seeing NDK limitations, we have more than one SO so it is not practical to statically link :(

We can do it, as long as we unexport all of the symbols. Although I don't know why we need two libraries, I asked @vidhis88 about this before and I think we can merge them.

**Comment by andy31415** [comment]
> > Ready for re-review: after seeing NDK limitations, we have more than one SO so it is not practical to statically link :(
> 
> We can do it, as long as we unexport all of the symbols. Although I don't know why we need two libraries, I asked @vidhis88 about this before and I think we can merge them.

The way things are it looks more like a build tree separation that causes 2 libraries - it is convenient, however we can really join them.

Still unsure about ot-commisioning (I was told it will be at least partially needed). even today, static link does not make the app crash for me, so we can switch if it turns out to make sense. 

My personal annoyance was the extra awkward rsync. After this PR my dev flow will be better at least.

**Pull request merged**
