### PR TITLE
Fix exchange manager test to not NewPairing on an uninitialized SecureSessionManager.

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
#### Problem
Tests fail because of a bad interaction between https://github.com/project-chip/connectedhomeip/pull/3640 and https://github.com/project-chip/connectedhomeip/pull/3923

 #### Summary of Changes
Fix test to initialize the object before using it.

### CODE REVIEW

**Review by rwalker-apple — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
I do wonder why this was not failing in CI, just locally.  That seems pretty odd.

**Comment by bzbarsky-apple** [comment]
It wasn't failing in CI because we were reading out of bounds memory, so the behavior was random.  https://github.com/project-chip/connectedhomeip/pull/3940 will fix that.

**Review by saurabhst — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
@jelderton @mspang @andy31415 Please take a look?

**Review by jelderton — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
Looks like this got fixed in #3704

**Pull request closed without merging**
