### PR TITLE
[linux] Fix server KVS init

### PR DESCRIPTION
**Pull request by erjiaqing**
#### Problem

We forget to init KVS for Linux in https://github.com/project-chip/connectedhomeip/pull/6309, which is breaking chip-tool/chip-device-controller in real and cirque test

 #### Summary of Changes

Add it.

### CODE REVIEW

**Review by saurabhst — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
@andy31415 ? @msandstedt ? @mspang ? Apparently this is blocking CSG testing using the python controller

**Comment by woody-apple** [comment]
@Damian-Nordic @jepenven-silabs ?

**Comment by woody-apple** [comment]
Removing hot fix, as this doesn’t break the build. We may have to re-evaluate the rules/requirements for it. However if this is breaking python tooling, we should have CI in place to catch it reliably.

**Comment by erjiaqing** [comment]
> Removing hot fix, as this doesn’t break the build. We may have to re-evaluate the rules/requirements for it. However if this is breaking python tooling, we should have CI in place to catch it reliably.

The CI test for Python was removed with cirque eariler.

**Comment by woody-apple** [comment]
> > Removing hot fix, as this doesn’t break the build. We may have to re-evaluate the rules/requirements for it. However if this is breaking python tooling, we should have CI in place to catch it reliably.
> 
> The CI test for Python was removed with cirque eariler.

Yup, as you’ve been working on, due to the reliability. Hopefully we can get it back up soon!

**Comment by woody-apple** [comment]
> > > Removing hot fix, as this doesn’t break the build. We may have to re-evaluate the rules/requirements for it. However if this is breaking python tooling, we should have CI in place to catch it reliably.
> > 
> > 
> > The CI test for Python was removed with cirque eariler.
> 
> Yup, as you’ve been working on, due to the reliability. Hopefully we can get it back up soon!

Alternatively - as a good point we should ask how things are tested for these changes. I’m assuming manual testing would have caught this?

**Comment by woody-apple** [comment]
@cjandhyala confirmed this is tested. Broken before, and working after. Allowing force merge.

**Pull request merged**
