### PR TITLE
Update ZAP to tip

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
#### Problem
Need some functionality that has been added in ZAP.

#### Change overview
Update ZAP to today's tip.

#### Testing
Reran codegen, verified there were no changes.

### CODE REVIEW

**Review by erjiaqing — CHANGES_REQUESTED** [review]
I also found 
```
🕐 File loading time: 136ms
TypeError: queryEndpoint.selectEndPointTypeIds is not a function
```

When update ZAP to tip, we need some changes to local helpers.

**Comment by bzbarsky-apple** [comment]
> TypeError: queryEndpoint.selectEndPointTypeIds is not a function

Huh.  Why is that not making generation fail????  @tecimovic @vivien-apple

**Comment by bzbarsky-apple** [comment]
Note that #8627 makes a lot of the same changes; I might just wait for that to merge first....

**Comment by bzbarsky-apple** [comment]
Addressed in #8627

**Pull request closed without merging**
