### PR TITLE
Add support for "commisionable" discovery advertisement

### PR DESCRIPTION
**Pull request by arunbharadwaj**
#### Problem
We need support for "commisionable" discovery advertisement according to Discovery spec for CHIP

 #### Summary of Changes
This adds support for "commisionable" discovery advertisement.

This builds on top of PR #4200 which adds "commisioning" and "operational" discovery advertisements
This adds the Advertise() function in lib/mdns/Advertiser_ImplMinimalMdns.cpp to advertise service as _chipd._udp while running in commisionable mode.
This also adds the class CommisionableAdvertisingParameters which additionally contains pairingInstr and pairingHint
Finally, this adds some test code in the  example/minimal-mdns/advertiser.cpp to test this mode.

### CODE REVIEW

**Comment by rwalker-apple** [comment]
This has the commits from #4200, right?

Would you mind re-requesting review once that's landed and this PR is rebased so we can examine your changes in isolation?

**Review by rwalker-apple — COMMENTED** [review]
.

**Comment by arunbharadwaj** [comment]
> This has the commits from #4200, right?
> 
> Would you mind re-requesting review once that's landed and this PR is rebased so we can examine your changes in isolation?

Yes, I will rebase this PR once #4200 is merged.

For now, posted here to get some early feedback.

**Comment by andy31415** [comment]
@arunbharadwaj - I believe #4200 has been merged and this should be ready for rebase/merge

**Comment by arunbharadwaj** [comment]
Created a new PR #4337 as there were too many merge conflicts after rebasing. Closing this PR.

**Pull request closed without merging**
