### PR TITLE
Update IM status code IB

### PR DESCRIPTION
**Pull request by yunhanw-google**
#### Problem
Need to align with IM encoding spec, where we only have status and cluster status for status IB(Information Block). 

#### Change overview
In this PR, we rewrite statusIB which is tlv structure and can handle both status and cluster status.

For add status api in command and write, it roughly do 3 things
1. Add a meaningful general status and no cluster-specific status, 
AddStatus(ConcreteCommandPath, Protocols::InteractionModel::Status), This one is implemented.
2. Add a general SUCCESS and a cluster-specific status,
   AddClusterSpecificSuccess(ConcreteCommandPath, uint8_t). Add the declaration, not implemented in this PR.
3. Add a general FAILURE and a cluster-specific status.
AddClusterSpecificFailure(ConcreteCommandPath, uint8_t). Add the declaration, not implemented in this PR.

#### Testing
Existing testing covers.

### CODE REVIEW

**Review by jmartinez-silabs — APPROVED** [review]

**Review by msandstedt — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
General question: what does 'IB' mean?

I saw this in another PR. The namespace of `chip::app::StatusIB` tells me it is for 'Status' however the IB part is still unclear to me. 
I see the namespace contains Type, Parser and Builder. Why not just 'Status' or some nesting of `chip::app::DataModel::Status`?

**Comment by bzbarsky-apple** [comment]
> General question: what does 'IB' mean?

@andy31415 "Information Block".  See the spec.

**Comment by bzbarsky-apple** [comment]
And yes, we should not have `StatusIB::Type`.  We should just have `StatusIB`, and the parser/builder can be classes defined inside that class if needed.  That's a separate cleanup from this PR, though.

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]
See comments.

**Review by msandstedt — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]

**Pull request merged**
