### PR TITLE
Add CI tests for fake platform

### PR DESCRIPTION
**Pull request by kghost**
#### Problem
Fake platform is not verified by GitHub CI.

#### Change overview
Run CI tests for fake platform on GitHub Action

#### Testing
Verified using unit-tests

### CODE REVIEW

**Review by woody-apple — CHANGES_REQUESTED** [review]
What is fake platform? This doesn’t appear in CI

**Review by woody-apple — CHANGES_REQUESTED** [review]
What is fake platform? If we’re adding new platforms we should be clear what they are

**Comment by kghost** [comment]
> What is fake platform? This doesn’t appear in CI

We have a fake platform under `src/platform/fake`

This part is build using `./gn_build.sh`, but it is not verified by GitHub CI tests. This PR will ensure that this part is tested in GitHub CI.

Currently `./gn_build.sh` fails due to some error in fake platform implementation. I'm updating build files to trigger the build now, expecting a failure CI run. I'll update the fix soon.

**Comment by woody-apple** [comment]
Thanks, please add CI to the main project here to catch this. We are currently not tracking any “fake platform”, if there’s work needed, we should track it, and make sure CI validates it.

**Comment by kghost** [comment]
> Note: for all platforms we need at least one example app as well, or tests for it.

The fake platform is only used for unit-tests. Example apps probably don't run well with fake platform. All unit-tests run well with fake platform.

**Comment by woody-apple** [comment]
What is fake platform adding over Linux?

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by kghost** [comment]
> What is fake platform adding over Linux?

I think it is platform independent. All its implementation functions are just returning unsupported.

**Comment by woody-apple** [comment]
> > What is fake platform adding over Linux?
> 
> I think it is platform independent. All its implementation functions are just returning unsupported.

This will add CI cost and time. Can we get this same value using Linux?

**Comment by kghost** [comment]
> This will add CI cost and time. Can we get this same value using Linux?

Not sure about the potential of the fake platform. Its implementation is much more pure and simple than Linux. Sometime it can help us analysis whether a unit-tests failure is platform dependent or not.

The discussion may be outside the scope of this PR. We already got the code, and lots of scripts are using it, then we should introduce CI to cover it.

**Comment by kghost** [comment]
It fails as expected.

https://github.com/project-chip/connectedhomeip/runs/4480120957?check_suite_focus=true

**Review by yunhanw-google — APPROVED** [review]

**Comment by andy31415** [comment]
@woody-apple I believe fake platform was primarely used to test mdns, so that it provides some abstractions that are not a real underlying system in #8946

Generally it is intended to test that calls to platform code occur as expected.Realistically I believe it is to be considered a 'validate that mdns works'.

**Comment by andy31415** [comment]
In #12887 I also enabled build_examples to be able to build and run tests for both current platform and fake.

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
We should pick a better name than fake if it’s for mdns, I’m still curious why Linux doesn’t cover this…

**Review by xylophone21 — APPROVED** [review]

**Comment by kpschoedel** [comment]
> What is fake platform adding over Linux?

One difference is that it uses the config defaults, from which every actual platform diverges. This caught a mistake in a test I added last week.

**Comment by cecille** [comment]
Apologies all - missed this before I went on vacation. Fake platform is for unit testing - it's a stub platform that can catch and check data that's sent to the platform layer. Right now the only test implemented is mdns, but it's not mdns specific. It is used to test that the data / commands etc. sent to the platform layer are correct.

**Pull request merged**
