### PR TITLE
[BL602] Update button, not use dts to init

### PR DESCRIPTION
**Pull request by jczhang777**
#### Problem
What is being fixed?  Examples:
* Update button to support factory reset.

#### Change overview
Update button to support factory reset.

#### Testing
How was this tested? (at least one bullet point required)
* Long press the reset button for at least 5s, the light will blink.

### CODE REVIEW

**Review by woody-apple — CHANGES_REQUESTED** [review]
We do not support flows of working on a branch, please keep work to a fork.

**Comment by jczhang777** [comment]
> We do not support flows of working on a branch, please keep work to a fork.

Thank you very much for your reply.This branch is forked from the interop_testing_te9 with a different name.Is that ok?

**Comment by jczhang777** [comment]
> We do not support flows of working on a branch, please keep work to a fork.

https://github.com/project-chip/connectedhomeip/pull/20929

**Comment by jczhang777** [comment]
> We do not support flows of working on a branch, please keep work to a fork.

https://github.com/project-chip/connectedhomeip/pull/20929     I have resubmitted the PR, please check it.

**Comment by jczhang777** [comment]
> We do not support flows of working on a branch, please keep work to a fork.

we are not quite understand, do you mean the interop_testing_te9 branch no longer accept changes? or we need to use a new branch in our forked repo, instead of "interop_testing_te9"?
The changes in this PR have already been merged into master branch, and as usual, we want to merge these changes into the interop_testing_te9 branch.

**Comment by jczhang777** [comment]
> We do not support flows of working on a branch, please keep work to a fork.

Google will use the branch until October. This change is necessary. Is it possible to merge this PR?

**Pull request closed without merging**
