### PR TITLE
[LICENSING][REUSE]Add REUSE tool to CI

### PR DESCRIPTION
**Pull request by aalexanderr**
There are no [file/dir exclusions for REUSE](https://reuse.software/faq/#exclude-file) and no increment checking thus this job is currently with 
```continue-on-error: true```
until REUSE compliance is achieved.

related: #27894

### CODE REVIEW

**Review by woody-apple — CHANGES_REQUESTED** [review]
All submissions to this repository must be Apache 2 licensed, and can you please elaborate what this is for?

**Comment by aalexanderr** [comment]
@woody-apple :
- I just reused the license that this trivial file came in with from their readme (https://github.com/marketplace/actions/reuse-compliance-check ) 
I will ask the authors if its ok to have it as Apache-2.0, otherwise I will switch this job to use fsfe docker image directly I guess

This is for switching to REUSE.software, I talked about it on calls in december 2022, there was a PR https://github.com/project-chip/connectedhomeip/pull/23561 here that went stale when I was on long sick leave.

There is also issue linked explaining what happened for now, linking to the initial issue that, like the PR went stale.

**Comment by aalexanderr** [comment]
Shortly what this PR introduces: Allows tracking of REUSE compliance starting from now. Next PR will be switching Apache license headers to shortrefs where such are available in the repository, I will push it tomorrow.

**Comment by andy31415** [comment]
> @woody-apple :
> 
> * I just reused the license that this trivial file came in with from their readme (https://github.com/marketplace/actions/reuse-compliance-check )
>   I will ask the authors if its ok to have it as Apache-2.0, otherwise I will switch this job to use fsfe docker image directly I guess
> 
> This is for switching to REUSE.software, I talked about it on calls in december 2022, there was a PR #23561 here that went stale when I was on long sick leave. some additional memory-joggers: spdx shortref, touching every file in the repository, clear licensing for everything (not just code but docs etc too) AFAIK adoption of REUSE was approved by TSC somewhere between Dec '22 and Jan '23
> 
> There is also issue linked explaining what happened for now, linking to the initial issue that, like the PR went stale.

I believe it seems reasonable to be able to use examples to build our own CI, so instead of copying the whole thing, given it is trivial, please write it specifically for the SDK (so it can get an apache2 license) and then we do not have this worry.

I would prefer a path of "you cannot copy & paste unless you can relicense" instead of allowing various files to have differing licenses. "all is apache2" seems much simpler.

**Comment by aalexanderr** [comment]
@andy31415, @woody-apple  i feel dumb but well, this time i wrote it myself, license is apache and copy is for CHIP Authors.

**Review by arkq — APPROVED** [review]

**Comment by arkq** [comment]
For those who do not know what this CI workflow will provide. It will show the current status of REUSE spec compliance in the project. As for now the status looks like this:
```
# SUMMARY

* Bad licenses:
* Deprecated licenses:
* Licenses without file extension:
* Missing licenses: Apache-2.0, BSD-3-Clause, Zlib
* Unused licenses:
* Used licenses: Apache-2.0, BSD-3-Clause, Zlib
* Read errors: 0
* Files with copyright information: 7540 / 12142
* Files with license information: 71 / 12142

Unfortunately, your project is not compliant with version 3.0 of the REUSE Specification :-(
```

**Comment by aalexanderr** [comment]
current output of reuse:
```
# SUMMARY

* Bad licenses:
* Deprecated licenses:
* Licenses without file extension:
* Missing licenses:
* Unused licenses:
* Used licenses: Apache-2.0, BSD-3-Clause, Zlib
* Read errors: 0
* Files with copyright information: 7923 / 12813
* Files with license information: 70 / 12813

Unfortunately, your project is not compliant with version 3.0 of the REUSE Specification :-(
```

I have added licenses found already (had SPDX shortref) to this PR

**Pull request closed without merging**
