### PR TITLE
ZAP embedded layer: cleanup, proper layering for codec and PAL integration

### PR DESCRIPTION
**Pull request by tecimovic**
#### Summary
Previous state of the app layer made little sense, as it was mostly a direct dump of two different Silicon Labs application layers. It required a cleanup of directory structure, and creation of API layers that will allow integration with CHIP specific codec, downward integration with platform and network transport layer and upward integration with the end-developer callbacks that process the received commands.
This PR is a step forward in proper organization and allows other developers to start contributing codecs, for example.

`make` and `make test` at the `src/app` level should work.

 #### Changes

- Much renaming: The previous renaming of directories was just a direct drop, we can do better. The plugins now have a meaningful prefix that categorizes them.
- API extraction: The headers are making some sense now.
- Plugins: all the code is in plugins now. Earlier there were few incomprehensible directories lying around, which were created ad-hoc because the code was just created out of the blue.
- Better unit tests that actually do something. (Though not enough yet.)

 #### Todos

- Solve the problem of using generated layer in a compiled form.
- Integrate with the overall build system. Currently there is tons of Makefiles lying around, which should in the long run all be generated as they are boilerplate.
- Remove the utest.* files from plugins. There should be a centralized unit testing plugin, no point polluting all the plugins with this.
- Add generation tooling for plugins and generated code = integrate zap UI and zap generator with all this.
- Properly integrate StructSpec and Struct layers to achieve library-based encoding/decoding of ZCL commands. Currently that is not yet done.
- Abstract out attribute database from the data model. They are kind intertwined now, but there is no reason why the attribute DB could not be abstracted and bound to a simple implementaiton.
- Many other things. (No kidding!)

### CODE REVIEW

**Review by bhaskar-apple — COMMENTED** [review]
LGTM
@tecimovic - thanks for this. Would you also please file GitHub issues tracking the remaining work for demo 1.

**Review by woody-apple — APPROVED** [review]

**Review by rwalker-apple — COMMENTED** [review]
lgtm

**Review by bhaskar-apple — COMMENTED** [review]
LGTM

**Review by hawk248 — APPROVED** [review]
ok

**Review by jelderton — APPROVED** [review]

**Pull request merged**
