### PR TITLE
Remove DeviceNetworkProvisioningDelegate interface to force vendor to use NetworkCommissioning interface…

### PR DESCRIPTION
**Pull request by yufengwangca**
Currently, we have two interfaces to provision WiFi, ScanNetworks/AddOrUpdateNetwork APIs in NetworkCommissioning drivers and ProvisionWiFi within DeviceNetworkProvisioningDelegate. DeviceNetworkProvisioningDelegate interfaces are not used except example shell command.

To prevent confusion, we should remove DeviceNetworkProvisioningDelegate interface

Solution:
Remove DeviceNetworkProvisioningDelegate interface to force vendor to use NetworkCommissioning interface.

### CODE REVIEW

**Review by Damian-Nordic — COMMENTED** [review]
Is this class used at all? I thought I switched to using NetworkCommissioning drivers. The only usage of `ProvisionWifi` I could find is some shell command and `ProvisionThread` is not used at all. Shouldn't we rather remove the class?

**Comment by yufengwangca** [comment]
> Is this class used at all? I thought I switched to using NetworkCommissioning drivers. The only usage of `ProvisionWifi` I could find is some shell command and `ProvisionThread` is not used at all. Shouldn't we rather remove the class?

Yes, this API is not used in any example app, but one of my internal product team has asked question about this, if we have alternative solution in NetworkCommissioning drivers, then we should remove this redundant APIs

**Comment by yufengwangca** [comment]
> 

@Damian-Nordic I found the NetworkCommissioning drivers provides ScanNetworks/AddOrUpdateNetwork APIs which can do the similar stuff, but only ProvisionWiFi within DeviceNetworkProvisioningDelegate could trigger the ProvisionWiFiNetwork API in ConnectivityMgr directly. This is higher level API used to connect to an access point in one shot. We also have example in chip_shell demonstrate how to use this API. Shall we keep it for now?

**Comment by yufengwangca** [comment]
> > 
> 
> @Damian-Nordic I found the NetworkCommissioning drivers provides ScanNetworks/AddOrUpdateNetwork APIs which can do the similar stuff, but only ProvisionWiFi within DeviceNetworkProvisioningDelegate could trigger the ProvisionWiFiNetwork API in ConnectivityMgr directly. This is higher level API used to connect to an access point in one shot. We also have example in chip_shell demonstrate how to use this API.

After second thought, if we provide two ways to do the similar thing, it will confuse the platform vendors, maybe you are right, by removing DeviceNetworkProvisioningDelegate API, we can force vendors to use  NetworkCommissioning drivers to provision WiFi.

**Comment by Damian-Nordic** [comment]
> After second thought, if we provide two ways to do the similar thing, it will confuse the platform vendors, maybe you are right, by removing DeviceNetworkProvisioningDelegate API, we can force vendors to use NetworkCommissioning drivers to provision WiFi.

Yes, if the NetworkCommissioning API is suitable for other needs, too, I think it would be better to remove DeviceNetworkProvisioningDelegate. Mostly because it is currently not tested by any CI tests.

**Review by Damian-Nordic — APPROVED** [review]

**Review by emargolis — APPROVED** [review]

**Pull request merged**
