### PR TITLE
Add endpoint id to command callback handler's param list 

### LINKED ISSUE #5098: [IM] Add Command object and endpoint id to params of current command handlers
**Problem**

Then it will be better to fix the current commands handlers to have a new parameter for it in a separate PR.
Please remove `src/app/clusters/im-compatibility`, it introduce a new generated folder in `src/` and creates a level of indirection that does not seems really needed.

_Originally posted by @vivien-apple in https://github.com/project-chip/connectedhomeip/pull/5032#discussion_r585391808_

Currently, the commands are using a global emberApsFrame & emberAfCluster object, this does not meet the needs of the requirement of CHIP datamodel.

The IME provideds a Command* object, and the command handlers in the future should be able to make use of them.

### PR DESCRIPTION
**Pull request by yufengwangca**
#### Problem
What is being fixed?  Examples:
* Now we have introduced new helper functions defined in the attributes/Accessors.h to manipulate attributes. To use those auto-generated helper functions, we need to pass endpoint to command callback handlers.
* Fixes #5098

#### Change overview
Add endpoint id to command handler's param list

#### Testing
How was this tested? (at least one bullet point required)
This PR just update the prototype of command callback handler with endpoint parameter, no logic change. regression check is done by current CI

### CODE REVIEW

**Comment by andy31415** [comment]
CI failure may be legitimate

**Review by bzbarsky-apple — COMMENTED** [review]
I would think the `chip::` prefix is not needed most of the places it's being used here, since those files are doing `using namespace chip`.  Please take it out where possible.

**Review by bzbarsky-apple — APPROVED** [review]
And I guess with the `chip::` removed looks fine.

**Comment by mrjerryjohns** [comment]
What about the other parameters as part of the command that need to be passed in? These include 'SuppressResponse' and whether it's a group targeted endpoint or not.

All of those should really be encapsulated within some kind of command params struct to avoid increasing the # of args being passed into functions (which already is quite high...).

**Comment by yufengwangca** [comment]
> I would think the `chip::` prefix is not needed most of the places it's being used here, since those files are doing `using namespace chip`. Please take it out where possible.

I found the  `chip::` prefix is used throughout template file *.zapt in which has 'using namespace chip', such as:
EmberAfStatus emberAf{{asUpperCamelCase label}}ClusterClientPreAttributeChangedCallback(chip::EndpointId endpoint, chip::AttributeId attributeId, EmberAfAttributeType attributeType, uint16_t size, uint8_t * value);

I have registered ticket https://github.com/project-chip/connectedhomeip/issues/8658 to clean them up all together in a separate PR.

**Comment by yufengwangca** [comment]
> What about the other parameters as part of the command that need to be passed in? These include 'SuppressResponse' and whether it's a group targeted endpoint or not.
> 
> All of those should really be encapsulated within some kind of command params struct to avoid increasing the # of args being passed into functions (which already is quite high...).

What is the use case of those params, are they common thought all command callback handler? currently, we have #zcl_command_arguments to encapsulate all params for a command, but those command params varies from function to function. How to refactor them to a struct and pass to different commands is a challenge.

**Review by Damian-Nordic — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
> I found the chip:: prefix is used throughout template file *.zapt in which has 'using namespace chip'

@yufengwangca I was specifically talking about the non-generated code, for what it's worth.  Cleaning this up in generated code is nice, but cleaning it up in non-generated code (all the cluster impls) is a must, imo.

**Pull request merged**
