### PR TITLE
Tool to check the copyright years on the files and a build to auto fix the issue on PR merge

### PR DESCRIPTION
**Pull request by aajain-com**
#### Problem
Copyright years on the files should reflect the year in which it is modified.

#### Change overview
- A tool to check and fix the copyright years on the file with the year it was modified. 
- A CI build to update the copyright year once a PR merges. NOTE: The CI build doesn't block a PR and runs on pushes.

#### Testing
How was this tested? (at least one bullet point required)
* Ran the tool locally on the source code to find and fix all the existing issues.

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]

**Comment by aajain-com** [comment]
@woody-apple the issue with getting the year in which a file was modified is now resolved. The issue was that by default GitHub Actions was cloning the file with depth of 1 while we needed the entire history.

**Comment by woody-apple** [comment]
@aajain-com I see the script can correct the errors, can it also push changes back? You can look at zap_regeneration.yaml as an example workflow that pushes back changes!

**Comment by aajain-com** [comment]
> @aajain-com I see the script can correct the errors, can it also push changes back? You can look at zap_regeneration.yaml as an example workflow that pushes back changes!

Currently it doesn't. I can look into it as a subsequent PR if that is not an essential feature.

**Comment by woody-apple** [comment]
@aajain-com Sounds good. Approved. (Please clean up conflicts and folks can review!)

**Review by andy31415 — CHANGES_REQUESTED** [review]
Please do not add a CI step to enforce copyright year. This would force all developers to update a comment every  new year, which seems just busy work.

if you did not add a CI step, please update your summary.

**Comment by woody-apple** [comment]
@aajain-com I think the request here is to make this auto fix as part of this PR, so it doesn't impact other developers with other files as they get changed. Please let me know if you need help with the GitHub CI pushing back changes (it looks like the script supports it).

**Comment by aajain-com** [comment]
> Please do not add a CI step to enforce copyright year. This would force all developers to update a comment every new year, which seems just busy work.

> if you did not add a CI step, please update your summary.

@andy31415 I updated the tool to not fail a CI build and instead auto correct and auto commit the fix after the PR merges. Please re-review.

**Comment by andy31415** [comment]
@aajain-com - please confirm that this was an explicit requirement of lawyers (please specifiy which company). Trying to ensure our work is guided by some requirement here.

**Pull request closed without merging**
