### PR TITLE
Changed the lower limit of the deadband to 0 to match the spec

### PR DESCRIPTION
**Pull request by drempelg**
#### Problem
The dead band hand a lower limit that didn't match the spec.  Spec says it should be 0.  Fixed

#### Change overview
modified the xml to reflect it's true limits.

Regenerated all the pre-generated stuff in the repo.

#### Testing
Tested on our DUT, was able to set the dead band attribute to 0.

### CODE REVIEW

**Review by bzbarsky-apple — APPROVED** [review]
Note: this needs restyle run on the generated Commands.h, because local clang-format and restyle disagree on the right style....

**Comment by andy31415** [comment]
@drempelg - needs zap regeneration

**Comment by bzbarsky-apple** [comment]
> @drempelg - needs zap regeneration

No, needs the restyle thing...  We really need to sort out why the pigweed clang-format locally has started producing different results from the restyle job and from whatever clang-format runs in CI.

**Comment by mlepage-google** [comment]
> > @drempelg - needs zap regeneration
> 
> No, needs the restyle thing... We really need to sort out why the pigweed clang-format locally has started producing different results from the restyle job and from whatever clang-format runs in CI.

Yeah I started getting hit by that too, annoying.

**Comment by drempelg** [comment]
what is going on with those tests?  I don't think the failure has anything to do with my changes....does it?  Seems like a multi fabric problem?

**Comment by andy31415** [comment]
> what is going on with those tests? I don't think the failure has anything to do with my changes....does it? Seems like a multi fabric problem?

Looks like passing now.  I believe for darwin the theory is that there is crosstalk between CI instances - VMs are supposed to be isolated however they seem not to be. #17087 attempts to fix this.

**Review by tcarmelveilleux — APPROVED** [review]

**Pull request merged**
