### PR TITLE
fix parameter error in 32 bits system

### PR DESCRIPTION
**Pull request by xylophone21**
#### Problem
* MediaPlaybackManager::Request get error mediaPlaybackRequest id in 32 bits system

#### Change overview
* The jni parameter should be a jint (32 bits) but set to long (64 bits)

#### Testing
* chip-tool mediaplayback media-seek

### CODE REVIEW

**Comment by xylophone21** [comment]
hello?

**Review by chrisdecenzo — APPROVED** [review]

**Review by electrocucaracha — APPROVED** [review]
/lgtm

The [first parameter](https://github.com/project-chip/connectedhomeip/blob/master/examples/tv-app/android/java/src/com/tcl/chip/tvapp/MediaPlaybackManager.java#L120-L121) represents the response status code

**Review by msandstedt — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Comment by xylophone21** [comment]
hello, is there anything I can do here?

**Pull request merged**
