### PR TITLE
Add IM event urgency option support

### PR DESCRIPTION
**Pull request by yunhanw-google**
#### Problem
IM Event has urgent option which means event needs to be sent via report immediately, add this support in report engine and event management.
#### Change overview
see above

#### Testing
Update the subscription test to check if the corresponding handler is dirty and report can be sent immediately without block when interested urgent event has been generated.

### CODE REVIEW

**Review by woody-apple — CHANGES_REQUESTED** [review]
Can we get some YAML tests here? Feels like this needs some end to end testing.

**Comment by yunhanw-google** [comment]
@woody-apple  currently IM event server support is not ready, pending PR for https://github.com/project-chip/connectedhomeip/pull/12059, no example integration for IM eventing so far. I am only able to test with unit test.

Per chat, Vivien would take care of Yaml test with eventing

**Comment by yunhanw-google** [comment]
> @woody-apple currently IM event server support is not ready, pending PR for #12059, no example integration for IM eventing so far. I am only able to test with unit test.
> 
> Per chat, Vivien would take care of Yaml test with eventing
@woody-apple  the yaml and chiptool testing work has been tracked on https://github.com/project-chip/connectedhomeip/issues/12460

**Review by yufengwangca — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]

**Comment by woody-apple** [comment]
Given this is only client, we can't do end to end it seems. When there is a server, please make sure the server has end to end tests in place.

**Review by woody-apple — APPROVED** [review]

**Comment by yunhanw-google** [comment]
> Given this is only client, we can't do end to end it seems. When there is a server, please make sure the server has end to end tests in place.

sure, thanks

**Pull request merged**
