### PR TITLE
[Cirque] Use session instead of screen to start flask

### PR DESCRIPTION
**Pull request by kghost**
#### Problem
* Sometime flask is not properly stopped after running cirque test.
* Using `ps | grep | kill` is not safe

#### Change overview
Use session instead of screen to start flask

#### Testing
* Manually tested with cirque script

### CODE REVIEW

**Review by saurabhst — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]

**Review by yunhanw-google — APPROVED** [review]

**Comment by woody-apple** [comment]
@Damian-Nordic @jepenven-silabs @mspang ?

**Comment by woody-apple** [comment]
@kghost  Note: these are real build failures

**Comment by yunhanw-google** [comment]
this pr is only updating the cirque script, which should not impact darwin at all, darwin is still failing, maybe rebase?

**Review by yunhanw-google — APPROVED** [review]
Thanks

**Review by jelderton — APPROVED** [review]

**Review by msandstedt — APPROVED** [review]

**Pull request merged**
