### PR TITLE
Bump pip-tools to 7.0.0

### PR DESCRIPTION
**Pull request by AnthonyDiGirolamo**
Pip v23.2 broke pip-tools, there is a fix in 7.0.0. This change also pins pip and setuptools to prevent future breakages.

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]
@AnthonyDiGirolamo is there a way to have constraints include cython for example?

**Comment by andy31415** [comment]
> @AnthonyDiGirolamo is there a way to have constraints include cython for example?

We may miss it now. I believe this PR has two things against cython:
 - it is build with python 3.11
 - even if built with python 3.9, we removed gdbgui which removes gevent which removes cython

**Comment by woody-apple** [comment]
> > @AnthonyDiGirolamo is there a way to have constraints include cython for example?
> 
> We may miss it now. I believe this PR has two things against cython:
> 
> * it is built with python 3.11 (gdbgui was excluded in that version)
> * even if built with python 3.9, we removed gdbgui which removes gevent which removes cython

Sure, but I'm guessing the python deps are larger than this requirements set? It seems awfully small for the surface area we have.

**Comment by AnthonyDiGirolamo** [comment]
I believe we could add this to requirements.all.txt

cython==0.29.36 ; python_version < "3.11"
cython==3.0.0 ; python_version >= "3.11"

Then just remove `--strip-extras` when running pip-compile.

Note I don't know if that's the right version to check for cython. Was just trying to pick one version for python 3.11 and a separate for 3.10 and lower.

**Comment by woody-apple** [comment]
> I believe we could add this to requirements.all.txt
> 
> cython==0.29.36 ; python_version < "3.11" cython==3.0.0 ; python_version >= "3.11"
> 
> Then just remove `--strip-extras` when running pip-compile.
> 
> Note I don't know if that's the right version to check for cython. Was just trying to pick one version for python 3.11 and a separate for 3.10 and lower.

Thanks! More my question was, how can we have this build a fully recursive and exhaustive set. This isn't the first time we've been bitten here.

**Comment by AnthonyDiGirolamo** [comment]
Passing in all the requirements.txt files to pip-compile does that:
```
pip-compile --output-file=constraints.txt --resolver=backtracking --strip-extras --allow-unsafe requirements.*.txt
```
here's the result:
[constraints.txt](https://github.com/project-chip/connectedhomeip/files/12074242/constraints.txt)

**Comment by woody-apple** [comment]
> Passing in all the requirements.txt files to pip-compile does that:
> 
> ```
> pip-compile --output-file=constraints.txt --resolver=backtracking --allow-unsafe requirements.*.txt
> ```
> 
> here's the result: [constraints.txt](https://github.com/project-chip/connectedhomeip/files/12074242/constraints.txt)

Thanks!

Is removing `--strip-extras` the difference from what we have?

**Comment by AnthonyDiGirolamo** [comment]
> Is removing `--strip-extras` the difference from what we have?

Yeah, just that and passing in all the requirements files.

**Comment by AnthonyDiGirolamo** [comment]
@woody-apple @andy31415 Should I add the fully expanded constraint to this PR?

**Comment by andy31415** [comment]
> @woody-apple @andy31415 Should I add the fully expanded constraint to this PR?

I would not add cython in particular here because we do not depend on cython anymore. The cython error was because we generated this on a python 3.11 and that guarded off some things.

So ideally we should run this on a docker image that is recent on 3.9 and update when CI is 3.11. Right now we have `itsdangerous<2.1 ; python_version < "3.11"` on esp32, so that is something that is missing.

**Comment by andy31415** [comment]
> > @woody-apple @andy31415 Should I add the fully expanded constraint to this PR?
> 
> I would not add cython in particular here because we do not depend on cython anymore. The cython error was because we generated this on a python 3.11 and that guarded off some things.
> 
> So ideally we should run this on a docker image that is recent on 3.9 and update when CI is 3.11. Right now we have `itsdangerous<2.1 ; python_version < "3.11"` on esp32, so that is something that is missing.

`requirements.all` should include all others right? I think that is sufficient.

**Comment by AnthonyDiGirolamo** [comment]
On second thought, let's do that in a follow up. This just pins pip and pip-tools correctly.

**Comment by andy31415** [comment]
> On second thought, let's do that in a follow up. This just pins pip and pip-tools correctly.

Yes, I believe that different freezing is a separate problem. We should pick one of the paths:
  - move CI to python 3.11
  - switch constraints to be generated by a python 3.9 system

**Comment by woody-apple** [comment]
> @woody-apple @andy31415 Should I add the fully expanded constraint to this PR?

Let's handle fully expanding this later :) (but soon please!)

**Comment by woody-apple** [comment]
> > On second thought, let's do that in a follow up. This just pins pip and pip-tools correctly.
> 
> Yes, I believe that different freezing is a separate problem. We should pick one of the paths:
> 
> * move CI to python 3.11
> * switch constraints to be generated by a python 3.9 system

We're moving CI to Python 3.11, that should be done tonight.

**Pull request merged**
