### PR TITLE
[controller-cluster] Enable missing door lock attributes

### PR DESCRIPTION
**Pull request by vivien-apple**
#### Problem

Playing with `./out/debug/standalone/chip-tool any read-by-id 0xffffffff 0xffffffff 0x12345 0xffff` I noticed that some door lock attributes that exists on the `all-clusters-app` were not enabled on the controller side.

#### Change overview
 * Enable them
 * Update the generated code

#### Testing

The command `./out/debug/standalone/chip-tool any read-by-id 0xffffffff 0xffffffff 0x12345 0xffff` does not fails on those attributes anymore

### CODE REVIEW

**Review by Damian-Nordic — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by vivien-apple** [comment]
If #14794 get approved this PR could be closed.

**Comment by vivien-apple** [comment]
Closing in favor of #14794

**Pull request closed without merging**
