### PR TITLE
added EthernetDriver on android tv

### PR DESCRIPTION
**Pull request by xylophone21**
#### Problem
* There is no Network Commissioning Cluster on android tv which is must

#### Change overview
* add it

#### Testing
* chip-tool networkcommissioning read *

### CODE REVIEW

**Review by chrisdecenzo — APPROVED** [review]

**Review by andy31415 — CHANGES_REQUESTED** [review]
Could you describe in the summary what approaches were considered and why using this method seems the cleanest?

When looking at the code, I am thinking that java generally already has JNI OnLoad events which are triggered very early. Why is a separate weak function the correct way to go?

**Review by andy31415 — COMMENTED** [review]
I grepped through the code and found things like:

examples/tv-app/linux/main.cpp has a empty ApplicationInit as well. Why does that exist and why is it empty?

**Comment by xylophone21** [comment]
> I grepped through the code and found things like:
> 
> examples/tv-app/linux/main.cpp has a empty ApplicationInit as well. Why does that exist and why is it empty?

because

**Comment by xylophone21** [comment]
As discussed in slack, the Network Commissioning Cluster is an option and has little value on android, we decided to not imply it. close

https://csamembers.slack.com/archives/G014G30SVV0/p1647306294842679

**Pull request closed without merging**
