### PR TITLE
Adding 3 more Yamls ( Test_TC_TM_2_1,Test_TC_TSUIC_2_1,Test_TC_PCC_2_1)

### PR DESCRIPTION
**Pull request by raju-apple**
Adding 3 more Yamls : 

Test_TC_TM_2_1 : Temperature Measurement Cluster
Test_TC_TSUIC_2_1 : Thermostat User Interface Configuration Cluster
Test_TC_PCC_2_1 : Pump Configuration and Control Cluster

Bunch of steps are still disabled for the following reasons : 
1. Lot of optional attributes are not yet implemented by SDK , so disabled for now 
2. Some of the values like `null` and types like `uint16` , `desc` need to still be implemented by the yaml framework as well so still disabled.

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
@saurabhst @Damian-Nordic ?

**Review by saurabhst — APPROVED** [review]

**Review by Damian-Nordic — APPROVED** [review]

**Comment by andy31415** [comment]
@raju-apple - conflicts

**Comment by raju-apple** [comment]
> @raju-apple - conflicts
Took care of it

**Review by jmartinez-silabs — APPROVED** [review]

**Comment by raju-apple** [comment]
Looks like I need to regenerate the code and submit the PR again , created a new PR with more changes to some of the existing Yamls , will merge that in instead . https://github.com/project-chip/connectedhomeip/pull/10050

**Pull request closed without merging**
