### PR TITLE
[Python] Improve type hints of cluster objects

### PR DESCRIPTION
**Pull request by agners**
Using `mypy` to check type hints reports errors on the automatically generated Cluster objects. This PR addresses some of the errors.

`mypy` can be run using the following command:

```
mypy --follow-imports=skip src/controller/python/chip/clusters/Objects.py
```

### CODE REVIEW

**Comment by agners** [comment]
This is currently WIP. There are still errors reported related to enums. Ideas welcome:

```
src/controller/python/chip/clusters/Objects.py:59: error: Incompatible types in assignment (expression has type "int", variable has type "IdentifyTypeEnum")                                                                                                                                                                  
src/controller/python/chip/clusters/Objects.py:134: error: Incompatible types in assignment (expression has type "int", variable has type "EffectIdentifierEnum")                                                                                                                                                             
src/controller/python/chip/clusters/Objects.py:135: error: Incompatible types in assignment (expression has type "int", variable has type "EffectVariantEnum")                                                                                                                                                                
src/controller/python/chip/clusters/Objects.py:168: error: Incompatible types in assignment (expression has type "int", variable has type "IdentifyTypeEnum")                                                                                                                                                                 
src/controller/python/chip/clusters/Objects.py:1410: error: Incompatible types in assignment (expression has type "int", variable has type "EffectIdentifierEnum")  
```

**Comment by andy31415** [comment]
Very old PR with merge conflicts and a comment of "this is still WIP". Assuming stale and closing.

**Comment by agners** [comment]
> Very old PR with merge conflicts and a comment of "this is still WIP". Assuming stale and closing.

Well, I actually rebased somewhat recently, and hoped to get it in soon, but was lacking reviews and then it got merge conflicts again :see_no_evil: . I'll rebase again and ping some folks for review.

**Comment by andy31415** [comment]
Re-opening as active. @agners please help with mergging to master and this close and re-open hopefully pushes us to move this higher up the priority list.

**Comment by agners** [comment]
> Re-opening as active. @agners please help with mergging to master and this close and re-open hopefully pushes us to move this higher up the priority list.

I've rebased to master, should be ready for review/merging now.

**Review by arkq — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Pull request merged**
