### PR TITLE
Upload logs after bootstrap

### PR DESCRIPTION
**Pull request by mspang**
Currently the bootstrap logs are discarded. Upload them to allow
diagnosis of any bootstrap problems.

### CODE REVIEW

**Review by Damian-Nordic — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]
Wish we could write this once and have all the workflow files pick it up....

**Review by andy31415 — APPROVED** [review]
How big are these artifacts? Github will limit the size of what we can store and currently we use this storage for binaries to compare for size differences.

**Comment by mspang** [comment]
> How big are these artifacts? Github will limit the size of what we can store and currently we use this storage for binaries to compare for size differences.

About 10K (per bootstrap == per workflow)

If we cannot store a small amount of logs then I think we have serious problems.

**Comment by mspang** [comment]
> Wish we could write this once and have all the workflow files pick it up....

I had the same thought but mostly turned up complaints from other GitHub customers about it. So I'm not sure if it's even possible.

**Pull request merged**
