### PR TITLE
Fix #13377 for compatibility with #13330

### PR DESCRIPTION
**Pull request by msandstedt**
#### Problem

The pull requests #13330 and #13377 were merged around the same time,
and have caused a small build breakage.

#### Change overview

Amend #13377 to work with #13330.

#### Testing

Tested to build without error.

### CODE REVIEW

**Review by saurabhst — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]
OK to fix build, but as a followup we should figure out whether this is in fact always a SecureSession session, right?  @turon

**Review by turon — APPROVED** [review]
LGTM :+1:  Was about to post the same.

**Comment by turon** [comment]
> OK to fix build, but as a followup we should figure out whether this is in fact always a SecureSession session, right? @turon

Yes, I had the same question for @kghost regarding the new API.  Specifically, what happens when `AsSecureSession` is called on an unsecured session? This use case simply needs to print info about the session that should be there regardless of session type (session id, local node id, is the session secure or not).  We should have a simple API for that that doesn't require a number of conditionals and branches to print the common data.

**Comment by msandstedt** [comment]
I guess I would defend this as no better or worse than the original code, which was extracting the chip::Optional GetLocalSessionId.Value without checking whether it exists first.  It seems sort of like the same underlying assumptions are at play in either case.

**Comment by turon** [comment]
> I guess I would defend this as no better or worse than the original code, which was extracting the chip::Optional GetLocalSessionId.Value without checking whether it exists first. It seems sort of like the same underlying assumptions are at play in either case.

Yes, basically the entire stack now calls `AsSecureSession()` when a secure session is assumed / required, which will `VerifyOrDie(GetSessionType() == SessionType::kSecure);`.

**Pull request merged**
