### PR TITLE
Add possibility to build Tizen apps with various options

### PR DESCRIPTION
**Pull request by arkq**
#### Problem

Possibility to build Tizen applications with sanitizers like ASAN, UBSAN, etc. Build Tizen apps with no WiFi and/or BT enabled.

#### Change overview

- add more options to TizenBuilder class
- fix warnings reported by flake8 in the scripts/build directory (by default Python line length limit set to 132 characters which is consistent with clang-tidy configuration, however, Python coding standard says that line length shall not exceed 80 characters, so IMHO wherever possible this line limit shall be respected) 

#### Testing

Building Tizen app locally with e.g. `./scripts/build/build_examples.py --target tizen-arm-light-asan build`.

### CODE REVIEW

**Review by dh79pyun — APPROVED** [review]
For '[build] Allow to build Tizen apps with variants] commit(https://github.com/project-chip/connectedhomeip/pull/16701/commits/471a870d18daf89dd323e92d59a0062a01a053d4)', it can be useful for tizen.

**Comment by wootak-jung** [comment]
How about split this PR for the changes of flake8? I think that is not for only Tizen.

**Review by woody-apple — APPROVED** [review]
Fast tracking, given this has had enough time for review (> 3 days)

**Review by msandstedt — APPROVED** [review]

**Pull request merged**
