### PR TITLE
Implement Docker best practices

### PR DESCRIPTION
**Pull request by electrocucaracha**
#### Problem
[Hadolint](https://github.com/hadolint/hadolint) is a tool which analyzes Dockerfile and provides applicable best practices.  [Version pinning](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#apt-get) reduce failures due to unanticipated changes in required packages. The [CHIP integration Docker images](integrations/docker/images) don't have version pinning implemented.

 #### Summary of Changes
These changes implement version pinning best practice as well as reduce some instructions like using `WORKDIR` Docker  and `--no-install-recommends` apt instructions

### CODE REVIEW

**Comment by woody-apple** [comment]
@electrocucaracha Thanks for the PR, can you please fix the merge conflict, and we can merge!

**Review by woody-apple — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Review by yunhanw-google — APPROVED** [review]

**Comment by electrocucaracha** [comment]
> @electrocucaracha Thanks for the PR, can you please fix the merge conflict, and we can merge! - also, please Restyle the Docker files

@woody-apple do you have style guidelines document where I can follow? or which changes are not following them?

**Comment by woody-apple** [comment]
> @electrocucaracha Thanks for the PR, can you please fix the merge conflict, and we can merge! - also, please Restyle the Docker files

Oops, they may not have run, running the checks now!

**Comment by woody-apple** [comment]
@saurabhst @msandstedt ?

**Review by msandstedt — APPROVED** [review]

**Comment by woody-apple** [comment]
This looks to have broken the docker build, trying to re-open

**Pull request merged**
