### PR TITLE
[docker] Fix spelling error (expressif -> espressif)

### LINKED ISSUE #2592: Espressif is called "expressif" in docker images
#### Problem
Espressif tooling is installed in a directory named "expressif" in docker images

 #### Proposed Solution
rename the install directory to espressif

### PR DESCRIPTION
**Pull request by mspang**
#### Problem
Espressif is spelled wrong on docker.

 #### Summary of Changes
Correct the spelling.

fixes #2592

### CODE REVIEW

**Review by saurabhst — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]

**Review by kedars — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
Wondering if we should change dockerfile version as well, since the images will have slightly different content.

**Comment by andy31415** [comment]
@mspang did not merge yet since wondering about version of dockerfile.

**Comment by mspang** [comment]
> @mspang did not merge yet since wondering about version of dockerfile.

This isn't worth rebuilding the images over, but preemptive version bump seems reasonable. Done.

**Review by rwalker-apple — APPROVED** [review]

**Comment by rwalker-apple** [comment]
looks like this can land without the docker.io push, 'cuz CI and devcontainer is still pointing at 0.4.7

**Pull request merged**
