### PR TITLE
[submodule] Use https clone url for bluez

### LINKED ISSUE #3431: [submodule] Bluez submodule should use https clone url
#### Problem
Currently, we are using git protocol for bluez submodule clone, the backend of git protocol is ssh, and the clone process is very slow (3 KB/s) in China. However, when using the https url, the speed is acceptable (1 MB/s).

 #### Proposed Solution
Change the repo url of bluez https://git.kernel.org/pub/scm/bluetooth/bluez.git to according to https://git.kernel.org/pub/scm/bluetooth/bluez.git/

### PR DESCRIPTION
**Pull request by erjiaqing**
#### Problem
Currently, we are using git protocol for bluez submodule clone, the backend of git protocol is ssh, and the clone process is very slow (3 KB/s) in China. However, when using the https url, the speed is acceptable (1 MB/s).

 #### Summary of Changes
Change the repo url of bluez https://kernel.googlesource.com/pub/scm/bluetooth/bluez.git to according to https://git.kernel.org/pub/scm/bluetooth/bluez.git/

 Fixes #3431

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

**Comment by rwalker-apple** [comment]
should we be using https://git.kernel.org/pub/scm/bluetooth/bluez.git instead?

**Comment by mspang** [comment]
> should we be using https://git.kernel.org/pub/scm/bluetooth/bluez.git instead?

@erjiaqing is this a protocol issue or a problem with the kernel.org site? If the former I agree we should stick with kernel.org instead of the googlesource.com mirror.

**Comment by erjiaqing** [comment]
> > should we be using https://git.kernel.org/pub/scm/bluetooth/bluez.git instead?
> 
> @erjiaqing is this a protocol issue or a problem with the kernel.org site? If the former I agree we should stick with kernel.org instead of the googlesource.com mirror.

This is a protocol issue, and seems using the https url on kernel.org will result in "cannot fetch unpublished objects"

**Comment by rwalker-apple** [comment]
> > > should we be using https://git.kernel.org/pub/scm/bluetooth/bluez.git instead?
> > 
> > 
> > @erjiaqing is this a protocol issue or a problem with the kernel.org site? If the former I agree we should stick with kernel.org instead of the googlesource.com mirror.
> 
> This is a protocol issue, and seems using the https url on kernel.org will result in "cannot fetch unpublished objects"

Is "cannot fetch unpublished objects" the literal error you get?  What are the steps to reproduce that error?

**Comment by erjiaqing** [comment]
> > > > should we be using https://git.kernel.org/pub/scm/bluetooth/bluez.git instead?
> > > 
> > > 
> > > @erjiaqing is this a protocol issue or a problem with the kernel.org site? If the former I agree we should stick with kernel.org instead of the googlesource.com mirror.
> > 
> > 
> > This is a protocol issue, and seems using the https url on kernel.org will result in "cannot fetch unpublished objects"
> 
> Is "cannot fetch unpublished objects" the literal error you get? What are the steps to reproduce that error?

The actual error is ` Error: error: Server does not allow request for unadvertised object e8f8a59660670d22214ecdfdf7014e353c3f56f2`

And the failed CI can be found at https://github.com/project-chip/connectedhomeip/runs/1306602174

`git submodule update --init` will not throw this error.

**Comment by rwalker-apple** [comment]
> > > > > should we be using https://git.kernel.org/pub/scm/bluetooth/bluez.git instead?
> > > > 
> > > > 
> > > > @erjiaqing is this a protocol issue or a problem with the kernel.org site? If the former I agree we should stick with kernel.org instead of the googlesource.com mirror.
> > > 
> > > 
> > > This is a protocol issue, and seems using the https url on kernel.org will result in "cannot fetch unpublished objects"
> > 
> > 
> > Is "cannot fetch unpublished objects" the literal error you get? What are the steps to reproduce that error?
> 
> The actual error is ` Error: error: Server does not allow request for unadvertised object e8f8a59660670d22214ecdfdf7014e353c3f56f2`
> 
> And the failed CI can be found at https://github.com/project-chip/connectedhomeip/runs/1306602174
> 
> `git submodule update --init` will not throw this error.
> 
> Since https://kernel.googlesource.com/pub/scm/bluetooth/bluez.git is a url listed on https://git.kernel.org/pub/scm/bluetooth/bluez.git/, I think it is ok to use.

ok, I see.  `--depth=1` is a problem for kernel.org, apparently

**Review by rwalker-apple — APPROVED** [review]

**Review by BroderickCarlin — APPROVED** [review]

**Pull request merged**
