### PR TITLE
[Cherry-pick] [v1.1-branch] Add a lint for SuccessOrExit without assignment. (#26854)

### PR DESCRIPTION
**Pull request by dhrishi**
* Add a lint for SuccessOrExit without assignment.

This is almost always a mistake, since it loses track of the error involved.

* Address review comment.

This cherrypicks #26854

### CODE REVIEW

**Comment by dhrishi** [comment]
@bzbarsky-apple There was a conflict in `lint.yml`. I have resolved it manually. Can you please check if the change done is correct. Thanks!

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
@dhrishi  linter maybe found an error

**Comment by bzbarsky-apple** [comment]
@dhrishi The lint.yml part is fine.

The lint failure is on this line in CASESession.cpp:
```
        SuccessOrExit(DeviceLayer::PlatformMgr().ScheduleWork(AfterWorkHandler, reinterpret_cast<intptr_t>(helper)));
```
which is actually correct code, since it's in a function that does not return errors; the exit block just does cleanup.  That code looks quite different on master, which is why the lint is not triggering there.

My suggestion: just don't enable the actual lint on 1.1 for now (but take the changes that fixed the lint, which is what we want).

**Comment by dhrishi** [comment]
>My suggestion: just don't enable the actual lint on 1.1 for now (but take the changes that fixed the lint, which is what we want).

Ack. Removed the changes from `lint.yml`

**Comment by andy31415** [comment]
> > My suggestion: just don't enable the actual lint on 1.1 for now (but take the changes that fixed the lint, which is what we want).
> 
> Ack. Removed the changes from `lint.yml`

I was hoping you would fix the bug instead?

**Comment by bzbarsky-apple** [comment]
> I was hoping you would fix the bug instead?

The code in question is not buggy; it just fails the lint.  And changing it on the branch is just extra risk.

**Pull request merged**
