### PR TITLE
Make in RAM NetworkCommissioning::Featuremap report kThreadDevice

### PR DESCRIPTION
**Pull request by andy31415**
#### Problem
Thread devices fail to commission currently. #14713 is addressing that, however it may take a while to make all devices work.

#### Change overview
Switch the default to 2 (i.e. thread device) from previous values of 0 (invalid really) and 1 (wifi). Other wifi platforms are generally covered:
   - linux and esp32 have an actual driver returning kWifi and not using the zap inram storage
   - darwin has a CI workaround forcing everything to be 0 (and this will need fixing separately)

#### Testing
Commissioned a NRF device on thread using `chip-tool pairing ble-thread`, it went past the cretendial selection

Validated all needed things changed via:

```
fd 'zap$' | xargs rg 'Network Commissioning' | cut -f1 -d: | uniq | xargs -n1 jq '.endpointTypes[].clusters[] | select(.name == "Network Commissioning") | {name: .name, attr: .attributes[] | {name:.name, default:.defaultValue, file: input_filename}} | select(.attr.name == "FeatureMap" and .attr.default != "2")'
```

### CODE REVIEW

**Review by Damian-Nordic — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]

**Comment by mrjerryjohns** [comment]
No matter which default you pick, you're going to be in the wrong. Might as well pick the default that does the most good...

Approved!

**Review by mrjerryjohns — APPROVED** [review]

**Comment by yunhanw-google** [comment]
Looks like thread test fails in cirque with this change
[1643927284.211125][4351:4356] CHIP:IN: Sending encrypted msg 0x7ffff3b32180 with MessageCounter:7292873 to 0x0000000000000001 (1) at monotonic time: 1584815 msec
[1643927284.211165][4351:4356] CHIP:EM: Flushed pending ack for MessageCounter:2355066 on exchange 37324i
ERROR:NetworkCommissioning:InteractionModelError: Failure (0x1)
Traceback (most recent call last):
  File "/home/runner/work/connectedhomeip/connectedhomeip/src/controller/python/test/test_scripts/network_commissioning.py", line 245, in run
    await self.test_thread(endpoint)
  File "/home/runner/work/connectedhomeip/connectedhomeip/src/controller/python/test/test_scripts/network_commissioning.py", line 166, in test_thread
    res = await self._devCtrl.SendCommand(nodeid=self._nodeid, endpoint=endpointId, payload=req)
  File "/usr/local/lib/python3.8/dist-packages/chip/ChipDeviceCtrl.py", line 540, in SendCommand
    return await future
chip.interaction_model.InteractionModelError: InteractionModelError: Failure (0x1)


See the log from all-cluster-app

[1643927284.109888][68:68] CHIP:DMG: InvokeRequestMessage =
[1643927284.109978][68:68] CHIP:DMG: {
[1643927284.110000][68:68] CHIP:DMG: 	suppressResponse = false, 
[1643927284.110009][68:68] CHIP:DMG: 	timedRequest = false, 
[1643927284.110016][68:68] CHIP:DMG: 	InvokeRequests =
[1643927284.110027][68:68] CHIP:DMG: 	[
[1643927284.110035][68:68] CHIP:DMG: 		CommandDataIB =
[1643927284.110047][68:68] CHIP:DMG: 		{
[1643927284.110053][68:68] CHIP:DMG: 			CommandPathIB =
[1643927284.110062][68:68] CHIP:DMG: 			{
[1643927284.110066][68:68] CHIP:DMG: 				EndpointId = 0x1,
[1643927284.110080][68:68] CHIP:DMG: 				ClusterId = 0x31,
[1643927284.110087][68:68] CHIP:DMG: 				CommandId = 0x0,
[1643927284.110095][68:68] CHIP:DMG: 			},
[1643927284.110104][68:68] CHIP:DMG: 			
[1643927284.110111][68:68] CHIP:DMG: 			CommandData = 
[1643927284.110118][68:68] CHIP:DMG: 			{
[1643927284.110127][68:68] CHIP:DMG: 				0x0 = [
[1643927284.110134][68:68] CHIP:DMG: 					
[1643927284.110142][68:68] CHIP:DMG: 			]
[1643927284.110149][68:68] CHIP:DMG: 				0x1 = 0, 
[1643927284.110171][68:68] CHIP:DMG: 			},
[1643927284.110177][68:68] CHIP:DMG: 		},
[1643927284.110187][68:68] CHIP:DMG: 		
[1643927284.110193][68:68] CHIP:DMG: 	],
[1643927284.110203][68:68] CHIP:DMG: 	
[1643927284.110210][68:68] CHIP:DMG: 	InteractionModelRevision = 1
[1643927284.110216][68:68] CHIP:DMG: },
[1643927284.110237][68:68] CHIP:DMG: AccessControl: checking f=1 a=c s=0x000000000001B669 t= c=0x0000_0031 e=1 p=o
[1643927284.110251][68:68] CHIP:DMG: Received command for Endpoint=1 Cluster=0x0000_0031 Command=0x0000_0000
[1643927284.110268][68:68] CHIP:DMG: ICR moving to [AddingComm]
[1643927284.110295][68:68] CHIP:DMG: ICR moving to [AddedComma]
[1643927284.110304][68:68] CHIP:ZCL: Failed to dispatch command, TLVError=../../zzz_generated/app-common/app-common/zap-generated/cluster-objects.cpp:7555: Success
[1643927284.110313][68:68] CHIP:DMG: Decreasing reference count for CommandHandler, remaining 0
[1643927284.110322][68:68] CHIP:EM: Piggybacking Ack for MessageCounter:7292872 on exchange: 37324r

**Comment by yunhanw-google** [comment]
When test code do 
        res = await self._devCtrl.ReadAttribute(nodeid=self._nodeid, attributes=[
            (endpointId,
             Clusters.NetworkCommissioning.Attributes.ConnectMaxTimeSeconds),
            (endpointId,
             Clusters.NetworkCommissioning.Attributes.ScanMaxTimeSeconds),
            (endpointId, Clusters.NetworkCommissioning.Attributes.MaxNetworks),
            (endpointId, Clusters.NetworkCommissioning.Attributes.FeatureMap)],
            returnClusterObject=True)

with this PR, it returns
INFO:NetworkCommissioning:The interface supports 0 networks.
INFO:NetworkCommissioning:ScanNetworks should take no more than 0 seconds.
INFO:NetworkCommissioning:ConnectNetwork should take no more than 0 seconds.
INFO:NetworkCommissioning:The feature map of this endpoint is 2.
INFO:NetworkCommissioning:Finished getting basic information of the endpoint

It seems thread scan network don't work. https://github.com/project-chip/connectedhomeip/pull/14713 mentioned thread scan has not yet been implemented....

**Comment by yunhanw-google** [comment]
In current master branch, cirque thread test is using Endpoint0 for thread commissioning test
with this change, it seems endpoint 1 is also configured with THREAD_NETWORK_FEATURE_MAP, but this endpoint1 has not yet been configured right in all-cluster-app with right thread support.
In master,
the good log is 
INFO:NetworkCommissioning:{0: {<class 'chip.clusters.Objects.NetworkCommissioning'>: NetworkCommissioning(maxNetworks=None, networks=None, scanMaxTimeSeconds=None, connectMaxTimeSeconds=None, interfaceEnabled=None, lastNetworkingStatus=None, lastNetworkID=None, lastConnectErrorValue=None, serverGeneratedCommandList=None, clientGeneratedCommandList=None, attributeList=None, featureMap=2, clusterRevision=None)}, 1: {<class 'chip.clusters.Objects.NetworkCommissioning'>: NetworkCommissioning(maxNetworks=None, networks=None, scanMaxTimeSeconds=None, connectMaxTimeSeconds=None, interfaceEnabled=None, lastNetworkingStatus=None, lastNetworkID=None, lastConnectErrorValue=None, serverGeneratedCommandList=None, clientGeneratedCommandList=None, attributeList=None, featureMap=0, clusterRevision=None)}}
INFO:NetworkCommissioning:Endpoint 0 is configured as Thread network, run Thread commissioning test.
...
INFO:NetworkCommissioning:Got response: NetworkCommissioning.Commands.ConnectNetworkResponse(networkingStatus=<NetworkCommissioningStatus.kSuccess: 0>, debugText='', errorValue=0)
INFO:NetworkCommissioning:Device connected to a network.
INFO:NetworkCommissioning:Skip endpoint 1 with featureMap 0

the bad log is
[1643938870.807715][4351:4356] CHIP:EM: Flushed pending ack for MessageCounter:10438479 on exchange 58048i
INFO:NetworkCommissioning:{0: {<class 'chip.clusters.Objects.NetworkCommissioning'>: NetworkCommissioning(maxNetworks=None, networks=None, scanMaxTimeSeconds=None, connectMaxTimeSeconds=None, interfaceEnabled=None, lastNetworkingStatus=None, lastNetworkID=None, lastConnectErrorValue=None, serverGeneratedCommandList=None, clientGeneratedCommandList=None, attributeList=None, featureMap=2, clusterRevision=None)}, 1: {<class 'chip.clusters.Objects.NetworkCommissioning'>: NetworkCommissioning(maxNetworks=None, networks=None, scanMaxTimeSeconds=None, connectMaxTimeSeconds=None, interfaceEnabled=None, lastNetworkingStatus=None, lastNetworkID=None, lastConnectErrorValue=None, serverGeneratedCommandList=None, clientGeneratedCommandList=None, attributeList=None, featureMap=2, clusterRevision=None)}}
...
INFO:NetworkCommissioning:Endpoint 0 is configured as Thread network, run Thread commissioning test.
...
INFO:NetworkCommissioning:Got response: NetworkCommissioning.Commands.ConnectNetworkResponse(networkingStatus=<NetworkCommissioningStatus.kSuccess: 0>, debugText='', errorValue=0)
INFO:NetworkCommissioning:Device connected to a network.
INFO:NetworkCommissioning:Endpoint 1 is configured as Thread network, run Thread commissioning test.

the code is here
    async def run(self):
        try:
            endpoints = await self._devCtrl.ReadAttribute(nodeid=self._nodeid, attributes=[(Clusters.NetworkCommissioning.Attributes.FeatureMap)], returnClusterObject=True)
            logger.info(endpoints)
            for endpoint, obj in endpoints.items():
                clus = obj[Clusters.NetworkCommissioning]
                if clus.featureMap == WIFI_NETWORK_FEATURE_MAP:
                    logger.info(
                        f"Endpoint {endpoint} is configured as WiFi network, run WiFi commissioning test.")
                    await self.test_wifi(endpoint)
                elif clus.featureMap == THREAD_NETWORK_FEATURE_MAP:
                    logger.info(
                        f"Endpoint {endpoint} is configured as Thread network, run Thread commissioning test.")
                    await self.test_thread(endpoint)
                else:
                    logger.info(
                        f"Skip endpoint {endpoint} with featureMap {clus.featureMap}")

So do we allow network commissioning cluster's thread feature is enabled in two endpoints? From the log, if the device has been commissioned with thread network, it looks like not right to commissioning the thread network using another endpoint in same devce.

So the workaround is that once one endpint's thread commisioning is complete, then skip the thread commissioning for another endpoint.

**Comment by andy31415** [comment]
Thank you @yunhanw-google  - I did not realize there were 2 endpoints with network configuration. Not sure what that even means and it seems unlikely that that is supported. I will set the featuremap on that endpoint to 0 and see if cirque passes.

**Pull request merged**
