### PR TITLE
Get chip-tool-darwin to be built by CI

### PR DESCRIPTION
**Pull request by vivien-apple**
#### Problem

`chip-tool-darwin` is not built by CI.

#### Change overview
 * Add a step to build it

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]
Fast tracking, given this is adding build testing

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
@vivien-apple The CI failure on Darwin is real.

**Review by jmeg-sfy — APPROVED** [review]

**Comment by vivien-apple** [comment]
> @vivien-apple The CI failure on Darwin is real.

FTR I know what is the source of the failure - I am currently discussing around to find a solution :/

**Comment by vivien-apple** [comment]
I have modified the `chip-tool-darwin/BUILD.gn` file in such a way that it does not fails if code signing fails. That should be OK for running tests as long as the process is not restarted.

**Pull request merged**
