### PR TITLE
Use enum class for message types and status codes for secure channel.

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
This should give us better type-safety.

 #### Problem
Secure channel message types and status codes are C-style enums, which gives worse type-safety properties than C++ enum classes.

 #### Summary of Changes
Use enum classes instead.

### CODE REVIEW

**Review by saurabhst — APPROVED** [review]

**Review by rwalker-apple — APPROVED** [review]

**Review by yufengwangca — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Comment by yufengwangca** [comment]
Just give a second thought, after we change to enum class, we now finally need to static_cast those strong typed values to int during encoding .

// Set the message type for this header.
payloadHeader.SetMessageType(msgType);

It seems not much gain we can achieve, right?

**Comment by bzbarsky-apple** [comment]
I would propose we add an API that looks like `payloadHeader.SetIsSecureChannelMessage(msgType)`, which takes the message type enum as the arg and sets both the protocol id and the message type together, with the cast happening at this point.  That ensures that the protocol id and the message type can't get out of sync.

We probably still need to leave the raw `SetMessageType` API for use by consumers that add extension protocols...

**Comment by bzbarsky-apple** [comment]
Or even just have an overload of `SetMessageType` that is specialized for the enum type and sets the protocol id along with the message type if we don't care to do the cross-checking between protocol name and message type....

**Comment by yufengwangca** [comment]
We also need to take care of the incoming path, convert the decoded int value to enum class for message type and status code at transport level.

Right now, the spec defines the protocol ID is a 32-bit unsigned int, and status code as a 16-bit unsigned int. So we use variables some like unit32_t protocol_id, uint16_t status_code to take and process the status code from all protocols. After switching to enum class, we need to use separate variables to host status code for each protocol, one for generic Common protocol status code and one for protocol specific status code.

If we plan to transit protocol ID also from enum to enum class, we need to make the same adjustment.

**Comment by bzbarsky-apple** [comment]
For the incoming path, I think the best we can do it offer the unsigned int in the payload header getter.  That said, for dispatch, we can consider having APIs on payload header like `IsSecureChannelMessage(SecureChannel::MsgType type)` that would do the type check and also check the right protocol, instead of doing compares to the members directly.

I agree that it might turn out that this is all too painful, and then we can revert back to the C-style enum, but I think the APIs I've mentioned so far would be useful to have in any case.

Protocol id can't easily become enum class, because the set of protocols is not really known ahead of time, unlike the set of messages or status codes per (standard) protocol.  Though I suppose we could have an enum class of "standard" protocols (with 0 vendor id).... Not sure it's worth it.

**Pull request merged**
