### PR TITLE
[docs] Added a guide for the chip-tool.

### PR DESCRIPTION
**Pull request by markaj-nordic**
#### Problem

The chip-tool needs a proper user guide.

#### Change overview

Added .md file with chip-tool documentation.

### CODE REVIEW

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
Fast tracking documentation changes.

**Comment by Diegorro98** [comment]
This guide has any info about softap pairing?

**Review by LuDuda — APPROVED** [review]

**Comment by markaj-nordic** [comment]
@Diegorro98 no, it's not in the scope of chip-tool-guide. I think softap is not even the part of 1.0.0 release.

**Comment by markaj-nordic** [comment]
Rebased and fixed the CLA signature (email).

**Pull request merged**
