### PR TITLE
[K32W0] Fix third_party paths

### PR DESCRIPTION
**Pull request by doru91**
#### Problem
What is being fixed?  Examples:
Fix third_party path for k32w platform.

#### Change overview
Change the paths from third_party/k32w_sdk/nxp/k32w/k32w0/ to third_party/nxp/k32w0_sdk

#### Testing
Manual testing of the build.

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
Fast tracking given platform change by platform maintainer, note though it fails. @doru91

**Comment by bzbarsky-apple** [comment]
@doru91 The build bustage on K32W looks real.

**Review by jmartinez-silabs — APPROVED** [review]

**Review by jelderton — APPROVED** [review]

**Comment by doru91** [comment]
> @doru91 The build bustage on K32W looks real.

It is real. I need to update the Docker image. I know how to modify the .Dockerfile (https://github.com/project-chip/connectedhomeip/blob/master/integrations/docker/images/chip-build-k32w/Dockerfile) but I don't know how to reference the new version of Docker in the CI builds? @bzbarsky-apple do you know how to do it?

**Comment by bzbarsky-apple** [comment]
I think we are just bumping the version in the CI builds as needed, right?  It's just in the relevant .yaml files.

**Comment by doru91** [comment]
> I think we are just bumping the version in the CI builds as needed, right? It's just in the relevant .yaml files.

Right, operated the suggested changes, I believe it's ready for merging.

**Pull request merged**
