### PR TITLE
Roll up Pigweed to 444f6d0

### PR DESCRIPTION
**Pull request by yyzhong-g**
Fix a linking error with building with pw_trace.

### CODE REVIEW

**Comment by woody-apple** [comment]
What is failing to link? Why is CI passing without this change?

**Review by woody-apple — CHANGES_REQUESTED** [review]
Can we add some CI/tests to verify pigweed? Sounds like it was broken without us knowing via CI.

**Comment by yyzhong-g** [comment]
It is breaking esp32 all-cluster-app if RPC is turned on. CL didn't catch it since RPC is off according to the script and sdkconfig defaults in sdkconfig_c3devkit.defaults.

Do will want to have the cl run RPC turned on? Or both on and off.

**Comment by andy31415** [comment]
I believe #12700 will add sufficient CI to validate RPC builds for ESP32 (and ipv6 as well).

Adding all possible builds is hard because there are a lot of variations, but we should try to have reasonable coverage.

**Review by woody-apple — APPROVED** [review]

**Pull request merged**
