### PR TITLE
Create CONTRIBUTORS

### PR DESCRIPTION
**Pull request by Itz-RogueX**
Create a list of people that are helping to work on this project

### CODE REVIEW

**Comment by rwalker-apple** [comment]
@Itz-RogueX can you please re-format your description using the PR template as a guide?

What problem are you trying to address?  Does https://github.com/project-chip/connectedhomeip/graphs/contributors address the problem?

**Review by rwalker-apple — CHANGES_REQUESTED** [review]
please address the PR description

**Comment by Itz-RogueX** [comment]
oh wow I'm blind. I did not see that s[page. Sorry.

**Comment by rwalker-apple** [comment]
> oh wow I'm blind. I did not see that s[page. Sorry.

np

**Pull request closed without merging**
