### PR TITLE
Align header include paths between Release and Debug configuration

### PR DESCRIPTION
**Pull request by sagar-apple**
#### Problem
What is being fixed?  Examples:
* Xcode release mode builds of CHIP Framework fail

#### Change overview
Align the includes between debug and release builds and fixup an include. 

#### Testing
How was this tested? (at least one bullet point required)
* Added a step in CI to also build CHIP Framework in release mode on iOS.

### CODE REVIEW

**Review by mspang — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
@saurabhst @jelderton @Damian-Nordic?

**Comment by woody-apple** [comment]
@jepenven-silabs @LuDuda ?

**Comment by woody-apple** [comment]
@msandstedt @saurabhst ?

**Review by msandstedt — APPROVED** [review]

**Pull request merged**
