### PR TITLE
Enable TSAN builds on CI

### PR DESCRIPTION
**Pull request by mrjerryjohns**
This enables TSAN checking when running the functional tests in CI.
    
This is currently only enabled on Linux since the various races there were fixed when #7478 landed.
    
When Darwin races are fixed, tsan can be enabled for those too.

### CODE REVIEW

**Comment by woody-apple** [comment]
Love to see failing tests :)

**Review by bzbarsky-apple — COMMENTED** [review]
The filenames for the failure-case artifact uploads probably need to include matrix.type, or we (more plausibly) should only do the uploads for the non-tsan case.

**Review by msandstedt — APPROVED** [review]

**Comment by mspang** [comment]
bikeshed: Can we change the name from no_tsan to something else? default? Naming it what it's not isn't a scalable scheme (don't want to end up calling no_tsan_no_asan_no_*).

**Comment by mspang** [comment]
> bikeshed: Can we change the name from no_tsan to something else? default? Naming it what it's not isn't a scalable scheme (don't want to end up calling no_tsan_no_asan_no_*).

Or maybe "debug".

**Comment by mrjerryjohns** [comment]
`debug` and `with_tsan` feel like an odd pairing...

Would `default` and `with_tsan` be preferable?

**Comment by mspang** [comment]
> `debug` and `with_tsan` feel like an odd pairing...(isn't with_tsan debug too?)
> 
> Would `default` and `with_tsan` be preferable?

The default is optimized for debug & test (optimizations are limited, debug-only assertions enabled, etc) which is why it is usually called "debug". These names are or should be understood in a broader context than just this workflow.

"default" and "tsan" seem OK though

**Review by mspang — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]

**Pull request merged**
