### PR TITLE
First implementation of iOS CHIP.framework and iOS code parser app

### PR DESCRIPTION
**Pull request by shana-apple**
First implementation of CHIP framework and a demo app

### CODE REVIEW

**Review by sagar-apple — COMMENTED** [review]
Why does the Framework use `CHP` instead of `CHIP` in a lot of places? Can we just update it to use `CHIP`?

**Review by rwalker-apple — CHANGES_REQUESTED** [review]
nice work, Shana!

can we please rename "iOS Framework" to CHIP_framework?  maybe put it under src, too?

**Review by rwalker-apple — CHANGES_REQUESTED** [review]
still hoping for a rename to something without spaces. is this untenable for some reason?

the reason I'm asking is that we haven't vetted all of our build and dist scripts for "space safety" and the world in general is pretty stupid about it.

since we have a good precedent in what WebKit's doing, can we adopt that?  the name for the directory/project would be `CHIP.framework`

**Review by rwalker-apple — CHANGES_REQUESTED** [review]
please scrub all instances of `CHP` from names, they're not necessary once inside the CHIP.framework subdirectory

**Review by rwalker-apple — DISMISSED** [review]

**Review by woody-apple — APPROVED** [review]

**Review by rwalker-apple — DISMISSED** [review]
my naming concerns have been addressed

**Review by jelderton — APPROVED** [review]

**Review by BroderickCarlin — APPROVED** [review]

**Pull request merged**
