### PR TITLE
Python modifcation for check for fabricSynchronization condition on Agregator device

### PR DESCRIPTION
**Pull request by jlatusek**
## Problem 
This PR is related to #34534.

## Changes

Like @tehampson suggested I extracted python modification related to fabricSynchronization testing into separate PR/

### CODE REVIEW

**Comment by tehampson** [comment]
@jlatusek Where is the Yaml. The YAML is the test part the the more important thing to get in today

**Comment by jlatusek** [comment]
@tehampson sorry I thought that you would like to merge python first, so create also separate PR with yaml from #34534?

**Comment by tehampson** [comment]
> @tehampson sorry I thought that you would like to merge python first, so create also separate PR with yaml from #34534?

@jlatusek 
I mentioned:
>I would split this up into yaml and all the CI test stuff separately so that you don't block getting the yaml test in

What I was trying to say here is that the python stuff will prevent the YAML from getting merged. The YAML is the test that needs to get in by EOD today. The YAML is the test implementation. If you can create another PR of just the YAML and ping me the PR that would be great. If you can't do that let me know and I will create the PR

**Comment by tehampson** [comment]
@jlatusek 

You might need to update https://github.com/project-chip/connectedhomeip/blob/master/scripts/tests/chiptest/__init__.py#L144

or one of the other lists to tell CI to not run your YAML and leave a comment saying that application to run test against is in development and expected to land sometime Aug 2024

**Comment by jlatusek** [comment]
@tehampson thank you for clarification, I created another PR #34629

**Review by andy31415 — APPROVED** [review]

**Review by saurabhst — APPROVED** [review]

**Review by samadDotDev — APPROVED** [review]

**Pull request merged**
