### PR TITLE
Import `inet` code

### PR DESCRIPTION
**Pull request by pan-apple**
The PR imports `inet` and its dependencies.

* `TunEndPoint.cpp` is not being built, as its dependencies are missing.
* `SystemPacketBuffer.cpp` is not imported yet. It's header is included in this PR

### CODE REVIEW

**Review by gerickson — APPROVED** [review]
Overall, looks good. At large, see prior pull request comments about include directives (<>) vs. ("").

**Review by turon — CHANGES_REQUESTED** [review]
Thanks for the timely contribution!

**Review by woody-apple — APPROVED** [review]
I think once the other items are addressed, this looks good to me. Thanks everyone for the careful eyes here!

**Review by turon — APPROVED** [review]
LGTM 👍

**Review by BroderickCarlin — APPROVED** [review]

**Review by jelderton — APPROVED** [review]

**Review by hawk248 — APPROVED** [review]
ok

**Pull request merged**
