### PR TITLE
Change waitForReport to manual in TC-SMOKECO

### PR DESCRIPTION
**Pull request by ericzijian1994**
- **Situation**
In TH tests, TC-SMOKECO may fail at the waitForReport step.

- **The problem** 
Because TH tests are slow, events are received before the waitForReport step.

-  **This PR change is targeted to** 
This is a PR backup that changes most of the waitForReport to a manual operation.

### CODE REVIEW

**Comment by bzbarsky-apple** [comment]
@ericzijian1994 So is this working around https://github.com/project-chip/connectedhomeip/pull/28257 not being merged?

**Comment by ericzijian1994** [comment]
> @ericzijian1994 So is this working around #28257 not being merged?

Yes...Recently I saw https://github.com/CHIP-Specifications/chip-certification-tool/issues/951 , So just think if we don't have it solved.. this PR can be a working around for the SVE..

**Review by bzbarsky-apple — APPROVED** [review]
Approving, but please make sure a revert is tracked in an issue and the dependency on the issue that would allow the revert is marked in it.

**Review by cjandhyala — APPROVED** [review]

**Review by raju-apple — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
Fast-tracking test-only change.

**Comment by ericzijian1994** [comment]
> Approving, but please make sure a revert is tracked in an issue and the dependency on the issue that would allow the revert is marked in it.

Issue filed for tracking purpose https://github.com/project-chip/connectedhomeip/issues/29065

**Pull request merged**
