### PR TITLE
Define and implement CHIP heap memory allocation indirection functions

### PR DESCRIPTION
**Pull request by yufengwangca**
Problem
We do not want the CHIP stack for devices to directly depend on C Standard Library heap functions

Summary of Changes
* Add heap memory allocation indirection functions in CHIP
* Update CHIP stack to use CHIP heap memory allocation functions

fixes #<1166>

### CODE REVIEW

**Review by saurabhst — APPROVED** [review]

**Comment by woody-apple** [comment]
@robszewczyk @gerickson ?

**Review by kedars — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Review by gerickson — CHANGES_REQUESTED** [review]
The indirection is a good start; however, what's the solution for the CHIP-equivalent of `CHIP_CONFIG_MEMORY_MGMT_MALLOC` (from `WEAVE_CONFIG_SECURITY_MGR_MEMORY_MGMT_MALLOC` implemented via https://github.com/openweave/openweave-core/blob/master/src/lib/core/WeaveSecurityMgr-Malloc.cpp),  `CHIP_CONFIG_MEMORY_MGMT_SIMPLE` (from `WEAVE_CONFIG_SECURITY_MGR_MEMORY_MGMT_SIMPLE` implemented via https://github.com/openweave/openweave-core/blob/master/src/lib/core/WeaveSecurityMgr-SimpleAlloc.cpp), and `CHIP_MEMORY_MGMT_PLATFORM` (from `WEAVE_CONFIG_SECURITY_MGR_MEMORY_MGMT_PLATFORM` implemented externally)?

Also, do we want to create a formal namespace here for `chip::Platform` or `chip::Port` or some such?

/cc/ @turon

**Comment by yufengwangca** [comment]
> The indirection is a good start; however, what's the solution for the CHIP-equivalent of `CHIP_CONFIG_MEMORY_MGMT_MALLOC` (from `WEAVE_CONFIG_SECURITY_MGR_MEMORY_MGMT_MALLOC` implemented via https://github.com/openweave/openweave-core/blob/master/src/lib/core/WeaveSecurityMgr-Malloc.cpp), `CHIP_CONFIG_MEMORY_MGMT_SIMPLE` (from `WEAVE_CONFIG_SECURITY_MGR_MEMORY_MGMT_SIMPLE` implemented via https://github.com/openweave/openweave-core/blob/master/src/lib/core/WeaveSecurityMgr-SimpleAlloc.cpp), and `CHIP_MEMORY_MGMT_PLATFORM` (from `WEAVE_CONFIG_SECURITY_MGR_MEMORY_MGMT_PLATFORM` implemented externally)?
> 
> Also, do we want to create a formal namespace here for `chip::Platform` or `chip::Port` or some such?
> 
> /cc/ @turon

Within Weave, we don't have global level memory management indirection, indirection are defined within flags WEAVE_CONFIG_SECURITY_MGR_MEMORY_MGMT_MALLOC/WEAVE_CONFIG_SECURITY_MGR_MEMORY_MGMT_SIMPLE/WEAVE_CONFIG_SECURITY_MGR_MEMORY_MGMT_PLATFORM only in SecurityMgr.

Per our previous talk, we need to have global level indirection in CHIP so that CHIP stack do not depend on C Standard Library directly. 

If we bring SecurityMgr to CHIP later and need SecurityMgr specific indirection, then we can add new ones besides those generic indirections.

**Comment by gerickson** [comment]
> > The indirection is a good start; however, what's the solution for the CHIP-equivalent of `CHIP_CONFIG_MEMORY_MGMT_MALLOC` (from `WEAVE_CONFIG_SECURITY_MGR_MEMORY_MGMT_MALLOC` implemented via https://github.com/openweave/openweave-core/blob/master/src/lib/core/WeaveSecurityMgr-Malloc.cpp), `CHIP_CONFIG_MEMORY_MGMT_SIMPLE` (from `WEAVE_CONFIG_SECURITY_MGR_MEMORY_MGMT_SIMPLE` implemented via https://github.com/openweave/openweave-core/blob/master/src/lib/core/WeaveSecurityMgr-SimpleAlloc.cpp), and `CHIP_MEMORY_MGMT_PLATFORM` (from `WEAVE_CONFIG_SECURITY_MGR_MEMORY_MGMT_PLATFORM` implemented externally)?
> > Also, do we want to create a formal namespace here for `chip::Platform` or `chip::Port` or some such?
> > /cc/ @turon
> 
> Within Weave, we don't have global level memory management indirection, indirection are defined within flags WEAVE_CONFIG_SECURITY_MGR_MEMORY_MGMT_MALLOC/WEAVE_CONFIG_SECURITY_MGR_MEMORY_MGMT_SIMPLE/WEAVE_CONFIG_SECURITY_MGR_MEMORY_MGMT_PLATFORM only in SecurityMgr.
> 
> Per our previous talk, we need to have global level indirection in CHIP so that CHIP stack do not depend on C Standard Library directly.
> 
> If we bring SecurityMgr to CHIP later and need SecurityMgr specific indirection, then we can add new ones besides those generic indirections.

@yufengwangca, precisely, which is why I shortened the CHIP-equivalents of these preprocessor definitions to the simpler and more global:

* CHIP_CONFIG_MEMORY_MGMT_*
- CHIP_CONFIG_MEMORY_MGMT_MALLOC
- CHIP_CONFIG_MEMORY_MGMT_MALLOC
- CHIP_CONFIG_MEMORY_MGMT_SIMPLE
- CHIP_CONFIG_MEMORY_MGMT_PLATFORM

If we don't offer the option for either the simple allocator or a platform allocator, then we really haven't provided much value with this check-in other than to place a single level of indirection to the C Standard Library heap.

**Comment by yufengwangca** [comment]
Follow-up works:

1. Update CHIP_CONFIG_SECURITY_MGR_MEMORY_MGMT_* to CHIP_CONFIG_MEMORY_MGMT_*;

2. Port weave pool based simple allocator to CHIP under flag CHIP_CONFIG_MEMORY_MGMT_SIMPLE;

3. Move those indirection functions to namespace chip::platform;

Did I miss anything?

**Comment by gerickson** [comment]
> Follow-up works:
> 
> 1. Update CHIP_CONFIG_SECURITY_MGR_MEMORY_MGMT_* to CHIP_CONFIG_MEMORY_MGMT_*;
> 2. Port weave pool based simple allocator to CHIP under flag CHIP_CONFIG_MEMORY_MGMT_SIMPLE;
> 3. Move those indirection functions to namespace chip::platform;
> 
> Did I miss anything?

Sounds good with the notion that what's already in this PR would be conditioned by `CHIP_CONFIG_MEMORY_MGMT_MALLOC`.

**Review by gerickson — APPROVED** [review]
Nice work; thanks.

**Comment by yufengwangca** [comment]
Updated based on comments, keep CHIPArgParser and CHIPTLVReader as is for now since it either uses std::malloc indirectly such as strdup or not fit for pool based memory allocation(the sizes and the order in which they are requested/released is not known).

**Review by jelderton — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Pull request merged**
