### PR TITLE
[Im] Add ClusterObjects API for AttributeWrite in CHIPClusters.cpp

### PR DESCRIPTION
**Pull request by erjiaqing**
#### Change overview
- Seperate WriteCallbacks from InteractionModelDelegate
- Create `src/controller/WriteInteraction.h` similar to InvokeInteraction
- Call WriteAttribute for existing writes
    - Workaround: we didn't generate CharSpan for attribute writes in write interaction, so a reinterpret_case is added.
 - Include GlobalAttributes in Cluster Attributes since the cluste id fields are different in different clusters
 - Fix namespace for ClusterId field.

#### Testing
As existing WriteAttribute is moved to this PR, this change is already covered.

### CODE REVIEW

**Review by msandstedt — APPROVED** [review]

**Review by yunhanw-google — APPROVED** [review]

**Review by mrjerryjohns — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Comment by erjiaqing** [comment]
@bzbarsky-apple @andy31415 Seems the Android build kept timing out and seems it is just slow, I created a branch to raise the timeout to 90min to see if it can pass.

**Comment by bzbarsky-apple** [comment]
We should see whether this PR made the Android builds significantly slower or not....  Shouldn't block on it, but I am worried about the compile-time impact of the recent IM work.

**Comment by erjiaqing** [comment]
> We should see whether this PR made the Android builds significantly slower or not.... Shouldn't block on it, but I am worried about the compile-time impact of the recent IM work.

I found the recent Android run is already reaching its time limit... The time on Action status page includes time in queue, when enter the detail page, the actual running time a bit shorter.

image

**Comment by erjiaqing** [comment]
And this time it was failed with exit code 137 (maybe a OOM kill?), quite weird.

**Pull request merged**
