### PR TITLE
Disable Cancelable copy constructor

### PR DESCRIPTION
**Pull request by rwalker-apple**
#### Problem
 Copy constructors for doubly-linked list nodes generate corrupt lists.

 #### Summary of Changes
 Disable Cancelable's copy constructor, update users to steer clear of it.

### CODE REVIEW

**Review by mspang — APPROVED** [review]

**Review by BroderickCarlin — APPROVED** [review]

**Comment by rwalker-apple** [comment]
@hawk248 @jelderton ?

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]
This is missing the actual change to disable the constructor.

**Comment by rwalker-apple** [comment]
> This is missing the actual change to disable the constructor.

wow, got lost in multi-tree work.  good catch

**Review by bzbarsky-apple — APPROVED** [review]
Yes, this is much more like it.  :)

**Pull request merged**
