### PR TITLE
CHIP wrappers for third_party libs

### PR DESCRIPTION
**Pull request by pan-apple**
Some minimum code wrappers for third party NL libs.

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]
Thanks @pan-apple ! Looks like a clean cut and addition here.

**Review by hawk248 — APPROVED** [review]
Looks good.

**Review by gerickson — CHANGES_REQUESTED** [review]

**Review by woody-apple — CHANGES_REQUESTED** [review]
I actually see lots of WeaveCore.h stuff in here, we should rename that if it's not inside third_party..

**Review by woody-apple — APPROVED** [review]
Scratch that, this looks clean in the latest commit!

**Review by gerickson — APPROVED** [review]

**Pull request merged**
