### PR TITLE
HSM support for ECC Public key operations

### PR DESCRIPTION
**Pull request by sujaygkulkarni-nxp**
Problem
HSM support needs to be added for ECC Public key crypto operations

Summary of Changes
HSM support for ECC Public key crypto operations (Msg Verify and Hash Verify)

### CODE REVIEW

**Comment by woody-apple** [comment]
@balducci-apple @pan-apple ?

**Review by jmartinez-silabs — APPROVED** [review]
Code lgtm. 
Just wondering why all this code is needed under `src/crypto/hsm/nxp`.
Is this an augment to mbedtls? Is it part in some way of nxp sdk?

**Comment by sujaygkulkarni-nxp** [comment]
> Code lgtm.
> Just wondering why all this code is needed under `src/crypto/hsm/nxp`.
> Is this an augment to mbedtls? Is it part in some way of nxp sdk?

1. `src/crypto/hsm` folder can hold implementation for different hsm modules. The implementation in this pull request is specific to NXP hsm module.
2. hsm implementation can be seen as alternative to mbedtls / openssl crypto implementation. Required crypto operations can be offloaded to hsm modules.

**Review by woody-apple — APPROVED** [review]

**Review by jelderton — APPROVED** [review]

**Comment by andy31415** [comment]
Could you add unit tests to validate the added code?

**Comment by sujaygkulkarni-nxp** [comment]
> Could you add unit tests to validate the added code?

CHIPCryptoPALTest already had the ECC sign/verify tests (modified to support ECC on HSM) which will validate the current implementation.

**Review by andy31415 — APPROVED** [review]

**Pull request merged**
