### PR TITLE
Remove Silicon Labs dotdot code

### LINKED ISSUE #2005: Remove Silicon Labs dotdot code
#### Problem
The code will be unused once we switch all our example apps to the zigbeepro code.

 #### Proposed Solution
Remove the unused code.

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
#### Problem
The Silicon Labs dotdot code is no longer used.

 #### Summary of Changes
Remove the unused code, update documentation that referenced it.

fixes https://github.com/project-chip/connectedhomeip/issues/2005

### CODE REVIEW

**Review by saurabhst — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Review by rwalker-apple — APPROVED** [review]

**Review by kedars — APPROVED** [review]

**Comment by andy31415** [comment]
This is still a draft but has lots of review approvals. What is the plan for this PR? Should we start moving towards review and merge?

**Comment by bzbarsky-apple** [comment]
It's a draft because it needs https://github.com/project-chip/connectedhomeip/pull/2014 to land first, which needs https://github.com/project-chip/connectedhomeip/pull/2009 to land first.  The main reason I created it was to trigger CI to make sure that all the pieces are working right...

**Comment by bzbarsky-apple** [comment]
Also, I still need to update the documentation around this PR...

**Comment by woody-apple** [comment]
@bzbarsky-apple FYI, needs a restyle merge :)

**Comment by woody-apple** [comment]
@andy31415 I think this is ready for review now!

**Review by andy31415 — APPROVED** [review]

**Pull request merged**
