### PR TITLE
Fix k32w paths

### PR DESCRIPTION
**Pull request by andy31415**
#### Problem
Path for K32W was changed to be inside the NXP subdirectory, but builds do not match that.

`./gn_build.sh` completely fails.

#### Change overview
Adjust paths. Make k32w only compile for release.

#### Testing
Ran gn_build.sh. Saw k32w output.
CI will also validate that nothing breaks in compilation (although gn_build will not be used).

### CODE REVIEW

**Comment by andy31415** [comment]
Marking hotfix: path renaming and apparently this codepath was not validated recently (CI never failed).

**Comment by andy31415** [comment]
Moved to draft: This went a bit more down the rabbit hole than I wanted: fixed paths, fixed gnbuild, now going into otarequester teritory.

@doru91 leaving this as draft in case you need to see how far I got, will close the PR once we have an actual working fix (as this one is not it)

**Comment by andy31415** [comment]
Moved PR out of draft after update from @doru91

**Comment by doru91** [comment]
I reverted d26cba02f4000c9e6887287c798fee2ecf384f27 and pushed a fix for LWIP define redefinition. Let's see if the CI is passing.

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by doru91** [comment]
@andy31415 , looks good to me now.

**Comment by woody-apple** [comment]
Fast tracking build fixes.

**Pull request merged**
