### PR TITLE
[docs] update OTBR setup with the latest OTBR changes

### LINKED ISSUE #5536: [docs] update OTBR setup guide
#### Problem
[OpenThread Border Router](https://openthread.io/guides/border-router) (OTBR) has been updated
to support bidirectional IPv6 connectivity and Service Discovery and comes with a [CodeLab](https://openthread.io/codelabs/openthread-border-router).

The [OTBR setup guide](https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/linux_thread_connectivity.md) should be updated with the latest OTBR changes.

 #### Proposed Solution
Replace the [OTBR setup guide](https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/linux_thread_connectivity.md) with a new document that points to the OTBR CodeLab.

### PR DESCRIPTION
**Pull request by wgtdkp**
#### Problem
[OpenThread Border Router](https://openthread.io/guides/border-router) (OTBR) has been updated
to support bidirectional IPv6 connectivity and Service Discovery and comes with a [CodeLab](https://openthread.io/codelabs/openthread-border-router).

The [OTBR setup guide](https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/linux_thread_connectivity.md) should be updated with the latest OTBR changes.

 #### Summary of Changes
Replace the [OTBR setup guide](https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/linux_thread_connectivity.md) with a new document that points to the OTBR CodeLab.

### CODE REVIEW

**Review by Damian-Nordic — CHANGES_REQUESTED** [review]
1. Could you add a reference to https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/openthread_rcp_nrf_dongle.md for using nRF52840 Dongle as the RCP? The codelab recommends nRF52840 DK, but since we have a guide for the dongle ready, there should be no harm in mentioning it as an alternative.
2. Remove `linux_thread_connectivity.svg` if it's no longer needed.
3. Fix reference to `linux_thread_connectivity.md` in https://github.com/project-chip/connectedhomeip/blob/master/src/controller/python/README.md#thread-provisioning.

While the RPi-based setup which you propose certainly provides more features etc, the old OTBR Docker-based setup was super fast and easy to configure even on a workstation, so it was a great choice for quick testing of new changes using Python CHIP Controller as it didn't require connecting RPi to do basic testing. Is it possible to run the `./script/setup` on a laptop so that it doesn't modify my Wi-Fi settings and just adds `wpan0` interface, starts OTBR services and configures routing properly?

**Review by andy31415 — APPROVED** [review]

**Comment by msandstedt** [comment]
> While the RPi-based setup which you propose certainly provides more features etc, the old OTBR Docker-based setup was super fast and easy to configure even on a workstation, so it was a great choice for quick testing of new changes using Python CHIP Controller as it didn't require connecting RPi to do basic testing. Is it possible to run the `./script/setup` on a laptop so that it doesn't modify my Wi-Fi settings and just adds `wpan0` interface, starts OTBR services and configures routing properly?

`./script/setup` differentiates between Ubuntu and Raspbian and will do different things.  See here: https://github.com/openthread/ot-br-posix/blob/68ea812ac4ab590ab14cfa24ed88316a478b2ce4/script/_initrc#L86

```
diff examples/platforms/raspbian/default examples/platforms/ubuntu/default -U4
--- examples/platforms/raspbian/default	2021-03-22 10:30:23.101892617 -0500
+++ examples/platforms/ubuntu/default	2021-03-22 10:30:23.101892617 -0500
@@ -29,7 +29,7 @@
 
 # shellcheck disable=SC2034
 NAT64=1
 DNS64=1
-DHCPV6_PD=1
-NETWORK_MANAGER=1
+DHCPV6_PD=0
+NETWORK_MANAGER=0
 BACKBONE_ROUTER=0
```

My experience is that the ubuntu setup will not mess with your wifi (I believe this is part of `NETWORK_MANAGER=0`), but does introduce some weirdness with NAT64, where after setup you may find that IPv4 no longer works properly unless the otbr-installed tayga NAT64 is running.  If you're installing on an important Ubuntu machine and you don't need NAT64, you might consider setting `NAT64=0`.

I can't speak to the macOS platform, except to say that I personally haven't had much success there.

As an aside, I believe the docker containers are native (ie. if you're on ubuntu, the container will also be ubuntu), so in effect, the `./scirpt/setup` config is the same as running directly on the host.  Running in the container obviously has less risk of clobbering your host configuration, so still seems like a good option to me so long as interface bridging, etc. is working.

**Comment by jwhui** [comment]
> While the RPi-based setup which you propose certainly provides more features etc, the old OTBR Docker-based setup was super fast and easy to configure even on a workstation, so it was a great choice for quick testing of new changes using Python CHIP Controller as it didn't require connecting RPi to do basic testing. Is it possible to run the `./script/setup` on a laptop so that it doesn't modify my Wi-Fi settings and just adds `wpan0` interface, starts OTBR services and configures routing properly?

We recently changed the raspbian default for `NETWORK_MANAGER` to `0` in https://github.com/openthread/ot-br-posix/pull/712

As @msandstedt mentioned, the ubuntu default for `NETWORK_MANAGER` is also `0`.

**Comment by Damian-Nordic** [comment]
@msandstedt @jwhui Thanks, I'll try that!

**Review by msandstedt — APPROVED** [review]

**Comment by wgtdkp** [comment]
@Damian-Nordic 
> Could you add a reference to https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/openthread_rcp_nrf_dongle.md for using nRF52840 Dongle as the RCP? The codelab recommends nRF52840 DK, but since we have a guide for the dongle ready, there should be no harm in mentioning it as an alternative.

Added!

> Remove linux_thread_connectivity.svg if it's no longer needed.

Removed!

> Fix reference to linux_thread_connectivity.md in https://github.com/project-chip/connectedhomeip/blob/master/src/controller/python/README.md#thread-provisioning.

Updated!

**Review by Damian-Nordic — APPROVED** [review]

**Review by jwhui — APPROVED** [review]

**Review by librasungirl — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Pull request merged**
