### PR TITLE
[Tizen] Add Thread stack manager implementation

### PR DESCRIPTION
**Pull request by ay-agarwal**
Problem
Thread Stack Manager is not implemented for Tizen.

Change overview
Add Thread Stack Manager implementation and thread network commissioning driver for Tizen.

Testing
chip-tool and chip-lighting-app examples

### CODE REVIEW

**Review by dh79pyun — APPROVED** [review]
Looks good

**Review by wootak-jung — APPROVED** [review]
Looks good to me.

**Review by woody-apple — APPROVED** [review]
Fast tracking platform changes.

**Review by hyunuktak — APPROVED** [review]
Looks good to me.

**Review by msandstedt — APPROVED** [review]

**Comment by dh79pyun** [comment]
We will raise the additional PR to add a command to download Tizen thread stack in Tizen docker file.
After applying Tizen docker's change, the fail issue will be resolved.
https://github.com/project-chip/connectedhomeip/runs/5826718468?check_suite_focus=true

**Comment by ay-agarwal** [comment]
Refer the PR for tizen docker modifications
https://github.com/project-chip/connectedhomeip/pull/17041

**Comment by dh79pyun** [comment]
Can we re-trigger the workflows?

**Comment by MoonkiHong** [comment]
@hrajendran-samsung Please take a look at the request [above](https://github.com/project-chip/connectedhomeip/pull/16749#issuecomment-1098540964)

**Comment by dh79pyun** [comment]
When I see the fail log no build fail, the test works with the previous tizen-docker. 0.5.58

https://github.com/project-chip/connectedhomeip/runs/6119450320?check_suite_focus=true

  Digest: sha256:a8d0e5007519adf36d5d15b0f46f73a9cc8d7aae865d261ca854088bb9ad3aee
  Status: Downloaded newer image for connectedhomeip/chip-build-tizen:0.5.58
  docker.io/connectedhomeip/chip-build-tizen:0.5.58
  /usr/bin/docker create --name cdbdfe4ef69e43d198e9786302cac2a7_connectedhomeipchipbuildtizen0558_b63be3 --label 294b31 --workdir /__w/connectedhomeip/connectedhomeip --network github_network_615c3f187f6b4ef1b62d451a4cb1c41a --user root -e "HOME=/github/home" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/tmp/bloat_reports":"/tmp/bloat_reports" -v "/tmp/output_binaries":"/tmp/output_binaries" -v "/home/runner/work":"/__w" -v "/home/runner/runners/2.290.1/externals":"/__e":ro -v "/home/runner/work/_temp":"/__w/_temp" -v "/home/runner/work/_actions":"/__w/_actions" -v "/opt/hostedtoolcache":"/__t" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" --entrypoint "tail" connectedhomeip/chip-build-tizen:0.5.58 "-f" "/dev/null"

We applied Tizen docker change into 0.5.61 version.

https://github.com/project-chip/connectedhomeip/pull/17041/files 

So need to run the testing using the latest docker.

**Comment by dh79pyun** [comment]
> When I see the fail log no build fail, the test works with the previous tizen-docker. 0.5.58
> 
> https://github.com/project-chip/connectedhomeip/runs/6119450320?check_suite_focus=true
> 
> Digest: sha256:a8d0e5007519adf36d5d15b0f46f73a9cc8d7aae865d261ca854088bb9ad3aee Status: Downloaded newer image for connectedhomeip/chip-build-tizen:0.5.58 docker.io/connectedhomeip/chip-build-tizen:0.5.58 /usr/bin/docker create --name cdbdfe4ef69e43d198e9786302cac2a7_connectedhomeipchipbuildtizen0558_b63be3 --label 294b31 --workdir /__w/connectedhomeip/connectedhomeip --network github_network_615c3f187f6b4ef1b62d451a4cb1c41a --user root -e "HOME=/github/home" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/tmp/bloat_reports":"/tmp/bloat_reports" -v "/tmp/output_binaries":"/tmp/output_binaries" -v "/home/runner/work":"/__w" -v "/home/runner/runners/2.290.1/externals":"/__e":ro -v "/home/runner/work/_temp":"/__w/_temp" -v "/home/runner/work/_actions":"/__w/_actions" -v "/opt/hostedtoolcache":"/__t" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" --entrypoint "tail" connectedhomeip/chip-build-tizen:0.5.58 "-f" "/dev/null"
> 
> We applied Tizen docker change into 0.5.61 version.
> 
> https://github.com/project-chip/connectedhomeip/pull/17041/files
> 
> So need to run the testing using the latest docker.

If I see the latest PR, it works on the latest tizen docker.

https://github.com/project-chip/connectedhomeip/pull/17675
https://github.com/project-chip/connectedhomeip/runs/6145754553?check_suite_focus=true

Status: Downloaded newer image for connectedhomeip/chip-build-tizen:0.5.64
  docker.io/connectedhomeip/chip-build-tizen:0.5.64

So can you re-trriger the work flow? Then the fail issue will be resolved

**Comment by dh79pyun** [comment]
> > When I see the fail log no build fail, the test works with the previous tizen-docker. 0.5.58
> > https://github.com/project-chip/connectedhomeip/runs/6119450320?check_suite_focus=true
> > Digest: sha256:a8d0e5007519adf36d5d15b0f46f73a9cc8d7aae865d261ca854088bb9ad3aee Status: Downloaded newer image for connectedhomeip/chip-build-tizen:0.5.58 docker.io/connectedhomeip/chip-build-tizen:0.5.58 /usr/bin/docker create --name cdbdfe4ef69e43d198e9786302cac2a7_connectedhomeipchipbuildtizen0558_b63be3 --label 294b31 --workdir /__w/connectedhomeip/connectedhomeip --network github_network_615c3f187f6b4ef1b62d451a4cb1c41a --user root -e "HOME=/github/home" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/tmp/bloat_reports":"/tmp/bloat_reports" -v "/tmp/output_binaries":"/tmp/output_binaries" -v "/home/runner/work":"/__w" -v "/home/runner/runners/2.290.1/externals":"/__e":ro -v "/home/runner/work/_temp":"/__w/_temp" -v "/home/runner/work/_actions":"/__w/_actions" -v "/opt/hostedtoolcache":"/__t" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" --entrypoint "tail" connectedhomeip/chip-build-tizen:0.5.58 "-f" "/dev/null"
> > We applied Tizen docker change into 0.5.61 version.
> > https://github.com/project-chip/connectedhomeip/pull/17041/files
> > So need to run the testing using the latest docker.
> 
> If I see the latest PR, it works on the latest tizen docker.
> 
> #17675 https://github.com/project-chip/connectedhomeip/runs/6145754553?check_suite_focus=true
> 
> Status: Downloaded newer image for connectedhomeip/chip-build-tizen:0.5.64 docker.io/connectedhomeip/chip-build-tizen:0.5.64
> 
> So can you re-trriger the work flow? Then the fail issue will be resolved

The same change is success to build on next PR.
https://github.com/project-chip/connectedhomeip/pull/16749

Maybe some env issue in the current PR.

**Comment by ay-agarwal** [comment]
Closing this PR since, same changes get merged via
https://github.com/project-chip/connectedhomeip/pull/17677

**Pull request closed without merging**
