### PR TITLE
Add a section based report for bloat reports

### PR DESCRIPTION
**Pull request by andy31415**
#### Problem
Bloat report is repetitive and not pretty to look at

 #### Summary of Changes
working towards #1021 and #1022

### CODE REVIEW

**Review by woody-apple — COMMENTED** [review]
/pullapprove-test

```
version: 3

github_api_version: "shadow-cat-preview"

############################################################
#  Conditions
############################################################

pullapprove_conditions:
    ############################################################
    #  Required status checks
    ############################################################
    - condition: "'*restyle*' in statuses.successful"
      unmet_status: "failure"
      explanation: "Style must be inline before reviewing can be complete"

    ############################################################
    #  Draft PRs
    ############################################################
    - condition: "'WIP' not in title"
      unmet_status: pending
      explanation: "Work in progress"

    - condition: "not draft"
      unmet_status: pending
      explanation: "Work in progress"

    ############################################################
    #  Conditions to Skip Review
    ############################################################
    - condition: "base.ref == 'master'"
      unmet_status: success
      explanation: "Review not required unless merging to master"

    ############################################################
    #  Bypass reviews
    ############################################################
    - "'hotfix' not in labels"

############################################################
#  Notifications
############################################################

notifications:
    ############################################################
    #  New contributors
    ############################################################
    - when: pull_request.opened
      if: "author_association == 'FIRST_TIME_CONTRIBUTOR'"
      comment: |
          Hey @{{ author }}, thanks for the PR! The review will start once
          the tests and CI checks have passed. If they don't, please review
          the logs and try to fix the issues (ask for help if you can't
          figure it out). A reviewer will be assigned once the tests are
          passing and they'll walk you through getting the PR finished
          and merged.

groups:
    ############################################################
    #  Base Required Reviewers
    ############################################################
    required-reviewers:
        type: required
        conditions:
            - files.include('*')
        reviews:
            required: 3
        reviewers:
            teams:
                - reviewers-amazon
                - reviewers-apple
                - reviewers-comcast
                - reviewers-google
                - reviewers-samsung
```

**Review by woody-apple — COMMENTED** [review]
/pullapprove-test

```
version: 3

github_api_version: "shadow-cat-preview"


notifications:
    ############################################################
    #  New contributors
    ############################################################
    - when: pull_request.opened
      if: "author_association == 'FIRST_TIME_CONTRIBUTOR'"
      comment: |
          Hey @{{ author }}, thanks for the PR! The review will start once
          the tests and CI checks have passed. If they don't, please review
          the logs and try to fix the issues (ask for help if you can't
          figure it out). A reviewer will be assigned once the tests are
          passing and they'll walk you through getting the PR finished
          and merged.

groups:
    ############################################################
    #  Base Required Reviewers
    ############################################################
    required-reviewers:
        type: required
        conditions:
            - files.include('*')
        reviews:
            required: 3
        reviewers:
            teams:
                - reviewers-amazon
                - reviewers-apple
                - reviewers-comcast
                - reviewers-google
                - reviewers-samsung
```

**Review by woody-apple — COMMENTED** [review]
/pullapprove-test

```
version: 3

github_api_version: "shadow-cat-preview"

pullapprove_conditions:
    ############################################################
    #  Required status checks
    ############################################################
    - condition: "'*restyle*' in statuses.successful"
      unmet_status: "failure"
      explanation: "Style must be inline before reviewing can be complete"

notifications:
    ############################################################
    #  New contributors
    ############################################################
    - when: pull_request.opened
      if: "author_association == 'FIRST_TIME_CONTRIBUTOR'"
      comment: |
          Hey @{{ author }}, thanks for the PR! The review will start once
          the tests and CI checks have passed. If they don't, please review
          the logs and try to fix the issues (ask for help if you can't
          figure it out). A reviewer will be assigned once the tests are
          passing and they'll walk you through getting the PR finished
          and merged.

groups:
    ############################################################
    #  Base Required Reviewers
    ############################################################
    required-reviewers:
        type: required
        conditions:
            - files.include('*')
        reviews:
            required: 3
        reviewers:
            teams:
                - reviewers-amazon
                - reviewers-apple
                - reviewers-comcast
                - reviewers-google
                - reviewers-samsung
```

**Review by woody-apple — COMMENTED** [review]
/pullapprove-test

```
version: 3

github_api_version: "shadow-cat-preview"

pullapprove_conditions:
    ############################################################
    #  Required status checks
    ############################################################
    - condition: "'*restyle*' in statuses.successful"
      unmet_status: "failure"
      explanation: "Style must be inline before reviewing can be complete"

    ############################################################
    #  Draft PRs
    ############################################################
    - condition: "'WIP' not in title"
      unmet_status: pending
      explanation: "Work in progress"

    - condition: "not draft"
      unmet_status: pending
      explanation: "Work in progress"

    ############################################################
    #  Conditions to Skip Review
    ############################################################
    - condition: "base.ref == 'master'"
      unmet_status: success
      explanation: "Review not required unless merging to master"

notifications:
    ############################################################
    #  New contributors
    ############################################################
    - when: pull_request.opened
      if: "author_association == 'FIRST_TIME_CONTRIBUTOR'"
      comment: |
          Hey @{{ author }}, thanks for the PR! The review will start once
          the tests and CI checks have passed. If they don't, please review
          the logs and try to fix the issues (ask for help if you can't
          figure it out). A reviewer will be assigned once the tests are
          passing and they'll walk you through getting the PR finished
          and merged.

groups:
    ############################################################
    #  Base Required Reviewers
    ############################################################
    required-reviewers:
        type: required
        conditions:
            - files.include('*')
        reviews:
            required: 3
        reviewers:
            teams:
                - reviewers-amazon
                - reviewers-apple
                - reviewers-comcast
                - reviewers-google
                - reviewers-samsung
```

**Review by woody-apple — COMMENTED** [review]
/pullapprove-test

```
version: 3

github_api_version: "shadow-cat-preview"

pullapprove_conditions:
    ############################################################
    #  Required status checks
    ############################################################
    - condition: "'*restyle*' in statuses.successful"
      unmet_status: "failure"
      explanation: "Style must be inline before reviewing can be complete"

    ############################################################
    #  Draft PRs
    ############################################################

    - condition: "not draft"
      unmet_status: pending
      explanation: "Work in progress"


notifications:
    ############################################################
    #  New contributors
    ############################################################
    - when: pull_request.opened
      if: "author_association == 'FIRST_TIME_CONTRIBUTOR'"
      comment: |
          Hey @{{ author }}, thanks for the PR! The review will start once
          the tests and CI checks have passed. If they don't, please review
          the logs and try to fix the issues (ask for help if you can't
          figure it out). A reviewer will be assigned once the tests are
          passing and they'll walk you through getting the PR finished
          and merged.

groups:
    ############################################################
    #  Base Required Reviewers
    ############################################################
    required-reviewers:
        type: required
        conditions:
            - files.include('*')
        reviews:
            required: 3
        reviewers:
            teams:
                - reviewers-amazon
                - reviewers-apple
                - reviewers-comcast
                - reviewers-google
                - reviewers-samsung
```

**Review by woody-apple — COMMENTED** [review]
/pullapprove-test

```
version: 3

github_api_version: "shadow-cat-preview"

pullapprove_conditions:
    ############################################################
    #  Required status checks
    ############################################################
    - condition: "'*restyle*' in statuses.successful"
      unmet_status: "failure"
      explanation: "Style must be inline before reviewing can be complete"


notifications:
    ############################################################
    #  New contributors
    ############################################################
    - when: pull_request.opened
      if: "author_association == 'FIRST_TIME_CONTRIBUTOR'"
      comment: |
          Hey @{{ author }}, thanks for the PR! The review will start once
          the tests and CI checks have passed. If they don't, please review
          the logs and try to fix the issues (ask for help if you can't
          figure it out). A reviewer will be assigned once the tests are
          passing and they'll walk you through getting the PR finished
          and merged.

groups:
    ############################################################
    #  Base Required Reviewers
    ############################################################
    required-reviewers:
        type: required
        conditions:
            - files.include('*')
        reviews:
            required: 3
        reviewers:
            teams:
                - reviewers-amazon
                - reviewers-apple
                - reviewers-comcast
                - reviewers-google
                - reviewers-samsung
```

**Review by woody-apple — COMMENTED** [review]
/pullapprove-test

```
version: 3

github_api_version: "shadow-cat-preview"

pullapprove_conditions:
    ############################################################
    #  Required status checks
    ############################################################
    - condition: "'*restyled*' in statuses.successful"
      unmet_status: "failure"
      explanation: "Style must be inline before reviewing can be complete"


notifications:
    ############################################################
    #  New contributors
    ############################################################
    - when: pull_request.opened
      if: "author_association == 'FIRST_TIME_CONTRIBUTOR'"
      comment: |
          Hey @{{ author }}, thanks for the PR! The review will start once
          the tests and CI checks have passed. If they don't, please review
          the logs and try to fix the issues (ask for help if you can't
          figure it out). A reviewer will be assigned once the tests are
          passing and they'll walk you through getting the PR finished
          and merged.

groups:
    ############################################################
    #  Base Required Reviewers
    ############################################################
    required-reviewers:
        type: required
        conditions:
            - files.include('*')
        reviews:
            required: 3
        reviewers:
            teams:
                - reviewers-amazon
                - reviewers-apple
                - reviewers-comcast
                - reviewers-google
                - reviewers-samsung
```

**Review by woody-apple — COMMENTED** [review]
/pullapprove-test

```
version: 3

github_api_version: "shadow-cat-preview"

pullapprove_conditions:
    ############################################################
    #  Required status checks
    ############################################################
    - condition: "'*restyled*' in statuses.successful"
      unmet_status: "failure"
      explanation: "Style must be inline before reviewing can be complete"

    ############################################################
    #  Draft PRs
    ############################################################
    - condition: "'WIP' not in title"
      unmet_status: pending
      explanation: "Work in progress"

notifications:
    ############################################################
    #  New contributors
    ############################################################
    - when: pull_request.opened
      if: "author_association == 'FIRST_TIME_CONTRIBUTOR'"
      comment: |
          Hey @{{ author }}, thanks for the PR! The review will start once
          the tests and CI checks have passed. If they don't, please review
          the logs and try to fix the issues (ask for help if you can't
          figure it out). A reviewer will be assigned once the tests are
          passing and they'll walk you through getting the PR finished
          and merged.

groups:
    ############################################################
    #  Base Required Reviewers
    ############################################################
    required-reviewers:
        type: required
        conditions:
            - files.include('*')
        reviews:
            required: 3
        reviewers:
            teams:
                - reviewers-amazon
                - reviewers-apple
                - reviewers-comcast
                - reviewers-google
                - reviewers-samsung
```

**Review by woody-apple — COMMENTED** [review]
/pullapprove-test

```
version: 3

github_api_version: "shadow-cat-preview"

pullapprove_conditions:
    ############################################################
    #  Required status checks
    ############################################################
    - condition: "'*restyled*' in statuses.successful"
      unmet_status: "failure"
      explanation: "Style must be inline before reviewing can be complete"

    ############################################################
    #  Draft PRs
    ############################################################
    - condition: "'WIP' not in title"
      unmet_status: pending
      explanation: "Work in progress"

    - condition: "not draft"
      unmet_status: pending
      explanation: "Work in progress"


notifications:
    ############################################################
    #  New contributors
    ############################################################
    - when: pull_request.opened
      if: "author_association == 'FIRST_TIME_CONTRIBUTOR'"
      comment: |
          Hey @{{ author }}, thanks for the PR! The review will start once
          the tests and CI checks have passed. If they don't, please review
          the logs and try to fix the issues (ask for help if you can't
          figure it out). A reviewer will be assigned once the tests are
          passing and they'll walk you through getting the PR finished
          and merged.

groups:
    ############################################################
    #  Base Required Reviewers
    ############################################################
    required-reviewers:
        type: required
        conditions:
            - files.include('*')
        reviews:
            required: 3
        reviewers:
            teams:
                - reviewers-amazon
                - reviewers-apple
                - reviewers-comcast
                - reviewers-google
                - reviewers-samsung
```

**Review by woody-apple — COMMENTED** [review]
/pullapprove-test

```
version: 3

github_api_version: "shadow-cat-preview"

pullapprove_conditions:
    ############################################################
    #  Required status checks
    ############################################################
    - condition: "'*restyled*' in statuses.successful"
      unmet_status: "failure"
      explanation: "Style must be inline before reviewing can be complete"

    ############################################################
    #  Draft PRs
    ############################################################
    - condition: "'WIP' not in title"
      unmet_status: pending
      explanation: "Work in progress"

notifications:
    ############################################################
    #  New contributors
    ############################################################
    - when: pull_request.opened
      if: "author_association == 'FIRST_TIME_CONTRIBUTOR'"
      comment: |
          Hey @{{ author }}, thanks for the PR! The review will start once
          the tests and CI checks have passed. If they don't, please review
          the logs and try to fix the issues (ask for help if you can't
          figure it out). A reviewer will be assigned once the tests are
          passing and they'll walk you through getting the PR finished
          and merged.

groups:
    ############################################################
    #  Base Required Reviewers
    ############################################################
    required-reviewers:
        type: required
        conditions:
            - files.include('*')
        reviews:
            required: 3
        reviewers:
            teams:
                - reviewers-amazon
                - reviewers-apple
                - reviewers-comcast
                - reviewers-google
                - reviewers-samsung
```

**Review by woody-apple — COMMENTED** [review]
/pullapprove-test

```
version: 3

github_api_version: "shadow-cat-preview"

pullapprove_conditions:
    ############################################################
    #  Required status checks
    ############################################################
    - condition: "'*restyled*' in statuses.successful"
      unmet_status: "failure"
      explanation: "Style must be inline before reviewing can be complete"

    ############################################################
    #  Draft PRs
    ############################################################
    - condition: "'WIP' not in title"
      unmet_status: pending
      explanation: "Work in progress"

    ############################################################
    #  Conditions to Skip Review
    ############################################################
    - condition: "base.ref == 'master'"
      unmet_status: success
      explanation: "Review not required unless merging to master"

    ############################################################
    #  Bypass reviews
    ############################################################
    - "'hotfix' not in labels"


notifications:
    ############################################################
    #  New contributors
    ############################################################
    - when: pull_request.opened
      if: "author_association == 'FIRST_TIME_CONTRIBUTOR'"
      comment: |
          Hey @{{ author }}, thanks for the PR! The review will start once
          the tests and CI checks have passed. If they don't, please review
          the logs and try to fix the issues (ask for help if you can't
          figure it out). A reviewer will be assigned once the tests are
          passing and they'll walk you through getting the PR finished
          and merged.

groups:
    ############################################################
    #  Base Required Reviewers
    ############################################################
    required-reviewers:
        type: required
        conditions:
            - files.include('*')
        reviews:
            required: 3
        reviewers:
            teams:
                - reviewers-amazon
                - reviewers-apple
                - reviewers-comcast
                - reviewers-google
                - reviewers-samsung
```

**Review by woody-apple — COMMENTED** [review]
/pullapprove-test

```
version: 3

# https://developer.github.com/v3/previews/#draft-pull-requests
github_api_version: "shadow-cat-preview"

pullapprove_conditions:
    ############################################################
    #  Required status checks
    ############################################################
    - condition: "'*restyled*' in statuses.successful"
      unmet_status: "failure"
      explanation: "Style must be inline before reviewing can be complete"

    ############################################################
    #  Draft PRs
    ############################################################
    - condition: "'WIP' not in title"
      unmet_status: pending
      explanation: "Work in progress"
    - condition: "not draft"
      unmet_status: "pending"
      explanation: "Work in progress"


    ############################################################
    #  Conditions to Skip Review
    ############################################################
    - condition: "base.ref == 'master'"
      unmet_status: success
      explanation: "Review not required unless merging to master"

    ############################################################
    #  Bypass reviews
    ############################################################
    - "'hotfix' not in labels"


notifications:
    ############################################################
    #  New contributors
    ############################################################
    - when: pull_request.opened
      if: "author_association == 'FIRST_TIME_CONTRIBUTOR'"
      comment: |
          Hey @{{ author }}, thanks for the PR! The review will start once
          the tests and CI checks have passed. If they don't, please review
          the logs and try to fix the issues (ask for help if you can't
          figure it out). A reviewer will be assigned once the tests are
          passing and they'll walk you through getting the PR finished
          and merged.

groups:
    ############################################################
    #  Base Required Reviewers
    ############################################################
    required-reviewers:
        type: required
        conditions:
            - files.include('*')
        reviews:
            required: 3
        reviewers:
            teams:
                - reviewers-amazon
                - reviewers-apple
                - reviewers-comcast
                - reviewers-google
                - reviewers-samsung
```

**Review by woody-apple — COMMENTED** [review]
/pullapprove-test

```
version: 3

# https://developer.github.com/v3/previews/#draft-pull-requests
github_api_version: "shadow-cat-preview"

############################################################
#  Conditions
############################################################

pullapprove_conditions:
    ############################################################
    #  Required status checks
    ############################################################
    - condition: "'*restyle*' in statuses.successful"
      unmet_status: "failure"
      explanation: "Style must be inline before reviewing can be complete"

    ############################################################
    #  Draft PRs
    ############################################################
    - condition: "'WIP' not in title"
      unmet_status: "pending"
      explanation: "Work in progress"

    - condition: "not draft"
      unmet_status: "pending"
      explanation: "Work in progress"

    ############################################################
    #  Conditions to Skip Review
    ############################################################
    - condition: "base.ref == 'master'"
      unmet_status: "success"
      explanation: "Review not required unless merging to master"

    ############################################################
    #  Bypass reviews
    ############################################################
    - "'hotfix' not in labels"

############################################################
#  Notifications
############################################################

notifications:
    ############################################################
    #  New contributors
    ############################################################
    - when: pull_request.opened
      if: "author_association == 'FIRST_TIME_CONTRIBUTOR'"
      comment: |
          Hey @{{ author }}, thanks for the PR! The review will start once
          the tests and CI checks have passed. If they don't, please review
          the logs and try to fix the issues (ask for help if you can't
          figure it out). A reviewer will be assigned once the tests are
          passing and they'll walk you through getting the PR finished
          and merged.

groups:
    ############################################################
    #  Base Required Reviewers
    ############################################################
    required-reviewers:
        description: >
            [Required
            Reviewers](https://github.com/project-chip/connectedhomeip/blob/master/CONTRIBUTING.md#review-requirements)
            This is the main group of required reviews for general Pull
            Requests.
        type: required
        conditions:
            - files.include('*')
        reviews:
            required: 3
            request: -1
            request_order: shuffle
        reviewers:
            teams:
                - reviewers-amazon
                - reviewers-apple
                - reviewers-comcast
                - reviewers-google
                - reviewers-samsung
```

**Review by woody-apple — COMMENTED** [review]
/pullapprove-test

```
version: 3

# https://developer.github.com/v3/previews/#draft-pull-requests
github_api_version: "shadow-cat-preview"

############################################################
#  Conditions
############################################################

pullapprove_conditions:
    ############################################################
    #  Required status checks
    ############################################################
    - condition: "'*restyle*' in statuses.successful"
      unmet_status: "failure"
      explanation: "Style must be inline before reviewing can be complete"

    ############################################################
    #  Draft PRs
    ############################################################
    - condition: "'WIP' not in title"
      unmet_status: "pending"
      explanation: "Work in progress"

    ############################################################
    #  Conditions to Skip Review
    ############################################################
    - condition: "base.ref == 'master'"
      unmet_status: "success"
      explanation: "Review not required unless merging to master"

    ############################################################
    #  Bypass reviews
    ############################################################
    - "'hotfix' not in labels"

############################################################
#  Notifications
############################################################

notifications:
    ############################################################
    #  New contributors
    ############################################################
    - when: pull_request.opened
      if: "author_association == 'FIRST_TIME_CONTRIBUTOR'"
      comment: |
          Hey @{{ author }}, thanks for the PR! The review will start once
          the tests and CI checks have passed. If they don't, please review
          the logs and try to fix the issues (ask for help if you can't
          figure it out). A reviewer will be assigned once the tests are
          passing and they'll walk you through getting the PR finished
          and merged.

groups:
    ############################################################
    #  Base Required Reviewers
    ############################################################
    required-reviewers:
        description: >
            [Required
            Reviewers](https://github.com/project-chip/connectedhomeip/blob/master/CONTRIBUTING.md#review-requirements)
            This is the main group of required reviews for general Pull
            Requests.
        type: required
        conditions:
            - files.include('*')
        reviews:
            required: 3
            request: -1
            request_order: shuffle
        reviewers:
            teams:
                - reviewers-amazon
                - reviewers-apple
                - reviewers-comcast
                - reviewers-google
                - reviewers-samsung
```

**Review by woody-apple — APPROVED** [review]

**Review by saurabhst — APPROVED** [review]

**Review by gerickson — CHANGES_REQUESTED** [review]
Might be missing some key sections.

**Review by gerickson — APPROVED** [review]

**Review by jelderton — APPROVED** [review]

**Pull request merged**
