### PR TITLE
use BUILD ARG USERNAME instead of hardcode

### PR DESCRIPTION
**Pull request by rwalker-apple**
#### Problem
 Dockerfile using hardcoded username

 #### Summary of Changes
 Use supplied ARG

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

**Review by gerickson — APPROVED** [review]

**Review by saurabhst — APPROVED** [review]

**Review by woody-apple — COMMENTED** [review]
/pullapprove-test

```
version: 3
groups:
    reviewers-amazon:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-amazon]

    reviewers-apple:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-apple]

    reviewers-comcast:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-comcast]

    reviewers-google:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-google]

    reviewers-samsung:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-samsung]

    shared:
        type: required
        conditions:
            - len(groups.approved.include('reviewers-*')) >= 3
        reviews:
            required: 0
```

**Review by woody-apple — COMMENTED** [review]
/pullapprove-test

```
version: 3
groups:
    reviewers-amazon:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-amazon]

    reviewers-apple:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-apple]

    reviewers-comcast:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-comcast]

    reviewers-google:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-google]

    reviewers-samsung:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-samsung]

    shared:
        type: required
        conditions:
            - len(groups.approved.include('reviewers-*')) >= 3
        reviews:
            required: 0
```

**Review by BroderickCarlin — APPROVED** [review]

**Review by woody-apple — COMMENTED** [review]
/pullapprove-test

```
version: 3
groups:
    reviewers-amazon:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-amazon]

    reviewers-apple:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-apple]

    reviewers-comcast:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-comcast]

    reviewers-google:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-google]

    reviewers-samsung:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-samsung]

    shared:
        type: required
        conditions:
            - len(groups.approved.include('reviewers-*')) >= 3
        reviews:
            required: 0
```

**Review by woody-apple — COMMENTED** [review]
version: 3
groups:
    reviewers-amazon:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-amazon]

    reviewers-apple:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-apple]

    reviewers-comcast:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-comcast]

    reviewers-google:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-google]

    reviewers-samsung:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-samsung]

    shared:
        type: required
        conditions:
            - len(groups.approved.include('reviewers-*')) >= 3
        reviews:
            required: 3

**Review by woody-apple — COMMENTED** [review]
/pullapprove-test

```
version: 3
groups:
    reviewers-amazon:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-amazon]

    reviewers-apple:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-apple]

    reviewers-comcast:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-comcast]

    reviewers-google:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-google]

    reviewers-samsung:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-samsung]

    shared:
        type: required
        conditions:
            - len(groups.approved.include('reviewers-*')) >= 3
        reviews:
            required: 3
```

**Review by woody-apple — COMMENTED** [review]
/pullapprove-test

```
version: 3
groups:
    code:
        reviewers-amazon:
            type: optional
            conditions:
                - files.include('*')
            reviewers:
                teams: [reviewers-amazon]

        reviewers-apple:
            type: optional
            conditions:
                - files.include('*')
            reviewers:
                teams: [reviewers-apple]

        reviewers-comcast:
            type: optional
            conditions:
                - files.include('*')
            reviewers:
                teams: [reviewers-comcast]

        reviewers-google:
            type: optional
            conditions:
                - files.include('*')
            reviewers:
                teams: [reviewers-google]

        reviewers-samsung:
            type: optional
            conditions:
                - files.include('*')
            reviewers:
                teams: [reviewers-samsung]

        shared:
            type: required
            conditions:
                - len(groups.approved.include('reviewers-*')) >= 3
            reviews:
                required: 0
```

**Review by woody-apple — COMMENTED** [review]
/pullapprove-test

```
version: 3
groups:
    reviewers-amazon:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-amazon]

    reviewers-apple:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-apple]

    reviewers-comcast:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-comcast]

    reviewers-google:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-google]

    reviewers-samsung:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-samsung]

    shared:
        type: required
        conditions:
            - len(groups.approved.include('reviewers-*')) >= 3
        reviews:
            required: 3
```

**Review by woody-apple — COMMENTED** [review]
/pullapprove-test

```
version: 3
groups:
    required-reviewers:
        type: required
        conditions:
            - files.include('.devcontainer/*')
            - len(groups.approved.include('reviewers-*')) >= 3
        reviews:
            required: 0

    reviewers-amazon:
        type: optional
        conditions:
            - files.include('.devcontainer/*')
        reviewers:
            teams: [reviewers-amazon]

    reviewers-apple:
        type: optional
        conditions:
            - files.include('.devcontainer/*')
        reviewers:
            teams: [reviewers-apple]

    reviewers-comcast:
        type: optional
        conditions:
            - files.include('.devcontainer/*')
        reviewers:
            teams: [reviewers-comcast]

    reviewers-google:
        type: optional
        conditions:
            - files.include('.devcontainer/*')
        reviewers:
            teams: [reviewers-google]

    reviewers-samsung:
        type: optional
        conditions:
            - files.include('.devcontainer/*')
        reviewers:
            teams: [reviewers-samsung]
```

**Review by woody-apple — COMMENTED** [review]
/pullapprove-test

```
version: 3
groups:
    required-reviewers:
        type: required
        conditions:
            - files.include('*')
        reviews:
            required: 4

    reviewers-amazon:
        type: optional
        conditions:
            - files.include('src/*')
        reviewers:
            teams: [reviewers-amazon]

    reviewers-apple:
        type: optional
        conditions:
            - files.include('src/*')
        reviewers:
            teams: [reviewers-apple]

    reviewers-comcast:
        type: optional
        conditions:
            - files.include('src/*')
        reviewers:
            teams: [reviewers-comcast]

    reviewers-google:
        type: optional
        conditions:
            - files.include('src/*')
        reviewers:
            teams: [reviewers-google]

    reviewers-samsung:
        type: optional
        conditions:
            - files.include('src/*')
        reviewers:
            teams: [reviewers-samsung]
```

**Review by woody-apple — COMMENTED** [review]
/pullapprove-test

```
version: 3
groups:
    required-reviewers:
        type: required
        conditions:
            - files.include('*')
            - len(groups.approved.include('reviewers-*')) >= 4
        reviews:
            required: 4

    reviewers-amazon:
        type: optional
        conditions:
            - files.include('src/*')
        reviewers:
            teams: [reviewers-amazon]

    reviewers-apple:
        type: optional
        conditions:
            - files.include('src/*')
        reviewers:
            teams: [reviewers-apple]

    reviewers-comcast:
        type: optional
        conditions:
            - files.include('src/*')
        reviewers:
            teams: [reviewers-comcast]

    reviewers-google:
        type: optional
        conditions:
            - files.include('src/*')
        reviewers:
            teams: [reviewers-google]

    reviewers-samsung:
        type: optional
        conditions:
            - files.include('src/*')
        reviewers:
            teams: [reviewers-samsung]
```

**Review by woody-apple — COMMENTED** [review]
/pullapprove-test

```
version: 3
groups:
    required-reviewers:
        type: required
        conditions:
            - len(groups.approved.include('reviewers-*')) >= 3
        reviews:
            required: 0

    reviewers-amazon:
        type: optional
        conditions:
            - files.include('src/*')
        reviewers:
            teams: [reviewers-amazon]

    reviewers-apple:
        type: optional
        conditions:
            - files.include('src/*')
        reviewers:
            teams: [reviewers-apple]

    reviewers-comcast:
        type: optional
        conditions:
            - files.include('src/*')
        reviewers:
            teams: [reviewers-comcast]

    reviewers-google:
        type: optional
        conditions:
            - files.include('src/*')
        reviewers:
            teams: [reviewers-google]

    reviewers-samsung:
        type: optional
        conditions:
            - files.include('src/*')
        reviewers:
            teams: [reviewers-samsung]
```

**Review by woody-apple — COMMENTED** [review]
/pullapprove-test

```
version: 3
groups:
    required-reviewers:
        type: required
        conditions:
            - len(groups.approved.include('reviewers-*')) >= 3
        reviews:
            required: 0

    reviewers-amazon:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-amazon]

    reviewers-apple:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-apple]

    reviewers-comcast:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-comcast]

    reviewers-google:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-google]

    reviewers-samsung:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-samsung]
```

**Review by woody-apple — COMMENTED** [review]
/pullapprove-test

```
version: 3

groups:
    required-reviewers:
        type: required
        conditions:
            - len(groups.approved.include('reviewer-groups-*')) >= 3
        reviews:
            required: 0
    reviewer-groups-amazon:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams:
                - reviewers-amazon
    reviewer-groups-apple:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams:
                - reviewers-apple
    reviewer-groups-comcast:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams:
                - reviewers-comcast
    reviewer-groups-google:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams:
                - reviewers-google
    reviewers-samsung:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams:
                - reviewers-samsung
```

**Review by woody-apple — COMMENTED** [review]
/pullapprove-test

```
version: 3

groups:
    ############################################################
    #  Base Required Reviewers
    ############################################################
    required-reviewers:
        type: required
        conditions:
            - files.include('*')
        reviews:
            required: 3
        reviewers:
            teams:
                - reviewers-amazon
                - reviewers-apple
                - reviewers-comcast
                - reviewers-google
                - reviewers-samsung
```

**Pull request merged**
