### PR TITLE
Unify Android build logic

### PR DESCRIPTION
**Pull request by austinh0**
#### Problem
* `scripts/build/builders/android.py` is used in the CI to build the Android CHIPTool, but `scripts/examples/android_app.sh` does the same thing and is used by devs locally

#### Change overview
* `android_app.sh` is renamed`android_app_ide.sh` and only supports the IDE build path now.
* Modify `android_app.py`
  * Add x86
  * `./gradlew build` -> `./gradlew assembleDebug`. `build` compiles debug and release APKs, which seems unnecessary and is slow.
* Update documentation

#### Testing
* Manually built and installed APK with both scripts.
* `android.py` used by Android CI

### CODE REVIEW

**Review by saurabhst — APPROVED** [review]

**Comment by austinh0** [comment]
Oops, didn't mean to re-request from Saurabh.

**Review by woody-apple — APPROVED** [review]

**Comment by austinh0** [comment]
@andy31415 @Damian-Nordic @jmartinez-silabs @chrisdecenzo @hawk248?

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
@austinh0 - the build_examples.py build script has unit tests. You will need to add/modify the file scripts/build/expected_all_platform_commands.txt (remeber to use the placeholders {out} and {root} and such.

**Comment by austinh0** [comment]
Updated the expected commands and the tests pass. Not sure what to do about spellcheck erroring out on `installDebug`, `matterBuildSrcDir`, etc...

**Pull request merged**
