### PR TITLE
Update builds to docker version 22

### PR DESCRIPTION
**Pull request by s07641069**
**Change overview**

- Update builds to docker version 22 https://github.com/project-chip/connectedhomeip/pull/29886
- Update Telink readme files
- Update Telink variables in examples/chef/chef.py

### CODE REVIEW

**Comment by s07641069** [comment]
@andy31415 Blocked by https://github.com/project-chip/connectedhomeip/pull/29886
just need to press update to master when new docker images will be available

**Review by andy31415 — COMMENTED** [review]
Should update cloudbuild yaml files as well since it seems we need compatibility updates in building chef for example.

**Comment by s07641069** [comment]
> Should update cloudbuild yaml files as well since it seems we need compatibility updates in building chef for example.

Maybe I didn't get you point fully, but looks like everything updated already.
If you mean update of "integrations/docker/images/vscode/chip-build-vscode/Dockerfile", here were used correct (new) environments before my changes:
```
ENV TELINK_ZEPHYR_BASE=/opt/telink/zephyrproject/zephyr
ENV TELINK_ZEPHYR_SDK_DIR=/opt/telink/zephyr-sdk-0.16.1
```

If you mean something else what is missing, just let me know.

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
> > Should update cloudbuild yaml files as well since it seems we need compatibility updates in building chef for example.
> 
> Maybe I didn't get you point fully, but looks like everything updated already. If you mean update of "integrations/docker/images/vscode/chip-build-vscode/Dockerfile", here were used correct (new) environments before my changes:
> 
> ```
> ENV TELINK_ZEPHYR_BASE=/opt/telink/zephyrproject/zephyr
> ENV TELINK_ZEPHYR_SDK_DIR=/opt/telink/zephyr-sdk-0.16.1
> ```
> 
> If you mean something else what is missing, just let me know.

Somehow I had missed the changes to cloudbuild files ... added checkmark.

**Pull request merged**
