### PR TITLE
Add telink support for script/build/build_examples.py

### PR DESCRIPTION
**Pull request by rikorsev**
#### Problem
https://github.com/project-chip/connectedhomeip/issues/8843

#### Change overview
* Update **scripts/build/build/factory** and  **scripts/build/build/targets.py** to make support id by Telink
* Create **scripts/build/builders/telink.py** builder script

#### Testing
Manually:
1. Run chip-build-vscode docker container
2. Check if following command works to build Telink example:
```$ ./scripts/build/build_examples.py --platform telink --board tlsr9518adk80d build```
3. Check if following command works to build all examples (including Telink one):
```$ ./scripts/build/build_examples.py --platform all build```

### CODE REVIEW

**Review by andy31415 — COMMENTED** [review]
The build_examples.py has a unit test  - you will need to modify `expected_all_platform_commands.txt`. To test do something like:

```
gn gen out
cd out
ninja  scripts/build:build_examples.tests
```

Please make sure you substitute variables as needed, likely needing to set extra environment options in scripts/build/test.py

**Comment by andy31415** [comment]
@rikorsev - could you resync and address the renum comment as well (either by removing enum   items or  adding app build support)?

Latest telink image should be built now in the vscode image and we had some updates in factory/target (added android and applied pep8 autoformat)

**Review by andy31415 — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
@saurabhst ?

**Review by saurabhst — APPROVED** [review]

**Pull request merged**
