### PR TITLE
[cirque] Re-enable cirque test w/o im tests

### PR DESCRIPTION
**Pull request by erjiaqing**
#### Problem

Enable cirque tests to make sure the protocol works well.

 #### Summary of Changes

- Enable cirque test, but remove interaction model from the list.
- Removed OnOffClusterTest since it is covered by MobileDeviceTest

 Fixes #<<<<<FILL ME IN  - issue number(s). If no issue, please create one>>>>>

### CODE REVIEW

**Review by saurabhst — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
@msandstedt @mspang @andy31415 ?

**Review by mspang — APPROVED** [review]

**Comment by erjiaqing** [comment]
@Damian-Nordic 
Hi, per test log

```
2021-04-21 17:25:31,273 [CHIPMobileDevice] INFO Sending On/Off commands to device 1
CHIP:ZCL: Successfully encoded 11 bytes
CHIP:IN: Secure message was encrypted: Msg ID 2
CHIP:IN: Sending msg from 0x000000000001b669 to 0x0000000000000001 at utc time: 1272046 msec
CHIP:IN: Sending secure msg on generic transport
CHIP:EM: ec pos: 1, id: 17769, Delegate: 0xf47900
CHIP:ZCL: APS frame processing success!
CHIP:ZCL: RX len 5, ep 1, clus 0x 6 
CHIP:ZCL:  FC 8 seq 2 cmd b payload[
CHIP:ZCL: 01 00 
CHIP:ZCL: ]
CHIP:ZCL: DefaultResponse:
CHIP:ZCL:   ClusterId: 0x0006
CHIP:ZCL:   CommandId: 0x01
CHIP:ZCL:   status: EMBER_ZCL_STATUS_SUCCESS (0x00)
CHIP:ZCL: emberAfDefaultResponseCallback: Missing success callback
CHIP:ZCL: emberAfDefaultResponseCallback: Missing failure callback
CHIP:ZCL: Data model processing success!
CHIP:IN: Secure msg send status No Error
CHIP:CTL: SendMessage returned No Error
```
Seems the python device controller sometimes failed to awake when it received the response of the command.

**Review by msandstedt — APPROVED** [review]

**Comment by andy31415** [comment]
I see cirque failure already in the checks here.

We disabled cirque because it seemed to create more false positives than finding bugs. Having it already fail in the 're-enabling' PR worries me.

**Review by andy31415 — CHANGES_REQUESTED** [review]
I would like to find some way to have assurances that cirque is stable or figure out some rules on when do we disable it again. I currently do not have confidence in cirque and it is a slow process.

I would like to either gain confidence (never breaks or if it breaks it proves to find real bugs) or have an agreement that we will disable it again on the first false positive.

**Comment by erjiaqing** [comment]
> I would like to find some way to have assurances that cirque is stable or figure out some rules on when do we disable it again. I currently do not have confidence in cirque and it is a slow process.
> 
> I would like to either gain confidence (never breaks or if it breaks it proves to find real bugs) or have an agreement that we will disable it again on the first false positive.

The cause of cirque test failing is https://github.com/project-chip/connectedhomeip/issues/6251.


Currently, we added debugging tools to Cirque and since the failures are caused by CHIP program and in the middle of the tests,  I believe it will become stable after the issue fixed or we can identify more bugs via this PR.

**Review by andy31415 — APPROVED** [review]

**Pull request merged**
