### PR TITLE
[android] Peristent storage fixes

### PR DESCRIPTION
**Pull request by Damian-Nordic**
#### Problem
Android CHIPTool crashes when trying to commission a device.

 #### Summary of Changes
Fix issues in the code for storing persistent data, causing crashes at the beginning of commissioning process in Android
CHIP Tool.
Note that the commissioning in Android CHIP Tool still must be switched to the new commissioning flow, but this is the first step to make it usable again.

### CODE REVIEW

**Review by saurabhst — APPROVED** [review]

**Comment by woody-apple** [comment]
@Damian-Nordic Is there any way to launch the Android app from CI to catch this? (Note: I'm working on this for the iOS app right now)

**Comment by woody-apple** [comment]
@Damian-Nordic - needs a restyle, sorry :( I tried to do it, but sadly - I don't have write access to your fork

**Comment by woody-apple** [comment]
/pull-approve-test
```yaml
version: 3

# https://developer.github.com/v3/previews/#draft-pull-requests
github_api_version: "shadow-cat-preview"

############################################################
#  Conditions
############################################################

pullapprove_conditions:
    ############################################################
    #  License Checks
    ############################################################
    - condition: "'*license/cla*' in statuses.successful"
      unmet_status: "pending"
      explanation: "CLA must be agreed to by all contributors"

    ############################################################
    #  Draft PRs
    ############################################################
    - condition: "'WIP' not in title"
      unmet_status: "pending"
      explanation: "Work in progress"

    - condition: "not draft"
      unmet_status: "pending"
      explanation: "Work in progress"

    ############################################################
    #  Conditions to Skip Review
    ############################################################
    - condition: "base.ref == 'master'"
      unmet_status: "success"
      explanation: "Review not required unless merging to master"

    ############################################################
    #  Bypass reviews
    ############################################################
    - "'hotfix' not in labels"

############################################################
#  Notifications
############################################################

notifications:
    ############################################################
    #  New contributors
    ############################################################
    - when: pull_request.opened
      if: "author_association == 'FIRST_TIME_CONTRIBUTOR'"
      comment: |
          Hey @{{ author }}, thanks for the PR! The review will start once
          the tests and CI checks have passed. If they don't, please review
          the logs and try to fix the issues (ask for help if you can't
          figure it out). A reviewer will be assigned once the tests are
          passing and they'll walk you through getting the PR finished
          and merged.

groups:
    ############################################################
    #  Shared Reviewer Groups
    ############################################################
    shared-reviewers-amazon:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-amazon]
        reviews:
            request: 1
    shared-reviewers-apple:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-apple]
        reviews:
            request: 1
    shared-reviewers-comcast:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-comcast]
        reviews:
            request: 1
    shared-reviewers-google:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-google]
        reviews:
            request: 1
    shared-reviewers-nordic:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-nordic]
        reviews:
            request: 1
    shared-reviewers-samsung:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-samsung]
        reviews:
            request: 1
    shared-reviewers-silabs:
        type: optional
        conditions:
            - files.include('*')
        reviewers:
            teams: [reviewers-silabs]
        reviews:
            request: 1

    ############################################################
    #  Base Required Reviewers
    ############################################################
    required-reviewers:
        description: >
            [Required
            Reviewers](https://github.com/project-chip/connectedhomeip/blob/master/CONTRIBUTING.md#review-requirements)
            This is the main group of required reviews for general pull
            requests.
        type: required
        requirements:
            - len(groups.approved.include('shared-reviewers-*')) >= 3
        reviews:
            required: 0
        labels:
            approved: "review - approved"
            pending: "review - pending"
            rejected: "review - changed requested"

    ############################################################
    #  Style
    ############################################################
    style:
        conditions:
            - "'*restyle*' in statuses.successful"
        type: required
        labels:
            rejected: "needs restyle"

    ############################################################
    #  Label Based Reviewers
    ############################################################
    codeowners-android:
        type: optional
        conditions:
            - "'android' in labels"
        reviewers:
            teams:
                - codeowners-android
        reviews:
            request: 1

    codeowners-app:
        type: optional
        conditions:
            - "'app' in labels"
        reviewers:
            teams:
                - codeowners-app
        reviews:
            request: 1

    codeowners-ble:
        type: optional
        conditions:
            - "'ble' in labels"
        reviewers:
            teams:
                - codeowners-ble
        reviews:
            request: 1

    codeowners-controller:
        type: optional
        conditions:
            - "'controller' in labels"
        reviewers:
            teams:
                - codeowners-controller
        reviews:
            request: 1

    codeowners-darwin:
        type: optional
        conditions:
            - "'darwin' in labels"
        reviewers:
            teams:
                - codeowners-darwin
        reviews:
            request: 1

    codeowners-crypto:
        type: optional
        conditions:
            - "'crypto' in labels"
        reviewers:
            teams:
                - codeowners-crypto
        reviews:
            request: 1

    codeowners-inet:
        type: optional
        conditions:
            - "'inet' in labels"
        reviewers:
            teams:
                - codeowners-inet
        reviews:
            request: 2

    codeowners-core:
        type: optional
        conditions:
            - "'core' in labels"
        reviewers:
            teams:
                - codeowners-core
        reviews:
            request: 2

    codeowners-protocols:
        type: optional
        conditions:
            - "'protocols' in labels"
        reviewers:
            teams:
                - codeowners-protocols
        reviews:
            request: 1

    codeowners-shell:
        type: optional
        conditions:
            - "'shell' in labels"
        reviewers:
            teams:
                - codeowners-shell
        reviews:
            request: 1

    codeowners-support:
        type: optional
        conditions:
            - "'support' in labels"
        reviewers:
            teams:
                - codeowners-support
        reviews:
            request: 1

    codeowners-platform:
        type: optional
        conditions:
            - "'platform' in labels"
        reviewers:
            teams:
                - codeowners-platform
        reviews:
            request: 1

    codeowners-qrcode:
        type: optional
        conditions:
            - "'qrcode' in labels"
        reviewers:
            teams:
                - codeowners-qrcode
        reviews:
            request: 1

    codeowners-setup-payload:
        type: optional
        conditions:
            - "'setup payload' in labels"
        reviewers:
            teams:
                - codeowners-setup-payload
        reviews:
            request: 1

    codeowners-system:
        type: optional
        conditions:
            - "'system' in labels"
        reviewers:
            teams:
                - codeowners-system
        reviews:
            request: 1

    codeowners-test-driver:
        type: optional
        conditions:
            - "'test driver' in labels"
        reviewers:
            teams:
                - codeowners-test-driver
        reviews:
            request: 1

    codeowners-github:
        type: optional
        conditions:
            - "'github' in labels"
        reviewers:
            teams:
                - codeowners-github
        reviews:
            request: 1

    codeowners-vscode:
        type: optional
        conditions:
            - "'vscode' in labels"
        reviewers:
            teams:
                - codeowners-vscode
        reviews:
            request: 2

    codeowners-integrations:
        type: optional
        conditions:
            - "'integrations' in labels"
        reviewers:
            teams:
                - codeowners-integrations
        reviews:
            request: 1

    codeowners-transport:
        type: optional
        conditions:
            - "'transport' in labels"
        reviewers:
            teams:
                - codeowners-transport
        reviews:
            request: 1

    codeowners-scripts:
        type: optional
        conditions:
            - "'scripts' in labels"
        reviewers:
            teams:
                - codeowners-scripts
        reviews:
            request: 1

    codeowners-documentation:
        type: optional
        conditions:
            - "'documentation' in labels"
        reviewers:
            teams:
                - codeowners-documentation
        reviews:
            request: 1

    codeowners-gn:
        type: optional
        conditions:
            - "'gn' in labels"
        reviewers:
            teams:
                - codeowners-gn
        reviews:
            request: 1
```

**Review by woody-apple — COMMENTED** [review]
<removing testing pull approve>

**Review by woody-apple — COMMENTED** [review]
Removing pull approve test

**Review by woody-apple — COMMENTED** [review]
<deleting pull approve test>

**Review by woody-apple — COMMENTED** [review]
<deleting pull approve test>

**Review by woody-apple — APPROVED** [review]

**Comment by Damian-Nordic** [comment]
@woody-apple There exists Android Emulator: https://developer.android.com/studio/run/emulator, but I have no experience with using it for automated testing. Also, Android CHIPTool uses the controller API defined in `src/controller/java` which is distributed as a JAR library, so it should be possible to write some tests in Java which link to the same JAR. However, the Bluetooth stack is implemented in the CHIP Tool itself so we wouldn't test the commissioning that way :(.

**Review by LuDuda — APPROVED** [review]

**Pull request merged**
