### PR TITLE
Add contact-sensor-app

### PR DESCRIPTION
**Pull request by andrei-menzopol**
* Add K32W0 contact-sensor-app example
* Add contact-sensor-app-common files
* Generate zap-files

Signed-off-by: Ethan Tan <ethan.tan@nxp.com>
Signed-off-by: Andrei Menzopol <andrei.menzopol@nxp.com>

### CODE REVIEW

**Comment by mrjerryjohns** [comment]
This should really be leveraging chef I'd think. (`examples/chef`). That provides a way to create device-type specific examples from a single generic 'builder'. Presumably, you could add your platform specific application guts there.

**Review by mrjerryjohns — DISMISSED** [review]
More and more example apps isn't the right answer - it just creates a lot of extra duplicated code for platform-specific business logic, as well as lots of extra generated code.

I'd like to see if we can leverage chef for something like this.

**Comment by andrei-menzopol** [comment]
@mrjerryjohns Thank you for the suggestion. I agree that a better solution is needed here. I didn't know about chef.
However, do you think we can let this pass and come later with a PR that switches the examples to chef. We need the contact-sensor-app example and the chef approach looks like it needs some work.

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
Fast tracking platform changes.

**Comment by mrjerryjohns** [comment]
> However, do you think we can let this pass and come later with a PR that switches the examples to chef. 

I'm fine with letting this PR in for now. @andrei-menzopol would you be able to see if you could eventually port it over to Chef as a follow-up?

**Comment by andrei-menzopol** [comment]
@mrjerryjohns Yes, I will port it to chef in a follow-up PR. Thanks.

**Pull request merged**
