### PR TITLE
increase default CHIP_CONFIG_MDNS_RESOLVE_LOOKUP_RESULTS to 3

### PR DESCRIPTION
**Pull request by rus084**
in this commit connecting to next resolved address was fixed https://github.com/project-chip/connectedhomeip/commit/f9339cc201cc05bf5c0e99cdae4db22e631b0cf6
but it doesn't work's because CHIP_CONFIG_MDNS_RESOLVE_LOOKUP_RESULTS is 1 and there is no next addresses

### CODE REVIEW

**Comment by andy31415** [comment]
This seems to have quite a bit of sideffects in terms of RAM usage. Should this be on a platform by platform instead?

**Comment by rus084** [comment]
> This seems to have quite a bit of sideffects in terms of RAM usage. Should this be on a platform by platform instead?
Seems there is some wifi routers that has IPV6 issues and CHIP_CONFIG_MDNS_RESOLVE_LOOKUP_RESULTS should be at least 2 for ability fallback to IPV4.

**Comment by cecille** [comment]
Is that really what we want? Given that IPv4 fallback isn't mandated in the spec, changing this in the base config rather than letting the individual configs handle it means we could be hiding problems by falling back to a non-mandated mechanism rather than root causing the issues.

**Comment by andy31415** [comment]
Old PR without any checkmarks or comment followup from author in a while now. Closing as stale.

**Pull request closed without merging**
