### PR TITLE
[hotfix] Fix build break with #7537

### PR DESCRIPTION
**Pull request by erjiaqing**
#### Problem
#7598 need to run codegen since template is changed before it is merged.

#### Change overview
Run codegen for #7598

#### Testing
- Build pass.

### CODE REVIEW

**Review by yufengwangca — APPROVED** [review]

**Review by mspang — APPROVED** [review]

**Comment by woody-apple** [comment]
https://github.com/project-chip/connectedhomeip/pull/7678 ?

**Comment by mspang** [comment]
> #7678 ?

hotfix doesn't work anymore?

**Comment by mspang** [comment]
> > #7678 ?
> 
> hotfix doesn't work anymore?

I'm not understanding the logic behind what status are always required now. It seems to be some examples/platforms but not others.

Having at least the ability to unilaterally revert seems useful.

**Review by yunhanw-google — APPROVED** [review]

**Comment by woody-apple** [comment]
Hotfix works fine? my question was - which approach are we taking?

**Comment by woody-apple** [comment]
Note, it looks like this broke it: https://github.com/project-chip/connectedhomeip/pull/7537

**Comment by mspang** [comment]
> Hotfix works fine? my question was - which approach are we taking?

I was not able to submit this PR without waiting for a subset of the checks in queue.

**Pull request merged**
