### PR TITLE
Android ide build and CHIPTest build into CI

### PR DESCRIPTION
**Pull request by xylophone21**
#### Problem
* CHIPTool IDE build, and CHIPTest build are not included in CI, We often break the build in commit

#### Change overview
* Add CHIPTool IDE build, and CHIPTest build into CI, to make sure every commit will not break the build

#### Testing
* Build local with basic test

### CODE REVIEW

**Comment by xylophone21** [comment]
There is a restyled-io issue I did not fixed because I failed to run restyled-io version on my local and this file same with online version of src/android/CHIPTool/gradlew. The patch looks like below:

```diff
diff --git a/src/android/CHIPTest/gradlew b/src/android/CHIPTest/gradlew
index 4f906e0c8..892bbbdad 100755
--- a/src/android/CHIPTest/gradlew
+++ b/src/android/CHIPTest/gradlew
@@ -26,22 +26,22 @@
 # Resolve links: $0 may be a link
 PRG="$0"
 # Need this for relative symlinks.
-while [ -h "$PRG" ] ; do
-    ls=`ls -ld "$PRG"`
-    link=`expr "$ls" : '.*-> \(.*\)$'`
-    if expr "$link" : '/.*' > /dev/null; then
+while [ -h "$PRG" ]; do
+    ls=$(ls -ld "$PRG")
+    link=$(expr "$ls" : '.*-> \(.*\)$')
+    if expr "$link" : '/.*' >/dev/null; then
         PRG="$link"
     else
-        PRG=`dirname "$PRG"`"/$link"
+        PRG=$(dirname "$PRG")"/$link"
     fi
 done
-SAVED="`pwd`"
-cd "`dirname \"$PRG\"`/" >/dev/null
-APP_HOME="`pwd -P`"
+SAVED="$(pwd)"
+cd "$(dirname \""$PRG"\")/" >/dev/null
+APP_HOME="$(pwd -P)"
 cd "$SAVED" >/dev/null
```

**Review by bzbarsky-apple — APPROVED** [review]
Rubber-stamping.

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
@mrjerryjohns @saurabhst @andy31415 @Damian-Nordic @jelderton @jepenven-silabs @jmartinez-silabs ?

**Review by jmeg-sfy — APPROVED** [review]

**Review by lazarkov — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]

**Review by chrisdecenzo — APPROVED** [review]

**Comment by andy31415** [comment]
Artifact generation seems broken:

```
2021-10-12 18:10:46 INFO    Adding /workspace/out/android-androidstudio-chip-tool/outputs/apk/debug/app-debug.apk into /workspace/artifacts/android-androidstudio-chip-tool.tar.gz/CHIPTool-debug.apk
Traceback (most recent call last):
  File "/workspace/./scripts/build/build_examples.py", line 213, in <module>
    main()
...
  File "/usr/lib/python3.9/tarfile.py", line 1842, in gettarinfo
    statres = os.lstat(name)
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/out/android-androidstudio-chip-tool/outputs/apk/debug/app-debug.apk'
ERROR
```

Tried to debug, however running locally `./scripts/build/build_examples.py --enable-flashbundle --target-glob '*studio*' build --copy-artifacts-to ./out/artifacts` fails with:

```
2021-10-12 18:25:01 WARNING > A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
2021-10-12 18:25:01 WARNING    > 2 files found with path 'lib/armeabi-v7a/libCHIPController.so' from inputs:
2021-10-12 18:25:01 WARNING       - /workspaces/connectedhomeip/src/android/CHIPTool/app/build/intermediates/merged_jni_libs/debug/out
2021-10-12 18:25:01 WARNING       - /workspaces/connectedhomeip/src/android/CHIPTool/app/build/intermediates/cmake/debug/obj
2021-10-12 18:25:01 WARNING      If you are using jniLibs and CMake IMPORTED targets, see
2021-10-12 18:25:01 WARNING      https://developer.android.com/r/tools/jniLibs-vs-imported-targets
2021-10-12 18:25:01 WARNING 
2021-10-12 18:25:01 WARNING * Try:
2021-10-12 18:25:01 WARNING Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

**Pull request merged**
