### PR TITLE
Update docker images to 0.5.50

### PR DESCRIPTION
**Pull request by pankore**
#### Problem
Update yaml files to adapt the docker update in #13695

#### Change overview
Update yaml files to the latest available version.

#### Testing
CI will validate that things compile.

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

**Review by LuDuda — APPROVED** [review]

**Comment by pankore** [comment]
Note: As this Ameba SDK update has dependency of PR #13408, it will have auto-build error before PR #13408 is merged.

**Comment by pankore** [comment]
Note: This PR is expected to be merged after PR #13866.

**Review by msandstedt — APPROVED** [review]

**Pull request merged**
