### PR TITLE
Use field identifiers when code gen struct items

### PR DESCRIPTION
**Pull request by mlepage-google**
#### Problem
Field identifiers were not being used. Instead, the order of field
identifiers was used, with ordinal (0 to N-1) indexes.

This is likely true of other code generated elements, but this PR only
fixes it for struct items.

#### Change overview
Generate struct field IDs code properly with actual fieldId rather than index.

This PR requires PR #326 in the third_party/zap/repo to function,
as that PR actually includes the field identifier in the query
results.

#### Testing
Tested by running Matter cert tests, and also by inspecting the
generated code for correctness.

### CODE REVIEW

**Comment by mlepage-google** [comment]
Converted to draft until submodule PR goes in, and submodule is updated to include it in this repo (likely in a further revision of this PR).

**Comment by mlepage-google** [comment]
(Note that presubmit tests on this PR will fail until the zap submodule is updated with the dependent changes.)

**Review by tcarmelveilleux — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]
Nice catch!

**Comment by mlepage-google** [comment]
Updated submodule, ran cert tests, so good to go. (Not sure why it says there's a conflict in the zap repo...)

**Comment by mlepage-google** [comment]
Argh, looks like master changed while I was updating this PR, between my merging master and updating the submodule.

**Comment by andy31415** [comment]
fast track - basic change, but requires zap merging

**Comment by mlepage-google** [comment]
Updated the couple generated files that changed. Re-ran cert tests. Should be good now?

**Review by jmartinez-silabs — APPROVED** [review]

**Comment by andy31415** [comment]
Removed fast track: has sufficient checkmarks

**Pull request merged**
