### PR TITLE
Update ZAP to version that generates min/max information.

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
The XML updates are based on examining the all-clusters app codegen
and removing spurious min-max constraints that just restate the value
range of the type (e.g. setting max to 0xFFFF for an int16u).  A few
attributes were made nullable in the process to remove an unnecessary
constraint like max="0xFFFE" when the spec says range is all but the
attribute is nullable.

#### Problem
min/max in XML are ignored in our codegen.

#### Change overview
Output min/max information in the generated endpoint_config.

#### Testing
Code inspection.  yaml tests are forthcoming, in followup PRs.

### CODE REVIEW

**Comment by vivien-apple** [comment]
@bzbarsky-apple The `.data` section increase seems huge ?

**Comment by bzbarsky-apple** [comment]
> @bzbarsky-apple The .data section increase seems huge ?

Yep, I am working on fixing that right now.  ;)

**Review by andy31415 — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
@saurabhst @msandstedt @Damian-Nordic @LuDuda @vivien-apple @woody-apple @jmartinez-silabs @jepenven-silabs could you please take a look?

**Review by woody-apple — APPROVED** [review]
Fast tracking this, given this is adding functionality for tests.

**Pull request merged**
