### PR TITLE
[K32W0] Read General Diagnostics cluster attribute at runtime

### PR DESCRIPTION
**Pull request by doru91**
#### Problem
* General Diagnostics cluster implementation was missing on K32W0 platform

#### Change overview
* Add General Diagnostics cluster implementation on K32W0

#### Testing
* manually tested using chip-tool

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]
Fast tracking, given this is a platform maintainer updating their platform.

**Comment by doru91** [comment]
Rebased.

**Pull request merged**
