### PR TITLE
Adjust PBUF_POOL_SIZE to the minimal size to run CHIP stack

### PR DESCRIPTION
**Pull request by yufengwangca**
#### Problem
 #5610 temporarily reduce the pbuf pool size to allow us enable exchange layer, after a serious of memory optimization, now we should have room to set PBUF_POOL_SIZE  to the minimal value to allow CHIP stack work.
 
We need at least 6 buffers to allow one protocol fully functional.
1. one buffer to send and one buffer to cache the sent message for CRMP.
2. one buffer to receive. 
3. one buffer to send standalong ack to ack out-of-exchange reliable message.
4. two buffers for MCSP.

4.9.1.1. Session Establishment over IP
....
[4.272] IPv6 fragmentation is not mandatory to support in CHIP, and the expected supported MTU is
1280 bytes, the minimum required by IPv6. Therefore, all CHIP messages used for session
establishment, or to be supported over CRMP, SHALL fit within that minimal IPv6 MTU. CRMP has
size requirements that also match this MTU constraint, see Section 4.14.6.1, “Message Size
Requirements”.

No CHIP messages shall use the payload larger than IPv6 MTU. Adjust the PBUF size to 1280 bytes.

Please note, the final lwip configuration should be set by vendor based on their use cases and capabilities. 

 #### Summary of Changes
1. Adjust PBUF_POOL_SIZE to the minimal size to allow CHIP stack work.
2. Change the PBUF size to fit within minimal IPv6 MTU.
3. Remove unused flags PBUF_POOL_SIZE_LARGE, PBUF_POOL_SIZE_MEDIUM, PBUF_POOL_SIZE_SMALL

### CODE REVIEW

**Comment by msandstedt** [comment]
> It looks PBUF_POOL_SIZE_LARGE, PBUF_POOL_SIZE_MEDIUM, PBUF_POOL_SIZE_SMALL are not used in current lwip stack, I was wondering if we can fine tune lwip stack further if those configs are used in the updated lwip version.

Last time I checked, I also couldn't find any use of PBUF_POOL_SIZE_LARGE, PBUF_POOL_SIZE_MEDIUM, PBUF_POOL_SIZE_SMALL either in our repo or in the newest lwip.

However, they have been tweaked for certain platforms in recent commits, indicating the fact they don't do anything is not well understood.  I would advocate that we remove them.

**Comment by yufengwangca** [comment]
> > It looks PBUF_POOL_SIZE_LARGE, PBUF_POOL_SIZE_MEDIUM, PBUF_POOL_SIZE_SMALL are not used in current lwip stack, I was wondering if we can fine tune lwip stack further if those configs are used in the updated lwip version.
> 
> Last time I checked, I also couldn't find any use of PBUF_POOL_SIZE_LARGE, PBUF_POOL_SIZE_MEDIUM, PBUF_POOL_SIZE_SMALL either in our repo or in the newest lwip.
> 
> However, they have been tweaked for certain platforms in recent commits, indicating the fact they don't do anything is not well understood. I would advocate that we remove them.

Will those config be used in the coming lwip release?

**Comment by msandstedt** [comment]
> > > It looks PBUF_POOL_SIZE_LARGE, PBUF_POOL_SIZE_MEDIUM, PBUF_POOL_SIZE_SMALL are not used in current lwip stack, I was wondering if we can fine tune lwip stack further if those configs are used in the updated lwip version.
> > 
> > 
> > Last time I checked, I also couldn't find any use of PBUF_POOL_SIZE_LARGE, PBUF_POOL_SIZE_MEDIUM, PBUF_POOL_SIZE_SMALL either in our repo or in the newest lwip.
> > However, they have been tweaked for certain platforms in recent commits, indicating the fact they don't do anything is not well understood. I would advocate that we remove them.
> 
> Will those config be used in the coming lwip release?

They don't exist in master branch at https://github.com/lwip-tcpip/lwip or https://git.savannah.gnu.org/git/lwip.git.  So I sure don't think so.  I'm not sure where they came from.  Perhaps these configs are deprecated.

**Comment by yufengwangca** [comment]
> > > > It looks PBUF_POOL_SIZE_LARGE, PBUF_POOL_SIZE_MEDIUM, PBUF_POOL_SIZE_SMALL are not used in current lwip stack, I was wondering if we can fine tune lwip stack further if those configs are used in the updated lwip version.
> > > 
> > > 
> > > Last time I checked, I also couldn't find any use of PBUF_POOL_SIZE_LARGE, PBUF_POOL_SIZE_MEDIUM, PBUF_POOL_SIZE_SMALL either in our repo or in the newest lwip.
> > > However, they have been tweaked for certain platforms in recent commits, indicating the fact they don't do anything is not well understood. I would advocate that we remove them.
> > 
> > 
> > Will those config be used in the coming lwip release?
> 
> They don't exist in master branch at https://github.com/lwip-tcpip/lwip or https://git.savannah.gnu.org/git/lwip.git. So I sure don't think so. I'm not sure where they came from. Perhaps these configs are deprecated.

It looks like those flags came from Weave and Weave use customized lwip stack. Thanks for checking.

**Review by msandstedt — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Comment by yufengwangca** [comment]
@Damian-Nordic @jepenven-silabs ?

**Review by jelderton — APPROVED** [review]

**Comment by andy31415** [comment]
I believe adjusting to bare minimum CRMP size may not be sufficient: recieving and replying to mDNS queries likely also requires at least 2 buffers (one for receive and one for reply).

**Pull request merged**
