### PR TITLE
[examples] Use correct endpoints for lock and lighting clusters

### PR DESCRIPTION
**Pull request by Damian-Nordic**
#### Problem
The commissioners assume that device clusters involved in the commissioning process are on endpoint 0. On the other hand, application clusters like OnOff or LevelControl should be on other endpoints. Lock and lighting examples don't meet these requirements. In particular, it's impossible to commision the lock-app into a network using standard commissioners.

#### Change overview
Modify lock-app and lighting-app examples to use endpoint 0 for utility clusters and endpoint 1 for application clusters.

#### Testing
I tested the full commissioning flow between Python CHIP Controller and nrfconnect lock-app and lighting-app.

### CODE REVIEW

**Review by bzbarsky-apple — COMMENTED** [review]
Ideally we would have the utility clusters on EP0 and the application functionality on EP1...

**Comment by Damian-Nordic** [comment]
> Ideally we would have the utility clusters on EP0 and the application functionality on EP1...

This is something unclear to me based on the spec. The chapter about the commissionable node discovery mentions that the device type of the node should be equal to the device type of endpoint 0 and it gives "Door Lock" as an example which would suggest that door lock clusters should be on endpoint 0.

In case I move all applications clusters to endpoint 1 or higher, what should be the device type of endpoint 0?

**Comment by bzbarsky-apple** [comment]
> device type of the node should be equal to the device type of endpoint 0

That's a bug.  See https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/3213 and https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/3254

> In case I move all application clusters to endpoint 1 or higher, what should be the device type of endpoint 0?

There's going to be a "Matter utility device" or some such defined.  When we actually get to the device library....

**Review by jmartinez-silabs — APPROVED** [review]
I validated efr32 lock app. The same changes must also be valid for window-app

**Comment by erjiaqing** [comment]
Can you update endpoint ids in the Python device controller document as well? Thanks.

https://github.com/project-chip/connectedhomeip/tree/master/src/controller/python#example-commissioning-flow-over

e.g.

change
```
chip-device-ctrl > zcl NetworkCommissioning AddWiFiNetwork 4546 1 0 ssid=str:TESTSSID credentials=str:P455W4RD breadcrumb=0 timeoutMs=1000
```
to
```
chip-device-ctrl > zcl NetworkCommissioning AddWiFiNetwork 4546 0 0 ssid=str:TESTSSID credentials=str:P455W4RD breadcrumb=0 timeoutMs=1000
```

**Comment by Damian-Nordic** [comment]
@erjiaqing yes, good point!

**Comment by Damian-Nordic** [comment]
@bzbarsky-apple I moved all clusters except OnOff and LevelControl to endpoint 0.

**Review by bzbarsky-apple — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Pull request merged**
