### PR TITLE
Show preview complex data type

### PR DESCRIPTION
**Pull request by JasonLiuZhuoCheng**
#### Change overview
- In cluster detail page, allow users to see 4 lines of preview of complex data type.

#### Testing
Manually tested.

### CODE REVIEW

**Comment by austinh0** [comment]
This PR adds on top of #11989. If you're going to do this, please separate the changes from that PR and this one into different commits and make it clear in the PR description.

The code here looks fine to me, but will wait to approve until #11989 merges.

**Comment by andy31415** [comment]
@austinh0 ?

**Comment by JasonLiuZhuoCheng** [comment]
> @austinh0 ?

Hi Andy, can you approve this first: https://github.com/project-chip/connectedhomeip/pull/11989
After that, this should be safe to merge in as well.

**Review by austinh0 — APPROVED** [review]
#11989 has merged, please rebase/add a merge commit.

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
Fast tracking given this has been in review for a while.

**Pull request merged**
