### PR TITLE
update cirque repo commit

### PR DESCRIPTION
**Pull request by mingchik**
#### Problem
What is being fixed?  Examples:
bump up cirque latest commit

#### Change overview
cirque latest commit

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
I think we merged the latest cirque fairly recently (1 day ago in #9032). Any reason for the frequent change? I would expect 'pull latest repo' to happen on a month+ basis rather than several times a week.

**Comment by mspang** [comment]
> I would expect 'pull latest repo' to happen on a month+ basis rather than several times a week.

Why? I'd say ideally things roll ~daily if they are actively developed (and that there be adequate testing to make sure that works).

We know that more frequent releases is correlated with better execution.

**Review by yunhanw-google — APPROVED** [review]

**Comment by andy31415** [comment]
> > I would expect 'pull latest repo' to happen on a month+ basis rather than several times a week.
> 
> Why? I'd say ideally things roll ~daily if they are actively developed (and that there be adequate testing to make sure that works).
> 
> We know that more frequent releases is correlated with better execution.

I have just not seen it update in  other places as frequently. If we want frequent syncs, I would try to automate it as PR creation and a separate 3-person review process  with sdk approved and technical review done seems really heavy effort.

If we do it infrequently, I don't care about automation as much. For more frequent changes, I would like  to script this or at least agree to hotfix/admin merge these.

**Comment by yunhanw-google** [comment]
i think it is not frequent sync, mingchi just forget to bring one latest change in last sync.

**Review by msandstedt — APPROVED** [review]

**Review by LuDuda — APPROVED** [review]

**Pull request merged**
