### PR TITLE
GN: Add OpenThread support to nRF5 examples

### LINKED ISSUE #1516: GN build parity: openthread in nrf5 samples
This got added to the sample along the way and the GN build files weren't updated. Update them.

### PR DESCRIPTION
**Pull request by mspang**
Bring up Thread support in the nRF5 example applications. This adds a
build file for the OpenThread nrf528xx platform that uses the installed SDK
instead of the one checked into OpenThread (except for the radio driver,
which causes a compile error currently). Using multiple SDK versions in the
build does not seem safe; we may need to update the code in OpenThread
to support the latest SDK.

Fixes #1516

Depends on #2044, #2036, #2034, #2032

### CODE REVIEW

**Review by gjc13 — APPROVED** [review]

**Review by bukepo — APPROVED** [review]
LGTM:+1:

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
@mspang note, conflicts after merges :)

**Review by BroderickCarlin — APPROVED** [review]

**Comment by mspang** [comment]
> @mspang note, conflicts after merges :)

Waiting on https://github.com/openthread/openthread/pull/5358

**Comment by mspang** [comment]
This is ready now.

**Comment by mspang** [comment]
@woody-apple

**Review by andy31415 — APPROVED** [review]

**Pull request merged**
