### PR TITLE
[v1.0 cherrypick] change for on off transitiontime feature (#21569)

### PR DESCRIPTION
**Pull request by Jerry-ESP**
#21569 
* change for on off transitiontime feature

* Fix subscription test to handle separate reports for different attributes better.

Co-authored-by: Restyled.io <commits@restyled.io>
Co-authored-by: Boris Zbarsky <bzbarsky@apple.com>

### CODE REVIEW

**Comment by chshu** [comment]
> @Jerry-ESP - we generally try to keep v1.0 reasonably stable in terms of functionality. We allow example changes and platform changes as those have less chances of ripple effects and also allow significant bugs fixed (e.g. we had some storage leak issues).
> 
> This PR does not seem to fit exactly in any of the above categories. What is the side-effect if this is NOT merged into 1.0?

@andy31415 Without the fix, the OnOffTransitionTime feature won't work for 1.0 Matter products. The current implementation just passes the certification test, but the Off fade-out feature does not work as expect, the off command is triggered immediately regardless of the transition time.

The fix is requested by a device maker, who implements the OnOffTransitionTime feature in Matter 1.0 lighting products. It would be good to have in 1.0 branch, as long as it passes the CI, and no side effects.

**Comment by bzbarsky-apple** [comment]
@chshu It's still not obvious to me that delaying the change to the "OnOff" attribute is spec-compliant here.  Neither "1.6.4.1.1. Effect of On/Off Commands on the CurrentLevel Attribute" nor "1.6.5.9. OnOffTransitionTime Attribute" talks about doing that.

As far as I can tell what the spec requires is:

1. The OnOff attribute becomes false.
2. The CurrentLevel evolves over time.
3. What happens to the physical light in the process is not really clearly defined, but application logic could prevent it from actually going off until the transition time elapses, without core changes.

Has a spec issue been raised about changing item 1 here, as this PR does?

**Comment by chshu** [comment]
@bzbarsky-apple The OnOffTransitionTime feature is defined clearly in the spec, but it doesn't specify what should be done by the SDK, and what else should be done by Application. I think it's more like a code implementation tadeoff, rather than spec issue.

From the application perspective, it's straightforward to map any attribute change to physical directly in the callbacks. If the SDK doesn't delay the change to the "OnOff" attribute, the additional logic has to be added to all applications that support OnOffTransitionTime (each developer has to implement it once). Implementing the logic in the SDK seems more reasonable, but understand the status of v1.0_branch, we'd leave the decision to maintainers on whether cherry-pick it or not.

Another related question may worth discuss: when should the On/Off change report be sent to the subscriber? If the OffTransition is still on going, should it show Off status on the Phone APPs/Hubs, or wait until the OffTransition is done?

**Comment by bzbarsky-apple** [comment]
> The OnOffTransitionTime feature is defined clearly in the spec

Where in the spec does it clearly say that "OnOff" becoming false is deferred?  @chshu

**Comment by chshu** [comment]
> > The OnOffTransitionTime feature is defined clearly in the spec
> 
> Where in the spec does it clearly say that "OnOff" becoming false is deferred? @chshu

The OnOffTransitionTime feature is clear that the device needs to implement the fade-in/fade-out logic, but agree that the Spec doesn't mention about deferring OnOff attribute change, I thought the Spec leaves it to the code implementation, either the SDK or the Applicaiton has to do the deferring. The PR just adds the defferring logic in SDK, to make it easier for developers.

I will file a Spec issue for further discussion.

**Comment by bzbarsky-apple** [comment]
>  I thought the Spec leaves it to the code implementation

The spec for the "Off" command says:

> On receipt of the Off command, a server SHALL set the OnOff attribute to FALSE.

How is that "left to code implementation"?

The fact is, the code changed involved is violating that SHALL requirement, as far as I can tell....

**Pull request closed without merging**
