### PR TITLE
Moving over to native GitHub CodeQL

### PR DESCRIPTION
**Pull request by woody-apple**
#### Problem
LGTM has been less maintained for a bit, and has been moving into GitHub natively. Let's move over :)

 #### Summary of Changes
Update our build/examples to use CodeQL

### CODE REVIEW

**Comment by woody-apple** [comment]
Note: Restyled still fails on workflow edits :( 

```
stderr ! [remote rejected]   restyled/pull-3032 -> restyled/pull-3032 (refusing to allow a GitHub App to create or update workflow `.github/workflows/build.yaml` without `workflows` permission)
```

So that will need to be bypassed for merge.

**Comment by woody-apple** [comment]
I've a note as well: I've been seeing some weird API timeouts on my fork, seeing if it still happens here

**Comment by rwalker-apple** [comment]
> Note: Restyled still fails on workflow edits :(
> 
> ```
> stderr ! [remote rejected]   restyled/pull-3032 -> restyled/pull-3032 (refusing to allow a GitHub App to create or update workflow `.github/workflows/build.yaml` without `workflows` permission)
> ```
> 
> So that will need to be bypassed for merge.

just run `./scripts/helpers/restyle-diff.sh` in your local tree and re-push

**Comment by rwalker-apple** [comment]
weird that pullapprove isn't going after reviewers-XXX ?

**Comment by woody-apple** [comment]
Yeah, was wondering what PullApprove was doing here. Looking.

**Comment by rwalker-apple** [comment]
mebbe it holds review requests until restyle is complete

**Comment by woody-apple** [comment]
Note: Guess I need to file a bug with GitHub, their CodeQL is getting rate limited... looks like

**Comment by woody-apple** [comment]
Ticket created here: https://support.github.com/ticket/personal/0/856445

**Review by mspang — APPROVED** [review]

**Comment by woody-apple** [comment]
Moving this to draft, let's not merge until we have the GitHub side sorted.

**Review by rwalker-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
Looks like this was fixed here!
https://github.com/github/codeql-action/pull/253

**Comment by woody-apple** [comment]
@saurabhst @jelderton @BroderickCarlin ? I think this is ready for review now!

**Review by saurabhst — APPROVED** [review]

**Pull request merged**
