### PR TITLE
[Ameba] Remove redundant linkage in chip_main.cmake

### PR DESCRIPTION
**Pull request by pankore**
#### Problem
* Remove redundant linkage in chip_main.cmake files

#### Change overview
* Remove the src/app related linkage in chip_main.cmake files

#### Testing
* Tested cmake build
* Tested commissioning via python controller

### CODE REVIEW

**Comment by woody-apple** [comment]
Fast tracking build changes, blocked on build though.

**Comment by pankore** [comment]
> Fast tracking build changes, blocked on build though.

Hi @woody-apple ,
Many thanks for your prompt review, the build failure is expected to be fixed after PR https://github.com/project-chip/connectedhomeip/pull/12463 is merged.
This docker update involves the wl grouping in the cmake file which helps to fix the 'undefined reference' error.
Thanks!

**Review by woody-apple — APPROVED** [review]

**Review by tcarmelveilleux — APPROVED** [review]

**Pull request merged**
