### PR TITLE
Zap on off optional attributes

### PR DESCRIPTION
**Pull request by vivien-apple**
#### Problem

Optional attributes are not enabled for the `OnOff` cluster.

This PR requires an update to ZAP to pass the ZAP templates CI since multiple network diagnostics has landed and they do use the same command name, which triggers https://github.com/project-chip/zap/issues/161

#### Change overview
 * Enable them on the `all-clusters-app` `server` side
 * Enable them on the `client` side for controllers
 
#### Testing
 * Some tests for those attributes have been autogenerated and runned into `src/darwin/Framework/CHIPTests`

### CODE REVIEW

**Comment by vivien-apple** [comment]
Here is the related ZAP PR https://github.com/project-chip/zap/pull/170

**Review by msandstedt — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by vivien-apple** [comment]
I have update the PR with a version of ZAP that contains project-chip/zap#170 and with some minor changes to the templates helper to reflect some renaming that has happened into the latest ZAP version.

I also have remove the `disabled` flag for some of the tests in `src/app/tests/suites/` since the `OnOff` cluster now contains those attributes.

**Comment by woody-apple** [comment]
@andy31415 @Damian-Nordic @LuDuda @jepenven-silabs ?

**Review by Damian-Nordic — APPROVED** [review]

**Pull request merged**
