### PR TITLE
Revert "[Kotlin] Implement Kotlin Cluster Library APIs"

### PR DESCRIPTION
**Pull request by yunhanw-google**
Reverts project-chip/connectedhomeip#30887

Two CI is broken, and revert it
https://github.com/project-chip/connectedhomeip/actions/runs/7174258939/job/19535318635
https://github.com/project-chip/connectedhomeip/actions/runs/7174258932/job/19535318458

### CODE REVIEW

**Review by joonhaengHeo — APPROVED** [review]

**Review by saurabhst — APPROVED** [review]

**Comment by yufengwangca** [comment]
It seems there is another change comes in when I address comments, please hold and will resolve the conflict soon

**Review by yufengwangca — CHANGES_REQUESTED** [review]
It seems there is another change comes in when I address comments, please hold and will resolve the conflict soon

**Review by andy31415 — CHANGES_REQUESTED** [review]
I think in this case we should zap-regen. I will create a PR

**Comment by yufengwangca** [comment]
Fixed by https://github.com/project-chip/connectedhomeip/pull/30943 by re-run the codegen.

**Comment by yufengwangca** [comment]
> I think in this case we should zap-regen. I will create a PR

Created
https://github.com/project-chip/connectedhomeip/pull/30943

**Pull request closed without merging**
