### PR TITLE
Switch to Telink Zephyr main branch (get rid of maintaining special Zephyr branch)

### PR DESCRIPTION
**Pull request by andriy-bilynskyy**
Change overview

Update the Telink BLEManagerImpl module
Update the Telink ThreadStackManagerImpl module
Update telink image to 0.6.52 (use Telink main Zephyr branch)
Testing

Tested manually with chip-tool.

Steps:

Run: $ chip-tool pairing ble-thread <...>
Wait till success
Run: $ chip-tool onoff on ${NODE_ID }1
Wait till success
Run: $ chip-tool onoff off ${NODE_ID }1
Wait till success

### CODE REVIEW

**Review by s07641069 — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]

**Comment by andriy-bilynskyy** [comment]
Please review this PR its touches only Telink vendor and focused on getting rid of special Zephyr branch for Matter project switching to main one (Due to resources it's difficult to maintain special branch)

**Review by andy31415 — APPROVED** [review]

**Comment by Kxuan** [comment]
Hi @andriy-bilynskyy 
It seems this PR breaks BLE advertising.

Devices are unable to be commissioned, since there is no BLE packet sent.

Do you have any idea to fix it?

**Comment by andriy-bilynskyy** [comment]
On which platform have you observed the issue? All merged files are relative only to Telink. Telink nightly CI tests (includung BLE) are OK as I know.

**Comment by Kxuan** [comment]
@andriy-bilynskyy  Yes. telink platform.
All log messages are seems normal. And it do shows log messages like "CHIPoBLE advertising started".

But acturally, devices does not send BLE packets.

**Comment by andriy-bilynskyy** [comment]
In that case please create ticket with your case details (used commit hashes, zephyr hash if yo are not using docker, sample app you are using, changes in configs). Because mainly it works as I already told all commissioning tests on our CI are passed.

**Comment by andriy-bilynskyy** [comment]
BTW: if you are using docker please change it's version. Commit introduces new docker version. With old docker it definitely not working.

**Comment by Kxuan** [comment]
Thanks @andriy-bilynskyy .

After updating zephyr, it works!

**Pull request merged**
