### PR TITLE
ESP32: Fixes for README.md

### PR DESCRIPTION
**Pull request by sweetymhaiske**
#### Problem
* Fixes for README.md for esp32.

#### Change overview
Fixes.

#### Testing
* Checked the modified commands.

### CODE REVIEW

**Review by Damian-Nordic — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]
Thank you!

**Comment by dhrishi** [comment]
@sweetymhaiske  In the same PR, can you please add any missing clusters those were present in all-clusters-app component.mk and not reflected in CMakeLists.txt. Let us make sure that nothing is missed

**Comment by sweetymhaiske** [comment]
> @sweetymhaiske In the same PR, can you please add any missing clusters those were present in all-clusters-app component.mk and not reflected in CMakeLists.txt. Let us make sure that nothing is missed

@dhrishi Done. Thanks.

**Review by jmartinez-silabs — APPROVED** [review]

**Comment by dhrishi** [comment]
Thanks. And one more thing, we had added such text in ESP32 example component.mk:
`# The list of extra component dirs must be in sync with that in all-clusters-app/esp32/Makefile`

You can safely remove that now from all the examples.

**Review by dhrishi — APPROVED** [review]

**Comment by sweetymhaiske** [comment]
> Thanks. And one more thing, we had added such text in ESP32 example component.mk:
> `# The list of extra component dirs must be in sync with that in all-clusters-app/esp32/Makefile`
> 
> You can safely remove that now from all the examples.

Done

**Pull request merged**
