### PR TITLE
[Ameba] Support Pigweed-app

### PR DESCRIPTION
**Pull request by pankore**
#### Problem
* Support Pigweed-app

#### Change overview
* Port Pigweed-app for ameba platform
* Update scripts/build for pigweed-app

#### Testing
Tested rpc.EchoService
Tested rpc.Lighting

### CODE REVIEW

**Comment by pankore** [comment]
The content of this PR relies on the docker update on PR #12979. So that the "Build example - Ameba" will succeed after PR #12979 is merged.

**Comment by pankore** [comment]
Hi @andy31415 @woody-apple ,
May I ask for your help to review this PR and see if this one can be marked with _**Fast Track**_ label or not.
Thanks!

**Review by bzbarsky-apple — APPROVED** [review]
Rubberstamping platform change from platform owner.

**Pull request merged**
