### PR TITLE
ESP32: Fix for CMake build failure for M5Stack and rebuild.

### LINKED ISSUE #5818: ESP32 idf.py build broken for all-clusters app
#### Problem
If I follow the steps in examples/all-clusters-app/esp32/README.md to try to build the all-clusters-app on ESP32, I get:
```
In file included from examples/common/screen-framework/include/Screen.h:28,
                 from examples/common/screen-framework/include/ListScreen.h:28,
                 from examples/common/screen-framework/ListScreen.cpp:26:
examples/common/screen-framework/include/Display.h:51:10: fatal error: tft.h: No such file or directory
 #include "tft.h"
          ^~~~~~~
compilation terminated.
```

 #### Proposed Solution
Following the directions should work.

For comparison, using the "old" way to build (via `source idf.sh` and then `idf make` works just fine.  The officially documented way should also work.

@dhrishi @sweetymhaiske

### PR DESCRIPTION
**Pull request by sweetymhaiske**
#### Problem
1. The CMake build failed for M5Stack.
2. The CMake rebuild failure:-
    After build if we make any changes in CHIP code, it won't get reflect or compiled. We need to clean the complete build to look for the changes.

 #### Summary of Changes
1. Added the needed changes in `/examples/common/screen-framework/CMakeLists.txt`
2. Added the fix under `config/esp32/components/chip/CMakeLists.txt`

 Fixes #5818

### CODE REVIEW

**Comment by renzbagaporo** [comment]
Does `PRIV_REQUIRES` suffice here?

**Review by Damian-Nordic — APPROVED** [review]

**Comment by sweetymhaiske** [comment]
> Does `PRIV_REQUIRES` suffice here?

Done.

**Comment by dhrishi** [comment]
@sweetymhaiske Please check if similar changes are required in `temperature-measurement-app` example as it also supports M5Stack

**Comment by sweetymhaiske** [comment]
> @sweetymhaiske Please check if similar changes are required in `temperature-measurement-app` example as it also supports M5Stack

@dhrishi These changes aren't example specific.

**Review by dhrishi — APPROVED** [review]

**Comment by sweetymhaiske** [comment]
Added the new commit b7634d8, to overcome the issue faced during a rebuild. Initially, the changes made into the CHIP code were not getting reflected in the build unless the complete build was cleaned.

**Review by mspang — APPROVED** [review]

**Comment by woody-apple** [comment]
@sweetymhaiske Sorry, there's a conflict :(

**Review by woody-apple — APPROVED** [review]

**Comment by sweetymhaiske** [comment]
> @sweetymhaiske Sorry, there's a conflict :(

@woody-apple Resolved.

**Review by dhrishi — APPROVED** [review]

**Comment by lijinlei2011** [comment]
hello,
When i compile esp32 CHIP demo code(..\CHIP\GitHub\connectedhomeip-master\examples\lock-app\esp32). compiling error  was attached.The compiler complaints because it can't find the file "nlbyteorder.hpp".
the code is from 

https://github.com/project-chip/connectedhomeip/tree/master/examples/lighting-app/esp32


Best Regards,

Ray

**Comment by sweetymhaiske** [comment]
> hello,
> When i compile esp32 CHIP demo code(..\CHIP\GitHub\connectedhomeip-master\examples\lock-app\esp32). compiling error was attached.The compiler complaints because it can't find the file "nlbyteorder.hpp".
> the code is from
> 
> https://github.com/project-chip/connectedhomeip/tree/master/examples/lighting-app/esp32
> 
> Best Regards,
> 
> Ray

Hi Ray,

In recent commit on the master branch https://github.com/project-chip/connectedhomeip/commit/a08f82697b88490fb83ba1f008b7056c4ab7beb2#diff-932d9987aafff70772d3ee399cd68aa76235f6c4ab7b2fbe2bff690469dfaafeR149, they have added the fix. Can you pull the recent commits and try it once?
It works fine.

Regards,
Switi.

**Pull request merged**
