### PR TITLE
[cmake] Initial cut at cmake build system.

### PR DESCRIPTION
**Pull request by turon**
#### Problem
CMake / ninja as an alternate build system provides the following benefits:
- faster build times
- simpler developer flow
- better integration with some IDEs
- better alignment with some platform environments such as Zephyr

#### Summary of Changes
This PR adds cmake support for standalone, linux, and nrf52840 platforms.
All chip libraries and unit tests are building for the above three platforms.

Usage details are provided in docs/BUILDING_CMAKE.md.
This initial Draft PR is posted for comment and review. 

Known issues to be solved before merge:
- [X] Add CircleCI support for cmake validation
- [X] Recast unit test build files to follow test lib + driver model
- [X] Capture performance difference and repair `BUILD_EXTERNALS_WITH_CMAKE` option.
- [X] Updates to follow new `git submodule` flow rather than `repos.conf`.
- [X] Verify `coverage` target output and make it to depend on `check`
- [x] Generalize DEBUG as option (-g flags)
- [ ] Generalize CRYPTO selection as option to override platform default (openssl vs. mbedtls) 
- [ ] Generalize NETWORK selection as option to override platform default (sockets vs. lwip) 
- [ ] Generalize cmake options to support minimal feature list in comments below 
- [x] Demonstrate example app-as-top-level integration with CHIP as a pure third_party library
- [ ] Improve auto-generation of include paths from PUBLIC lib dependencies
- [ ] Improve flexibility of app-level configuration and platform overrides
- [ ] Isolate PR to cmake build system only -- pull out any source updates to separate PRs
- [ ] Verify build framework in place to support QEMU builds
- [ ] Verify Nordic embedded firmware generated is operationally correct

Known issues for follow-up PRs include:
- ESP and EFR platform support

Summary instructions to evaluate follow:

```
# Currently use existing bootstrap script to pull in repos.conf
make -f Makefile-bootstrap repos

mkdir out
cd out
mkdir standalone
cd standalone
cmake -GNinja ../..
ninja
ninja test

# Linux build assumes Linux host
cd ..
mkdir linux
cd linux
cmake -GNinja ../.. -DCHIP_PLATFORM=linux
ninja
ninja test

# Nordic build assumes environment setup
cd ..
mkdir nrf
cd nrf
cmake -GNinja ../.. -DCHIP_PLATFORM=nrf52840
ninja
```

Change list details:
- Extended to build main libs.
- Update headers. Add crypto and setup_payload.
- Add lwip, nlassert, and nlio to build.
- Add nlfaultinjection.
- Rebase and update build/config to config/.
- Add system/tests.
- system tests build
- Enable 'ninja test' support -- move platform config to top-level.
- Update cmake license headers.
- Update gitignore.
- Add inet tests.
- Add ble tests.
- Add crypto tests.
- Add core, support, and crypto tests.
- Add make check of nllibs to 'ninja test'
- Add setup payload tests.
- Extend platform cmake.
- Speed up initial run of nllib tests.
- Rebase and correct crypto tests.
- Add coverage target
- Fix coverage and pretty module options.
- Add initial doxygen option. Use BUILD_ namespace for options.
- Add initial documentation.
- Set chip-config via cmake rather than BuildConfig.h
- Add option to directly build nlfriends with cmake.
- Addition of arm toolchain and cross-compile support.
- Support Nordic nRF52840 platform
- Support linux-embedded build.
- Auto-generate CHIPVersion.h
- Add shell lib and tests
- Add transport lib
- Add platform nrf52840
- Add zcl data model lib.
- Centralize C++11 and C99 defs.
- Use pkgconfig for openssl.
- Add shell example app.
- Fix standalone to work on both linux and macos
- Add platform tests.
- Add nrf lock-app.
- Generalize start/end group linker flags.
- Fixes for NoThread support.

### CODE REVIEW

**Review by e-rk — COMMENTED** [review]
Fantastic addition. I hope it becomes the build system of choice.

So far I have one suggestion.

**Review by andy31415 — APPROVED** [review]

**Review by gerickson — CHANGES_REQUESTED** [review]

**Review by gerickson — CHANGES_REQUESTED** [review]
At a high-level, the big issues highlighted in depth in the files are:

1. Re-creating nl* builds.
2. Missing comments, file headers, and file description blocks.
3. Regression of unit tests builds to be composed of a test library + test driver (though SystemLayer gets this right).
4. Use of `test` rather than `check` for running tests. Maybe support both?
5. User/builder configuration of package options (debug/no debug, OpenSSL/mbedTLS, etc.). That list today is, at minimum:

* --enable-stdio-logging-timestamps
* --enable-debug
* --disable-profile
* --enable-coverage
* --enable-coverage-reports
* --enable-optimization
* --enable-warnings-as-errors
* --enable-tests
* --disable-tools
* --disable-docs
* --disable-ipv4
* --disable-adns
* --with-logging-style=STYLE
* --with-happy=HAPPY
* --with-network-layer=LAYER
* --with-device-layer=LAYER
* --with-target-network=NETWORK
* --with-inet-endpoint=ENDPOINT
* --with-chip-system-project-includes=FILE|DIR
* --with-chip-ble-project-includes=FILE|DIR
* --with-chip-inet-project-includes=FILE|DIR
* --with-chip-project-includes=FILE|DIR
* --with-chip-device-project-includes=FILE|DIR
* --with-crypto=CRYPTO
* --with-openssl=DIR
* --with-openssl-includes=DIR
* --with-openssl-libs=DIR
* --with-mbedtls=DIR
* --with-mbedtls-includes=DIR
* --with-mbedtls-libs=DIR
* --with-lwip=DIR
* --with-lwip-includes=DIR
* --with-lwip-libs=DIR
* --with-lwip-target=TARGET
* --with-nlio=DIR
* --with-nlio-includes=DIR
* --with-nlio-libs=DIR
* --with-nlassert=DIR
* --with-nlassert-includes=DIR
* --with-nlassert-libs=DIR
* --with-nlfaultinjection=DIR
* --with-nlfaultinjection-includes=DIR
* --with-nlfaultinjection-libs=DIR
* --with-nlunit_test=DIR
* --with-nlunit_test-includes=DIR
* --with-nlunit_test-libs=DIR

**Review by mspang — COMMENTED** [review]
> At a high-level, the big issues highlighted in depth in the files are:
> 
> 1. Re-creating nl* builds.
> 2. Missing comments, file headers, and file description blocks.
> 3. Regression of unit tests builds to be composed of a test library + test driver (though SystemLayer gets this right).

FWIW https://github.com/project-chip/connectedhomeip/pull/1205 does what you're asking, and it's stated simply and concisely:

```
chip_test_suite("tests") {
  common_sources = [
    "TestSystemErrorStr.cpp",
    "TestSystemLayer.h",
    "TestSystemObject.cpp",
    "TestSystemPacketBuffer.cpp",
    "TestSystemTimer.cpp",
    "TestTimeSource.cpp",
  ]

  public_deps = [
    "${chip_root}/src/inet",
    "${chip_root}/src/system",
    "${nlunit_test_root}:nlunit-test",
  ]

  tests = [
    "TestSystemErrorStr",
    "TestSystemObject",
    "TestSystemPacketBuffer",
    "TestSystemTimer",
    "TestTimeSource",
  ]
}
```

That's the entire build file (other than a couple imports).

I noticed this PR uses only private dependencies and private configurations (esp include dirs) which forces duplication of these options in every build file. We should avoid this.

> 4. Use of `test` rather than `check` for running tests. Maybe support both?
> 5. User/builder configuration of package options (debug/no debug, OpenSSL/mbedTLS, etc.). That list today is, at minimum:

https://github.com/project-chip/connectedhomeip/pull/1205 supports many of these as well (not all).

> 
> * --enable-stdio-logging-timestamps
> * --enable-debug
> * --disable-profile
> * --enable-coverage
> * --enable-coverage-reports
> * --enable-optimization
> * --enable-warnings-as-errors
> * --enable-tests
> * --disable-tools
> * --disable-docs
> * --disable-ipv4
> * --disable-adns
> * --with-logging-style=STYLE
> * --with-happy=HAPPY
> * --with-network-layer=LAYER
> * --with-device-layer=LAYER
> * --with-target-network=NETWORK
> * --with-inet-endpoint=ENDPOINT
> * --with-chip-system-project-includes=FILE|DIR
> * --with-chip-ble-project-includes=FILE|DIR
> * --with-chip-inet-project-includes=FILE|DIR
> * --with-chip-project-includes=FILE|DIR
> * --with-chip-device-project-includes=FILE|DIR
> * --with-crypto=CRYPTO
> * --with-openssl=DIR
> * --with-openssl-includes=DIR
> * --with-openssl-libs=DIR
> * --with-mbedtls=DIR
> * --with-mbedtls-includes=DIR
> * --with-mbedtls-libs=DIR
> * --with-lwip=DIR
> * --with-lwip-includes=DIR
> * --with-lwip-libs=DIR
> * --with-lwip-target=TARGET
> * --with-nlio=DIR
> * --with-nlio-includes=DIR
> * --with-nlio-libs=DIR
> * --with-nlassert=DIR
> * --with-nlassert-includes=DIR
> * --with-nlassert-libs=DIR
> * --with-nlfaultinjection=DIR
> * --with-nlfaultinjection-includes=DIR
> * --with-nlfaultinjection-libs=DIR
> * --with-nlunit_test=DIR
> * --with-nlunit_test-includes=DIR
> * --with-nlunit_test-libs=DIR

**Comment by woody-apple** [comment]
@turon can we rebase this?

**Comment by turon** [comment]
> @turon can we rebase this?

I had rebased and force pushed, but the updates don't seem to appear here yet.  Investigating.

**Comment by mspang** [comment]
Probably need to create a new PR entirely.

**Comment by turon** [comment]
Closing as this PR needs to be recreated due to move from private to public repos.

**Pull request closed without merging**
