### PR TITLE
Make bloat check work with github actions

### PR DESCRIPTION
**Pull request by andy31415**
#### Problem
We moved from CircleCI to github (which supports IPv6). Need to update bloat check since APIs are probably different.

 #### Summary of Changes
Exploring changes needed to get bloat checks to work again

### CODE REVIEW

**Comment by andy31415** [comment]
Size increase report for "esp32-example-build"

  File | Section | File | VM
---- | ---- | ----- | ---- 


<details>
  <summary>Full report output</summary>

```
Bloat report for job 'esp32-example-build'

Files found only in the baseline:
    chip-wifi-echo.elf


```

</details>

**Comment by andy31415** [comment]
Size increase report for "esp32-example-build"

  File | Section | File | VM
---- | ---- | ----- | ---- 


<details>
  <summary>Full report output</summary>

```
Bloat report for job 'esp32-example-build'

Files found only in the baseline:
    chip-wifi-echo.elf


```

</details>

**Comment by andy31415** [comment]
Size increase report for "esp32-example-build"

  File | Section | File | VM
---- | ---- | ----- | ---- 


<details>
  <summary>Full report output</summary>

```
Bloat report for job 'esp32-example-build'

Files found only in the baseline:
    chip-wifi-echo.elf


```

</details>

**Review by BroderickCarlin — APPROVED** [review]

**Comment by andy31415** [comment]
Marked this for review: you can see my strugles with it, it still does not fully work because pull requests are very protected by github (we can generate reports, however we cannot post them in comments).

My current approach for followups would be:
   - save bloat reports as 'artifacts' as part of the PR
   - have a separate scheduled process that grabs the artifacts and posts them as PR comments
   - have a scheduled process to cleanup the artifacts from master, so we do not run over the 2GB limit

What this PR currently does and is useful:
   - unique naming for artifacts using commit SHA (so that we can find the artifacts to compare against for bloat)
   - a working implementation of artifact fetching
   - setup bloat scripts for all examples

**Comment by andy31415** [comment]
Another idea would be for PRs to upload their binaries as usual and have the bloat check run in the scheduled process (we delete the outputs when bloats are generated). This would have the benefit of easily figuring out if a bloat report already ran or not.

**Comment by gerickson** [comment]
> Another idea would be for PRs to upload their binaries as usual and have the bloat check run in the scheduled process (we delete the outputs when bloats are generated). This would have the benefit of easily figuring out if a bloat report already ran or not.

I think @jwhui and the OpenThread team has some of these problems addressed. Are there solutions we can leverage there?

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
@jelderton @robszewczyk @hawk248 ?

**Comment by andy31415** [comment]
> > Another idea would be for PRs to upload their binaries as usual and have the bloat check run in the scheduled process (we delete the outputs when bloats are generated). This would have the benefit of easily figuring out if a bloat report already ran or not.
> 
> I think @jwhui and the OpenThread team has some of these problems addressed. Are there solutions we can leverage there?

I believe the solution there was a github app - I had the link when we previously discussed this. 
@jwhui - did you have any issues with fork repo permissions during the openthread bloat checker setup?

**Comment by andy31415** [comment]
https://github.com/apps/size-report/ was mentioned in https://github.com/project-chip/connectedhomeip/issues/541

**Comment by andy31415** [comment]
> https://github.com/apps/size-report/ was mentioned in #541

Docs are a bit light there. I believe I currently know what to do to make our bloaty-based reports work, however I cannot estimate what it takes to get size-report to work. I would prefer if someone else more familiar tries for the size-report integration and then we can compare (or if one approach seems a time sync, we should just keep with whatever we get working first)

**Comment by andy31415** [comment]
@bukepo or @jwhui  - do you want to try the path of making size-report work now that we are not a private repo anymore?

**Comment by bukepo** [comment]
@andy31415 could you install the size-report app on this project, so that I can try bringing it up on this project?

**Comment by andy31415** [comment]
> @andy31415 could you install the size-report app on this project, so that I can try bringing it up on this project?

I don't think I have sufficient rights. @woody-apple: can we install the size-report app?

**Comment by andy31415** [comment]
Separately, for this PR in particular: @saurabhst @jelderton @robszewczyk ?

**Comment by woody-apple** [comment]
> > @andy31415 could you install the size-report app on this project, so that I can try bringing it up on this project?
> 
> I don't think I have sufficient rights. @woody-apple: can we install the size-report app?

Done!

**Review by jelderton — APPROVED** [review]

**Comment by woody-apple** [comment]
@andy31415 can you sign the CLA? we can merge then :)

**Comment by andy31415** [comment]
This will apparently require some iterations to fix - still unclear to me why builds fail since this was supposed to be a python only change.

**Pull request merged**
