### PR TITLE
Update Door Lock Cluster definitions

### PR DESCRIPTION
**Pull request by Morozov-5F**
#### Problem
Update Door Lock Cluster definitions.

#### Change overview
* Moved Door Lock Cluster definitions to the separate XML file and updated them according to the spec. I tried to be as close to the spec as I could hence the command renames.
* Tweaked the current door lock cluster implementation so it actually builds and runs. There were no functional changes to the Door Lock Plugin yet -- they should be addressed later.
* Fixed ZAP files that were referencing Door Lock Cluster.
* Small generator fixes because it was confused by some of the Door Lock Cluster definitions (for example, it did not expect Nullable in the command response arguments).

**NOTE**: I did not include auto-generated files on purpose because they are constantly changing in the upstream. I would prefer to upload them once the main code review is complete but I can upload then whenever they needed.

#### Testing
* Manual testing of the All-Clusters-App with Chip-Tool (both on macOS 12.0.1 and Ubuntu 21.04 on RPI 4 8GB RAM). I've tried to lock/unlock the door, set/get PIN Code and user. 
* Ran tests for Mac (basically ran Darwin CI Workflow locally)
* Ran through CI in my fork in a separate branch: [Actions Report](https://github.com/Morozov-5F/connectedhomeip/actions?query=branch%3Afeature%2Fupdate-door-lock-cluster-definitions-test-build).

### CODE REVIEW

**Comment by Morozov-5F** [comment]
I am not sure whether I need to sign the CLA because I am already a member of Matter Work Group in CSA. I wonder if I need to request some additional access to contribute properly, can anyone please clarify?

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
Fast tracking given this has been in review for a while, and has had enough time for comment.

**Comment by woody-apple** [comment]
Fast tracking this given this has been in review for > 3 days

**Pull request merged**
