### PR TITLE
Consolidate error types

### LINKED ISSUE #7688: Unify chip errors (rather than CHIP_ERROR, INET_ERROR, BLE_ERROR, ASN1_ERROR, System::Error etc)
#### Problem

CHIP currently has `CHIP_ERROR`, `INET_ERROR`, `BLE_ERROR`, `ASN1_ERROR`, `System::Error`. Since they're all integers underneath, there is no type checking, and existing code routinely treats them as interchangeable.

Each type also has a `…_NO_ERROR` code which is independently configurable, but existing code assumes they are equal. It seems likely that there is also existing code that assumes the C/C++ convention that the no-error value is 0, but there is no practical way to look for this.

#### Proposed Solution

- Unify error types into one, `CHIP_ERROR`.
- _Retain_ the existing numeric ranges (i.e. `…_CONFIG_ERROR_MIN`) and constant names within the unified type.
- Consolidate exactly redundant codes (e.g. `CHIP_SYSTEM_ERROR_NO_MEMORY`, `BLE_ERROR_NO_MEMORY`, `INET_ERROR_NO_MEMORY` → `CHIP_ERROR_NO_MEMORY`). _Retain_ merely similar codes unless/until a domain expert decides they are redundant.
- Remove configurability of `CHIP_NO_ERROR` — define it as 0.

As a followup, look for unnecessary error code remapping or erasure, to reduce code size.

### PR DESCRIPTION
**Pull request by kpschoedel**
#### Problem

CHIP currently has `CHIP_ERROR`, `INET_ERROR`, `BLE_ERROR`,
`ASN1_ERROR`, `System::Error`. Since they're all integers underneath,
there is no type checking, and existing code routinely treats them
as interchangeable. There is also existing code that uses `int` and
`int32_t`.  Each also has a `…_NO_ERROR` code which is independently
configurable, but existing code assumes they are equal, and there is
exising code that assumes the C convention that the value is 0.

#### Change overview

Fixes #7688 Unify chip errors

This change is largely a mechanical replacement of type and some error
code names, with a few cleanups of weak typing.

Consolidated error types to one, `CHIP_ERROR`.

Removed configurability of `CHIP_NO_ERROR`; it must be 0.

Added `CHIP_ERROR_FORMAT` to replace hardcoded `PRI…32` in `printf()`
format strings.

Added `CHIP_ERROR_SENTINEL` to replace the use of `CHIP_ERROR_MAX` as a
sentinel.

Renamed or consolidated the following errors, which have the same
meaning. Merely similar codes are left alone. This change contains
compatibility defintitions to avoid breaking PRs in flight, which
will be removed in a followup.

| before                                 | after                               |
|:---------------------------------------|:------------------------------------|
| ASN1_ERROR                             | CHIP_ERROR                          |
| ASN1_NO_ERROR                          | CHIP_NO_ERROR                       |
| BLE_ERROR                              | CHIP_ERROR                          |
| BLE_NO_ERROR                           | CHIP_NO_ERROR                       |
| BLE_ERROR_BAD_ARGS                     | CHIP_ERROR_INVALID_ARGUMENT         |
| BLE_ERROR_INCORRECT_STATE              | CHIP_ERROR_INCORRECT_STATE          |
| BLE_ERROR_MESSAGE_INCOMPLETE           | CHIP_ERROR_MESSAGE_INCOMPLETE       |
| BLE_ERROR_NOT_IMPLEMENTED              | CHIP_ERROR_NOT_IMPLEMENTED          |
| BLE_ERROR_NO_ENDPOINTS                 | CHIP_ERROR_ENDPOINT_POOL_FULL       |
| BLE_ERROR_NO_MEMORY                    | CHIP_ERROR_NO_MEMORY                |
| BLE_ERROR_OUTBOUND_MESSAGE_TOO_BIG     | CHIP_ERROR_OUTBOUND_MESSAGE_TOO_BIG |
| BLE_ERROR_RECEIVED_MESSAGE_TOO_BIG     | CHIP_ERROR_INBOUND_MESSAGE_TOO_BIG  |
| CHIP_SYSTEM_NO_ERROR                   | CHIP_NO_ERROR                       |
| CHIP_SYSTEM_ERROR_ACCESS_DENIED        | CHIP_ERROR_ACCESS_DENIED            |
| CHIP_SYSTEM_ERROR_BAD_ARGS             | CHIP_ERROR_INVALID_ARGUMENT         |
| CHIP_SYSTEM_ERROR_NOT_SUPPORTED        | CHIP_ERROR_UNSUPPORTED_CHIP_FEATURE |
| CHIP_SYSTEM_ERROR_NO_MEMORY            | CHIP_ERROR_NO_MEMORY                |
| CHIP_SYSTEM_ERROR_REAL_TIME_NOT_SYNCED | CHIP_ERROR_REAL_TIME_NOT_SYNCED     |
| CHIP_SYSTEM_ERROR_UNEXPECTED_EVENT     | CHIP_ERROR_UNEXPECTED_EVENT         |
| CHIP_SYSTEM_ERROR_UNEXPECTED_STATE     | CHIP_ERROR_INCORRECT_STATE          |
| INET_ERROR                             | CHIP_ERROR                          |
| INET_NO_ERROR                          | CHIP_NO_ERROR                       |
| INET_ERROR_BAD_ARGS                    | CHIP_ERROR_INVALID_ARGUMENT         |
| INET_ERROR_INBOUND_MESSAGE_TOO_BIG     | CHIP_ERROR_INBOUND_MESSAGE_TOO_BIG  |
| INET_ERROR_INCORRECT_STATE             | CHIP_ERROR_INCORRECT_STATE          |
| INET_ERROR_MESSAGE_TOO_LONG            | CHIP_ERROR_MESSAGE_TOO_LONG         |
| INET_ERROR_NO_CONNECTION_HANDLER       | CHIP_ERROR_NO_CONNECTION_HANDLER    |
| INET_ERROR_NO_ENDPOINTS                | CHIP_ERROR_ENDPOINT_POOL_FULL       |
| INET_ERROR_NOT_IMPLEMENTED             | CHIP_ERROR_NOT_IMPLEMENTED          |
| INET_ERROR_NOT_SUPPORTED               | CHIP_ERROR_UNSUPPORTED_CHIP_FEATURE |
| INET_ERROR_NO_MEMORY                   | CHIP_ERROR_NO_MEMORY                |
| INET_ERROR_CONNECTION_ABORTED          | CHIP_ERROR_CONNECTION_ABORTED       |

#### Testing

Modified some unit tests to account for consolidated error codes.

Built locally with `CHIP_ERROR` hardcoded to `int32_t`, `uint32_t`,
`int16_t`, and `uint16_t` to shake out mistaken type assumptions.

### CODE REVIEW

**Comment by kpschoedel** [comment]
Intended followups:
- Remove compatibility definitions
- Use smaller constants that fit in instruction immediate fields to save flash on small platforms. Subject to measurements, this _might_ take the form of a compound code (bit mask or even class) as suggested in #7722.

Possible additional followup:
- Remove error erasures (e.g. `VerifyOrReturnError(result == CHIP_NO_ERROR, CHIP_ERROR_INTERNAL)`) to save flash.

**Comment by kpschoedel** [comment]
The various `Error.h` files have a comment at the top,

     *  NOTE WELL: On some platforms, this header is included by C-language programs.

Is that still true, or just a leftover from inherited code?

**Comment by bzbarsky-apple** [comment]
@kpschoedel The ZAP failure seems to be because this PR hand-edited generated files without modifying the generation templates accordingly...  Should probably change the templates (and then regenerate the generated bits instead of hand-editing).

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
@saurabhst @msandstedt @Damian-Nordic @jepenven-silabs @mspang ?

**Review by saurabhst — APPROVED** [review]

**Comment by woody-apple** [comment]
@mspang @Damian-Nordic @LuDuda @jmartinez-silabs ?

**Review by jmartinez-silabs — APPROVED** [review]

**Review by mspang — APPROVED** [review]

**Pull request merged**
