### PR TITLE
Enable Descriptor Cluster on example apps which do not have this cluster enabled

### LINKED ISSUE #6952: Add Descriptor Cluster implementation under the Endpoint 0 of Bridge App example
#### Problem
no Descriptor cluster has been implemented under Bridge app:
[https://github.com/project-chip/connectedhomeip/tree/master/examples/bridge-app](url)
As spec defined, Descriptor cluster should be supported by each node, Bridge device should implement this cluster, then the bridged Partslist can be reflected here. 
 

 #### Proposed Solution
Add the this new cluster by update the zap files.

### PR DESCRIPTION
**Pull request by yufengwangca**
#### Problem
This issue was reported from Schneider in pre-development of a zigbee-CHIP bridge. The Descriptor Cluster is not enabled on the example bridge app.

Per-spec, this cluster should be enabled on all type of devices. It describes an endpoint instance on the node, independently from other endpoints, but also allows composition of endpoints to conform to complex device type patterns.

* Fixes #6952 Add Descriptor Cluster implementation under the Endpoint 0 of Bridge App example.

#### Change overview
Enable Descriptor Cluster on Bridge App example apps

#### Testing
How was this tested? (at least one bullet point required)
1. Launch ZAP configuration tools: ./scripts/tools/zap/configure.sh.
2. Goto Menu and open Bridge App example's configuration files.
3. Confirm Descriptor Cluster(0x001D) is enabled under Generic.
4. Run ./scripts/tools/zap_regen_all.py to generates codes for all examples and confirm no errors.
5. Run ./gn_build.sh and confirm build succeed.

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]

**Comment by tima-q** [comment]
> Size increase report for "gn_qpg6100-example-build" from [7dbc566](https://github.com/project-chip/connectedhomeip/commit/7dbc566208af0c16bfa83354b4d0ce4f06bb733a)
> 
> File	Section	File	VM
> chip-qpg6100-lighting-example.out	.text	2304	2304
> chip-qpg6100-lighting-example.out	.bss	0	1016
> chip-qpg6100-lighting-example.out	.heap	0	-1016
> Full report output

How can this cluster alone add 1k of RAM (and 2kB of flash) ? Are there other parts activated by this now ?

**Comment by yufengwangca** [comment]
> > Size increase report for "gn_qpg6100-example-build" from [7dbc566](https://github.com/project-chip/connectedhomeip/commit/7dbc566208af0c16bfa83354b4d0ce4f06bb733a)
> > File	Section	File	VM
> > chip-qpg6100-lighting-example.out	.text	2304	2304
> > chip-qpg6100-lighting-example.out	.bss	0	1016
> > chip-qpg6100-lighting-example.out	.heap	0	-1016
> > Full report output
> 
> How can this cluster alone add 1k of RAM (and 2kB of flash) ? Are there other parts activated by this now ?

I also noticed this report this morning, I found there is same amount  of RAM decrease in heap, so the total RAM is not added. Text increase is likely we activate some components, lets me check.

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
> > > Size increase report for "gn_qpg6100-example-build" from [7dbc566](https://github.com/project-chip/connectedhomeip/commit/7dbc566208af0c16bfa83354b4d0ce4f06bb733a)
> > > File	Section	File	VM
> > > chip-qpg6100-lighting-example.out	.text	2304	2304
> > > chip-qpg6100-lighting-example.out	.bss	0	1016
> > > chip-qpg6100-lighting-example.out	.heap	0	-1016
> > > Full report output
> > 
> > 
> > How can this cluster alone add 1k of RAM (and 2kB of flash) ? Are there other parts activated by this now ?
> 
> I also noticed this report this morning, I found there is same amount of RAM decrease in heap, so the total RAM is not added. Text increase is likely we activate some components, lets me check.

I believe this addz 1K of BSS (basically 1K of static 0-initialized data). The + and - values you see is just "the amount of ram available on the chip is constant". Because we now use 1K of data, we have 1K less heap available.

**Comment by yufengwangca** [comment]
The increased RAM 1k and Text 2k are all from auto-generated code for Descriptor Cluster. Here is the break down from my ESP32 lock example:

Total sizes:
 DRAM .data size:   16176 bytes
 DRAM .bss  size:   45720 bytes   ---> +1024
Used static DRAM:   61896 bytes (  62684 available, 49.7% used)  --> +1024

Used static IRAM:  116655 bytes (  14417 available, 89.0% used)

      Flash code:  701251 bytes --> +940
    Flash rodata:  155800 bytes --> +1168
Total image size:~ 989882 bytes (.bin may be padded larger)

Symbols within the archive: libmain.a (Not all symbols may be reported)


Symbols from section: .dram0.bss

 attributeData(2606) ---> +1018

Section total: 15889  ---> +1018

Symbols from section: .dram0.data
Section total: 15

Symbols from section: .flash.rodata
_ZL17generatedDefaults(2539) ---> +1016 
 _ZL19generatedAttributes(1248)  ---> +60 
 _ZL17generatedClusters(240)  ---> +20 
 _Z41emberAfPluginDescriptorServerInitCallbackv.str1.1(71) --> +71
  CSWTCH$123(4) ---> +4


Section total: 10572  --> +1171

Symbols from section: .flash.text
 _Z15emberAfCopyListtP24EmberAfAttributeMetPhS1_i(1710) ---> +208
 _Z26emberAfClusterInitCallbackht(256) ---> +16 
 _Z29emberAfAttributeValueListSizettPKh(172) ---> +36
 _Z41emberAfPluginDescriptorServerInitCallbackv(142)  --> +142
 _Z20emberAfGetNthClusterhhb(100) --> +100
 _Z19emberAfClusterCounthb(91) --> +91
 _Z26writeClientServerAttributehb(84) --> +84
 _Z11emberAfInitPN4chip9Messaging15ExchangeManagerE(82)  ---> +2
 _Z19writePartsAttributeh(78) --> +78
 _Z20writeDeviceAttributeh(60) --> +60
 _Z14writeAttributehtPhi(46) --> +46
 _Z22emberAfContainsClusterht(25) --> +25
 _Z20writeClientAttributeh(18) --> +18
 _Z20writeServerAttributeh(18) --> +18
 _Z36emberAfDescriptorClusterInitCallbackh(5) --> +5

Section total: 28758  ---> +929

**Comment by yufengwangca** [comment]
@tima-q 

Currently, we can not specify the List type directly with size in attribute, we use ARRAY to specify list type, not sure what is the default size of ARRAY type.

<attribute side="server" code="0x0000" define="DEVICE_LIST" type="ARRAY" entryType="DeviceType" length="254" writable="false" optional="false">device list</attribute>

It seems this is the price we need to pay for Descriptor Cluster in which all items are of type ARRAY.

**Comment by bzbarsky-apple** [comment]
> How can this cluster alone add 1k of RAM (and 2kB of flash)

The short answer is that the current representation of lists in the attribute store is quite wasteful: we always allocate a list of length 254, even if we know it's length is much smaller (as we do statically at the moment for the descriptor cluster).  Not sure whether there's an issue tracking this.

And we always allocate space in RAM even for attributes that never change from their default value (see #5926).

**Comment by tima-q** [comment]
> @tima-q
> 
> Currently, we can not specify the List type directly with size in attribute, we use ARRAY to specify list type, not sure what is the default size of ARRAY type.
> 
> `<attribute side="server" code="0x0000" define="DEVICE_LIST" type="ARRAY" entryType="DeviceType" length="254" writable="false" optional="false">device list</attribute>`
> 
> It seems this is the price we need to pay for Descriptor Cluster in which all items are of type ARRAY.
> 
> @vivien-apple

@yufengwangca , thanks for looking into this a bit more.
Seems the ARRAY type should be dimensionable given the application - the `length="254"` is the spec maximum, but surely a device should not be forced to keep that memory as it will typically support a few.
A light would fi have a dimmable and color - as the DeviceType struct is 3 bytes (non-padded...), this could indeed explain the 1kB of RAM used up.

Can we make the 254 configurable in some manner ?

**Comment by tima-q** [comment]
> > How can this cluster alone add 1k of RAM (and 2kB of flash)
> 
> The short answer is that the current representation of lists in the attribute store is quite wasteful: we always allocate a list of length 254, even if we know it's length is much smaller (as we do statically at the moment for the descriptor cluster). Not sure whether there's an issue tracking this.
> 
> And we always allocate space in RAM even for attributes that never change from their default value (see #5926).

comments crossed - fully agree

**Comment by yufengwangca** [comment]
@tima-q @bzbarsky-apple 

Since this is the restriction of current ZAP, I think we have two options now.
1. Enable Descriptor Cluster with rest of example apps and migrate to the List type later when it is supported 
2. Enable Descriptor Cluster only on Bridge app to unblock Schneider

I personally prefer Option 2.

**Comment by bzbarsky-apple** [comment]
Is just enabling it for all apps running into space limits?  If so, let's do option 2.

**Comment by yufengwangca** [comment]
> Is just enabling it for all apps running into space limits? If so, let's do option 2.

No, actually we didn't run into space limit on any example apps. We just noticed the unreasonable RAM/Text increase for this cluster, now we know this is a known issue.

**Comment by yufengwangca** [comment]
Change to enable Descriptor Cluster only on Bridge app to unblock Schneider at this moment.

**Review by saurabhst — APPROVED** [review]

**Review by Kevin552270 — COMMENTED** [review]
@yufengwangca thanks for your help, then it works for me now!

**Pull request merged**
