### PR TITLE
[Tizen] Fix deadlock caused by mutex lock inversion

### LINKED ISSUE #25466: [BUG] [Tizen] Calling `ChipDnssdResolve` with the CHIP stack locked can cause deadlock
### Reproduction steps

During our (SmartThings) testing on the Tizen platform we have been encountering an issue where the DNS-SD implementation may become deadlocked when attempting to resolve multiple devices at the same time. I have determined that this occurs because we call `ChipDnssdResolve` with the CHIP stack locked. Consider the following scenario with threads [1] and [2]:

1. [2] Is in the middle of handling a request for service resolution.
2. [1] Some function calling `ChipDnssdResolve` acquires the CHIP stack lock some arbitrary amount of time beforehand.
3. [2] The service is resolved and this thread acquires the NSD lock ([ref](https://git.tizen.org/cgit/platform/core/api/nsd/tree/src/dns-sd/dns-sd.c?h=accepted/tizen_unified#n1179))
4. [1] As a result of calling `ChipDnssdResolve`, this thread reaches `dnssd_create_remote_service` and attempts to acquire the NSD lock. It waits.
5. [2] The callback `OnResolve` in the Matter SDK attempts to acquire the CHIP stack lock. It also waits ([here](https://github.com/project-chip/connectedhomeip/blob/020554c1da7cb0632c9df7dbaa218ef4d6ab590d/src/platform/Tizen/DnssdImpl.cpp#L381)).

As a result, the mutually dependent NSD and CHIP stack locks become deadlocked.

If it helps, I've also modified the `TestDnssd` unit test and some build files on a branch in a fork to demonstrate this issue (just a rough patch using your existing work with containers, @arkq). You can find it at https://github.com/gharveymn/connectedhomeip/tree/tizen-deadlock. You can run the test by starting up the docker container and executing `gen-cmd.sh` and then `ninja -C out/tizen-unit-check check-unit`.

CC: @msandstedt @arkq @hyunuktak @chulspro

### Bug prevalence

Whenever successfully resolving multiple devices concurrently

### GitHub hash of the SDK that was being used

39573776dd08f0357691bbe569dc7686669bef6c

### Platform

other

### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by arkq**
### Problem

Tizen mDNS API uses callbacks for notifying caller about particular events, like resolving service. Unfortunately, Tizen API internally uses global recursive mutex for every API call, which is not unlocked before calling callbacks...

The problem arises when the caller uses its own mutex which needs to be locked inside a callback function passed to mDNS API. We might have a case when:

- in thread 1, we are running callback function, which holds mDNS API internal lock, and in that callback we need to lock our lock
- in thread 2, mDNS API is called under callers lock, which internally tries to lock its internal lock

### Changes

As a workaround, mDNS callback function will not lock matter stack mutex, but instead it will only gather all data and schedule further data processing to a glib idle source callback. Fixes #25466

### Testing

Tested using test case provided in https://github.com/project-chip/connectedhomeip/issues/25466

### CODE REVIEW

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by msandstedt** [comment]
Can't we just acquire the lock at the top of each iteration of https://github.com/project-chip/connectedhomeip/blob/master/src/platform/Tizen/MainLoop.h?  This would ensure that locks are always acquired in the same order in all threads.

This would also ensure that any calls from the Tizen's `MainLoop.h` into the larger body of sdk code are always thread safe.

**Comment by arkq** [comment]
> This would ensure that locks are always acquired in the same order in all threads.

I don't see how that would happen, unless we will somehow add matter locking into dns-sd Tizen library... The problem here is that Tizen library calls callback function (`OnResolve()` in our case) with DNSSD internal mutex locked. And there is no way to lock matter lock before that unless we will rewrite `g_main_loop_run()` function, so the matter stack lock will be acquired before calling the `g_main_dispatch()`. The true problem here is not with matter SDK code, but with Tizen DNS-SD library. True fix, should be in the library, so the callback is not called with mutex locked.... I guess that someone didn't know how to solve this problem correctly, so instead of proper internal locking, we've got recursive mutex... which in most cases works, but from time to time someone will have to face locking inversion...

**Comment by msandstedt** [comment]
> > This would ensure that locks are always acquired in the same order in all threads.
> 
> I don't see how that would happen, unless we will somehow add matter locking into dns-sd Tizen library... The problem here is that Tizen library calls callback function (`OnResolve()` in our case) with DNSSD internal mutex locked. And there is no way to lock matter lock before that unless we will rewrite `g_main_loop_run()` function, so the matter stack lock will be acquired before calling the `g_main_dispatch()`. Of course, we could write custom g_main_loop_run in Tizen platform, but IMHO that's an overkill. The true problem here is not with matter SDK code, but with Tizen DNS-SD library. True fix, should be in the library, so the callback is not called with mutex locked.... I guess that someone didn't know how to solve this problem correctly, so instead of proper internal locking, we've got recursive mutex... which in most cases works, but from time to time someone will have to face locking inversion...

Isn't the g_main_loop thread that's dispatching the callbacks started in https://github.com/project-chip/connectedhomeip/blob/master/src/platform/Tizen/MainLoop.h?  If so, can't we wrap the g_poll() function with one that matter stack mutex?  Better yet, can't we execute Tizen's main loop from the sdk's event loop / scheduler?  glib should be amenable to either or these approaches.

More generally, if the Tizen platform layer is starting its own event loop on a thread separate from the the sdk's main event loop + thread, it seems like this should have built-in thread safety for calling back into the sdk, as I think many of the tasks, timers and callbacks executing from `Tizen/MainLoop` are going to be doing just this.  And to do so safely, the matter stack mutex must be acquired.  Have we audited everything  that executes from `Tizen/MainLoop` to verify that all calls into the main sdk properly acquire the lock?  If `Tizen/MainLoop` just always did this on its own, we could be much more confident.

**Comment by arkq** [comment]
> More generally, if the Tizen platform layer is starting its own event loop on a thread separate from the the sdk's main event loop + thread, it seems like this should have built-in thread safety for calling back into the sdk

Yes, I can see your point. Some time ago I've been doing some refactoring of glib main thread in Linux platform. Tizen platform might need similar refactoring, because right now instead of running a single dedicated thread with main event loop, new thread is spawned every time async processing is needed. I know that even better would be to incorporate glib main event loop processing into matter event loop. I've started such refactoring in Linux, but I had to skip it because of other important tasks.

PS.
Did you "somehow" approved this PR? pullapprove removed "review - pending" tag (it's possible to merge it), but this PR's got only one approve.... However, I'd like to wait for @gharveymn confirmation

**Review by dh79pyun — APPROVED** [review]
Looks good.

Before refactorying glib main thread. We can apply to resolve the critical deadlock issue.
And we will prepare Tizen SDK's modification to remove the basic cause of this issue.

**Comment by arkq** [comment]
@msandstedt What do you think about merging it as is? Currently, I'm working on Tizen glib thread refactoring, but it will take some time. Firstly I will unify all glib threads into one thread, and later I'll try to add proper locking when calling back to matter stack. However, as I think of it right now, adding matter stack lock directly into the glib main event loop will defeat the purpose of separate thread... because all actions will be sequenced with matter thread. Anyway, I'll try to think of something...

PS. when done with Tizen platform, Linux also will have to be "fixed", because it also runs separate thread for glib main event loop.

**Comment by msandstedt** [comment]
> @msandstedt What do you think about merging it as is? Currently, I'm working on Tizen glib thread refactoring, but it will take some time. Firstly I will unify all glib threads into one thread, and later I'll try to add proper locking when calling back to matter stack. However, as I think of it right now, adding matter stack lock directly into the glib main event loop will defeat the purpose of separate thread... because all actions will be sequenced with matter thread. Anyway, I'll try to think of something...
> 
> PS. when done with Tizen platform, Linux also will have to be "fixed", because it also runs separate thread for glib main event loop.

That sounds fine.  The logic looks correct, and I understand the challenge with attempting a larger refactor.

**Review by msandstedt — APPROVED** [review]

**Pull request merged**
