### PR TITLE
Prepare to have bloat check run scheduled (allow command line run for now)

### PR DESCRIPTION
**Pull request by andy31415**
#### Problem
CI triggered by pull reports have no rights to comment on pull requests.

 #### Summary of Changes
Looking to have the ability to run bloat reports in an async manner, so that either bots or humans can run them

### CODE REVIEW

**Comment by andy31415** [comment]
Size increase report for "nrf-example-build"

  File | Section | File | VM
---- | ---- | ----- | ---- 


<details>
  <summary>Full report output</summary>

```
BLOAT REPORT

Files found only in the build output:
    report.csv

Comparing ./master_artifact/chip-nrf52840-lock-example.out and ./pull_artifact/chip-nrf52840-lock-example.out:

sections,vmsize,filesize


```

</details>

**Comment by andy31415** [comment]
Size increase report for "linux-example-build"

  File | Section | File | VM
---- | ---- | ----- | ---- 


<details>
  <summary>Full report output</summary>

```
BLOAT REPORT

Files found only in the build output:
    report.csv

Comparing ./master_artifact/chip-standalone-demo.out and ./pull_artifact/chip-standalone-demo.out:

sections,vmsize,filesize


```

</details>

**Comment by andy31415** [comment]
Size increase report for "esp32-example-build"

  File | Section | File | VM
---- | ---- | ----- | ---- 


<details>
  <summary>Full report output</summary>

```
BLOAT REPORT

Files found only in the build output:
    report.csv

Comparing ./master_artifact/chip-wifi-echo.elf and ./pull_artifact/chip-wifi-echo.elf:

sections,vmsize,filesize


```

</details>

**Comment by andy31415** [comment]
Size increase report for "nrf-example-build"

  File | Section | File | VM
---- | ---- | ----- | ---- 


<details>
  <summary>Full report output</summary>

```
BLOAT REPORT

Files found only in the build output:
    report.csv

Comparing ./master_artifact/chip-nrf52840-lock-example.out and ./pull_artifact/chip-nrf52840-lock-example.out:

sections,vmsize,filesize


```

</details>

**Comment by andy31415** [comment]
Size increase report for "linux-example-build"

  File | Section | File | VM
---- | ---- | ----- | ---- 


<details>
  <summary>Full report output</summary>

```
BLOAT REPORT

Files found only in the build output:
    report.csv

Comparing ./master_artifact/chip-standalone-demo.out and ./pull_artifact/chip-standalone-demo.out:

sections,vmsize,filesize


```

</details>

**Comment by andy31415** [comment]
Size increase report for "esp32-example-build"

  File | Section | File | VM
---- | ---- | ----- | ---- 


<details>
  <summary>Full report output</summary>

```
BLOAT REPORT

Files found only in the build output:
    report.csv

Comparing ./master_artifact/chip-wifi-echo.elf and ./pull_artifact/chip-wifi-echo.elf:

sections,vmsize,filesize


```

</details>

**Comment by andy31415** [comment]
I was able to run this bloat report PR manually and it seems to correctly report statuses. Marking ready for review.

**Comment by andy31415** [comment]
Size increase report for "nrf-example-build"

  File | Section | File | VM
---- | ---- | ----- | ---- 


<details>
  <summary>Full report output</summary>

```
BLOAT REPORT

Files found only in the build output:
    report.csv

Comparing ./master_artifact/chip-nrf52840-lock-example.out and ./pull_artifact/chip-nrf52840-lock-example.out:

sections,vmsize,filesize
.debug_info,0,602
.debug_str,0,168
.debug_loc,0,37
.debug_line,0,31
.debug_frame,0,16
.debug_aranges,0,8
.debug_ranges,0,8
[Unmapped],0,2


```

</details>

**Comment by andy31415** [comment]
Size increase report for "linux-example-build"

  File | Section | File | VM
---- | ---- | ----- | ---- 


<details>
  <summary>Full report output</summary>

```
BLOAT REPORT

Files found only in the build output:
    report.csv

Comparing ./master_artifact/chip-standalone-demo.out and ./pull_artifact/chip-standalone-demo.out:

sections,vmsize,filesize


```

</details>

**Comment by andy31415** [comment]
Size increase report for "esp32-example-build"

  File | Section | File | VM
---- | ---- | ----- | ---- 


<details>
  <summary>Full report output</summary>

```
BLOAT REPORT

Files found only in the build output:
    report.csv

Comparing ./master_artifact/chip-wifi-echo.elf and ./pull_artifact/chip-wifi-echo.elf:

sections,vmsize,filesize
.debug_info,0,474
.debug_str,0,168
.debug_line,0,35
.debug_abbrev,0,27
.debug_frame,0,24
.debug_aranges,0,8
.debug_ranges,0,8
[Unmapped],0,4


```

</details>

**Review by jelderton — APPROVED** [review]

**Review by BroderickCarlin — APPROVED** [review]

**Comment by andy31415** [comment]
Size increase report for "nrf-example-build"

  File | Section | File | VM
---- | ---- | ----- | ---- 


<details>
  <summary>Full report output</summary>

```
BLOAT REPORT

Files found only in the build output:
    report.csv

Comparing ./master_artifact/chip-nrf52840-lock-example.out and ./pull_artifact/chip-nrf52840-lock-example.out:

sections,vmsize,filesize
.debug_info,0,602
.debug_str,0,168
.debug_loc,0,37
.debug_line,0,31
.debug_frame,0,16
.debug_aranges,0,8
.debug_ranges,0,8
[Unmapped],0,2


```

</details>

**Comment by andy31415** [comment]
Size increase report for "linux-example-build"

  File | Section | File | VM
---- | ---- | ----- | ---- 


<details>
  <summary>Full report output</summary>

```
BLOAT REPORT

Files found only in the build output:
    report.csv

Comparing ./master_artifact/chip-standalone-demo.out and ./pull_artifact/chip-standalone-demo.out:

sections,vmsize,filesize


```

</details>

**Comment by andy31415** [comment]
Size increase report for "esp32-example-build"

  File | Section | File | VM
---- | ---- | ----- | ---- 


<details>
  <summary>Full report output</summary>

```
BLOAT REPORT

Files found only in the build output:
    report.csv

Comparing ./master_artifact/chip-wifi-echo.elf and ./pull_artifact/chip-wifi-echo.elf:

sections,vmsize,filesize
.debug_info,0,474
.debug_str,0,168
.debug_line,0,35
.debug_abbrev,0,27
.debug_frame,0,24
.debug_aranges,0,8
.debug_ranges,0,8
[Unmapped],0,4


```

</details>

**Review by woody-apple — APPROVED** [review]

**Pull request merged**
