### PR TITLE
[Mbed] Add OTA-requestor-app and DFU support

### PR DESCRIPTION
**Pull request by ATmobica**
#### Problem
Adding OTA Requestor application for Mbed platform

#### Change overview
Add OTA requestor app - simply commissioning with AnnounceOtaProvider event handling
Implement Mbed version of OTARequestor, OTADownloader, OTAImageProcessor (only stub)

#### Testing
Tested manually
Run OTA provider Linux app and commissioned using Python device controller.
Flashed requestor on Mbed supported board and commissioned using Python device controller.
Fired a ZCL command AnnounceOtaProvider to start and apply for data transfer

Required changes:
- [x] #13416
- [ ] #13629

### CODE REVIEW

**Comment by ATmobica** [comment]
@woody-apple @holbrookt @carol-apple

**Comment by ATmobica** [comment]
@woody-apple @holbrookt @carol-apple
And one more question:
If we can run mbed OTA Requestor example with the Linux version of the OTA provider should we implement the Mbed version of it? Is it required?

**Review by woody-apple — APPROVED** [review]
Fast tracking, platform maintainer, adding platform code.

**Comment by woody-apple** [comment]
@ATmobica awesome news, thank you!   @carol-apple @franck-apple

**Comment by bzbarsky-apple** [comment]
@ATmobica Need to fix style?  And is this supposed to still be draft?

**Comment by ATmobica** [comment]
> @ATmobica Need to fix style? And is this supposed to still be draft?

@bzbarsky-apple Sure, we restyle changes and the end of implementation. Yes, it's still a draft we wait to merge some necessary changes in Mbed-os implementation.  The DFU service for the Mbed platform is also in progress. I hope we will finish this week.

**Comment by andy31415** [comment]
@ATmobica - is this still in draft? It has been in this state for a while now, wondering if you are waiting for a review or still working on this.

**Comment by ATmobica** [comment]
> @ATmobica - is this still in draft? It has been in this state for a while now, wondering if you are waiting for a review or still working on this.

@andy31415 We still working on this but probably until the end of this week. Now, we have all the necessary changes in mbed-os but the generic OTA implementation constantly changed. We need to keep following these changes, apply them and test our solution, after that the PR will be ready to review.

**Comment by woody-apple** [comment]
Fast tracking, given > 3 days for review and platform changes.

**Review by woody-apple — APPROVED** [review]

**Pull request merged**
