### PR TITLE
Fixed the problem of unable to stop ble-scan from the second time on …

### PR DESCRIPTION
**Pull request by tianfeng-yang**
Fixed the problem of unable to stop Bluetooth scanning from the second time on Linux platform
Under Linux, `mIsStopping` scan status is not modified after `StopScan`, and `StopScan` cannot take effect from the second time on.

### CODE REVIEW

**Review by andy31415 — CHANGES_REQUESTED** [review]
Could you update the summary to describe the issue and solution? existing summary of `Fixed the problem of unable to stop Bluetooth scanning from the second time on Linux platform` does not actually explain what the problem was and what the approach of fixing is.

From what I can see, the fix is to reset isStopping back to false in the Stop method ... why is this correct and why is this correct to do before the delegate scan complete callback is called? Should the stop be a RAII that sets it to true at start and false at end instead? Why is it called `isStopping` instead of `stopScanExecuting` for example to be precise about its intended usage?

**Comment by andy31415** [comment]
> Could you update the summary to describe the issue and solution? existing summary of `Fixed the problem of unable to stop Bluetooth scanning from the second time on Linux platform` does not actually explain what the problem was and what the approach of fixing is.
> 
> From what I can see, the fix is to reset isStopping back to false in the Stop method ... why is this correct and why is this correct to do before the delegate scan complete callback is called? Should the stop be a RAII that sets it to true at start and false at end instead? Why is it called `isStopping` instead of `stopScanExecuting` for example to be precise about its intended usage?

The fix may be correct - since it seems once you say StopScan you can never reset mIsStopping to false again.

However I am unsure about intended design - maybe this was supposed to create a new scan for every new scan and never re-use a scanner (even though that is odd...). Maybe instead `Init` should ensure that previous resources are released and should also initialize mIsStopping to false.

**Comment by andy31415** [comment]
It looks like BleManagerImpl::InitiateScan will do Init and StartScan on mDeviceScanner.

To me this seems like Init should make sure that stopped status is cleared (and also ensure it cancels any current scan).

**Comment by tianfeng-yang** [comment]
> It looks like BleManagerImpl::InitiateScan will do Init and StartScan on mDeviceScanner.
> 
> To me this seems like Init should make sure that stopped status is cleared (and also ensure it cancels any current scan). Or more likely make `ShutDown` set mIsStopping to false rather than the existing change in Stop.

Yes, `mIsStopping` can indeed be cleared during `Init` or `Shutdown`, but from my point of view, the role of `mIsStopping` is more to prevent reentrancy while waiting for `PlatformMgrImpl().GLibMatterContextInvokeSync(MainLoopStopScan, this)`, so I think the value should be cleared immediately after the function ends.

**Comment by andy31415** [comment]
> > It looks like BleManagerImpl::InitiateScan will do Init and StartScan on mDeviceScanner.
> > To me this seems like Init should make sure that stopped status is cleared (and also ensure it cancels any current scan). Or more likely make `ShutDown` set mIsStopping to false rather than the existing change in Stop.
> 
> Yes, `mIsStopping` can indeed be cleared during `Init` or `Shutdown`, but from my point of view, the role of `mIsStopping` is more to prevent reentrancy while waiting for `PlatformMgrImpl().GLibMatterContextInvokeSync(MainLoopStopScan, this)`, so I think the value should be cleared immediately after the function ends.

This explanation should be as part of the comment when this is set to false. This also feels a bit like a code-smell for such coupling, however I have no immediate ideas on how to lay things out to not feel as messy.

**Comment by andy31415** [comment]
> > > It looks like BleManagerImpl::InitiateScan will do Init and StartScan on mDeviceScanner.
> > > To me this seems like Init should make sure that stopped status is cleared (and also ensure it cancels any current scan). Or more likely make `ShutDown` set mIsStopping to false rather than the existing change in Stop.
> > 
> > 
> > Yes, `mIsStopping` can indeed be cleared during `Init` or `Shutdown`, but from my point of view, the role of `mIsStopping` is more to prevent reentrancy while waiting for `PlatformMgrImpl().GLibMatterContextInvokeSync(MainLoopStopScan, this)`, so I think the value should be cleared immediately after the function ends.
> 
> This explanation should be as part of the comment when this is set to false. This also feels a bit like a code-smell for such coupling, however I have no immediate ideas on how to lay things out to not feel as messy.

Actually looking at the code, the MainLoopStopScan is called to isStopping false, so having this cleared in ShutDown does sound like it would work and prevent reentrancy problems. Name is still odd ("currently stopping vs fully stopped").

Maybe we should have a state enum variable instead with states like `Uninitialized, Initialized, Stopping, Stopped` or something like that.

**Pull request closed without merging**
