### PR TITLE
[WIP]Fix m1 build failed for Pigweed force using Rosetta

### PR DESCRIPTION
**Pull request by xylophone21**
#### Problem
* build failed on M1 https://github.com/project-chip/connectedhomeip/issues/16759

#### Change overview
* Pigweed  force to using Rosetta on M1

#### Testing
* mac build, not pass yet, just for discuss now

### CODE REVIEW

**Review by andy31415 — CHANGES_REQUESTED** [review]
I expect this to be fixed after https://pigweed.googlesource.com/pigweed/pigweed/+/9ad199a37b2111acbd888549a60aef80f1cbbe83

(at least according to Pigweed team).

Maybe we should roll to pigweed latest version?

**Review by andy31415 — APPROVED** [review]
Just noticed this included the pigweed rollup as well - seems like potentially the right fix. Wondering if `activate.sh` also needs updates.

**Comment by andy31415** [comment]
This may be fixed after #17247

**Comment by xylophone21** [comment]
great, so I think this PR are not needed anymore, I will close it, thanks

**Comment by xylophone21** [comment]
Yes,

**Comment by xylophone21** [comment]
close because https://github.com/project-chip/connectedhomeip/pull/17247 fixed it

**Pull request closed without merging**
