### PR TITLE
RPC: Refactor RPC examples for better code reuse, and add RPCs to EFR lock app

### PR DESCRIPTION
**Pull request by rgoliver**
#### Problem
All RPC examples currently implement there own Rpc.cpp file which creates the service, this is generally all copy pasted.

#### Change overview
- Move the Rpc.cpp files to examples/platfrom so they  can be shared between platform implementations.
- Add compiler definitions to indicate which RPC services should be enabled for each application.
- Add RPCs to the EFR32 lock app as an example for how this is done after the refactor.

#### Testing
Tested RPCs using the rpc-console on: esp32 all-clusters, nrf lighting, efr32 lighting, efr32 lock.

### CODE REVIEW

**Review by jmartinez-silabs — APPROVED** [review]

**Comment by andy31415** [comment]
@rgoliver -  I believe this requires a rebase/merge to fix both  CI conflict and checkout issues.

**Comment by rgoliver** [comment]
> @rgoliver - I believe this requires a rebase/merge to fix both CI conflict and checkout issues.

@andy31415 This is rebased and passing now.

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
fast track: domain owner change for RPC, has checkmarks and has been up for a while now.

**Pull request merged**
