### PR TITLE
Add HAP Crypto to src/crypto

### PR DESCRIPTION
**Pull request by bhaskar-apple**
#### Problem
No APIs to support symmetric key based payload encryption available in CHIP

 #### Summary of Changes
Adds new files from [HAP ADK](https://github.com/apple/HomeKitADK). These have been scrubbed to replace occurrences of `HAP` with `ADK`

```
src/crypto/CHIPBase+CompilerAbstraction.h
src/crypto/CHIPBase+Crypto.c
src/crypto/CHIPCrypto.h
src/crypto/CHIPOpenSSL.c
src/crypto/Makefile.am
src/crypto/tests/CHIPCryptoTest.c
src/crypto/tests/Makefile.am
```

fixes #147

### CODE REVIEW

**Review by hawk248 — APPROVED** [review]
nice

**Review by turon — CHANGES_REQUESTED** [review]
I'm confused by submission of crypto algorithms that the Security group does not plan to use.

**Review by woody-apple — APPROVED** [review]
Thanks @bhaskar-apple @balducci-apple Looks like a great start for our baseline

**Review by BroderickCarlin — APPROVED** [review]

**Review by gerickson — CHANGES_REQUESTED** [review]
How do we resolve the questions about the cryptographic primitives consensus questions here?

**Pull request merged**
