### PR TITLE
Adding YAML Test Scripts - Dec 14th

### PR DESCRIPTION
**Pull request by kvikrambhat**
**Summary**
1.Adding the following YAML test scripts.
-Test_TC_DD_1_5
-Test_TC_DD_1_6
-Test_TC_DD_1_7
-Test_TC_DD_1_8
-Test_TC_DD_1_9

**Testing**
- Executed all YAML test scripts, attached logs for reference
- [YAMLTestRunLogs.txt](https://github.com/project-chip/connectedhomeip/files/7710623/YAMLTestRunLogs.txt)

### CODE REVIEW

**Review by jmeg-sfy — APPROVED** [review]

**Comment by andy31415** [comment]
@kvikrambhat @vivien-apple @bzbarsky-apple - the Darwin failure seems "legitimate" in the sense that it looks like there are no quotes  set in the ".mm" file by the zap generation. Is this something we need zap template fixes?

**Comment by krypton36** [comment]
> @kvikrambhat @vivien-apple @bzbarsky-apple - the Darwin failure seems "legitimate" in the sense that it looks like there are no quotes set in the ".mm" file by the zap generation. Is this something we need zap template fixes?

Yes, this needs to be fixed in ZAP. I created a [PR](https://github.com/project-chip/connectedhomeip/pull/13002) that addresses this.

**Comment by kvikrambhat** [comment]
rebased.

**Comment by bzbarsky-apple** [comment]
@kvikrambhat Need to regenerate the darwin tests?

**Review by andy31415 — APPROVED** [review]

**Pull request merged**
