### PR TITLE
Fix incremental builds on Mac

### PR DESCRIPTION
**Pull request by mspang**
#### Problem

Mac incrementals are still broken even after #2996 due to wrong wheel file name.

 #### Summary of Changes

Use the pep425tags module for setuptools to ensure the right filename is used.

### CODE REVIEW

**Review by yunhanw-google — APPROVED** [review]
Thank you!

**Review by rwalker-apple — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
LGTM however the comment was saying `TODO: pigweed virtualenv don't have pep425tags,...`

Did we change the virtualenv so that the tags are included now?

**Comment by andy31415** [comment]
LGTM.com complains about 3 unused imports. Guessing we can clean those up as well.

**Comment by mspang** [comment]
> LGTM however the comment was saying `TODO: pigweed virtualenv don't have pep425tags,...`
> 
> Did we change the virtualenv so that the tags are included now?

No, this is just importing it from a different package.

**Review by BroderickCarlin — APPROVED** [review]

**Pull request merged**
