### PR TITLE
[shell] Change file names in lib/shell to CamelCase

### LINKED ISSUE #2533: [shell] Solve shell/shell.h file name collision in Zephyr
#### Problem
During work on #2426 I replaced all "#include <shell/...>" directives with "#include <lib/shell/...>" ones to workaround the file name collision between lib/shell/shell.h and Zephyr's shell/shell.h. This, however, introduces some inconsistency because the rest of CHIP code assumes `lib` is among include directories, so it doesn't have to be used in #include directives.

 #### Proposed Solution
Rename lib/shell/shell.h to CHIPShell.h. Also rename the other files in the directory to CamelCase as it seems to be most common naming convention in CHIP.

### PR DESCRIPTION
**Pull request by Damian-Nordic**
#### Problem
During work on #2426 I replaced all "#include <shell/...>" directives with "#include <lib/shell/...>" ones to workaround the file name collision between lib/shell/shell.h and Zephyr's shell/shell.h. This, however, introduces some inconsistency because the rest of CHIP code assumes `lib` is among include directories, so it doesn't have to be used in #include directives.

 #### Summary of Changes
Rename lib/shell/shell.h to CHIPShell.h. Also rename the other files in the directory to CamelCase as it seems to be most common naming convention in CHIP.

fixes #2533

### CODE REVIEW

**Comment by mspang** [comment]
IMO - This is a bit of a bandait, the right fix is to make all the paths
  "chip/lib/shell/$whatever.h"

which requires rearranging the source tree.

**Comment by rwalker-apple** [comment]
> IMO - This is a bit of a bandaid, the right fix is to make all the paths
> "chip/lib/shell/$whatever.h"
> 
> which requires rearranging the source tree.

yes, bandaid indeed.

perhaps we should quickly get "chip/" into the include paths (a la openssl) and fix up the install steps for builds accordingly instead

**Comment by rwalker-apple** [comment]
@Damian-Nordic I think, given mspang's thumbsup above, that you can close this PR.  That ok with you?  Thank you for filing the issue and following up.

I'll update the issue, ok?

**Comment by Damian-Nordic** [comment]
> @Damian-Nordic I think, given mspang's thumbsup above, that you can close this PR. That ok with you? Thank you for filing the issue and following up.
> 
> I'll update the issue, ok?

Sure, no problem.

**Pull request closed without merging**
