### PR TITLE
Fix Window app commissioning flow

### PR DESCRIPTION
**Pull request by jmartinez-silabs**
#### Problem
Commissioning flow is broken on window-app as the operational clusters have not been moved to endpoint 0 for this example common generated code.

#### Change overview
Modify window-app.zap to move all operational clusters (NetworkCommissioning, Basic, Diagnostics) to endpoint 0, Keep application cluster (WindowCovering) on endpoint 1

_First commit is the changes to the .zap file.
2nd is the regeneration of the files_

#### Testing
Manual testing, validated commissioning flow on python controller with NetworkCommissioning on endpoint 0  and validated WindowCovering cluster commmands are received on the EFR device using endpoint 1

### CODE REVIEW

**Comment by jmartinez-silabs** [comment]
Investigating this ZAP failure in the CI. The CI does a regen and removes commands that should not be removed. It happends locally also, but once committed the regen does the opposite, re-adds the commands.

**Review by bzbarsky-apple — APPROVED** [review]
Looks reasonable, though maybe removing instead of disabling the endpoint-0 bits from the other endpoint would have made more sense...

**Comment by bzbarsky-apple** [comment]
I wonder whether the zap failure is similar to the one that keeps biting tv-app.  @vivien-apple

**Comment by jmartinez-silabs** [comment]
> Looks reasonable, though maybe removing instead of disabling the endpoint-0 bits from the other endpoint would have made more sense...

@bzbarsky-apple I agree, Not sure how to effectively delete them in zap. In endpoint 1, I changed all of them from"Server" to not a value. Created endpoint 0 and set them to server. I thought the regen would delete them from endpoint 1 but it just disabled them. Is there another way to go?

**Comment by bzbarsky-apple** [comment]
> I thought the regen would delete them from endpoint 1 but it just disabled them. Is there another way to go?

I don't know.  I have yet to use the ZAP UI; I've just ended up hand-editing .zap files as needed...

**Comment by jmartinez-silabs** [comment]
@bzbarsky-apple I just validated with the zap team.
`We do store both entries like that intentionally, at least for the disabled commands/attributes configuration just in case. However,  I think we are planning a project to remove at least some of this duplcication due to the large size of the ZAP files.`

Also the generation issue adding/removing the commands are due to a helper issue with incomming commands. and that helper should be replace by a new one for command parsing

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
@jmartinez-silabs - merge conflicts

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
@jmartinez-silabs these look like real errors.

@saurabhst @msandstedt?

**Comment by jmartinez-silabs** [comment]
@woody-apple Right those are real errors that I fixed with #7619 . I will rebase this PR, should fix it.

**Review by msandstedt — APPROVED** [review]

**Review by jmeg-sfy — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
@jmartinez-silabs This was reverted because of a merge issue that caused it to break the build... Needs to be rebased on ToT, codegen rerun, and the build issue addressed.

**Comment by jmartinez-silabs** [comment]
@bzbarsky-apple ok thank you Boris. Will address this.

**Pull request merged**
