### PR TITLE
Fix some alerts founded the LGTM system

### PR DESCRIPTION
**Pull request by tdrozdovsky**
Signed-off-by: Taras Drozdovskyi <t.drozdovsky@samsung.com>

**Problem**

Fix LGTM alerts
**Change overview**

Some LGTM alerts are fixed.

### CODE REVIEW

**Comment by andy31415** [comment]
@tdrozdovsky - zap failures. Guessing some python files are generated from zap and you have to update the zap templates. Also make sure that the templates will not eventually use the given imports

**Comment by tdrozdovsky** [comment]
> 
> 
> @tdrozdovsky - zap failures. Guessing some python files are generated from zap and you have to update the zap templates. Also make sure that the templates will not eventually use the given imports

@andy31415 I excluded this file. Next time I carefully examine this question. Thank you!

**Review by bzbarsky-apple — APPROVED** [review]

**Review by msandstedt — APPROVED** [review]

**Review by Damian-Nordic — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
After ToT merging I got:

```
ImportError: Failed to import test module: test_generated_clusterobjects
Traceback (most recent call last):
  File "/usr/lib/python3.9/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/__w/connectedhomeip/connectedhomeip/src/controller/python/test/unit_tests/test_generated_clusterobjects.py", line 2, in <module>
    import chip.clusters as Clusters
  File "/__w/connectedhomeip/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/chip/clusters/__init__.py", line 25, in <module>
    from . import Attribute
  File "/__w/connectedhomeip/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/chip/clusters/Attribute.py", line 199, in <module>
    None, py_object, c_uint16, c_uint32, c_uint32, c_uint16, c_void_p, c_size_t)
NameError: name 'c_void_p' is not defined
```

**Comment by andy31415** [comment]
At this point I am not sure I trust this LGTM thing. For the '== None' vs 'is None' fine, but the various improvements in imports seems not very stable.

**Comment by andy31415** [comment]
In hindsight maybe a `/rebase` before merging such PRs would have helped with CI. guessing new usages of things appeared in time.

**Comment by tdrozdovsky** [comment]
@andy31415 

> After ToT merging I got:
> 
> ```
> ImportError: Failed to import test module: test_generated_clusterobjects
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/unittest/loader.py", line 436, in _find_test_path
>     module = self._get_module_from_name(name)
>   File "/usr/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
>     __import__(name)
>   File "/__w/connectedhomeip/connectedhomeip/src/controller/python/test/unit_tests/test_generated_clusterobjects.py", line 2, in <module>
>     import chip.clusters as Clusters
>   File "/__w/connectedhomeip/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/chip/clusters/__init__.py", line 25, in <module>
>     from . import Attribute
>   File "/__w/connectedhomeip/connectedhomeip/.environment/pigweed-venv/lib/python3.9/site-packages/chip/clusters/Attribute.py", line 199, in <module>
>     None, py_object, c_uint16, c_uint32, c_uint32, c_uint16, c_void_p, c_size_t)
> NameError: name 'c_void_p' is not defined
> ```

Looking at these lines, I see that there is the error. Tell me please, what you did I would like to reproduce to avoid further.
Of course this import is a smell code and in this case, I can suggest exclude this type of error as false-positive. 

Please give me the answer or what do think about it. It is very important for me. 
P.S. From the LGTM side, it is only recommendations, but if you look deeper from the security side, the incorrect transformation of pointers can lead to vulnerability.

**Pull request merged**
