### PR TITLE
Update cxx_rules

### PR DESCRIPTION
**Pull request by rwalker-apple**
* support skipping GCOV, VALGRIND, etc. with `make GCOV=`, etc.
* support seeing commands with `make _@=`

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]
I imagine we'll iterate on this a lot, but this looks like a great start to me. Approved.

**Review by robszewczyk — APPROVED** [review]
A feature I found helpful and useful in other build systems was to have both the brief and verbose progress in the build.  This change moves us in the direction, but not all the way there.  I'm happy to approve, but I'd like to understand the end point.

**Review by gerickson — APPROVED** [review]
Approved on the condition that we identify a line in the sand on when we transition to a "standing on the shoulders of giants" build system that rockets us ahead in terms of solving some basics that are being created whole cloth at the moment.

**Review by hawk248 — APPROVED** [review]
I am ok with override options for code coverage during lower level build. Ultimately, code coverage can be enforced outside build in a CI pipeline.

**Pull request merged**
