### PR TITLE
Revert "Use RAII for ExchangeContext contruction and destruction instead of Alloc/Free."

### PR DESCRIPTION
**Pull request by yunhanw-google**
Summary of Changes:
This issue is making Last exchange context of every PASE/CASE exchange is leaked in issue #6856
and also make cirque IM test under weather again because of this leak.

chip::Messaging::ExchangeManager::Shutdown()::<lambda(auto:2*)> [with auto:2 = chip::Messaging::ExchangeContext]: Assertion `false' failed.

Not sure how we guarantee the ec are deterministically released after this change.
since the app can call Shutdown at anytime, if any exchange is not deterministically released we should see the error.

Reverts project-chip/connectedhomeip#6808

### CODE REVIEW

**Review by yufengwangca — APPROVED** [review]

**Review by mrjerryjohns — APPROVED** [review]

**Comment by woody-apple** [comment]
@bzbarsky-apple ping as he's looking at leaks

**Review by jmartinez-silabs — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
@yunhanw-google I don't understand the description of the problem here...

>  chip-im-initiator: ../../../../../src/messaging/ExchangeMgr.cpp:104: CHIP_ERROR chip::Messaging::ExchangeManager::Shutdown(): Assertion `ec.GetReferenceCount() == 0' faile

This is what the assert would have been _before_ https://github.com/project-chip/connectedhomeip/pull/6685 as far as I can tell.  The assert after that PR would be on a different line and would just be `assert(false)`.  What am I missing?

**Comment by yufengwangca** [comment]
> @yunhanw-google I don't understand the description of the problem here...
> 
> > chip-im-initiator: ../../../../../src/messaging/ExchangeMgr.cpp:104: CHIP_ERROR chip::Messaging::ExchangeManager::Shutdown(): Assertion `ec.GetReferenceCount() == 0' faile
> 
> This is what the assert would have been _before_ #6808 as far as I can tell. The assert after that PR would be on a different line and would just be `assert(false)`. What am I missing?

@yunhanw-google 

Pasted the old log? the crash log you posted in chat is 

chip::Messaging::ExchangeManager::Shutdown()::<lambda(auto:2*)> [with auto:2 = chip::Messaging::ExchangeContext]: Assertion `false' failed.

**Comment by bzbarsky-apple** [comment]
OK, but if we revert #6808 does the assert actually go away, or is it replaced by the `ec.GetReferenceCount() == 0` assert?

**Comment by kghost** [comment]
@yunhanw-google can you confirm that reverting this PR can temporary bypass the Cirque tests ?

And I'll try to fix #6856 today. Hope we can fix the cirque test without reverting this one.

**Comment by yunhanw-google** [comment]
@kghost is trying to fix this issue, close this one

**Comment by kghost** [comment]
The problem will be tracked by #6915

**Comment by kghost** [comment]
The problem should be fixed by #6918

**Pull request closed without merging**
