### PR TITLE
Bump CI dockerfile version to 0.5.18

### PR DESCRIPTION
**Pull request by andy31415**
#### Problem
Docker image was updated, moving the CI builds (and vscode) to latest  version, which will  include new platforms (AmebaD in this case).
#### Change overview

Basically:

```sh
find .devcontainer .github -type f | xargs perl -p -i -e 's/0\.5\.15/0.5.18/'
```

(except I used the more comprehensive command to makse sure we do not have other paths somewhere else with this version)

```sh
rg '0\.5\.18' --hidden | cut -f1 -d: | uniq | grep -v \.git/ | xargs sd 0.5.15 0.5.18
```

#### Testing
CI will validate this.

### CODE REVIEW

**Review by bzbarsky-apple — APPROVED** [review]
This seems fine, but what is "rg" in the commit message?  Is that "ripgrep"?  And what is "sd"?

It might be better to use "git sed" for this sort of thing, at least in terms of things people can easily reproduce as needed....

**Comment by andy31415** [comment]
> It looks like the MBedOS changes do not let things compile anymore.
> 
> @ATmobica for #9432 ?

Saw that PR seems to include a line of `ENV PW_ENVIRONMENT_ROOT=/home/vscode/pigweed/env` which I missed during the review: that line seems wrong as vscode should not be a user in a general build. There should be no reason to change/hardcode the PW_ENVIRONMENT_ROOT, especially to a non-existent user home.

**Comment by andy31415** [comment]
I rolled back the mbedos moving to the latest docker image. I kept that one pinned to 0.5.15 for now.

**Review by LuDuda — APPROVED** [review]

**Comment by andy31415** [comment]
Updated to 0.5.18 since that fixes mbedOS as well.

**Review by kghost — APPROVED** [review]

**Pull request merged**
