### PR TITLE
ESP32: Fix temperature-measurement app

### LINKED ISSUE #7302: ESP32 temperature-measurement-app fails to build
I can get the all-clusters ESP32 example to build and run, however the temperature-measurement-app fails to build.
 
I have followed Instructions here: https://github.com/project-chip/connectedhomeip/blob/master/examples/temperature-measurement-app/esp32/README.md
 
ESP-IDF release/v4.2
CHIP commit b40ed7a710fca26c1df013c2132e6e073e566ff0
 
This built fine about two weeks ago. 

af-event.cpp:90: undefined reference to `emberAfPluginTemperatureMeasurementServerReadEventControl'

 ```
/home/wpeacock/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/main/libmain.a(af-event.cpp.obj):/home/wpeacock/chip/connectedhomeip/examples/temperature-measurement-app/esp32/build/../third_party/connectedhomeip/src/app/util/af-event.cpp:90: undefined reference to `emberAfPluginTemperatureMeasurementServerReadEventControl'
/home/wpeacock/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/main/libmain.a(af-event.cpp.obj):(.data.emAfEvents+0x4): undefined reference to `emberAfPluginTemperatureMeasurementServerReadEventHandler()'
collect2: error: ld returned 1 exit status
```

Regards
Wayne

### PR DESCRIPTION
**Pull request by dhrishi**
#### Problem
temperature-measurement-app for ESP32 cannot compile at ToT

This is due to the latest changes related to temeprature-measurement cluster #7026 

#### Change overview
The APIs emberAfPluginTemperatureMeasurementServerReadEventControl and emberAfPluginTemperatureMeasurementServerReadEventHandler are removed from the above PR and hence removing them from here

#### Testing
Locally compiled the temperature-measurement app with CMake 

Fixes #7302

### CODE REVIEW

**Comment by dhrishi** [comment]
Note that, this might still require adding the actual calls for temperature-measurement cluster. But, currently, we use this example for optimization of the Flash/RAM footprint and hence the build failure needs to be fixed sooner.

**Review by woody-apple — DISMISSED** [review]
Can you please fill out the testing template?

**Review by andy31415 — APPROVED** [review]
This file looks to be in a 'gen' folder which implies generated file.

Is this true or not @vivien-apple 
I have conflicting signals here: "gen" says generated, but our XML files do not contain 'events' as far as I am aware  (at least https://github.com/project-chip/connectedhomeip/blob/master/src/app/zap-templates/zcl/data-model/silabs/schema/zcl.xsd does not show it)

Approving assuming gen_event is not generated.

**Review by bzbarsky-apple — APPROVED** [review]
This file _is_ originally generated by Simplicity Studio, but has not been migrated to ZAP yet.  See https://github.com/project-chip/connectedhomeip/issues/3637#issuecomment-762869176

**Review by jmartinez-silabs — APPROVED** [review]

**Pull request merged**
