### PR TITLE
[linux] Delete the dbus generated files

### LINKED ISSUE #1936: linux: delete the dbus generated files
Ack, will do after we finalize the WiFi support

_Originally posted by @yufengwangca in https://github.com/project-chip/connectedhomeip/pull/1909#discussion_r463410990_

### PR DESCRIPTION
**Pull request by yufengwangca**
Problem
DbusBluez.c is auto-generated in run-time and its source file also get checked in to the repository

Summary of Changes
Remove file DbusBluez.c and use auto generated file

fixes #1936

### CODE REVIEW

**Review by rwalker-apple — APPROVED** [review]

**Comment by mspang** [comment]
What about the other 4 files?

**Review by mspang — CHANGES_REQUESTED** [review]
Also delete

```
DbusBluez.h
DbusWpa.h
DbusWpaInterface.h
DbusWpaNetwork.h
```

**Comment by yufengwangca** [comment]
> Also delete
> 
> ```
> DbusBluez.h
> DbusWpa.h
> DbusWpaInterface.h
> DbusWpaNetwork.h
> ```

We can only delete the header files after we remove autotools since Make build system need the header files be there before the files is generated from Makefile. 

But I strongly suggest to keep those header files for debugging purpose, otherwise, we even don't know the prototype of the functions we are going to use.

**Comment by mspang** [comment]
> > Also delete
> > ```
> > DbusBluez.h
> > DbusWpa.h
> > DbusWpaInterface.h
> > DbusWpaNetwork.h
> > ```
> 
> We can only delete the header files after we remove autotools since Make build system need the header files be there before the files is generated from Makefile.

Nobody should be building with autotools for Linux at this point. We can just remove the code for that.

> 
> But I strongly suggest to keep those header files for debugging purpose, otherwise, we even don't know the prototype of the functions we are going to use.

What's wrong with just looking at the files in the output dir? We shouldn't have these unused files checked in.

**Comment by yufengwangca** [comment]
> Nobody should be building with autotools for Linux at this point. We can just remove the code for that.

Should we clean up all autotools Make files from repository? otherwise, other people might try to maintain this build system like me.

**Comment by rwalker-apple** [comment]
> > Nobody should be building with autotools for Linux at this point. We can just remove the code for that.
> 
> Should we clean up all autotools Make files from repository? otherwise, other people might try to maintain this build system like me.

we're trying, as fast as we can

**Review by mspang — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Comment by rwalker-apple** [comment]
@hawk248 @jelderton @BroderickCarlin @saurabhst ?

**Review by saurabhst — APPROVED** [review]

**Pull request merged**
