### PR TITLE
Add ability to redirect CHIP logs to a callback and add python log callback integration

### PR DESCRIPTION
**Pull request by andy31415**
#### Problem
Python scripting cannot easily capture logs (and generally log redirects do not seem possible)

 #### Summary of Changes
Add the ability to redirect CHIP Logging to a callback, implement such a log redirect in python.

### CODE REVIEW

**Review by jelderton — APPROVED** [review]

**Comment by msandstedt** [comment]
Can this be rebased on master?  The history is pretty hard to look at with all of the commits from #4960.

**Comment by andy31415** [comment]
> Can this be rebased on master? The history is pretty hard to look at with all of the commits from #4960.

The best I could do would be to squash all commits. Master does squash merges today so I cannot properly rebase it (or at least I tried and failed).

**Comment by msandstedt** [comment]
> > Can this be rebased on master? The history is pretty hard to look at with all of the commits from #4960.
> 
> The best I could do would be to squash all commits. Master does squash merges today so I cannot properly rebase it (or at least I tried and failed).

I meant rebase and squash locally, and then force-push.  This is fine though as long as whomever merges uses the squash option.

**Review by msandstedt — APPROVED** [review]

**Review by mspang — DISMISSED** [review]
1. There is missing synchronization between replacing and accessing callbacks.
2. How does this work with the Python GIL ?

**Comment by andy31415** [comment]
> 1. There is missing synchronization between replacing and accessing callbacks.
> 2. How does this work with the Python GIL ?

Python sets the callbacks at startup, before the CHIP threads are initialized or have a chance to log anything.

**Comment by andy31415** [comment]
Added synchronization via std::atomic

**Review by woody-apple — APPROVED** [review]

**Pull request merged**
