### PR TITLE
[spell] Fix slew of spelling errors.

### PR DESCRIPTION
**Pull request by turon**
#### Problem
There are spelling errors scatter across the codebase.

#### Change overview
Attempt to fix as many of them as possible.

#### Testing
Most of these were detected by spell-check CI, so CI can validate.

### CODE REVIEW

**Comment by turon** [comment]
This patch seemed to have kill restyled.  It ran and failed, but didn't create a correct branch as expected.

**Review by bzbarsky-apple — APPROVED** [review]
@turon, need to restyle?

**Comment by turon** [comment]
> @turon, need to restyle?

Yes, per Andrei: "Restyler for some security reasons is not allowed to change anything inside the .github directory. The word lists are in .github."

He said he'd bypass the restyle checks for this one.  I ran restyle locally.

**Review by msandstedt — APPROVED** [review]

**Review by yunhanw-google — APPROVED** [review]

**Pull request merged**
