### PR TITLE
WindowCovering: Activate test and update Zap config + PICs 

### LINKED ISSUE #18794: [TC-WNCV-4.3] CurrentPositionLiftPercentage attribute showing value mismatch error
Summary:
As per testplan of TC-WNCV-4.3 
Step 1a: TH reads CurrentPositionLiftPercent100ths attribute from DUT and saved value as attrCurrentPositionLiftPercent100ths got value as 500
Step 1c: TH reads CurrentPositionLiftPercentage from  DUT + assert CurrentPositionLiftPercent100ths/100 equals CurrentPositionLiftPercentage expected value is 5 but got 50 

Testplan screenhot:
image
YAML screenshot:
image
Execution logs:
[exe_log.txt](https://github.com/project-chip/connectedhomeip/files/8770879/exe_log.txt)

### LINKED ISSUE #19055: [TC-WNCV-4.4] -  CurrentPositionTiltPercentage attribute value is not matched with the expected outcome
**Problem:**
As per testplan CurrentPositionTiltPercent100ths attribute value /100 should be equal to the  CurrentPositionTiltPercentage attribute value.but values are mismatched.

**Actual outcome:**
CurrentPositionTiltPercent100ths: 500
 CurrentPositionTiltPercentage: 50

**Expected outcome:**
CurrentPositionTiltPercent100ths: 500
CurrentPositionTiltPercentage: 5

**steps to reproduce:**
CurrentPositionTiltPercentage must be equal to CurrentPositionTiltPercent100ths / 100 

App used - allclusters app
Platform-Raspberrypi

Here i attached the logs for your reference:

[TC-WNCV-4.4.txt](https://github.com/project-chip/connectedhomeip/files/8814591/TC-WNCV-4.4.txt)

### PR DESCRIPTION
**Pull request by jmeg-sfy**
**Problem**
What is being fixed? Examples:
* Activate several disabled tests on WNCV
* Update Zap Config + add missing attributes for WindowCovering Cluster
* Fix some values

**Change overview**
What's in this PR
* YAML WNCV 3.2 3.1 2.1 4.3 4.4
* PICS addition for WindowCovering
* Tweak PICS linter to support comments and empty lines

**Testing**
How was this tested? (at least one bullet point required)
* All units test ok !

Fix  #18794 and #19055 19055

### CODE REVIEW

**Review by Damian-Nordic — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]

**Comment by andy31415** [comment]
@jmeg-sfy needs merge with master and zap regen.

**Comment by andy31415** [comment]
@jmeg-sfy - we seem out of flash on TI-CC26X2X7

**Comment by woody-apple** [comment]
@jmeg-sfy can you resolve conflicts? Looks approved!

**Comment by jmeg-sfy** [comment]
> @jmeg-sfy can you resolve conflicts? Looks approved!
I have been doing so since 3 weeks :( :( , yes i am crying :)

**Pull request merged**
