### PR TITLE
Use our EndpointId type in more places.

### LINKED ISSUE #3574: Use the EndpointId type in data model code
#### Problem
Data model code just asses `uint8_t` for the endpoint id.

 #### Proposed Solution
Use the EndpointId type we have instead, to make it clearer which things are endpoint ids.

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
#### Problem
We are hardcoding endpoint ids as `uint8_t`.

 #### Summary of Changes
Switch to the `chip::EndpointId` and `CHIPEndpointId` types so we can change the sizing easily.

 Fixes https://github.com/project-chip/connectedhomeip/issues/3574

### CODE REVIEW

**Comment by gerickson** [comment]
Thank you! So much prefer semantic types to bare types if only for readability, never mind singular location, ease of changing.

**Review by gerickson — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
I'm fairly confused by the `rodata` size increase.  Looking into that.

**Comment by bzbarsky-apple** [comment]
> I'm fairly confused by the `rodata` size increase. Looking into that.

Looks like we have symbols like `emAfPluginBarrierControlServerSetBarrierPosition(unsigned char, unsigned char)::__PRETTY_FUNCTION__` (`_ZZ48emAfPluginBarrierControlServerSetBarrierPositionhhE19__PRETTY_FUNCTION__` before demangling) that got 9 bytes bigger; over enough of them that added up.

But the important question is why these are in the binary at all.

**Comment by bzbarsky-apple** [comment]
@kedars I am trying to sort out our build and link flags for the esp32 libmain and binary bits, but do you know offhand why the `__PRETTY_FUNCTION__` stuff would be appearing if we don't actualy use `__PRETTY_FUNCTION__` anywhere?

**Review by jelderton — APPROVED** [review]

**Review by mspang — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
Oh, I bet I know!  Those functions use `assert` and that pulls in `__PRETTY_FUNCTION__`.

**Comment by bzbarsky-apple** [comment]
@saurabhst @BroderickCarlin @chrisdecenzo Can you take a look, please?

**Review by saurabhst — APPROVED** [review]

**Pull request merged**
