### PR TITLE
Rationalize includes in chip-tool-darwin a bit.

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
Ideally chip-tool-darwin would just include CHIP/CHIP.h.  In practice,
because it's trying to reuse various code that chip-tool also uses,
this is not possible, but we want to be as close to it as we can.

Specific changes:

* Use CHIP/CHIP.h instead of including individual framework public headers.

* Minimize use of CHIPError_Internal.h by commoning up the "log it and
  SetCommandExitStatus" logic, which is forced on us by the
  code-sharing with chip-tool.

* Minimize the use of other "internal" SDK headers.  For each one,
  document exactly why it's being used.

#### Problem
See above.

#### Change overview
See above.

#### Testing
chip-tool-darwin still compiles.  Should be no behavior changes, except slightly more consistent logging (ChipLogError in error conditions, ChipLogProgress if just logging when there is no error).

### CODE REVIEW

**Comment by krypton36** [comment]
@bzbarsky-apple Thanks for this. Can you please add the following? 
* Fixes #14909

**Review by krypton36 — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
I don't think this fixes https://github.com/project-chip/connectedhomeip/issues/14909 -- it's not changing ChipLogError behavior at all...

**Comment by krypton36** [comment]
> I don't think this fixes #14909 -- it's not changing ChipLogError behavior at all...

The issue is a little vague, but it was in reference to [this](https://github.com/project-chip/connectedhomeip/pull/14816#discussion_r802035535) comment which suggest to use ChipLogError as option one or 'Have a mode (controlled by what, not sure) where ChipLogError gets logged via NSLog.'. This appears to be doing option 1. If you think we should ultimately do option 2, we can leave it open.

**Comment by bzbarsky-apple** [comment]
> The issue is a little vague, but it was in reference to https://github.com/project-chip/connectedhomeip/pull/14816#discussion_r802035535 comment which suggests to use ChipLogError as option one or 'Have a mode (controlled by what, not sure) where ChipLogError gets logged via NSLog.'. This appears to be doing option 1. If you think we should ultimately do option 2, we can leave it open.

No, that comment was suggesting we do _both_ 1 and 2.  As in, use ChipLogError, but have an optional way to make that forward to NSLog.

**Comment by bzbarsky-apple** [comment]
Fast-tracking Darwin-only test-only change.

**Pull request merged**
