### PR TITLE
Update README.md for Air Quality and Dishwasher

### PR DESCRIPTION
**Pull request by lboue**
Replace CHIP by Matter

### CODE REVIEW

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by lboue** [comment]
Do you know why 'Documentation Build / build-and-publish (pull_request)' fails?

**Comment by bzbarsky-apple** [comment]
@lboue Presumably this part:
```
/home/runner/work/connectedhomeip/connectedhomeip/matter/docs/_build/src/examples/dishwasher-app/linux/README.md:14: WARNING: 'myst' cross-reference target not found: 'chip-linux-lighting-example' [myst.xref_missing]
```

And I am guessing that's because you renamed the section but didn't change the anchor target here.  So it's catching a real problem.

**Comment by woody-apple** [comment]
I tried, but I can't push to your branch.

**Comment by lboue** [comment]
> @lboue can you run this command for restyled? `curl https://restyled.io/gh/project-chip/repos/connectedhomeip/jobs/3763586/patch | git am`

I will do it ASAP.

**Comment by lboue** [comment]
@woody-apple I've just applied the patch.

**Comment by lboue** [comment]
I think there is an issue with 'ZAP / ZAP templates generation'. Other tests passed fine.

**Review by cecille — APPROVED** [review]

**Comment by cecille** [comment]
I believe the Zap failure was caused by https://github.com/project-chip/connectedhomeip/pull/30682/files. If you update to master is should pass.

**Comment by lboue** [comment]
> I believe the Zap failure was caused by https://github.com/project-chip/connectedhomeip/pull/30682/files. If you update to master is should pass.

Let's try this.

**Comment by lboue** [comment]
@cecille Ready to merge

**Pull request merged**
