### PR TITLE
[Ameba] Support NetworkCommissioning

### PR DESCRIPTION
**Pull request by pankore**
#### Problem

- Support NetworkCommissioning

#### Change overview

- Add NetworkCommissioningDriver.h and NetworkCommissioningWiFiDriver.cpp
- Update NetworkCommissioning related files in src/platform/Ameba

#### Testing
Tested with chiptool

### CODE REVIEW

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by pankore** [comment]
#13170

**Comment by andy31415** [comment]
fast track: platform specific change made by a platform maintainer.

**Pull request merged**
