### PR TITLE
Checking third party deps doesn't pass after someone fixes it

### PR DESCRIPTION
**Pull request by woody-apple**
This is causing confusion and forcing people to close and re-open PRs because it only fails, never passes

### CODE REVIEW

**Comment by andy31415** [comment]
@woody-apple what is the difference? I believe it generally works except it uses the "event label" which is only available at the time the PR is created. Does this allow a "restart" after we add the label? Maybe this is what the description should be.

**Comment by woody-apple** [comment]
> @woody-apple what is the difference? I believe it generally works except it uses the "event label" which is only available at the time the PR is created. Does this allow a "restart" after we add the label? Maybe this is what the description should be.

What doesn't work, is it doesn't check for the presence of the label and pass. So it leaves the PR in a failed state, that requires the filer (or someone like I was doing last night) to open and close the PR to re-evaluate the rule.

**Comment by woody-apple** [comment]
I updated the title to reflect the issue.

**Comment by woody-apple** [comment]
> @woody-apple what is the difference? I believe it generally works except it uses the "event label" which is only available at the time the PR is created. Does this allow a "restart" after we add the label? Maybe this is what the description should be.

Yes, this restarts it post adding the label

**Review by Alami-Amine — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Pull request merged**
