### PR TITLE
[clusters] Fix scheduled actions in clusters

### PR DESCRIPTION
**Pull request by Damian-Nordic**
#### Problem
PR #9469 changed the implementation of EventControlHandler function from af-event.cpp, but only updated Color Control Cluster code to use the new approach. As a result, all other clusters using scheduled actions, such as LevelControl.MoveToLevel, got broken.

#### Change overview
Make sure both methods of initializing cluster events are supported until all clusters are aligned one way or another.
Also, add a cirque test for LevelControl.MoveToLevel.

#### Testing
Tested by Cirque and using nRF Connect lighting-app.

### CODE REVIEW

**Comment by Damian-Nordic** [comment]
FYI @mkardous-silabs

**Comment by mkardous-silabs** [comment]
Might be worth while to update level-control to use the updated version EventControlHandler instead adding back the old code that use depracted event management through generated code that isn't generated anymore.

**Comment by Damian-Nordic** [comment]
@mkardous-silabs Yes, but there are more clusters that need to be updated, so I would prefer to fix the regression and later start transitioning subsequent clusters.

**Comment by mkardous-silabs** [comment]
@Damian-Nordic Fair enough, but if you have the time, it seems like an opportune moment to update the level-control cluster at the same time to the updated implementation.

**Review by woody-apple — APPROVED** [review]

**Review by LuDuda — APPROVED** [review]

**Review by jepenven-silabs — APPROVED** [review]

**Pull request merged**
