### PR TITLE
use docker image 0.6.27

### PR DESCRIPTION
**Pull request by pankore**
- use docker image 0.6.27

### CODE REVIEW

**Comment by s07641069** [comment]
@pankore Here is older PR with image update and Telink Fix https://github.com/project-chip/connectedhomeip/pull/24200

**Comment by andy31415** [comment]
@pankore this update seems to still have some issues:
- chef build fails for NRF (not sure why)
- NRF complains about:

```
# WARNING: Your current NCS revision (188a16036ab968bc0f9226ba178ca461548a8c66)       #
# differs from the recommended (004a23217d72ab50d55fb1cb981a797a8ca46cee).            #
```

so maybe we need to update `config/nrfconnect/.nrfconnect-recommended-revision` as well

**Comment by Damian-Nordic** [comment]
We have updated nRF Connect SDK in the docker image but not in the Matter yet. `examples-nrfconnect.yaml` workflow just updates it back to the previous version and hence it works. I'll try to create a PR with necessary changes to unblock you.

**Review by bzbarsky-apple — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Comment by s07641069** [comment]
@andy31415 I don't think that Telink examples build CI will pass without adaptation from https://github.com/project-chip/connectedhomeip/pull/24200

**Comment by andy31415** [comment]
> @andy31415 I don't think that Telink examples build CI will pass without adaptation from #24200

I can move Telink to 0.6.18 as well then.

**Comment by s07641069** [comment]
> > @andy31415 I don't think that Telink examples build CI will pass without adaptation from #24200
> 
> I can move Telink to 0.6.18 as well then.

Ok, in this case I will revert in my PR update images and just update for Telink into 0.6.27 after merge of this PR

**Pull request merged**
