### PR TITLE
[mbedtls] Bump version from 2.18 to 2.25

### PR DESCRIPTION
**Pull request by Damian-Nordic**
#### Problem
The future of crypto API on embedded devices is the PSA crypto API: https://armmbed.github.io/mbed-crypto/html/index.html. We will probably want to switch to that in Matter at some point in the future and in order to experiment with that we need quite a recent version of mbedtls. The one we currently use is quite old (from 2019).

#### Change overview
Bump mbedtls from 2.18 to 2.25

#### Testing
Verified that our unit tests for mbedTLS-based crypto are passing.
Also, compiled Python CHIP Controller with `chip_crypto="mbedtls"` and performed the full commissioning to verify that both PASE and the secure channel work correctly.

### CODE REVIEW

**Comment by Damian-Nordic** [comment]
@tima-q I checked the Qorvo build error and it appears that:
1. in mbedtls 2.25 `mbedtls_pk_write_key_der()` refers to `mbedtls_ecp_write_key()` function defined in `ecp.c` provided that `MBEDTLS_ECP_C && !MBEDTLS_ECP_ALT`.
2. Qorvo uses `third_party/qpg_sdk/repo/qpg6100/comps/libmbedtls/qpg6100-mbedtls-config.h` as the mbedtls config. It defines both `MBEDTLS_ECP_C` and `MBEDTLS_ECP_ALT`.
3. Despite of defining `MBEDTLS_ECP_ALT`, the Qorvo's sdk doesn't seem to provide any implementation of the `mbedtls_ecp_write_key()` function. 
Do you know how can I fix the build? Is `mbedtls_ecp_write_key` provided as any static library or is the mbedtls config invalid?

**Review by jmartinez-silabs — APPROVED** [review]

**Comment by tima-q** [comment]
> @tima-q I checked the Qorvo build error and it appears that:
> 
> 1. in mbedtls 2.25 `mbedtls_pk_write_key_der()` refers to `mbedtls_ecp_write_key()` function defined in `ecp.c` provided that `MBEDTLS_ECP_C && !MBEDTLS_ECP_ALT`.
> 2. Qorvo uses `third_party/qpg_sdk/repo/qpg6100/comps/libmbedtls/qpg6100-mbedtls-config.h` as the mbedtls config. It defines both `MBEDTLS_ECP_C` and `MBEDTLS_ECP_ALT`.
> 3. Despite of defining `MBEDTLS_ECP_ALT`, the Qorvo's sdk doesn't seem to provide any implementation of the `mbedtls_ecp_write_key()` function.
>    Do you know how can I fix the build? Is `mbedtls_ecp_write_key` provided as any static library or is the mbedtls config invalid?

@Damian-Nordic
I suspect our current mbedtls alt implementation (included in a static lib) is built against a lower mbedtls API version, hence missing the function. Will need to coordinate internally how/when we can bump this. Will keep you posted.

**Review by woody-apple — APPROVED** [review]

**Review by LuDuda — APPROVED** [review]

**Comment by woody-apple** [comment]
@Damian-Nordic looks like a real failure

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
@Damian-Nordic seems we need to fix some compilation issues.

**Comment by mspang** [comment]
> > @tima-q I checked the Qorvo build error and it appears that:
> > 
> > 1. in mbedtls 2.25 `mbedtls_pk_write_key_der()` refers to `mbedtls_ecp_write_key()` function defined in `ecp.c` provided that `MBEDTLS_ECP_C && !MBEDTLS_ECP_ALT`.
> > 2. Qorvo uses `third_party/qpg_sdk/repo/qpg6100/comps/libmbedtls/qpg6100-mbedtls-config.h` as the mbedtls config. It defines both `MBEDTLS_ECP_C` and `MBEDTLS_ECP_ALT`.
> > 3. Despite of defining `MBEDTLS_ECP_ALT`, the Qorvo's sdk doesn't seem to provide any implementation of the `mbedtls_ecp_write_key()` function.
> >    Do you know how can I fix the build? Is `mbedtls_ecp_write_key` provided as any static library or is the mbedtls config invalid?
> 
> @Damian-Nordic
> I suspect our current mbedtls alt implementation (included in a static lib) is built against a lower mbedtls API version, hence missing the function. Will need to coordinate internally how/when we can bump this. Will keep you posted.

Can you build mbedtls from source please? Including an MbedTLS .a file in your SDK without even shipping the corresponding headers doesn't make much sense.

**Comment by tima-q** [comment]
> Can you build mbedtls from source please? Including an MbedTLS .a file in your SDK without even shipping the corresponding headers doesn't make much sense.

@mspang The lib only contains the _alt pieces that are Qorvo specific. The remainder is built from the third_party/mbedtls folder. 
As the SDK is created to support this project, including the headers twice did not make sense at the time.

We planned in the task to update the mbedtls_alt implementation used. This should be ready by next week.
@Damian-Nordic this would come in the form of a submodule update of our qpg_sdk - do we contribute it to your PR directly ?

**Comment by Damian-Nordic** [comment]
@tima-q yeah, let me know when the new sdk is ready, so I can include the update in my PR.

**Comment by woody-apple** [comment]
@Damian-Nordic Looks like a real build failure on QPG

**Review by mspang — APPROVED** [review]

**Pull request merged**
