### PR TITLE
Revert "Integrate commissioner and device clusters with operational credentials"

### PR DESCRIPTION
**Pull request by yunhanw-google**
Reverts project-chip/connectedhomeip#6705

This PR has broken PASE connection for chip-tool/python chip device controller in real device and virtual CIRQUE mobile device test, and make TE3 branch cutoff(Today) in danger, this change is also blocking song's another TE3 critical fix(https://github.com/project-chip/connectedhomeip/pull/6761) 

Issues: 
https://github.com/project-chip/connectedhomeip/issues/6797 

With this change, cirque mobile test is broken
https://github.com/project-chip/connectedhomeip/runs/2582236209?check_suite_focus=true
Without this change, cirque mobile test pass
https://github.com/yunhanw-google/connectedhomeip/runs/2582288143?check_suite_focus=true

### CODE REVIEW

**Comment by yunhanw-google** [comment]
@woody-apple  please decide if we can revert it, considering TE3 cutoff date is today, not sure if TE3 needs to test this feature. thanks

**Comment by cecille** [comment]
The conflict here is that the controller needs access to the clusters to perform commissioning, including operational certificate exchange. chip-device-ctrl swaps out the IM delegate wholesale and assumes that nothing else will be touching anything to do with the clusters. I've run into the same problem for IP commissioning. Right now, I'm working on a PR that will allow this to be controlled by a build flag, which is obviously not ideal in the long term. If we revert this, it will affect TE3 - we won't be able to test operational certificates or IP commissioning.

**Comment by woody-apple** [comment]
@pan-apple ?

**Comment by pan-apple** [comment]
> @pan-apple ?

I agree with what @cecille said above. The flow is breaking because how chip-device-ctrl is handling the IM messages. Reverting #6705 is not the right fix. I think Song is working on a PR to fix the actual issue.

Also, for reference, the commissioning flow is working fine with iOS CHIPTool app.

**Comment by yunhanw-google** [comment]
> > @pan-apple ?
> 
> I agree with what @cecille said above. The flow is breaking because how chip-device-ctrl is handling the IM messages. Reverting #6705 is not the right fix. I think Song is working on a PR to fix the actual issue.
> 
> Also, for reference, the commissioning flow is working fine with iOS CHIPTool app.

Per latest TOT test result from @cjandhyala 
chip-tool is also breaking because of this issue.
ios app is also breaking in tot
Song's PR fails to fix the above issue, that is why we try to revert.
After revert, chip-tool and chip-device-ctrl can work

**Comment by yunhanw-google** [comment]
close this one, since TE3 is pushed to next Friday, we would focus on right solution forward

**Pull request closed without merging**
