### PR TITLE
[cirque] Build chip-cirque-device-base with cache mechanism and fix & re-enable cirque test

### PR DESCRIPTION
**Pull request by erjiaqing**
#### Problem

Cirque tests are broken because of mismatched version of ot-br-posix and openthread, this error is not catched by cirque test in presubmit checks.

According to our plan, the base image and cirque test should
1. Run otbr-agent built from checkout specified by CHIP repo submodule ot-br-posix.
2. Run ot-ncp built from checkout specified by CHIP repo submodule openthread.

 #### Summary of Changes

1. Nolonger pull docker image for chip-cirque-device-base from docker hub
2. Use Github cache to accelerate `docker build`.
3. Always run docker build to avoid potential build flag change (will not pull ot-br-posix version, but may break the test, docker should be able to detect this).

Example run:

Cold run: https://github.com/erjiaqing/connectedhomeip/runs/2302467940

Cache hit: https://github.com/erjiaqing/connectedhomeip/runs/2302541752

 Fixes #<<<<<FILL ME IN  - issue number(s). If no issue, please create one>>>>>

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]
Is the openthread submodule update intentional?

**Review by woody-apple — APPROVED** [review]

**Comment by erjiaqing** [comment]
Convert this to draft to address some issues.

**Comment by erjiaqing** [comment]
> Is the openthread submodule update intentional?

The ot-br-posix submodule update is intentional, the version used on ToT is not compatiable with the openthread version in CHIP.

**Review by yunhanw-google — APPROVED** [review]

**Comment by erjiaqing** [comment]
@andy31415 @woody-apple @mspang @Damian-Nordic PTAL

**Review by yufengwangca — APPROVED** [review]

**Comment by msandstedt** [comment]
ot-br-posix has its own openthread submodule that by definition will always work with the given rev of ot-br-posix.  Why doesn't the code that depends on this relationship simply use the openthread inside ot-br-posix?

**Review by jmartinez-silabs — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Comment by erjiaqing** [comment]
> ot-br-posix has its own openthread submodule that by definition will always work with the given rev of ot-br-posix. Why doesn't the code that depends on this relationship simply use the openthread inside ot-br-posix?

On real linux devices, the user is required to build a seperate openthread image for the RCP board. It could be confusing when that version does not match the one in openthread submodule.

**Pull request merged**
