### PR TITLE
[BL602] Update Bouffa Lab sdk repo

### PR DESCRIPTION
**Pull request by jczhang777**
#### Problem
What is being fixed?  Examples:
* Update Bouffa Lab sdk repo.

#### Change overview
Update Bouffa Lab sdk repo.Update bl602 sdk and impl. Adjust the directory structure, once again the subsequent addition of other types of chips

#### Testing
How was this tested? (at least one bullet point required)
* use chip tool commission with bl602, and basic command can be successful performed.

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
approve for v1 as plaform-specific change

**Comment by andy31415** [comment]
@jczhang777 - this needs conflict resolution

**Review by woody-apple — APPROVED** [review]

**Comment by andy31415** [comment]
Accepted for 1.0: platform specific change.

**Comment by jczhang777** [comment]
@andy31415 May I ask if the PR can be merged and if there is anything else I need to do.

**Pull request merged**
