### PR TITLE
[chip-tool] Add Optional endpoint id for the test command

### PR DESCRIPTION
**Pull request by vivien-apple**
#### Problem

It is useful to override the endpoint id uses by `chip-tool` for the test command

#### Change overview
 * Add an optional endpoint id

### CODE REVIEW

**Comment by woody-apple** [comment]
Fast tracking, given this is adding functionality to a test tool.

**Review by bzbarsky-apple — COMMENTED** [review]
I don't understand how this can work given the code as it landed in PR #11729.  That code will error out (with a very confusing message) if an optional argument is actually passed, and optional arguments are not initialized in that code [Edit: this claim is wrong].

I feel like the approach in #11642 at least answers those questions, and that answer is that you use named optional args and make the names look like something that looks like a command-line-arg naming convention, so in this case "--endpoint-id" or so.

Seems like we should fix that, and then this approach, with `Optional`, seems fine.

**Comment by vivien-apple** [comment]
> I don't understand how this can work given the code as it landed in PR #11729. That code will error out (with a very confusing message) if an optional argument is actually passed, and optional arguments are not initialized in that code.
> 
> I feel like the approach in #11642 at least answers those questions, and that answer is that you use named optional args and make the names look like something that looks like a command-line-arg naming convention, so in this case "--endpoint-id" or so.
> 
> Seems like we should fix that, and then this approach, with `Optional`, seems fine.

The code just assume that if you have arguments `A`, `B`, `C` where `B` and `C` are optionals, that if you want to use `C` you also need to provide `B`.

I agree, that adding a way to specify the argument is good, and I spoke with @krypton36 about adding support for it already as a way to make #11729 better.

**Comment by bzbarsky-apple** [comment]
> The code just assume that if you have arguments A, B, C where B and C are optionals, that if you want to use C you also need to provide B.

Right, but that's a pretty weird thing to require.

In any case, I see I was misreading it and we do initialize the optionals, so I guess this is ok as-is for now.

**Review by bzbarsky-apple — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Pull request merged**
