### PR TITLE
Propose Documentation for Software Best Practices, Coding Conventions, and Style

### LINKED ISSUE #335: Propose Documentation for Software Best Practices, Coding Conventions, and Style
#### Problem
CHIP will be composed of much software contributed from participating member organizations. However, for any new CHIP code, there should be documentation for software best practices, coding conventions, and style.

#### Proposed Solution
Submit a strawman documentation proposal for such software best practices, coding conventions, and style.

### PR DESCRIPTION
**Pull request by gerickson**
#### Problem
CHIP will be composed of much software contributed from participating member organizations. However, for any new CHIP code, there should be documentation for software best practices, coding conventions, and style.

#### Summary of Changes
Proposed a documentation guide, in AsciiDoc format, for software best practices, coding conventions, and style.

Fixes #335

### CODE REVIEW

**Review by jelderton — APPROVED** [review]

**Review by woody-apple — CHANGES_REQUESTED** [review]
Can we use ascii doc here, given we're using that for other things.

**Review by BroderickCarlin — APPROVED** [review]

**Review by saurabhst — APPROVED** [review]

**Review by woody-apple — CHANGES_REQUESTED** [review]
I'm struggling a little bit with the scope of the document here. I like the Doxygen push, as well as much of the C/C++ pushes, but this feels a little overly prescriptive - as well as duplicates clang-format/restyled.

Can this be reduced somehow to something more palatable for people to consume + read? (This took me a while to review...)

**Comment by rwalker-apple** [comment]
> > The last discussion ended with a mandate that we spend no more cycles on this. If there are things that everyone comes to agreement across companies (and, at that, there does not even seem to be alignment within companies), we can bubble those things up and memorialize them in a from-empty-to-plus-plus approach rather than in a as-is-to-minus-minus approach.
> 
> @rwalker-apple @gerickson I suggest we close this for now, then open up an organic document as things come in? Thoughts?

Fine with me, but can we get that document up first?

**Comment by gerickson** [comment]
Closing in lieu of https://github.com/project-chip/connectedhomeip/pull/1504.

**Comment by gerickson** [comment]
> > > The last discussion ended with a mandate that we spend no more cycles on this. If there are things that everyone comes to agreement across companies (and, at that, there does not even seem to be alignment within companies), we can bubble those things up and memorialize them in a from-empty-to-plus-plus approach rather than in a as-is-to-minus-minus approach.
> > 
> > 
> > @rwalker-apple @gerickson I suggest we close this for now, then open up an organic document as things come in? Thoughts?
> 
> Fine with me, but can we get that document up first?

See here for such a document: https://github.com/project-chip/connectedhomeip/pull/1504

**Pull request closed without merging**
