### PR TITLE
Move diagnostic operations from ConnectivityMgr to DiagnosticDataProvider

### PR DESCRIPTION
**Pull request by yufengwangca**
#### Problem
What is being fixed?  Examples:
* We have dedicated DiagnosticDataProvider to process all diagnostic operations. Need to relocate all diagnostic operations to this interface from existing interfaces.

#### Change overview
1. Move diagnostic operations from ConnectivityMgr to DiagnosticDataProvider
2. Remove all generic CRTP based intermediate implementations

#### Testing
How was this tested? (at least one bullet point required)
* Confirm we can get the correct  feature-map result with this refactor
```
yufengw@yufengw-SEi:~/connectedhomeip/out/debug/standalone$ ./chip-tool wifinetworkdiagnostics read packet-unicast-rx-count 12344321 0
.......
[1637684366.753363][444973:444978] CHIP:DMG: ReportDataMessage =
[1637684366.753367][444973:444978] CHIP:DMG: {
[1637684366.753370][444973:444978] CHIP:DMG: 	AttributeReportIBs =
[1637684366.753374][444973:444978] CHIP:DMG: 	[
[1637684366.753378][444973:444978] CHIP:DMG: 		AttributeReportIB =
[1637684366.753382][444973:444978] CHIP:DMG: 		{
[1637684366.753389][444973:444978] CHIP:DMG: 			AttributeDataIB =
[1637684366.753393][444973:444978] CHIP:DMG: 			{
[1637684366.753397][444973:444978] CHIP:DMG: 				AttributePathIB =
[1637684366.753403][444973:444978] CHIP:DMG: 				{
[1637684366.753407][444973:444978] CHIP:DMG: 					Endpoint = 0x0,
[1637684366.753412][444973:444978] CHIP:DMG: 					Cluster = 0x36,
[1637684366.753417][444973:444978] CHIP:DMG: 					Attribute = 0x0000_0009,
[1637684366.753421][444973:444978] CHIP:DMG: 				}
[1637684366.753426][444973:444978] CHIP:DMG: 					
[1637684366.753431][444973:444978] CHIP:DMG: 					Data = 193, 
[1637684366.753435][444973:444978] CHIP:DMG: 				DataVersion = 0x0,
[1637684366.753439][444973:444978] CHIP:DMG: 			},
[1637684366.753444][444973:444978] CHIP:DMG: 			
[1637684366.753447][444973:444978] CHIP:DMG: 		},
[1637684366.753452][444973:444978] CHIP:DMG: 		
[1637684366.753456][444973:444978] CHIP:DMG: 	],
[1637684366.753461][444973:444978] CHIP:DMG: 	
[1637684366.753464][444973:444978] CHIP:DMG: 	SuppressResponse = true, 
[1637684366.753468][444973:444978] CHIP:DMG: }
[1637684366.753487][444973:444978] CHIP:ZCL: ReadAttributesResponse:
[1637684366.753490][444973:444978] CHIP:ZCL:   ClusterId: 0x0000_0036
[1637684366.753494][444973:444978] CHIP:ZCL:   attributeId: 0x0000_0009
[1637684366.753498][444973:444978] CHIP:ZCL:   status: Success                (0x0000)
[1637684366.753501][444973:444978] CHIP:ZCL:   attribute TLV Type: 0x04
[1637684366.753505][444973:444978] CHIP:TOO: Int32u attribute Response: 193

```

### CODE REVIEW

**Comment by Damian-Nordic** [comment]
Switching from CRTP to virtual interfaces comes at a cost of increased flash usage which may really become a blocker at some point. It is because, the linker can't easily optimize out unused functions as they are still referenced by a vtable. In my opinion, if the direction is to use virtual interfaces we should keep the interfaces small so that platforms may choose which interfaces they want to implement. For example, I think we should have separate `EthernetDiagnosticProvider`, `WiFiDiagnosticProvider` and `ThreadDiagnosticProvider` interfaces. The additional advantage of that is that more code will be reusable - for example, all OpenThread-based platform will be able to use the same, say `OpenThreadDiagnosticProvider`, implementation. Thoughts?

**Review by jmartinez-silabs — APPROVED** [review]

**Comment by yufengwangca** [comment]
> Switching from CRTP to virtual interfaces comes at a cost of increased flash usage which may really become a blocker at some point. It is because, the linker can't easily optimize out unused functions as they are still referenced by a vtable. In my opinion, if the direction is to use virtual interfaces we should keep the interfaces small so that platforms may choose which interfaces they want to implement. For example, I think we should have separate `EthernetDiagnosticProvider`, `WiFiDiagnosticProvider` and `ThreadDiagnosticProvider` interfaces. The additional advantage of that is that more code will be reusable - for example, all OpenThread-based platform will be able to use the same, say `OpenThreadDiagnosticProvider`, implementation. Thoughts?

That is right, CRTP to virtual will increase the flash cost, we already have a lot of debates on if converting CRTP to virtual interface. The consensus is only converting ConfigurationMgr to virtual interface to better fit lower storage interface and keep the rest of interface as is.

The diagnostic APIs are complete new, keep adding tons of methods to PlatformManager/ConnectivityManager will make it hard to override and cause system dependencies against all drivers in those two classes. And we will have various delegate interfaces to be added later to support event. Obviously, current route is not scale-able  and difficult to maintain later

After discussing with @tcarmelveilleux , we would like to separate this out from giant PlatformManager/ConnectivityManager with the cost of virtual interface just for diagnostic operations. 

I agree with your proposal to split it further, but we have more than three diagnostic cluster now, log, general, software, wifi, ethernet, thread,  make all of them separate? I think only thread is optional in our example app.

**Comment by Damian-Nordic** [comment]
@yufengwangca I'm not sure if `DiagnosticDataProvider` needs to be split now as it's not very big yet, however WiFi, Ethernet and Thread diagnostics are going to be big and in many devices only one type of network will be supported, so I think that splitting it instead of creating one big interface may be a good idea so that the devices don't pay much for something they don't use. Of course, I'm OK with doing it as a follow up, but just wanted to express my feelings about the usage of virtual interfaces :)

**Review by Damian-Nordic — APPROVED** [review]

**Comment by yufengwangca** [comment]
> 


> @yufengwangca I'm not sure if `DiagnosticDataProvider` needs to be split now as it's not very big yet, however WiFi, Ethernet and Thread diagnostics are going to be big and in many devices only one type of network will be supported, so I think that splitting it instead of creating one big interface may be a good idea so that the devices don't pay much for something they don't use. Of course, I'm OK with doing it as a follow up, but just wanted to express my feelings about the usage of virtual interfaces :)

Maybe one solution is to split it to following sub-interfaces in the follow-ups:
1. general & software 
2. ethernet
3. wifi
4. thread
5. log

**Review by yunhanw-google — APPROVED** [review]

**Pull request merged**
