### PR TITLE
Support building CHIP with GN

### PR DESCRIPTION
**Pull request by mspang**
#### Problem
Builds (especially configuration, incrementals) can be much faster.

 #### Summary of Changes
A port of CHIP's automake build to the GN build system for Linux, Mac, & nRF5 example app.

### CODE REVIEW

**Review by rwalker-apple — CHANGES_REQUESTED** [review]
wow, lotsa work!

I'd like to see this split into at least 5 PRs:
1. the change to use git submodules for the relevant third_party/... repos
2. the import of the nrf5_sdk as a third_party/... submodule (actually why is this coming in as all the files?)
3. the changes to source files to deal with the pared down include directives (with accompanying updates to the autotools-based make system)
4. the import of pigweed
5. the actual GN stuff

**Review by turon — CHANGES_REQUESTED** [review]
This looks good!  Posted a few initial comments -- mostly minor:
1) Separate code changes (ifdef fixes) into separate PRs, so adding GN is isolated.
2) Some minor requests on file structure to minimize gni files and group them together in build/gn.

**Review by woody-apple — COMMENTED** [review]
This looks awesome. @mspang Could you make a separate copy of build.yml that's a gn build?

If you're not familiar with the GitHub workflows side of things, I'm also happy to help if you point me at some documentation for how to use gn :)

**Comment by mspang** [comment]
Opened a new PR since this one can no longer be updated after the repo went public

https://github.com/project-chip/connectedhomeip/pull/1456

**Comment by mspang** [comment]
Will look into build.yml !

**Pull request closed without merging**
