### PR TITLE
TE8 fixes

### PR DESCRIPTION
**Pull request by doru91**
#### Problem
Fixes different issues encountered during TE8 on K32W0 plaform.

#### Change overview
OTA
* add support for compiling without OTA support. If this happens, then the
application is written at address 0 in flash (instead at 0 + 16K - required
for SSBL). Also, more space is available for the app in this case;
* add detailed README instructions;
* increase idle task stack size - that's because writes to the eeprom are
done on the idle task;
* allow the application to specify the block size for each OTA fragment;
* add NXP SDK fixes for fixing eeprom race conditions;
* add NXP SDK fix for allowing the processing of OTA blocks of different
sizes;
* add support for parsing the OTA header.

Tokenizer
* add detailed README instructions.

Light app/Lock app
* enable lock tracking;
* schedule OTA/Matter attribute change/Server operations on the Matter task;
* avoid checking if thread is provisioned in a busy loop on eeprom - use an
event instead;
* disable mbedtls error logging (~13K) and instead add error logs in MemConfig.cpp
in case mbedtls memory allocations fail;
* change task priorities such that the app task has a smaller priority than the
Matter one;
* enable CHIP_DEVICE_CONFIG_ENABLE_TEST_SETUP_PARAMS such that the PBKDF are
hard-coded on the device side;
* refactor the gn options such that K32W0 module can be easily configured to be
attached to a dk different than DK6;
* group initialization calls in a single function;
* consider the case when WriteConfigValueStr is not called with a NULL-terminated
string.

#### Testing
How was this tested? (at least one bullet point required)
* manual testing using chip-tool.

### CODE REVIEW

**Review by bzbarsky-apple — APPROVED** [review]
Rubber-stamping (did not review carefully) platform-specific changes.

**Review by woody-apple — APPROVED** [review]
Fast tracking, given this has had enough time for review (> 3 days)

**Comment by doru91** [comment]
> /rebase

rebased. I can't get rid of the restyled error - sometimes it works, sometimes it doesn't. This this is very stubborn and I can't make it work even after several rebase attempts.

**Review by woody-apple — APPROVED** [review]
Thanks!

**Comment by doru91** [comment]
@woody-apple , I think that I accidentally removed your changes (while trying to remove third_party/efr32_sdk/repo) from your forced-push. Please re-add them if needed.

**Comment by woody-apple** [comment]
@doru91 Note, still conflicts here :(

**Comment by doru91** [comment]
> @doru91 Note, still conflicts here :(

Solved.

**Pull request merged**
