### PR TITLE
Add rsync to CHIP docker image.

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
This way we don't have to install it as part of CI jobs

#### Problem
We use rsync in our "Tests" job and end up installing it during the job on Linux.

#### Change overview
Include rsync in the docker image.

#### Testing
Not sure how to test, short of waiting for this to land, updating images, then removing the manual install and seeing the "Tests" job still pass.

### CODE REVIEW

**Comment by mspang** [comment]
Still confused @ https://github.com/project-chip/connectedhomeip/pull/7652/files#r652759128

**Comment by andy31415** [comment]
I believe this also needs to change dockerfile version (since it is different in contents now)

**Comment by bzbarsky-apple** [comment]
> Still confused @ https://github.com/project-chip/connectedhomeip/pull/7652#discussion_r652759128

Does https://github.com/project-chip/connectedhomeip/pull/7652#discussion_r652916669 help answer that?

**Comment by bzbarsky-apple** [comment]
> I believe this also needs to change dockerfile version (since it is different in contents now)

@andy31415 Good catch, done.

**Review by andy31415 — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Review by mspang — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
@msandstedt @Damian-Nordic @jmartinez-silabs @saurabhst Please take a look?

**Review by saurabhst — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]

**Pull request merged**
