### PR TITLE
NXP mw320 first commit to matter test_event_6.lts

### PR DESCRIPTION
**Pull request by JasonLan0223**
#### Problem
NXP MW320 wifi support for matter test_event_6.lts branch
#### Change overview
All MW320 matter sources

#### Testing
Using test event 6 chip tool to do the follow command:
Bypass pairing
./chip-tool pairing bypass "IPv6 address" 5540
Read MW320 led status
./chip-tool onoff read on-off 1
Turn on MW320 led
./chip-tool onoff on 1
Turn off MW320 led
./chip-tool onoff off 1

### CODE REVIEW

**Comment by andy31415** [comment]
@JasonLan0223  - please run the restyler: copy from #15130 or run `./scripts/helpers/restyle-diff.sh` or run something like (while adjusting for the right docker socket path):

```sh
docker run --interactive --rm                                   \
   --env HOST_DIRECTORY="$PWD"                                  \
   --env UNRESTRICTED=1                                         \
   --volume "$PWD":/code                                        \
   --volume /tmp:/tmp                                           \
   --volume "$XDG_RUNTIME_DIR/docker.sock":/var/run/docker.sock \
   --entrypoint restyle-path                                    \
   docker.io/restyled/restyler:edge                             \
   $(git diff --ignore-submodules --name-only "master" | tr "\n" " ")
```

**Comment by andy31415** [comment]
Also please adjust the summary - right now it contains just the template and it is wrong.

**Review by andy31415 — CHANGES_REQUESTED** [review]
Request changes: please restyle and update summary.

**Comment by JasonLan0223** [comment]
@andy31415  Thank you for your suggestion. We have run restyle-diff.sh and push some files modification. Is it still problem for "Restyled by gn"? Do you have any suggestion for it? Thank you for your help again.

**Comment by JasonLan0223** [comment]
We close it and using PR14826

**Pull request closed without merging**
