### PR TITLE
Fix cancellation of subscriptions to work correctly.

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
When a subscription came in with KeepSubscriptions set to false, we would just directly delete the ReadHandlers for the subscriptions not being kept, instead of calling Close().

That meant we skipped deleting subscription persistence data, and also failed to correcly update the reporting engine's round-robin reporting state, which could lead to subscriptions not being serviced fairly.

The fix is to just call Close() just like we do for out-of-resource eviction, instead of manually deleting the object.

### CODE REVIEW

**Review by yunhanw-google — APPROVED** [review]
In original logic, assume we have not yet added persistent subscription logic,  then we delete the readhandler from pool, the destructor would be called, it would call onReportConfirm if it is in IsAwaitingReportResponse so the report engine's state can be updated well. after applying your improvement, it would call close, and it move to AwaitingDestruction and reporting engine's state can be updated as well.





[11:35](https://csamembers.slack.com/archives/G01F7T68LHZ/p1691476520703369)
since we have added persistent subscription logic, we do need clear the persistent logic via explicit close call
just approve the pr, thanks

**Comment by yunhanw-google** [comment]
../../src/app/InteractionModelEngine.cpp -o obj/src/app/libCHIPDataModel.InteractionModelEngine.cpp.o
../../src/app/InteractionModelEngine.cpp:618:48: error: lambda capture 'this' is not used [-Werror,-Wunused-lambda-capture]
  618 |             mReadHandlers.ForEachActiveObject([this, apExchangeContext](ReadHandler * handler) {

this needs to be tested.

**Comment by yunhanw-google** [comment]
can we have the job to enable CHIP_CONFIG_PERSIST_SUBSCRIPTIONS flag, and test the persistent subscription can be removed when closing the readhandler?

**Comment by bzbarsky-apple** [comment]
>  so the report engine's state can be updated well

No, it was still missing the `ResetReadHandlerTracker()` call.  Basically, it was just broken as long as Close or InteractionModelEngine::OnDone had any logic in them.

**Comment by bzbarsky-apple** [comment]
> this needs to be tested.

I did test it, fwiw, on esp32 where I ran into the issue.  It compiles there.  ;)

**Review by jtung-apple — APPROVED** [review]

**Pull request merged**
