### PR TITLE
Tests add test tc bi 1 1

### PR DESCRIPTION
**Pull request by raju-apple**
### Problem

Adding TC_BI_1_1.yaml test case into CI

### Testing

Tested locally and passed.

### CODE REVIEW

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by andy31415** [comment]
Please sign the CLA

**Review by andy31415 — APPROVED** [review]

**Comment by raju-apple** [comment]
> Please sign the CLA

I did sign it a couple days back , not sure why its still not approved. Let me check with @woody-apple

**Comment by bzbarsky-apple** [comment]
@saurabhst @msandstedt @Damian-Nordic Please take a look?

**Review by Damian-Nordic — APPROVED** [review]

**Pull request merged**
