### PR TITLE
Allow serial number to be both an unsigned int and a string

### PR DESCRIPTION
**Pull request by shana-apple**
#### Problem
- Serial number could only be provided as a string

 #### Summary of Changes
- Serial number can be provided as string or uint32
- Simplify some of the APIs for vendors so they don't have to deal with OptionaQRCodeInfo objects but instead can just add optional data by passing a tag and value
- Fix the iOS Framework tests and add new ones testing the optional data parsing

fixes #932 #1042

### CODE REVIEW

**Review by rwalker-apple — DISMISSED** [review]
did you intend to submit INSTALL and COPYING?

**Review by bhaskar-apple — COMMENTED** [review]
LGTM pending other requested changes by Rob

**Review by woody-apple — APPROVED** [review]

**Review by andy31415 — CHANGES_REQUESTED** [review]
I see a GPL3 COPYING file in here.

Are we allowing GPL licenses in CHIP? it is open source but I think if people want to link there may be an issue with closed source apps that other vendors may build.

Do we have a list of licenses allowed? All code we have is copyright by chip authors right now. Also if GPL is not allowed, we have to make sure that code is not copied/derived from GPL

**Review by woody-apple — CHANGES_REQUESTED** [review]
Remove GPL code

**Review by gerickson — DISMISSED** [review]
Seems fine less deletion of the `INSTALL` and `COPYING` files.

**Review by woody-apple — APPROVED** [review]
Approving pending build works :)

**Review by andy31415 — APPROVED** [review]

**Review by jelderton — APPROVED** [review]

**Pull request merged**
