### PR TITLE
Remove file that only exists because of a mis-merge.

### LINKED ISSUE #2603: examples/chip-tool/gen should not exist for the moment
#### Problem
This looks like a merge issue from merging 74798d4d23b1ca50177b5802fd0e3cb13b0d1a92 (from <https://github.com/project-chip/connectedhomeip/pull/2475>) and 4ee55341da87f28fd0ae8d766fdb32a72150d202 (from #2365).  The former added a file (`af-gen-event.h`) and the latter moved all files out of the directory that file was in, but didn't actually move the new file...

 #### Proposed Solution
Remove the leftover file.

### PR DESCRIPTION
**Pull request by bzbarsky-apple**
Revision 74798d4 added the file.  Revision 4ee5534 should have moved it, but didn't.

 #### Problem
File shouldn't be there.

 #### Summary of Changes
Remove the file.

fixes https://github.com/project-chip/connectedhomeip/issues/2603

### CODE REVIEW

**Review by erjiaqing — APPROVED** [review]
Thanks!

**Review by saurabhst — APPROVED** [review]

**Review by mspang — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Review by BroderickCarlin — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
@rwalker-apple could you take a look, please?

**Review by rwalker-apple — COMMENTED** [review]
I put this here deliberately in order to get something compiling.

this header *will* eventually exist in every application, we just don't need it for chip-tool yet.

since it looks like killing this header didn't kill any builds, this is fine to land.

**Review by rwalker-apple — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
> I put this here deliberately in order to get something compiling.

Sure, because at that point this dir had a full set of generated files... Then they all went away.

**Pull request merged**
