### PR TITLE
fix --copy-artifacts-to issue in build_example.py

### PR DESCRIPTION
**Pull request by xylophone21**
#### Problem
* Fixes --copy-artifacts-to issue for build_example.py
    *https://github.com/project-chip/connectedhomeip/pull/10371#issuecomment-941299971

#### Change overview
fixed file path

#### Testing
* build test

### CODE REVIEW

**Review by andy31415 — CHANGES_REQUESTED** [review]
Requesting changes:

I checked out this PR and tryied this in my VSCode instance:

```
./scripts/build/build_examples.py --enable-flashbundle --target-glob '*studio*' build --copy-artifacts-to ./out/artifacts
```

1) It failed with

```
2021-10-13 17:04:56 WARNING FAILURE: Build failed with an exception.
2021-10-13 17:04:56 WARNING 
2021-10-13 17:04:56 INFO    50 actionable tasks: 25 executed, 25 up-to-date
2021-10-13 17:04:56 WARNING * What went wrong:
2021-10-13 17:04:56 WARNING Execution failed for task ':app:mergeDebugNativeLibs'.
2021-10-13 17:04:56 WARNING > A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
2021-10-13 17:04:56 WARNING    > 2 files found with path 'lib/armeabi-v7a/libCHIPController.so' from inputs:
2021-10-13 17:04:56 WARNING       - /workspaces/connectedhomeip/src/android/CHIPTool/app/build/intermediates/merged_jni_libs/debug/out
2021-10-13 17:04:56 WARNING       - /workspaces/connectedhomeip/src/android/CHIPTool/app/build/intermediates/cmake/debug/obj
2021-10-13 17:04:56 WARNING      If you are using jniLibs and CMake IMPORTED targets, see
2021-10-13 17:04:56 WARNING      https://developer.android.com/r/tools/jniLibs-vs-imported-targets
2021-10-13 17:04:56 WARNING 
2021-10-13 17:04:56 WARNING * Try:
2021-10-13 17:04:56 WARNING Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
2021-10-13 17:04:56 WARNING 
2021-10-13 17:04:56 WARNING * Get more help at https://help.gradle.org
2021-10-13 17:04:56 WARNING 
2021-10-13 17:04:56 WARNING BUILD FAILED in 4m 50s
```

2) it polluted my source folder (did not generate everything in ./out) by creating:

- src/android/CHIPTool/app/build
- src/android/CHIPTool/app/.cxx
- src/android/CHIPTool/chip-library/build
- ./src/android/CHIPTest/app/.cxx/cmake/

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by xylophone21** [comment]
> I retried and succeeded to compile after really cleaning my android src dir. I believe the relevant step was cleaning `src/android/CHIPTest/app/libs/jniLibs` and similar, however this was hard to discover (I removed .gitignores so that git shows what is extra there).
> 
> My complaint is that this hidden file generation makes my source dirty and gitignore hides it away. Can we update the build so that it does not generate this extra data? After a clean I see these generated during the build:
> 
> * src/android/CHIPTool/.gradle/
> * src/android/CHIPTool/app/.cxx/
> * src/android/CHIPTool/app/build/
> * src/android/CHIPTool/chip-library/build/

It is because of a issue of maybe gradle I asked here, so I removed -PbuildDir= in android.py
https://stackoverflow.com/questions/69564314/android-studio-project-with-library-project-build-failed-when-set-pbuilddir

While I found a workaround way to added -PbuildDir= back, it is now better but still not fix everything. And I also found our old way also added some files under CHIPTool/, they are:
> * src/android/CHIPTool/.gradle/
> * src/android/CHIPTool/app/.cxx/

I understand that this my source dirty, but
1. we can not fix it unless gradle fix it, even we do not turn on this code
2. without such code, we can not keep android studio build pass

So could we let it work first and let`s keeping find perfect solutions?

**Comment by andy31415** [comment]
> > I retried and succeeded to compile after really cleaning my android src dir. I believe the relevant step was cleaning `src/android/CHIPTest/app/libs/jniLibs` and similar, however this was hard to discover (I removed .gitignores so that git shows what is extra there).
> > My complaint is that this hidden file generation makes my source dirty and gitignore hides it away. Can we update the build so that it does not generate this extra data? After a clean I see these generated during the build:
> > 
> > * src/android/CHIPTool/.gradle/
> > * src/android/CHIPTool/app/.cxx/
> > * src/android/CHIPTool/app/build/
> > * src/android/CHIPTool/chip-library/build/
> 
> It is because of a issue of maybe gradle I asked here, so I removed -PbuildDir= in android.py https://stackoverflow.com/questions/69564314/android-studio-project-with-library-project-build-failed-when-set-pbuilddir
> 
> While I found a workaround way to added -PbuildDir= back, it is now better but still not fix everything. And I also found our old way also added some files under CHIPTool/, they are:
> 
> > * src/android/CHIPTool/.gradle/
> > * src/android/CHIPTool/app/.cxx/
> 
> I understand that this my source dirty, but
> 
> 1. we can not fix it unless gradle fix it, even we do not turn on this code
> 2. without such code, we can not keep android studio build pass
> 
> So could we let it work first and let`s keeping find perfect solutions?

The difficutly I had was that a compile error was impossible to track down because I assumed that my src was clean (according to git status) but that was wrong: I had jnilibs in places hidden by .gitignore.

At first I assumed 'this does not compile at all' hence the changes requested. The "Dirty source" is still there I guess.
Could we maybe symlink the 'build' directory into the output folder?

**Comment by xylophone21** [comment]
> > > I retried and succeeded to compile after really cleaning my android src dir. I believe the relevant step was cleaning `src/android/CHIPTest/app/libs/jniLibs` and similar, however this was hard to discover (I removed .gitignores so that git shows what is extra there).
> > > My complaint is that this hidden file generation makes my source dirty and gitignore hides it away. Can we update the build so that it does not generate this extra data? After a clean I see these generated during the build:
> > > 
> > > * src/android/CHIPTool/.gradle/
> > > * src/android/CHIPTool/app/.cxx/
> > > * src/android/CHIPTool/app/build/
> > > * src/android/CHIPTool/chip-library/build/
> > 
> > 
> > It is because of a issue of maybe gradle I asked here, so I removed -PbuildDir= in android.py https://stackoverflow.com/questions/69564314/android-studio-project-with-library-project-build-failed-when-set-pbuilddir
> > While I found a workaround way to added -PbuildDir= back, it is now better but still not fix everything. And I also found our old way also added some files under CHIPTool/, they are:
> > > * src/android/CHIPTool/.gradle/
> > > * src/android/CHIPTool/app/.cxx/
> > 
> > 
> > I understand that this my source dirty, but
> > 
> > 1. we can not fix it unless gradle fix it, even we do not turn on this code
> > 2. without such code, we can not keep android studio build pass
> > 
> > So could we let it work first and let`s keeping find perfect solutions?
> 
> The difficutly I had was that a compile error was impossible to track down because I assumed that my src was clean (according to git status) but that was wrong: I had jnilibs in places hidden by .gitignore.
> 
> At first I assumed 'this does not compile at all' hence the changes requested. The "Dirty source" is still there I guess. Could we maybe symlink the 'build' directory into the output folder?

I tried 

> > > I retried and succeeded to compile after really cleaning my android src dir. I believe the relevant step was cleaning `src/android/CHIPTest/app/libs/jniLibs` and similar, however this was hard to discover (I removed .gitignores so that git shows what is extra there).
> > > My complaint is that this hidden file generation makes my source dirty and gitignore hides it away. Can we update the build so that it does not generate this extra data? After a clean I see these generated during the build:
> > > 
> > > * src/android/CHIPTool/.gradle/
> > > * src/android/CHIPTool/app/.cxx/
> > > * src/android/CHIPTool/app/build/
> > > * src/android/CHIPTool/chip-library/build/
> > 
> > 
> > It is because of a issue of maybe gradle I asked here, so I removed -PbuildDir= in android.py https://stackoverflow.com/questions/69564314/android-studio-project-with-library-project-build-failed-when-set-pbuilddir
> > While I found a workaround way to added -PbuildDir= back, it is now better but still not fix everything. And I also found our old way also added some files under CHIPTool/, they are:
> > > * src/android/CHIPTool/.gradle/
> > > * src/android/CHIPTool/app/.cxx/
> > 
> > 
> > I understand that this my source dirty, but
> > 
> > 1. we can not fix it unless gradle fix it, even we do not turn on this code
> > 2. without such code, we can not keep android studio build pass
> > 
> > So could we let it work first and let`s keeping find perfect solutions?
> 
> The difficutly I had was that a compile error was impossible to track down because I assumed that my src was clean (according to git status) but that was wrong: I had jnilibs in places hidden by .gitignore.
> 
> At first I assumed 'this does not compile at all' hence the changes requested. The "Dirty source" is still there I guess. Could we maybe symlink the 'build' directory into the output folder?

I tried this:
1. latest code will move build to different folder, so I think the build issue should be fixed. They are:
* android/CHIPTool/app/build/  -> android/CHIPTool/app/out/android-androidstudio-chip-tool
* android/CHIPTool/chip-library/build -> android/CHIPTool/chip-library/out/android-androidstudio-chip-tool
* android/CHIPTool/build ->  android/CHIPTool/out/android-androidstudio-chip-tool

2. I also tried to make symlink, but the code looks not good because there are 3 builds, the code looks like below.
```python
            # Workaround: using relative path for -PbuildDir to avoid below issue
            # https://stackoverflow.com/questions/69564314/android-studio-project-with-library-project-build-failed-when-set-pbuilddir
            try:
                self._Execute(['rm', '%s/src/android/%s/app/build' % (self.root,
                                                                      self.app.AppName())])
            except:
                pass

            try:
                self._Execute(['mkdir', '-p', '%s/android_build/%s/app' %
                              (self.output_dir,
                               self.app.AppName())])
            except:
                pass
            self._Execute(['ln', '-s', '%s/android_build/%s/app' % (self.output_dir,
                                                                    self.app.AppName()), '%s/src/android/%s/app/build' % (self.root, self.app.AppName())
                           ])

            try:
                self._Execute(['rm', '%s/src/android/%s/chip-library/build' % (self.root,
                                                                               self.app.AppName())])
            except:
                pass

            try:
                self._Execute(['mkdir', '-p', '%s/android_build/%s/chip-library' %
                              (self.output_dir,
                               self.app.AppName())])
            except:
                pass

            self._Execute(['ln', '-s', '%s/android_build/%s/chip-library' % (self.output_dir,
                                                                             self.app.AppName()), '%s/src/android/%s/chip-library/build' % (self.root, self.app.AppName())
                           ])
```

So, do you think we should do as 1 ( put build under android/CHIPTool/app/out/android-androidstudio-chip-tool ) or as 2 ( syslinke 3 build folders to out/android-androidstudio-chip-tool/xxx ) ?

**Review by andy31415 — APPROVED** [review]
Approving: it seems that my request of trying not to dirty our source code resulted in significant build complexity. I did not expect or intended this to be as derailing.

If in-source build keeps complexity lower, I am ok with that as well and seem to even prefer it now that I see hacks regarding dry run and other rmdir/mkdir logic

**Comment by austinh0** [comment]
Agree with Andrei, I don't like how complex this is. Could we instead have the build script accept a custom build directory (i.e. the in-source build dir) just for Android, independent of `output_dir`, and run `./gradlew clean` inbetween builds?

**Review by austinh0 — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Pull request merged**
