### PR TITLE
Rename SubSpan to subspan

### PR DESCRIPTION
**Pull request by kghost**
#### Problem
`Span`/`FixedSpan` is mimicking STL `std::span` APIs

#### Change overview
Rename `Span::SubSpan` to `subspan`

#### Testing
Running unit-tests

### CODE REVIEW

**Review by bzbarsky-apple — COMMENTED** [review]
So... The semantics of `SubSpan` differ from those of the std `subspan`.  Given that, I wonder whether it's actually more misleading to name them the same...

And apart from that, Span is different enough from `std::span` at this point in terms of various convenience functions, that replacing one with the other would be quite a bit of work, so I am not sure how much value there is in trying to mimic the API naming convention either.

**Comment by Damian-Nordic** [comment]
Yeah, I think Matter code should follow Matter's (informal) coding conventions which seems to be using CamelCase for functions and methods.

**Comment by kghost** [comment]
I think the idea is that we can easily plug in `std::span` to replace our span, when upgrade to C++17. It also releases us from document it, because STL is already well documented.

I hate to see there are both naming style in our code, So we should made the decision, continue following STL style or branch off totally. I don't think there is any other path to wiggle between.

**Comment by bzbarsky-apple** [comment]
> I think the idea is that we can easily plug in std::span to replace our span,

I suspect this is quite difficult given the various convenience helpers we have on our Span that std::span lacks....

**Comment by msandstedt** [comment]
> I think the idea is that we can easily plug in std::span to replace our span, when upgrade to C++17. It also releases us from document it, because STL is already well documented.

Is there a plan to upgrade to C++17?

**Pull request closed without merging**
