### PR TITLE
Add Chef rootnode_fan as sample device

### LINKED ISSUE #22628: [Platform] Add Chef rootnode FAN sample device
### Reproduction steps / Feature

```bash
The current Chef sample devices doesn't contain FAN only type. We need to add a FAN only device type for testing and verification.
```

### Platform

other

### Platform Version(s)

_No response_

### Type

Unit tested

### (Optional) If manually tested please explain why this is only manually tested

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by erwinpan1**
Add Chef rootnode_fan as sample device
including .zap / .matter / zzz-generated files

#### Issue Being Resolved
* Fixes #22628 

#### Change overview
Add sample device .zap / .matter / zzz-generated callbacks

### CODE REVIEW

**Review by mspang — APPROVED** [review]

**Comment by andy31415** [comment]
@erwinpan1 - please check the new file with `./scripts/idl_lint.py`

**Review by andy31415 — DISMISSED** [review]
Request changes: this is not a valid matter file:

it has a default for supported locales (which is an array and the default is en-us which is invalid).
when fixing this:

```


2022-09-15 10:36:11 ERROR   ERROR: Required attributes: EP0:AccessControl does not expose SubjectsPerAccessControlEntry(2) attribute at /home/andrei/tmp/rootnode_fan_7N2TobIlOX.matter:1343:3
2022-09-15 10:36:11 ERROR   ERROR: Required attributes: EP0:AccessControl does not expose TargetsPerAccessControlEntry(3) attribute at /home/andrei/tmp/rootnode_fan_7N2TobIlOX.matter:1343:3
2022-09-15 10:36:11 ERROR   ERROR: Required attributes: EP0:AccessControl does not expose AccessControlEntriesPerFabric(4) attribute at /home/andrei/tmp/rootnode_fan_7N2TobIlOX.matter:1343:3
2022-09-15 10:36:11 ERROR   ERROR: Required attributes: EP0:Basic does not expose CapabilityMinima(19) attribute at /home/andrei/tmp/rootnode_fan_7N2TobIlOX.matter:1351:3
2022-09-15 10:36:11 ERROR   ERROR: Required attributes: EP0:LocalizationConfiguration does not expose ActiveLocale(0) attribute at /home/andrei/tmp/rootnode_fan_7N2TobIlOX.matter:1384:3
2022-09-15 10:36:11 ERROR   ERROR: Required attributes: EP0:GeneralCommissioning does not expose SupportsConcurrentConnection(4) attribute at /home/andrei/tmp/rootnode_fan_7N2TobIlOX.matter:1398:3
2022-09-15 10:36:11 ERROR   ERROR: Required attributes: EP0:Switch does not expose number of positions(0) attribute at /home/andrei/tmp/rootnode_fan_7N2TobIlOX.matter:1548:3
2022-09-15 10:36:11 ERROR   ERROR: Required attributes: EP0:Switch does not expose current position(1) attribute at /home/andrei/tmp/rootnode_fan_7N2TobIlOX.matter:1548:3
```

**Comment by andy31415** [comment]
@erwinpan1 - I updated to latest code where the linter runs.

The error in parsing is because of the default value on available locales - external values should not have a default (and array defaults are not clear in general ... arrays are always external). So having a default there is not something that zap considered, so idl generation also chokes and generates an invalid IDL.

**Comment by erwinpan1** [comment]
@andy31415 

Got it. I've removed 2 invalid array default values and committed.

**Pull request merged**
