### PR TITLE
Add DevinfoInit to Relevant CC13xx apps

### PR DESCRIPTION
**Pull request by adabreuti**
#### Problem
Device info cluster is not initialized at the correct location.

#### Change overview
Initialize dev info cluster
#### Testing
Verified labels are able to be correctly created in all clusters cc13xx implementation and that the projects build.

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
@adabreuti - it looks like this needs restyle fixes.

**Comment by adabreuti** [comment]
> @adabreuti - it looks like this needs restyle fixes.

Resolved

**Comment by adabreuti** [comment]
@andy31415 It appears as if all PR's are currently not able to be merged due to the "Test Suites - Darwin" case failing. Is it possible for this to be overridden as this PR is platform specific?

**Comment by andy31415** [comment]
Retrying runs. `TC_PCC_2_1` seems flaky: #22239

**Comment by andy31415** [comment]
1.0 accepted as platform-specific change.

**Pull request merged**
