### PR TITLE
[Tizen] Implement thread scan network functions

### PR DESCRIPTION
**Pull request by dh79pyun**
Implement Device Layer's scan functions for Thread Driver.
The scan parameter for openthread was based on the latest modification.
https://github.com/openthread/ot-br-posix/pull/1814

### CODE REVIEW

**Comment by dh79pyun** [comment]
The Build example - tizen fail issue depends on Tizen SDK's modification.
Tizen SDK already be modified for this PR in https://download.tizen.org/snapshots/TIZEN/Tizen/Tizen-Unified/tizen-unified_20230816.124244/repos/standard/packages/armv7l/. But it did not apply into docker.

**Comment by dh79pyun** [comment]
> Implement Device Layer's scan functions for Thread Driver. The scan parameter for openthread was based on the latest modification. [openthread/ot-br-posix#1814](https://github.com/openthread/ot-br-posix/pull/1814)

To update Tizen docker, raise next PR
https://github.com/project-chip/connectedhomeip/pull/28765

**Comment by woody-apple** [comment]
@dh79pyun Is this still a relevant PR?

**Comment by dh79pyun** [comment]
> @dh79pyun Is this still a relevant PR?

This PR is valid, and verified on Tizen. But, the request for updating Tizen Docker was not accepted.
In currently. There is no way to fix the mid version for Tizen docker.

Actually, I thought to create Tizen SDK package repo in github, and use it. But don't have a time to spend this now.

Will try it, and re-raise this PR with docker update.

**Comment by andy31415** [comment]
Tizen build failed on this tizen-specific PR. No updates in several months. Closing as assuming stale.

**Pull request closed without merging**
