### PR TITLE
Add extra bootstrap hint to gn_build.sh

### PR DESCRIPTION
**Pull request by mspang**
This is pretty confusing right now due to the transition, and has
tripped up multiple people. Add an extra note before bootstrap about
what "run bootstrap" means for us.

 #### Problem
Instruction to "Run bootstrap" is not clear while we still have multiple bootstraps.

 #### Summary of Changes
Add a note saying which bootstrap to run.

### CODE REVIEW

**Review by yunhanw-google — APPROVED** [review]

**Review by saurabhst — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]

**Review by rwalker-apple — APPROVED** [review]

**Comment by rwalker-apple** [comment]
@hawk248 @jelderton ?

**Review by kedars — APPROVED** [review]

**Comment by mspang** [comment]
@andy31415

**Comment by rwalker-apple** [comment]
@hawk248 @jelderton ?

**Comment by rwalker-apple** [comment]
@andy31415 ?

**Review by BroderickCarlin — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Pull request merged**
