### PR TITLE
Delay processing test event in Smoke CO Alarm

### PR DESCRIPTION
**Pull request by ericzijian1994**
Because TH run step is slow, delay the processing of test event.

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
Hold on.  This seems to be working around some bug in the test plan, but are all the actual devices supposed to work around this bug too?   @cjandhyala

**Comment by cjandhyala** [comment]
not sure why we need that delay to triggerEvent. @ericzijian1994 any TH ticket that you filed ?

**Comment by umbraHare** [comment]
> not sure why we need that delay to triggerEvent. @ericzijian1994 any TH ticket that you filed ?

Because TH is a slow test, it will wait a few seconds after sending the eventTrigger command before executing the waitForReport step. This would miss the timing of the attribute change, causing waitForReport to wait until it times out. So I added the timer to change the attribute 5 seconds after receiving the eventTrigger command.

**Comment by ericzijian1994** [comment]
I don't know if this is a bug, maybe waitForReport needs to be optimized. @cjandhyala

**Comment by bzbarsky-apple** [comment]
If waitForReport only sees reports that come _after_ it starts, that's a problem.  There are tons of tests that assume they can change a thing and then waitForReport....  @vivien-apple @cjandhyala

**Comment by bzbarsky-apple** [comment]
And in particular: we can't expect real devices to delay processing like this!  But we do want them to pass our cert tests.  So if our cert tests are buggy we need to fix those bugs, not just work around them.

**Comment by cjandhyala** [comment]
I totally agree we can not add delay in the SDK code to work around a TH issue. If you see any issue with TH, pls file ticket on TH.

**Comment by umbraHare** [comment]
Looks like #19861 has already mentioned this. @cjandhyala

**Pull request merged**
