### PR TITLE
fixup-merge-cross

### PR DESCRIPTION
**Pull request by rwalker-apple**
#### Problem
 Vivien and NRF guys missed each other, mismatched types for setupdisc

 #### Summary of Changes
 fix that

### CODE REVIEW

**Review by saurabhst — APPROVED** [review]

**Comment by vivien-apple** [comment]
Fixed by #2598

**Comment by mspang** [comment]
dupe?

**Comment by bzbarsky-apple** [comment]
Yep, dupe of https://github.com/project-chip/connectedhomeip/pull/2598

**Comment by rwalker-apple** [comment]
thanks!

**Pull request closed without merging**
