### PR TITLE
Add UI to dynamically change number of onOff endpoints/cluster and adopt CHIPFramework API to control different lights/endpoints

### LINKED ISSUE #4566: Add UI to dynamically change number of onOff endpoints/cluster and adopt CHIPFramework API to control different lights/endpoints
#### Problem
While there is currently basic UI to control lights, developer has to go in code to modify number of lights to be controlled. Only one light could be controlled regardless as as CHIPFramework had changed

 #### Proposed Solution
Add UI to dynamically change how many lights user wants to control. This number of lights is persisted in defaults.
Depending on how many endpoints/lights are requested, create different clusters pointing to correct endpoint.

### PR DESCRIPTION
**Pull request by shana-apple**
- Adds UI to change how many light endpoints developer wants to control
- Hooks up the different light endpoints to the various clusters

 #### Problem
While there is currently basic UI to control lights, developer has to go in code to modify number of lights to be controlled. Only one light could be controlled regardless as as CHIPFramework had changed

 #### Summary of Changes
- Add UI to dynamically change how many lights user wants to control. This number of lights is persisted in defaults.
- Depending on how many endpoints/lights are requested, create different clusters pointing to correct endpoint.
- Tested for regressions

 Fixes #4566 

https://user-images.githubusercontent.com/61782012/106274901-4d069d80-6235-11eb-863b-bbcb91fe8189.mov
IMG_0840
IMG_0843
IMG_0841

### CODE REVIEW

**Comment by shana-apple** [comment]
Don't merge, although only UI change hookup to correct API, need to check for regressions when controlling endpoint 1.

**Review by woody-apple — APPROVED** [review]

**Comment by shana-apple** [comment]
Ready to merge!

**Comment by woody-apple** [comment]
@saurabhst @jelderton @andy31415 ?

**Review by saurabhst — APPROVED** [review]

**Comment by woody-apple** [comment]
@andy31415 ?

**Review by andy31415 — APPROVED** [review]

**Pull request merged**
