### PR TITLE
QR code TLV implementation

### PR DESCRIPTION
**Pull request by shana-apple**
#### Problem
Needed to implement the TLV portion of the QRCode. 

 #### Summary of Changes
QR code TLV implementation. This implementation does not expose that we are using Weave TLV but allows adopter to add string and integer optional info to the setup payload.

Also made all setup payload tests adopted nltest

fixes #315 
fixes #189

### CODE REVIEW

**Review by bhaskar-apple — DISMISSED** [review]

**Review by rwalker-apple — CHANGES_REQUESTED** [review]

**Review by rwalker-apple — CHANGES_REQUESTED** [review]

**Review by bhaskar-apple — COMMENTED** [review]
LGTM

**Review by rwalker-apple — APPROVED** [review]
lgtm with the issues filed

**Review by woody-apple — APPROVED** [review]
Looking good!

**Review by jelderton — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]
LGTM with the request to add an issue for memory leaks

**Pull request merged**
