### PR TITLE
Fix for issue #25538

### LINKED ISSUE #25538: [BUG] Writing more than 10 binding entries for binding attribute in binding cluster does not respond with status 0x89 (RESOURCE_EXHAUSTED)
### Reproduction steps

I executed

`./chip-tool binding write binding '[{"node" : 2 , "cluster" : "0x0006" , "endpoint" : 1 }, { "node" : 3 , "cluster" : "0x0006" , "endpoint" : 1 }, { "node" : 4 , "cluster" : "0x0006" , "endpoint" : 1 }, { "node" : 5 , "cluster" : "0x0006" , "endpoint" : 1 }, { "node" : 6 , "cluster" : "0x0006" , "endpoint" : 1 }, { "node" : 7 , "cluster" : "0x0006" , "endpoint" : 1 }, { "node" : 8 , "cluster" : "0x0006" , "endpoint" : 1 }, { "node" : 9 , "cluster" : "0x0006" , "endpoint" : 1 }, { "node" : 10 , "cluster" : "0x0006" , "endpoint" : 1 }, { "node" : 11 , "cluster" : "0x0006" , "endpoint" : 1 }, { "node" : 12 , "cluster" : "0x0006" , "endpoint" : 1 }, { "node" : 13 , "cluster" : "0x0006" , "endpoint" : 1 }]' 1 1`
I did not see a status of 0x89 (RESOURCE_EXHAUSTED). The command returned status 0x00 (SUCCESS). I tried to write 12 entries to binding.

 

Next, when I executed 

`./chip-tool binding read binding 1 1 `
The output had 10 entries which were the first 10 of 12 entries that I tried to write in the previous step. MATTER specification for binding (https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/data_model/Binding-Cluster.adoc) says If, during the creation of multiple bindings, there are no available resources to create an entry, or to establish a binding relationship, the client SHALL respond with a status of RESOURCE_EXHAUSTED, and the binding SHALL NOT be created.

Please see attached log for writing 12 binding entries for binding attribute. The log for following read operation on binding attribute is also attached.
[Log_Binding_Read.txt](https://github.com/project-chip/connectedhomeip/files/10913360/Log_Binding_Read.txt)
[Log_Binding_Write_12_entries.txt](https://github.com/project-chip/connectedhomeip/files/10913361/Log_Binding_Write_12_entries.txt)

### Bug prevalence

Whenever I do this

### GitHub hash of the SDK that was being used

4f53be4505d2ea81e7b3e5de62bee9c63c2f19e1

### Platform

all
### Platform Version(s)

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by HusseinElsherbini**
`Fixes #25538 `
modified functions associated with writing binding entries that weren't properly returning ERROR messages

### CODE REVIEW

**Comment by jmartinez-silabs** [comment]
This pr addresses the same issue. Was open a few hours before yours

https://github.com/project-chip/connectedhomeip/pull/25549

**Comment by HusseinElsherbini** [comment]
Issue already fixed

**Comment by HusseinElsherbini** [comment]
> 

Thanks for noting this.

**Comment by bzbarsky-apple** [comment]
@HusseinElsherbini for future reference, the changes here did return an error, but not the error the spec calls for...

**Comment by HusseinElsherbini** [comment]
@bzbarsky-apple thanks for the heads up, I did have one more commit to correct this behavior but its unnecessary now.

**Pull request closed without merging**
