### PR TITLE
[Telink] Add w91 dual core OTA, board versions & Update builds to docker version 81

### PR DESCRIPTION
**Pull request by interfer**
Changes

- w91 matter dual core OTA support:
  - DTS remove all partitions instead of one by one
  - Change N22 Image offset & size
  - OTA multi image in single slot
  - use correct sign key
  - add W91 continue-on-error CI jobs
  - add python script for process binaries
  - updated readme files
  - use merged.bin as final bin for flashing and matter.ota for OTA
- Update compatible builds to docker version 81 https://github.com/project-chip/connectedhomeip/pull/35827

- Added W91 board hardware configuration to have both old v1.0 and latest v2.1 (v2.1 builds for default `tlsr9118bdk40d` )
- Fixed status-led in Lighting app (caused by #35621 )
- Small side changes related to MbedTLS HW accelerated configs (part of https://github.com/telink-semi/zephyr/pull/351)

The diferrences mostly are in DeviceTree regarding LEDs, PWMs and Buttons.
Running `west build -b tlsr9118bdk40d` will build v2 config(latest). Also it's possible to build explicitly for v1 or v2 by using `tlsr9118bdk40d_v1` or `tlsr9118bdk40d` for developers' needs.

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
@interfer it seems Tlink builds need fixing

**Comment by interfer** [comment]
> @interfer it seems Tlink builds need fixing

@andy31415  Sure, thanks, we're waiting for changes in Zephyr to be merged to get the new Docker ready

**Comment by interfer** [comment]
Draft for now, DNM

**Comment by s07641069** [comment]
Docker (Zephyr Update) part PR: https://github.com/project-chip/connectedhomeip/pull/35827

**Comment by s07641069** [comment]
@interfer 
Added [Telink] w91 dual core OTA support changes https://github.com/s07641069/connectedhomeip/pull/344
PR title and description need to fix.
As well after creation of new docker image will add Update images commit (will disable update Zephyr to specific revision (for developers purpose)).

**Comment by s07641069** [comment]
@interfer please mark PR as ready for review

**Review by andy31415 — APPROVED** [review]

**Pull request merged**
