### PR TITLE
Build for Ubuntu using docker container

### PR DESCRIPTION
**Pull request by pan-apple**
- `docker_build.sh` builds all
- `docker_build.sh clean` build clean
- `docker_build.sh run_tests` builds and runs tests

Useful for people who are not using Ubuntu as native development environment.
Needs docker to be installed on the machine.

It can also be run from any folder in the workspace. e.g. from top level
`./tools/docker_build.sh`

### CODE REVIEW

**Review by BroderickCarlin — APPROVED** [review]

**Review by gerickson — CHANGES_REQUESTED** [review]
I'd like to push back on this. What does Docker buy us? Our experience is that we can build both openthread and openweave across both Mac OS X and Linux, across a variety of versions, without Docker. Docker certainly adds overhead and complexity and introduces "start-up" costs to those wanting to use and interact with the CHIP stack.

**Review by woody-apple — CHANGES_REQUESTED** [review]
Can we please update the readme in the tools directory, to explain how to install docker (links for all platforms), and what the tool does? It's important we document this.

**Review by woody-apple — APPROVED** [review]

**Review by BroderickCarlin — APPROVED** [review]

**Review by hawk248 — APPROVED** [review]
👍 I am not opposed to Docker as a way to build, test and speed up CI/CD.

**Review by gerickson — CHANGES_REQUESTED** [review]
Thanks for adding the README content. I'd like to propose the creation of a top-level "build/..." directory under which this "scripts/docker_build.sh" is created. If there will be multiple such scripts, I'd propose "scripts/docker/docker_build.sh".

**Review by gerickson — APPROVED** [review]

**Pull request merged**
