### PR TITLE
Android: use ENABLE_NOTIFICATION_VALUE instead of ENABLE_INDICATION_VALUE

### LINKED ISSUE #5593: Android CHIPTool uses invalid BLE CCCD descriptor value during "PROVISION CHIP DEVICE WITH WI-FI"
#### Problem
The CCCD value per CHIP Specification should be 0x01 (ENABLE_NOTIFICATION_VALUE), not 0x02 (ENABLE_INDICATION_VALUE)
 * Expected behavior: Complete the provision process
 * Actual behavior: Provision process aborts with writeDescriptor error code 0x6 (GATT_REQUEST_NOT_SUPPORTED)
 * Steps to reproduce: Select "PROVISION CHIP DEVICE WITH WI-F" and scan the QR code on the M5 Stack device running the all-clusters-app
 * Configuration: Android Samsung Galaxy S9+, M5 Stack running the all-clusters-app
 * screenshots, images, logs, etc.
 Android log:
```
2021-03-24 07:15:17.054 14662-21648/com.google.chip.chiptool D/chip.BluetoothManager: null.onCharacteristicWrite: 18ee2ef5-263d-4559-959f-4f9c429f9d11 -> 0
2021-03-24 07:15:17.054 14662-21648/com.google.chip.chiptool D/CTL: Received SubscribeCharacteristic
2021-03-24 07:15:17.054 14662-21648/com.google.chip.chiptool D/CTL: Calling Java SubscribeCharacteristic
2021-03-24 07:15:17.055 14662-21648/com.google.chip.chiptool D/BluetoothGatt: setCharacteristicNotification() - uuid: 18ee2ef5-263d-4559-959f-4f9c429f9d12 enable: true
2021-03-24 07:15:17.082 14662-21648/com.google.chip.chiptool D/BluetoothGatt: onConnectionUpdated() - Device=B8:F0:09:C4:99:AE interval=39 latency=0 timeout=500 status=0
2021-03-24 07:15:17.141 14662-21648/com.google.chip.chiptool D/chip.BluetoothManager: null.onDescriptorWrite: 00002902-0000-1000-8000-00805f9b34fb -> 6
2021-03-24 07:15:17.142 14662-21648/com.google.chip.chiptool E/AndroidChipStack: onDescriptorWrite for 00002902-0000-1000-8000-00805f9b34fb failed with status: 6
```

M5 Stack Log:
```
GAP procedure initiated: advertise; disc_mode=2 adv_channel_map=0 own_addr_type=0 adv_filter_policy=0 adv_itvl_min=3200 adv_itvl_max=3200
I (104518) CHIP[DL]: Write request received for CHIPoBLE RX characteristic con 0 12
I (104528) chip[BLE]: local and remote recv window sizes = 3
I (104528) chip[BLE]: selected BTP version 3
I (104528) chip[BLE]: using BTP fragment sizes rx 128 / tx 20.
E (119538) chip[BLE]: receive handshake timed out, closing ep 0x3ffcd5e8
I (119538) chip[BLE]: Releasing end point's BLE connection back to application.
I (120758) chip[DL]: BLE GAP connection terminated (con 29948
```

 #### Proposed Solution
```
diff --git a/src/controller/java/src/chip/devicecontroller/AndroidChipStack.java b/src/controller/java/src/chip/devicecontroller/AndroidChipStack.java
index fd2f0390b..f751c9d2c 100644
--- a/src/controller/java/src/chip/devicecontroller/AndroidChipStack.java
+++ b/src/controller/java/src/chip/devicecontroller/AndroidChipStack.java
@@ -162,7 +162,7 @@ public final class AndroidChipStack {
               return;
             }

-            if (desc.getValue() == BluetoothGattDescriptor.ENABLE_INDICATION_VALUE) {
+            if (desc.getValue() == BluetoothGattDescriptor.ENABLE_NOTIFICATION_VALUE) {
               handleSubscribeComplete(
                   connId, svcIdBytes, charIdBytes, status == BluetoothGatt.GATT_SUCCESS);
             } else if (desc.getValue() == BluetoothGattDescriptor.DISABLE_NOTIFICATION_VALUE) {
@@ -302,7 +302,7 @@ public final class AndroidChipStack {

     BluetoothGattDescriptor descriptor =
         subscribeChar.getDescriptor(UUID.fromString(CLIENT_CHARACTERISTIC_CONFIG));
-    descriptor.setValue(BluetoothGattDescriptor.ENABLE_INDICATION_VALUE);
+    descriptor.setValue(BluetoothGattDescriptor.ENABLE_NOTIFICATION_VALUE);
     if (!bluetoothGatt.writeDescriptor(descriptor)) {
       Log.e(TAG, "writeDescriptor failed");
       return false;
```

### PR DESCRIPTION
**Pull request by robertfarnum**
#### Problem
Apply patch from Issue #5593 to resolve provisioning a chip device for WIFI over Bluetooth from the Android CHIPTool

 #### Summary of Changes
 Applied patch from Issue #5593

 Fixes #5593

### CODE REVIEW

**Comment by wissn84** [comment]
Could you merge this PR?
After applying this PR, it is working well between Android and M5Stack.

**Comment by robertfarnum** [comment]
This PR is currently being blocked due to the pullapprove and restyled status checks and appears to be restricted to authorized users.  Until someone with permissions is able to resolve these issues I am unable to merge this PR>

**Comment by andy31415** [comment]
please run `./scripts/helpers/restyle-diff.sh` to apply restyle fixes locally.

It looks like it only wants to add a terminating newline to AndroidChipStack.java  (not your code, but apparently our restyler is stricter now)

**Review by andy31415 — APPROVED** [review]

**Review by jelderton — APPROVED** [review]

**Comment by robertfarnum** [comment]
Restyle status check now passes, but Cirque has failed after restyle resolution.

**Review by jmartinez-silabs — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Review by saurabhst — APPROVED** [review]

**Pull request merged**
