### PR TITLE
Revert "add CLI tab-to-autocomplete ability and implement for nrfconnect"

### PR DESCRIPTION
**Pull request by woody-apple**
Reverts project-chip/connectedhomeip#13630

This causes a build failure here:
https://github.com/project-chip/connectedhomeip/runs/4962987772?check_suite_focus=true

@lmpprk as an FYI

### CODE REVIEW

**Comment by lmpprk** [comment]
thanks! it was a race between PRs, I can fix this quickly by pushing a change if that works better?

**Comment by woody-apple** [comment]
@lmpprk Sorry for the confusion, I do need to get the tree running, but if you put up a PR, with the fix from trunk, I can prioritize it coming in!

**Comment by woody-apple** [comment]
@lmpprk I will be online for the next hour, otherwise I can pick this up tomorrow AM! (FYI)

**Comment by lmpprk** [comment]
thanks no worries, mine can wait :) I'll sync and send it later. Thank you for the help in resolving!

**Pull request merged**
