### PR TITLE
Added updated Testscripts

### PR DESCRIPTION
**Pull request by kowsisoundhar12**
[Uploading execution-logs-feb24.zip…]()
Updated Scripts :
	Test_TC_BOOL_1_1.yaml
	Test_TC_BOOL_2_1.yaml
	Test_TC_BRAC_1_1.yaml
	Test_TC_ILL_1_1.yaml
	Test_TC_LVL_1_1.yaml
	Test_TC_LVL_2_1.yaml
	Test_TC_LVL_3_1.yaml
	Test_TC_LVL_4_1.yaml
	Test_TC_LVL_5_1.yaml
	Test_TC_LVL_6_1.yaml
	Test_TC_MC_3_11.yaml
	Test_TC_MC_3_7.yaml
	Test_TC_MC_9_1.yaml
	Test_TC_OCC_2_1.yaml
	Test_TC_OCC_2_2.yaml
	Test_TC_OO_2_1.yaml
	Test_TC_PCC_1_1.yaml
	Test_TC_PCC_2_1.yaml
	Test_TC_PRS_2_1.yaml
	Test_TC_PS_1_1.yaml
	Test_TC_RH_1_1.yaml
	Test_TC_RH_2_1.yaml
	Test_TC_RH_2_2.yaml
	Test_TC_TM_1_1.yaml
	Test_TC_TM_2_2.yaml
	Test_TC_TSTAT_1_1.yaml
	Test_TC_TSTAT_2_1.yaml
	Test_TC_TSUIC_1_1.yaml
	Test_TC_TSUIC_2_1.yaml
	Test_TC_TSUIC_2_2.yaml
	Test_TC_WIFIDIAG_1_1.yaml

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]
Fast tracking testing updates

**Comment by kowsisoundhar12** [comment]
opening new PR for this testscripts

**Comment by manjunathambiger23** [comment]
Opened new PR : https://github.com/project-chip/connectedhomeip/pull/16164

**Pull request closed without merging**
