### PR TITLE
[Infineon] Update PSoC6 assets to latest release

### PR DESCRIPTION
**Pull request by praveenCY**
This PR 
1. Updates Infineon PSOC6 assets to latest release tags 
2. Rename P6 to PSOC6 for better readability
3. Refined OTA functionality with new Infineon Assets like ota-update
4. Removed unused libraries
5. Add some dependent files needed for Infineon PSOC6 BSP
6. Flashing scripts are updated to use openocd directly

Testing 
Manually tested all the example apps supported by Infineon PSOC6

### CODE REVIEW

**Comment by kiel-apple** [comment]
this PR will need to be re-opened with the `changing-submodules-on-purpose` label - if you can't add the label, let me know and I'll be happy to add it for you :)

**Comment by praveenCY** [comment]
> this PR will need to be re-opened with the `changing-submodules-on-purpose` label - if you can't add the label, let me know and I'll be happy to add it for you :)
@kiel-apple  can you please add the label as i don't have permission for the same.

**Review by andy31415 — APPROVED** [review]
Approving as platform-specific changes. I did not actually review (this is a 15K lines added and almost 10k lines removed ... this is not reviewable in practice)

**Review by kiel-apple — APPROVED** [review]
also rubber-stamping the platform-specific changes by platform owner

**Pull request merged**
