### PR TITLE
[K32W0] SDK 2.6.13 changes

### PR DESCRIPTION
**Pull request by marius-alex-tache**
Changelog:

- Add support for OTA encryption.
- Add support for simple hash verification, a less secure alternative to secure boot.
- Add support for SSBL versioning. Version can be accessed and logged at application level.
- Add mechanism for exposing BLE events to the application.
- Add support for ICD for contact sensor reference app.
- Update factory data generator script.
- Fix an AES related bug during OTA.
- Other fixes and README updates.

Signed-off-by: Axel Le Bourhis [axel.lebourhis@nxp.com](mailto:axel.lebourhis@nxp.com)
Signed-off-by: Ethan Tan [ethan.tan@nxp.com](mailto:ethan.tan@nxp.com)
Signed-off-by: marius-alex-tache [marius.tache@nxp.com](mailto:marius.tache@nxp.com)

### CODE REVIEW

**Comment by marius-alex-tache** [comment]
How do I update the stage 2 docker image if it references an SDK stored on github, e.g. it clones a repo on a specific branch. The branch was updated to latest SDK version, but there are no changes required in the Dockerfile, since the branch name is the same. Do I have to rebuild the image and push it manually? I'm not sure I understand at what point the image is pushed in the images hub. @bzbarsky-apple, @andy31415, could you please help if you have any advice?

**Comment by andy31415** [comment]
> How do I update the stage 2 docker image if it references an SDK stored on github, e.g. it clones a repo on a specific branch. The branch was updated to latest SDK version, but there are no changes required in the Dockerfile, since the branch name is the same. Do I have to rebuild the image and push it manually? I'm not sure I understand at what point the image is pushed in the images hub. @bzbarsky-apple, @andy31415, could you please help if you have any advice?

@marius-alex-tache 
Using a branch name was a mistake because this makes docker builds non-reproducible. You are seeing the results now.

Please create a new PR where even if you check the branch name you are forcing a specific SHA. Docker files should not select a moving target if the actual moving target matters: selecting "latest version of wget" for example is ok, but "checkout SDK from a branch" is not.

**Comment by marius-alex-tache** [comment]
Thank you! That makes sense. I will try to create the PR.

**Comment by marius-alex-tache** [comment]
https://github.com/project-chip/connectedhomeip/pull/30820

**Review by andy31415 — APPROVED** [review]

**Pull request merged**
