### PR TITLE
ESP32: Optimize the temperature-measurement-app to use less RAM and Flash.

### LINKED ISSUE #3977: ESP32: Optimize the temperature-measurement-app to use less RAM and Flash
#### Problem
Need to optimize the temperature-measurement-app to use less RAM and Flash

 #### Proposed Solution
Add optimization in the sdkconfig related to: code size, Wi-Fi and lwIP configuration options, minimal logging, BLE maximum connections  etc.

### PR DESCRIPTION
**Pull request by sweetymhaiske**
#### Problem
 Need to optimize the temperature-measurement-app to use less RAM and Flash.

 #### Summary of Changes
 a) Added the optimization in the sdkconfig for 
     1. Wi-Fi and BLE
     2. Disable asserts. 
     3. FreeRTOS unicore mode
     
  Footprint values are as below
  
**Default without optimization**
 ```
  1 Total sizes:
  2  DRAM .data size:   16200 bytes
  3  DRAM .bss  size:   35736 bytes
  4 Used static DRAM:   51936 bytes (  72644 available, 41.7% used)
  5 Used static IRAM:  116428 bytes (  14644 available, 88.8% used)
  6       Flash code:  643146 bytes
  7     Flash rodata:  127888 bytes
  8 Total image size:~ 939398 bytes (.bin may be padded larger)
```
   Free Heap :- **169012** bytes

**Optimization with new sdkconfig.defaults**
It includes:-
1. Bluetooth/NimBLE
2. Compiler size optimization
3. FreeRTOS Unicore
4. WiFi
```
  1 Total sizes:
  2  DRAM .data size:   14120 bytes
  3  DRAM .bss  size:   35120 bytes
  4 Used static DRAM:   49240 bytes (  75340 available, 39.5% used)
  5 Used static IRAM:  113108 bytes (  17964 available, 86.3% used)
  6       Flash code:  639259 bytes
  7     Flash rodata:  125876 bytes
  8 Total image size:~ 927483 bytes (.bin may be padded larger)
```
   Free Heap: **196004** bytes

**Optimization with 'is_debug = false'**
It includes the above optimization along with the following
1. Asserts
2. Log disable
  ```
  1 Total sizes:
  2  DRAM .data size:   13392 bytes
  3  DRAM .bss  size:   35104 bytes
  4 Used static DRAM:   48496 bytes (  76084 available, 38.9% used)
  5 Used static IRAM:  111064 bytes (  20008 available, 84.7% used)
  6       Flash code:  620159 bytes
  7     Flash rodata:   84148 bytes
  8 Total image size:~ 863867 bytes (.bin may be padded larger)
  ```
   Free Heap :- **196748** bytes

 b) Chose NimBLE as a default BT host for CI sdkconfig.

 Fixes #3977

### CODE REVIEW

**Comment by dhrishi** [comment]
LGTM

**Review by mspang — CHANGES_REQUESTED** [review]
Please don't disable assertions for CHIP developers. We should separate optimized, release appropriate setting from those suitable for development.

**Comment by dhrishi** [comment]
>Please don't disable assertions for CHIP developers. We should separate optimized, release appropriate setting from those suitable for development.

Hi @mspang I thought of demonstrating all possible optimizations in the `temperature-measurement-app` so that we have a footprint constrained configuration ready. Although, I totally agree with your point. Will it be okay if we add an application specific config option, say release mode (disabled by default) and when enabled, it disables asserts and logs. The other optimized configuration options stay in the sdkconfig.defaults as done in the PR.

**Comment by mspang** [comment]
> > Please don't disable assertions for CHIP developers. We should separate optimized, release appropriate setting from those suitable for development.
> 
> Hi @mspang I thought of demonstrating all possible optimizations in the `temperature-measurement-app` so that we have a footprint constrained configuration ready. Although, I totally agree with your point. Will it be okay if we add an application specific config option, say release mode (disabled by default) and when enabled, it disables asserts and logs. The other optimized configuration options stay in the sdkconfig.defaults as done in the PR.

We have such a setting for other apps, it's called "is_debug". ESP32 should have similar.

Debug should be the default.

**Review by msandstedt — APPROVED** [review]

**Comment by sweetymhaiske** [comment]
Hi @mspang, PR is ready as per the changes mentioned.

**Comment by dhrishi** [comment]
Can the relevant folks please take a look and merge if it looks okay. Thanks!

**Review by mspang — APPROVED** [review]

**Review by jelderton — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]

**Pull request merged**
