### PR TITLE
Remove EmberAfProfileId and its dependencies

### LINKED ISSUE #3444: We should probably get rid of EmberAfProfileId
#### Problem
I don't think we're going to have profiles in the APS sense in CHIP.  We should remove code references to the profile

 #### Proposed Solution
Remove the `EmberAfProfileId` type and the `profileId` member of EmberApsFrame, then fix anything that doesn't compile as a result.

@rwalker-apple

### PR DESCRIPTION
**Pull request by vivien-apple**
#### Problem
  EmberAfProfileId will likely not be used.

I also removes methods that use the profile id and are related to security. My understanding so far is that all messages will be encrypted anyway...

 #### Summary of Changes
 * Remove references to emberAfProfileId
 * Remove methods that use the profile and are related to security. 

Fixes #3444

### CODE REVIEW

**Comment by jepenven-silabs** [comment]
This work should be done directly inside the ZAP tool since content of the /gen/ folder can changes when user generate a new config

**Comment by vivien-apple** [comment]
> This work should be done directly inside the ZAP tool since content of the /gen/ folder can changes when user generate a new config

Makes sense for the parts in `*/gen/callback-stubs.c` but the bits on `src/app/util/*` are not part of ZAP or did I missed something ?

**Comment by jepenven-silabs** [comment]
> > This work should be done directly inside the ZAP tool since content of the /gen/ folder can changes when user generate a new config
> 
> Makes sense for the parts in `*/gen/callback-stubs.c` but the bits on `src/app/util/*` are not part of ZAP or did I missed something ?

Yeah my comment was mostly about the part in /gen/. On another note, seems like we might overlap in our work, I'll have a PR up in a few hours for the ZAP integration. I'll tag you in so you can have a look.

**Review by andy31415 — APPROVED** [review]

**Review by rwalker-apple — APPROVED** [review]

**Review by saurabhst — APPROVED** [review]

**Review by BroderickCarlin — APPROVED** [review]

**Comment by vivien-apple** [comment]
I will wait for #3464 to land first and update the given `.zapt` files there for the `gen/*` changes.

**Review by jelderton — APPROVED** [review]

**Review by mspang — APPROVED** [review]

**Comment by vivien-apple** [comment]
I finally rebased this PR. Should be ready to land.

**Pull request merged**
