### PR TITLE
[OpenThread][LWIP] Remove OT ICMP6 set echo mode call to disabled as …

### PR DESCRIPTION
**Pull request by mihai-ignat**
…this setting configures the OT ICMP module to not respond to specific Thread multicast addresses

Fixes #30122 

Removing the otIcmp6SetEchoMode lets the OT ICMP6 module to respond to Thread Multicast Addresses.
This issue was observed during OT certification using a Matter application with OT CLI enabled.

### CODE REVIEW

**Comment by mihai-ignat** [comment]
Hello, @bukepo.
I traced the change to a commit that you did in 2020. Can you please comment on the issue?
BR,
Mihai

**Comment by bukepo** [comment]
> Hello, @bukepo. I traced the change to a commit that you did in 2020. Can you please comment on the issue? BR, Mihai

Hi @mihai-ignat the multicast forwarding rule was changed by https://github.com/openthread/openthread/pull/5852 after the https://github.com/project-chip/connectedhomeip/commit/4b97e1b5f6ac2be331a2cf4c6dec1d3c1f12d078. 

I think we should fix this issue in OpenThread, because we do expect link-local multicast traffic being passed to host sooner or later, thoughts? @jwhui

**Comment by bukepo** [comment]
Sent https://github.com/openthread/openthread/pull/9817 to discuss the proposed fix in OpenThread.

**Comment by jwhui** [comment]
> I think we should fix this issue in OpenThread, because we do expect link-local multicast traffic being passed to host sooner or later, thoughts? @jwhui

Yes, we should allow link-local traffic to pass to host.

**Comment by mihai-ignat** [comment]
@bukepo @jwhui, as a temporary workaround, do you think the fix in this PR is fine? This is until we can get your OT stack fix.

**Comment by bukepo** [comment]
@mihai-ignat We have merged a change to forward multicast packets to host. Could you try the latest OpenThread?

**Comment by mihai-ignat** [comment]
Hello, @bukepo . I tried applying the fix as a patch to an older stack version from July 2023, which was used to do the actual certification for the product and it didn't work. I will see how to accommodate the newer stack on our Matter codebase and retest. Do you have any validation results on your side? Thanks.

**Comment by marius-preda** [comment]
Hi @bukepo, and @jwhui, the fix made in the OT stack to allow all multicast traffic to pass to the host doesn't solve the issue reported by @mihai-ignat without registering the Thread multicast addresses on the host side. This should include all Thread specific multicast addresses, but in my view, this isn't something we should do in Matter. All the multicast addresses are already registered in the Thread stack and I don't see a reason why this traffic should go to the host. 

The original question from this PR was why in the Matter LWIP Thread IP interface `otIcmp6SetEchoMode(Impl()->OTInstance(), OT_ICMP6_ECHO_HANDLER_DISABLED)` was used to disable ICMP echo in the Thread stack. I assume it was to prevent double replies from the OT and LWIP stacks for the same Echo request. In the case of multicast, it's not an issue since nobody is registering the OT multicast addresses on the LWIP side. We could change the setting and allow only multicast pings in the OT stack replacing  `OT_ICMP6_ECHO_HANDLER_DISABLED` with `OT_ICMP6_ECHO_HANDLER_MULTICAST_ONLY`.

Can you clarify how you see this working in a system where there are 2 IP stacks, OT and another host IP layer like LWIP, and the application (Matter for example) is using the host sockets to transmit/receive data?

**Comment by bukepo** [comment]
I think we should keep IPv6 addresses including multicast addresses identical on the Thread network interfaces on both host(lwIP) IP stack and OpenThread IP stack. This is to make sure that an app developed on host stack can get IPv6 packets received and transmitted via Thread network interface just like a normal IPv6 node in the network. We do this on POSIX platforms.

**Comment by marius-preda** [comment]
> I think we should keep IPv6 addresses including multicast addresses identical on the Thread network interfaces on both host(lwIP) IP stack and OpenThread IP stack. This is to make sure that an app developed on host stack can get IPv6 packets received and transmitted via Thread network interface just like a normal IPv6 node in the network. We do this on POSIX platforms.

OK, thx for the answer.

**Comment by mihai-ignat** [comment]
> I think we should keep IPv6 addresses including multicast addresses identical on the Thread network interfaces on both host(lwIP) IP stack and OpenThread IP stack. This is to make sure that an app developed on host stack can get IPv6 packets received and transmitted via Thread network interface just like a normal IPv6 node in the network. We do this on POSIX platforms.

Hello, @bukepo, can you please provide reference to POSIX implementation?
Thanks.

**Comment by bukepo** [comment]
You can find it here: https://github.com/openthread/openthread/blob/main/src/posix/platform/netif.cpp

**Comment by andy31415** [comment]
This PR has no reviews since >6 months. Closing as stale.

**Pull request closed without merging**
