### PR TITLE
Add endpoint 0 on the all-clusters-app

### PR DESCRIPTION
**Pull request by vivien-apple**
#### Problem

 The `all-clusters-app` endpoints count currently starts from `1`. This PR add a endpoint `0` and
 activate some clusters on it:
  * Basic
  * Descriptor
  * General Commissioning
  * Binding
  * Group Key Management
  * Network Commissioning

 The main reason to do it is because the `Descriptor` cluster for endpoint `0` as a special
 behavior, where it list all the endpoints on the node.

 #### Summary of changes
 * Add endpoint `O` to `all-clusters-app.zap`
 * Activate required clusters on it
 * Deactivate some clusters on other endpoints since they are now turned on on the endpoint `0`
 * Regen the `gen/` folder

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]

**Review by saurabhst — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
@vivien-apple conflict here.

@saurabhst @msandstedt ?

**Review by msandstedt — APPROVED** [review]

**Comment by vivien-apple** [comment]
Snif. CI is broken because someone has again forgotten to land some changes generated from the templates. I really need to finish #5459.

**Review by yufengwangca — APPROVED** [review]

**Comment by yufengwangca** [comment]
@vivien-apple please fix the style issue

**Comment by vivien-apple** [comment]
> @vivien-apple please fix the style issue

@yufengwangca I'm not sure what to do here. I have already force-pushed twice to trigger the restyler but it seems to not run. That's strange since it seems to be the same issue with https://github.com/project-chip/connectedhomeip/pull/6059

**Comment by yufengwangca** [comment]
@vivien-apple removed restyled-ignore tag, could you rebase your branch to the tot of master and do another force push?

**Pull request merged**
