### PR TITLE
TV app, prepare Endpoint 0 as root node device type 

### PR DESCRIPTION
**Pull request by lazarkov**
#### Problem
TV example app clusters at endpoint 0 are not prepared for root node device type

#### Change overview
- Copied endpoint 0 from all-tv-clusters.zap json from  and replaced endpoint 0 of tv.zap json
- Created generated files by running zap_regen_all.py
- Updated failiure logs to use `ChipLogError`

#### Testing
How was this tested? (at least one bullet point required)
- Used the `./gn_build.sh` to verify the building is successful
- Run tv example app locally on Mac OS
` ./out/debug/chip-tv-app `
- Sent pairing command from chip tool to tv example app and got success response
`./out/debug/standalone/chip-tool pairing onnetwork  0 20202021 3840 ::1 11097`
- Sent get tv channel list command from chip-tool to tv example app and got tv channel list
`./out/debug/standalone/chip-tool tvchannel read tv-channel-list 0`
- Sent read command for mac address of WakeOnLan cluster to tv example app and got success response `./out/debug/standalone/chip-tool wakeonlan read wake-on-lan-mac-address 1`
- Sent. read command for vendor name of ApplicationBasic cluster to tv example app and got success response
`./out/debug/standalone/chip-tool applicationbasic read vendor-name 4`

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]

**Review by chrisdecenzo — APPROVED** [review]

**Comment by lazarkov** [comment]
Fixed the conflicts.

**Comment by lazarkov** [comment]
rebased

**Comment by lazarkov** [comment]
Fixed the conflicts.

**Review by saurabhst — APPROVED** [review]

**Pull request merged**
