### PR TITLE
[android] Read NFC tag containing CHIP setup payload

### LINKED ISSUE #3600: [Android package] Add support for reading NFC tag containing CHIP setup payload
#### Problem
Currently, a device may share its Setup/Onboarding Payload with CHIP Controller using QR Code or Manual Pairing Code. Devices which don't have a display would benefit from another way to send the Setup Payload, that is, via NFC Tag.
Note that usage of NFC in CHIP is not yet confirmed, so the feature should be considered experimental.

 #### Proposed Solution
* Make CHIPTool for Android read NFC Tags containing a NDEF record of type "URI" with scheme "ch:"
* Interpret the URI record as CHIP QR Code Payload

### PR DESCRIPTION
**Pull request by Damian-Nordic**
#### Problem
Currently, a device may share its Setup/Onboarding Payload with CHIP Controller using QR Code or Manual Pairing Code. Devices which don't have a display would benefit from another way to send the Setup Payload, that is, via NFC Tag.
Note that usage of NFC in CHIP is not yet confirmed, so the feature should be considered experimental.

 #### Summary of Changes
* Make CHIPTool for Android read NFC Tags containing a NDEF record of type "URI" with scheme "ch:"
* Interpret the URI record as CHIP QR Code Payload
* Switch to Device Details screen to present decoded information

Note: Currently the app assumes the URI record contains QR Code Payload which technically isn't a valid URI since it may contain a space character. It works correctly on Android despite of that flaw, but it will need to be discussed during spec work.

 Fixes #3600

### CODE REVIEW

**Comment by mspang** [comment]
Is adding experimental features desirable at this stage of development?

**Comment by Damian-Nordic** [comment]
> Is adding experimental features desirable at this stage of the project?

Isn't it? I mean, there's a PR adding corresponding requirements to the CHIP spec, so this change isn't completely groundless, but the details haven't been decided yet. I thought we still follow the "code first" principle, but let me know if the approach has changed :).

**Comment by LuDuda** [comment]
@mspang [here](https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/313) is the spec PR that adds optional support for NFC. The firmware side is just about to be published as well.

I think that support for NFC is well separated from other core functionalities and adding it should not bring much of a risk.

**Review by andy31415 — APPROVED** [review]

**Review by jelderton — APPROVED** [review]

**Comment by mspang** [comment]
> > Is adding experimental features desirable at this stage of the project?
> 
> Isn't it? I mean, there's a PR adding corresponding requirements to the CHIP spec, so this change isn't completely groundless, but the details haven't been decided yet. I thought we still follow the "code first" principle, but let me know if the approach has changed :).

If it's on its way to landing in the spec, this is fine, I just misunderstood your note.

**Review by mspang — APPROVED** [review]

**Review by rwalker-apple — APPROVED** [review]

**Pull request merged**
