### PR TITLE
Add attestation app communcation layer

### PR DESCRIPTION
**Pull request by jlportillo**
#### Problem
For security, during setup of an IoT device running CHIP, the operational credentials generated by the device must be attested and validated by an ecosystem before allowing apps to send or receive information from the device.

#### Summary of Changes
Adds basic communication layer to external attestation apps
Queries for all apps which have an activity with the action "chip.intent.action.ATTESTATION"
Currently randomly chooses an app but will show an app picker in the future
Full API still WIP

### CODE REVIEW

**Comment by andy31415** [comment]
Could you add some details about what the external app is?

Either as PR description or some readme in the source.

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
Some description on who provides chip.intent.action.ATTESTATION and how and if there are some restrictions that are needed (what if I install several apps that can handle this intent ... is this even possible?)

**Review by bzbarsky-apple — APPROVED** [review]

**Review by vidhis88 — APPROVED** [review]

**Comment by rwalker-apple** [comment]
> Adds communication to external attestation app via startActivityForResult

@jlportillo: would you mind using the PR template to describe what's here?

**Review by BroderickCarlin — APPROVED** [review]

**Comment by jlportillo** [comment]
Updated the PR description with more details. Once the full API is defined I will add details/instructions to the README as well

**Pull request merged**
