### PR TITLE
Adjust priority of Shutdown event in basic cluster

### PR DESCRIPTION
**Pull request by yufengwangca**
#### Problem
What is being fixed?  Examples:
* Currently, the Shutdown event always get lost and never get a chance to be sent out to subscribers.
* The priority of ShutDown event should be adjusted to CRITICAL as Startup event, since this is the event get logged right before the device shutdown, if we don't mark it as CRITICAL, it will not get sent out immediately as Urgent, and it will get lost during shut down since the event circular buffer is not in persistent memory.

#### Change overview
Adjust priority of Shutdown event in basic cluster

#### Testing
How was this tested? (at least one bullet point required)
* Confirm the Shutdown event is logged as Urgent event from log.

### CODE REVIEW

**Review by yunhanw-google — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]
This does not seem like the right fix.  The right fix would be to flush out the event buffer on shutdown, no?  Probably right after queuing the shutdown event....

That said, if that buffer does not fit in a single message we could still have a problem.  So maybe we do need to make this event critical... but in that case that needs to be raised as a spec level issue (possibly in parallel with the code change).

**Comment by yufengwangca** [comment]
> This does not seem like the right fix. The right fix would be to flush out the event buffer on shutdown, no? Probably right after queuing the shutdown event....
> 
> That said, if that buffer does not fit in a single message we could still have a problem. So maybe we do need to make this event critical... but in that case that needs to be raised as a spec level issue (possibly in parallel with the code change).

We don't flush the event buffer on shutdown, only critical event get sent immediately, other event will be sent when we reach next reporting interval.
  
I already put a PR in spec side before this PR.
https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/4787

**Comment by bzbarsky-apple** [comment]
> We don't flush the event buffer on shutdown

I know we _don't_.  I am saying we _should_, best-effort.  That's in addition to changing the event priority here.

**Review by bzbarsky-apple — APPROVED** [review]
Approving given spec change PR, which should have been mentioned in this one.  But please file a followup to best-effort flush events at shutdown, because that's the right thing to do.

**Comment by yufengwangca** [comment]
> flush out the event buffer on shutdown,

Acked. https://github.com/project-chip/connectedhomeip/issues/13008

**Pull request merged**
