### PR TITLE
Remove FabricStorage

### PR DESCRIPTION
**Pull request by kghost**
#### Problem
`FabricStorage` is basically same as `PersistentStorageDelegate`

#### Change overview
Remove `FabricStorage` and all its related classes and funtions.

The `FabricStorage` usage inside `FabricTable` is replaced by a `PersistentStorageDelegate`

#### Testing
Passed unit-tests

### CODE REVIEW

**Comment by woody-apple** [comment]
@sagar-apple @bzbarsky-apple ?

**Review by bzbarsky-apple — APPROVED** [review]
I have some other changes to this stuff to make it not store a single blob and use the key allocator, etc, but this is a great start, thank you!

**Comment by bzbarsky-apple** [comment]
@woody-apple I did check with @sagar-apple and we agree that this is actually moving us in the direction we want to go anyway.

**Review by Damian-Nordic — APPROVED** [review]

**Review by msandstedt — APPROVED** [review]

**Comment by andy31415** [comment]
@kghost needs merging with master and this seems to fail cirque test consistently.

**Review by tcarmelveilleux — APPROVED** [review]

**Comment by kghost** [comment]
Thanks for help me fixing the error. I should be more careful to avoid mistake like this.

**Pull request merged**
