### PR TITLE
[docs] Add initial quick start guide pointing to nested example docs.

### PR DESCRIPTION
**Pull request by turon**
#### Problem
The top-level documentation does not easily steer new developers to the proper nested documentation to pull together a tangible demo of CHIP running on actual dev boards.

 #### Summary of Changes
Offer an initial cut at a Quick Start guide to provide an overview of the various Example apps and how to tie them together into a simple topology and working system by providing pointers and references to details for the various platform instances.

### CODE REVIEW

**Comment by woody-apple** [comment]
@turon Thanks for the docs update! Can you click through and sign the CLA? :)

**Review by woody-apple — APPROVED** [review]
@turon

**Comment by woody-apple** [comment]
@turon Note, doxygen error here

**Review by jelderton — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Comment by turon** [comment]
> @turon Note, doxygen error here

Are such unresolved reference issues common when adding a new file to docs?

I've added `docs/QUICK_START.md` and reference it exactly as `./BUILDING.md`, `./VSCODE_DEVELOPMENT.md`, and others are referenced in the same file.  Do I need to split this into two PRs or commits, one that adds the file and another that references it?

RE:
```
/home/runner/work/connectedhomeip/connectedhomeip/docs/README.md:14: error: unable to resolve reference to './QUICK_START.md' for \ref command (warning treated as error, aborting now)
```

**Comment by woody-apple** [comment]
@turon note: the style differences are here: https://github.com/project-chip/connectedhomeip/pull/6885/commits/1c7af401ca7ca5d6233b169f84d5ef89efe1e384

Your doxygen error is here: https://github.com/project-chip/connectedhomeip/actions/runs/850524441

I'll push the re-style for you.

**Comment by woody-apple** [comment]
@turn Restyle pushed, note the instructions to do so are here: https://github.com/project-chip/connectedhomeip/pull/6885

**Comment by woody-apple** [comment]
@turon To your question above (sorry), I would say adding the new thing at the same time as part of this PR, otherwise Doxygen will fail.

**Comment by woody-apple** [comment]
Looks like another commit came in, now need to wait on restyle to check again.

**Review by jmartinez-silabs — APPROVED** [review]

**Review by saurabhst — APPROVED** [review]

**Comment by turon** [comment]
> @turon To your question above (sorry), I would say adding the new thing at the same time as part of this PR, otherwise Doxygen will fail.

The failure occurs whether or not I post one commit (reference to new file in same commit) or two (reference to new file separate).  I'm trying removing the reference to the new file altogether to see if that passes CI.

**Pull request merged**
