### PR TITLE
RFC: Deprecate make for ESP in favor of cmake

### PR DESCRIPTION
**Pull request by rgoliver**
#### Problem
Currently many esp examples have build files for both make and cmake. The readme files all give directions for building with cmake but the presubmit checks all test make. This can lead to builds being broken if the build files are not kept in sync.

 #### Summary of Changes
This CL attempts to move towards having just cmake.

Looking for feedback from espressif if this is all that's needed or if there are other items I'm unaware of.

### CODE REVIEW

**Review by Damian-Nordic — APPROVED** [review]

**Comment by andy31415** [comment]
Please also add a part of 'how this was tested' to the PR summary.

**Comment by dhrishi** [comment]
@rgoliver  Thanks for the PR. Few generic suggestions:
1. idf.sh files from all the ESP32 examples should be removed.
2. Documentation of ESP32 examples should be revisited to see if there's any mention of automake commands "idf make " etc.
3. The CI seems to fail (error - idf.py command not found) because now we need to use `. ./export.sh` along with `./install.sh` from ESP-IDF.
I really appreciate all your help. If these things would be a bit too much, then @sweetymhaiske  can work on a PR and bring this to completion. I had already created an issue for this #6850 after our discussion and she was going to take up this today.

**Comment by rgoliver** [comment]
> @rgoliver Thanks for the PR. Few generic suggestions:
> 
> 1. idf.sh files from all the ESP32 examples should be removed.
> 2. Documentation of ESP32 examples should be revisited to see if there's any mention of automake commands "idf make " etc.
> 3. The CI seems to fail (error - idf.py command not found) because now we need to use `. ./export.sh` along with `./install.sh` from ESP-IDF.
>    I really appreciate all your help. If these things would be a bit too much, then @sweetymhaiske  can work on a PR and bring this to completion. I had already created an issue for this #6850 after our discussion and she was going to take up this today.

Thanks for the feedback, sure that would be great if @sweetymhaiske can finish this up! Once this is in, I'll create a PR to compile the pigweed RPCs.

**Comment by dhrishi** [comment]
That works. Thanks @rgoliver ! @sweetymhaiske should already be on it.

**Comment by dhrishi** [comment]
#7034 is WIP for this

**Pull request closed without merging**
