### PR TITLE
[nrf5] Put common code for examples in seperate directory

### PR DESCRIPTION
**Pull request by erjiaqing**
#### Problem
In the near future, we will create many example apps for many platforms, it is necessary to maintain common code at the same place.

 #### Summary of Changes
This PR attempts to solve the problem by moving `Server.cpp` and some code in `main.cpp` to `common/nrf5/common`, and some common utility classes such as `LEDWidget` to `common/nrf5/util`.

I also moved gdb scripts to `common/nrf5/gdb`.

See #1259

### CODE REVIEW

**Review by bukepo — COMMENTED** [review]
How about:
```bash
mv examples/common/nrf5 examples/platforms/nrf528xx
```

**Review by gerickson — CHANGES_REQUESTED** [review]
Overall, good move forward. Please see comments about C++-ifying headers themselves rather than wrapping them locally with `extern "C" { ... }` here.

**Comment by erjiaqing** [comment]
> How about:
> 
> ```shell
> mv examples/common/nrf5 examples/platforms/nrf528xx
> ```

I wonder if `platforms` is a good name, since these code does not intend to do something about HAL?

**Comment by erjiaqing** [comment]
Close this PR because Github does not recognize my push to my forked repo, see #1416 instead.

**Pull request closed without merging**
