### PR TITLE
Fixed All Clusters App ZAP Test Script File

### PR DESCRIPTION
**Pull request by emargolis**
- Removed all Thread Network Diagnostics Cluster events, which are currently not implemented in the SDK at all.
  - Removed all Actions Cluster events, which are currently not implemented in the SDK.
  - Removed BatFaultChange event of the Power Source Cluster, which is not implemented in the SDK..
  - Removed StateChange event of the Boolean State Cluster, which is not implemented for the All Clusters App.
  - Removed all events of the Pump Configuration and Control Cluster, which are currently not implemented in the SDK.

### CODE REVIEW

**Comment by andy31415** [comment]
@emargolis  could you update this and #25046 , #25047 to master since it includes #24991?

I hope that event list changes will start showing up in matter files.

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by andy31415** [comment]
@emargolis  why do we need to change the test file? The test file is not building any apps and just ensures we know what deltas occur when we alter zapt or zap versions.

**Comment by emargolis** [comment]
> @emargolis why do we need to change the test file? The test file is not building any apps and just ensures we know what deltas occur when we alter zapt or zap versions.

Yes, I agree that there is no strong reason to update this test script but still wanted to have it aligned with the actual example zap file.

**Comment by emargolis** [comment]
> @emargolis could you update this and #25046 , #25047 to master since it includes #24991?
> 
> I hope that event list changes will start showing up in matter files.

All mentioned and other PR were updated accordingly

**Review by yufengwangca — APPROVED** [review]

**Pull request merged**
