### PR TITLE
Add a bridged switched device to the bridge app (#10302)

### LINKED ISSUE #10302: Add a bridged switched device to the bridge app
#### Problem
For testing the switch cluster on a Bridge device we want to add a (virtual) switch to the bridge app.

 #### Proposed Solution
Add it.

### PR DESCRIPTION
**Pull request by pjzander-signify**
#### Problem
For testing the switch cluster on a Bridge device we want to add a (virtual) switch to the bridge app.

#### Change overview
- Extended the switch cluster with the FeatureMap  definitions
- Enable the switch cluster in controller-clusters.zap 
- Add the FeatureMap attribute in controller-clusters.zap 
- Enable the MultiPressMax attribute in all-clusters-app.zap
- Add the feature map attribute in all-clusters-app.zap
- Add the switch cluster in bridge-app.zap 
- Add support for the switch cluster in the bridge-app

#### Testing
- Manual tested with the chip-tool and the bridge-app
- Passed all Github workflows.

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

**Review by mrjerryjohns — CHANGES_REQUESTED** [review]
I think we should wait till #10681 goes in, at which point, the various list attributes being implemented in this file would need to be replaced with the `AttributeAccessInterface`, as well as removing the descriptor cluster bits in this file.

**Review by woody-apple — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]

**Review by mrjerryjohns — APPROVED** [review]

**Comment by andy31415** [comment]
fast track: example app update

**Comment by andy31415** [comment]
@pjzander-signify - could you fix the merge conflicts? Then we can merge as fast-track

**Comment by bzbarsky-apple** [comment]
@msandstedt @saurabhst @jepenven-silabs @jmartinez-silabs @LuDuda @Damian-Nordic Please take a look?

**Review by jmartinez-silabs — APPROVED** [review]

**Pull request merged**
