### PR TITLE
Add simulated test dm

### PR DESCRIPTION
**Pull request by krypton36**
#### Problem
* Adding new Simulated device test.

#### Change overview
* Adding new YAML file for new test.
* Updated test java script file.
* Updated PICS file with THREAD
* Generated code.

#### Testing
* Started Simulator with specific Test.
* Ran commands in Chip-tool_commands.txt
* Passing logs attached.
[Chip-tool_commands.txt](https://github.com/project-chip/connectedhomeip/files/7892961/Chip-tool_commands.txt)
[Simulated_logs_pass.txt](https://github.com/project-chip/connectedhomeip/files/7892962/Simulated_logs_pass.txt)

### CODE REVIEW

**Review by bzbarsky-apple — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]
Fast tracking given this is adding tests.

**Pull request merged**
