### PR TITLE
Add screen manager and virtual sensors to app

### PR DESCRIPTION
**Pull request by mlepage**
- add simple UI framework for tiny screens and few buttons
- add README documenting simple UI framework
- add screens for list of items, QR code
- add demo devices/endpoints/clusters/attributes
- improve display wake behaviour

 #### Problem
<the issue this PR is intended to address>

 #### Summary of Changes
<what's in this PR>

fixes #<issue number, or numbers. if no issue, please create one>

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

**Review by BroderickCarlin — APPROVED** [review]

**Review by woody-apple — COMMENTED** [review]
(cleaning up pullapprove-test requests)

**Review by woody-apple — COMMENTED** [review]
(cleaning up pullapprove-test requests)

**Review by woody-apple — COMMENTED** [review]
(cleaning up pullapprove-test requests)

**Review by woody-apple — COMMENTED** [review]
(cleaning up pullapprove-test requests)

**Pull request closed without merging**
