### PR TITLE
[Infineon]Slight changes to variable names in p6 examples.

### PR DESCRIPTION
**Pull request by mcatee-infineon**
#### Problem
* Consistency update

#### Change overview
Change variable names in p6 examples for consistency between examples.

### CODE REVIEW

**Review by bzbarsky-apple — APPROVED** [review]
This seems to include parts of another PR in it...

**Comment by mcatee-infineon** [comment]
> This seems to include parts of another PR in it...

Removed the changes you mentioned and fixed restyle issue.

**Review by bzbarsky-apple — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Review by jmeg-sfy — APPROVED** [review]

**Pull request merged**
