### PR TITLE
[YAML] Update TestCommand.cpp so it does not automatically wait for the device to be retrieved but do it conditionally if WaitForCommissionee is used in the test

### PR DESCRIPTION
**Pull request by vivien-apple**
#### Problem

YAML tests can not be used for testing commissioning since they automatically try to retrieve a device previously commissioned.

#### Change overview
  * Add `WaitForCommissionee` command
  * Add a test step before each tests that requires a device to has been previously commissioned
  * Update the tests runners
  * Update generated code
  
#### Testing
 The test step has been added to most step (except 1)

### CODE REVIEW

**Review by jmeg-sfy — APPROVED** [review]

**Comment by jmeg-sfy** [comment]
Don't you think this was maybe better to do it per Cluster rather than having it into every single test file ?
or having a tag saying pre-commissioned as a requirements ..

**Review by Damian-Nordic — APPROVED** [review]

**Comment by vivien-apple** [comment]
> Don't you think this was maybe better to do it per Cluster rather than having it into every single test file ?
> or having a tag saying pre-commissioned as a requirements ..

This is unrelated to clusters themselves so it has to live into the test file.
About using a tag I was hesitant between adding an explicit test step and a boolean in the config. But now, let's imagine that you want a test that connects to 2 commissionees ? At least with the explicit test step we can introduce some parameters if needed and differentiates between the commissioners.

**Review by bzbarsky-apple — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
Fast tracking given this enables tests.

**Pull request merged**
