### PR TITLE
NXP MW320 first pull request to project-chip github

### PR DESCRIPTION
**Pull request by JasonLan0223**
#### Problem
What is being fixed?  Examples:
* support NXP MW320 matter for wifi function.

#### Change overview
relegated with examples\lighting-app\mw320 

#### Testing
Using the follow chip tool command:
-   Bypass pairing
./chip-tool pairing bypass "IP6 address" 5540
-   Read MW320 led status
./chip-tool onoff read on-off 1
-   Turn on MW320 led
./chip-tool onoff on 1
-   Turn off MW320 led
./chip-tool onoff off 1

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
@JasonLan0223 please fix the CLA issue.

**Review by woody-apple — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
@JasonLan0223 Is it intentional that this is trying to merge into the TE6 lts branch (which is very out of date) and not into tip?

**Comment by JasonLan0223** [comment]
@[bzbarsky-apple](https://github.com/bzbarsky-apple) Because we only implemented it on CHIP_BYPASS_RENDEZVOUS mode, we think only TE6 have this support. After pairing success for NXP MW320 platform, we will try to push new branch. Thank you for your information.

**Comment by JasonLan0223** [comment]
Could someone help how to run the restyler on the newly added files? Thank you for your help.

**Comment by JasonLan0223** [comment]
@bzbarsky-apple We have recreated PR at https://github.com/project-chip/connectedhomeip/pull/15129. Do you think it is like your suggestion? Thank you for your help.

**Comment by bzbarsky-apple** [comment]
No need to re-create the PR; can just update this one....  In any case, it still has restyling differences: https://github.com/project-chip/connectedhomeip/pull/15130/commits/7316bd41bdedefa41916293f5ea5d06ee14c1b5a

**Comment by JasonLan0223** [comment]
@bzbarsky-apple There are 12 commit in this PR. Do you think it is OK to pull request? Thank you.

**Comment by bzbarsky-apple** [comment]
> There are 12 commit in this PR. Do you think it is OK to pull request?

Yes.  I don't see what the number of commits has to do with anything.....

**Comment by JasonLan0223** [comment]
@bzbarsky-apple Thank you for your help again. What else do we missing at this PR?

**Comment by bzbarsky-apple** [comment]
Kicked off the CI run.  Once that passes, this can merge, looks like.

**Comment by bzbarsky-apple** [comment]
@andy31415 @woody-apple The ESP32 failures seem to be a general thing on the TE6 LTS branch, right?

Same for the Darwin failures.  So not new with this PR...

**Comment by JasonLan0223** [comment]
Thanks for woody-apply's help.
Thanks for babarsky-apply's help.
Thanks for andy31415's help.

**Pull request merged**
