### PR TITLE
Correct PICS values for TC_DGTHREAD attributes

### LINKED ISSUE #20719: Test_TC_DGTHREAD_2_1 the PICS values for the attributes are off by one. [SVE1]
#### Problem

In Test_TC_DGTHREAD_2_1 the PICS values for the attributes are off by one.

E.g. the channel attribute is 0, but the PICS value is DGTHREAD.S.A0001, https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_DGTHREAD_2_1.yaml#L31-L37.

 #### Proposed Solution

Reduce the numbers in the PICS by one.

### PR DESCRIPTION
**Pull request by markus-becker-tridonic-com**
#### Problem

* PICS values were not according to spec.
* Fixes https://github.com/project-chip/connectedhomeip/issues/20719

#### Change overview

PICS values adapted to spec.

#### Testing

No testing. Only manual comparison between YAML and spec.

### CODE REVIEW

**Comment by markus-becker-tridonic-com** [comment]
This is SVE relevant.

**Review by Damian-Nordic — APPROVED** [review]

**Comment by markus-becker-tridonic-com** [comment]
This PR is discussed and checked with the support team from SVE1. Before merging, check whether they have approved/commented or put in a replacement PR. It seems the YAML is partially automatically created and the tool creating them has an off-by-one error.

**Comment by markus-becker-tridonic-com** [comment]
Will likely be solved through a testplan-update and testplan-2-pics-script.

**Comment by markus-becker-tridonic-com** [comment]
Test plan was updated in https://github.com/jaehs6sam/chip-test-plans/commit/240c2ee04ee559f44869891ee981707c4fdfcdaf.
Another import src/app/tests/suites/certification/Test_TC_DGTHREAD_2_1.yaml is required.

**Pull request closed without merging**
