### PR TITLE
[Linux] Initial support of WiFi provisioning

### LINKED ISSUE #3383: validate Linux WiFi support on Pi
CHIP builds on Pi now, but I've heard reports that CHIP is not playing nice with wpa_supplicant.

Make the CHIP WiFi connectivity support run smoothly on the Pi, and document any extra steps.

### PR DESCRIPTION
**Pull request by erjiaqing**
#### Problem
CHIP Linux Example app does not support network provisioning.

 #### Summary of Changes
Add initial support of wifi provisioning to Linux platform, this is intended to unblock those who are testing this. Follow ups is required to make this better.

 Fixes #3383

### CODE REVIEW

**Review by yunhanw-google — APPROVED** [review]

**Comment by mspang** [comment]
There are two consecutive PRs for this

https://github.com/project-chip/connectedhomeip/pull/3595
https://github.com/project-chip/connectedhomeip/pull/3596

**Comment by mspang** [comment]
You lost the race (just barely)

Can you rebase on #3595

**Comment by erjiaqing** [comment]
dup #3595

**Comment by yufengwangca** [comment]
....LOL, what a coincidence. @erjiaqing You can indicate in the issue and say you are working on it to avoid effort collision in future.

**Pull request closed without merging**
