### PR TITLE
Build fixes for chip_logging=false configuration

### PR DESCRIPTION
**Pull request by kpschoedel**
#### Problem

Building with `chip_logging=false` fails.

#### Summary of Changes

Added a few braces and `#if`s.

### CODE REVIEW

**Comment by kpschoedel** [comment]
The goal was to estimate the flash used for logging — it's around 16K code plus strings.

**Comment by andy31415** [comment]
This will clash with #4741

Could we wait for that one instead?

**Comment by Damian-Nordic** [comment]
@kpschoedel Would it be easier to maintain if the logging macros resolved to `((void)0)` when `chip_logging=false`? In such a case the braces around CHIP logging wouldn't be needed.

**Comment by kpschoedel** [comment]
Yes, good point. In any case I'll defer this until Andrei's logging work is complete.

**Comment by mspang** [comment]
@kpschoedel

**Pull request closed without merging**
