### PR TITLE
Pull submodules

### PR DESCRIPTION
**Pull request by mspang**
Via scripts/helpers/pull_submodules.sh

Updates:
    git -C examples/common/m5stack-tft/repo log 42cadf2..42cadf2
    git -C third_party/openthread/repo log 5f0e36eeb..b9a7903f1
    git -C third_party/ot-br-posix/repo log 77a9156..eefef71
    git -C third_party/pigweed/repo log 023f35b..34d9b07

### CODE REVIEW

**Comment by rwalker-apple** [comment]
should we have a blurb about what we're picking up from these updates?

**Comment by mspang** [comment]
> should we have a blurb about what we're picking up from these updates?

Do you mean appending something like --pretty=oneline in the description or something manual?

**Comment by rwalker-apple** [comment]
I was thinking that some rationale would be offered, but perhaps that could be a policy for non-master branches.

**Comment by mspang** [comment]
> I was thinking that some rationale would be offered, but perhaps that could be a policy for non-master branches.

Current rationale is
- m5stack-tft is out of sync between repos.conf & submodules again. 
- We're not testing new changes in the dependencies unless we keep them updated (better to catch problems early).

**Review by turon — APPROVED** [review]
This should be okay, but we'll need to think about what our policy should be for updating openthread and https://github.com/openthread/ot-br-posix.git such that possilble regressions are avoided. once we have stable Thread support.  Perhaps a good simulation framework such as cirque can help here.  @gjc13

**Comment by rwalker-apple** [comment]
> > I was thinking that some rationale would be offered, but perhaps that could be a policy for non-master branches.
> 
> Current rationale is
> 
> * m5stack-tft is out of sync between repos.conf & submodules again.

Is this is addressable with use of a specific hash instead of a branch (as repos.conf is just a symlink)?

> * We're not testing new changes in the dependencies unless we keep them updated (better to catch problems early).

Fair enough for master.

**Comment by mspang** [comment]
> > > I was thinking that some rationale would be offered, but perhaps that could be a policy for non-master branches.
> > 
> > 
> > Current rationale is
> > 
> > * m5stack-tft is out of sync between repos.conf & submodules again.
> 
> Is this is addressable with use of a specific hash instead of a branch (as repos.conf is just a symlink)?

It's using specific hashes, however the hash in .gitmodules has fallen out of sync with the one in the git tree. We can certainly sync them back up without pulling everything, though.

> 
> > * We're not testing new changes in the dependencies unless we keep them updated (better to catch problems early).
> 
> Fair enough for master.

**Comment by rwalker-apple** [comment]
> > > > I was thinking that some rationale would be offered, but perhaps that could be a policy for non-master branches.
> > > 
> > > 
> > > Current rationale is
> > > 
> > > * m5stack-tft is out of sync between repos.conf & submodules again.
> > 
> > 
> > Is this is addressable with use of a specific hash instead of a branch (as repos.conf is just a symlink)?
> 
> It's using specific hashes, however the hash in .gitmodules has fallen out of sync with the one in the git tree. We can certainly sync them back up without pulling everything, though.

I think that the repos.conf workflow is unaware of the hashes, only git submodules is.  That's what produces the skew.  I'm suggesting that the .gitmodules file use an @<hash> format so that the repos.conf workflow matches the git submodules workflow.

**Review by andy31415 — APPROVED** [review]

**Review by saurabhst — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Comment by mspang** [comment]
> > > > > I was thinking that some rationale would be offered, but perhaps that could be a policy for non-master branches.
> > > > 
> > > > 
> > > > Current rationale is
> > > > 
> > > > * m5stack-tft is out of sync between repos.conf & submodules again.
> > > 
> > > 
> > > Is this is addressable with use of a specific hash instead of a branch (as repos.conf is just a symlink)?
> > 
> > 
> > It's using specific hashes, however the hash in .gitmodules has fallen out of sync with the one in the git tree. We can certainly sync them back up without pulling everything, though.
> 
> I think that the repos.conf workflow is unaware of the hashes, only git submodules is. That's what produces the skew. I'm suggesting that the .gitmodules file use an @ format so that the repos.conf workflow matches the git submodules workflow.

Actually we already fixed that. That's what the "commit" lines in the .gitmodules are.

But you either need to use pull_submodules.sh to update both at the same time, or keep them in sync manually.

**Comment by andy31415** [comment]
@mspang - requires conflict fixing before merge

**Pull request merged**
