### PR TITLE
Require issues for all PRs

### PR DESCRIPTION
**Pull request by woody-apple**
#### Problem
Resolving: #22456 

#### Change overview
Updating pull approve, and adding a new action

#### Testing
CI

### CODE REVIEW

**Review by andy31415 — DISMISSED** [review]
I think this should not be a hard enforcement: hotfixes or trivial changes should be ok.

**Comment by andy31415** [comment]
> I think this should not be a hard enforcement: hotfixes or trivial changes should be ok.

Is it possible to add some alternate like 'No Issue reason: ...' to the check? So one or the other?

**Comment by woody-apple** [comment]
> > I think this should not be a hard enforcement: hotfixes or trivial changes should be ok.
> 
> Is it possible to add some alternate like 'No Issue reason: ...' to the check? So one or the other?

HotFix will override this, or Fast track. Per our TT meetings, let's see how this goes, we can grant exceptions, but exceptions should be exceptional :)

**Comment by woody-apple** [comment]
> I think this should not be a hard enforcement: hotfixes or trivial changes should be ok.

Trivial changes should not be allowed if they're not part of the categories already approved by the TT. Renames were already pushed out, as an example of this.

**Review by jtung-apple — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]

**Pull request merged**
