### PR TITLE
Improve ESP32 Docker image used by Build example - ESP32 workflow

### PR DESCRIPTION
**Pull request by electrocucaracha**
#### Problem
[Hadolint](https://github.com/hadolint/hadolint) tool helps to build Docker images following best practices. Using those guidelines can help to reduce the size of the image and speed up the pulling process during the CI execution.

#### Change overview
This change uses the [multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/) feature to get the Espressif IoT Development Framework in one stage and installing it in the following stage. As result the image size has been reduced from 5.5GB to 5.36GB

#### Testing
This was tested locally using the act tool (`$ act -j esp32`) using the Docker image built with these changes.

### CODE REVIEW

**Review by msandstedt — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Comment by electrocucaracha** [comment]
@andy31415 should I need to bump the version here as well?

**Comment by andy31415** [comment]
> @andy31415 should I need to bump the version here as well?

Yes, any change to any docker image should bump the version so that we can roll  back if any problem occurs.

**Comment by electrocucaracha** [comment]
> > @andy31415 should I need to bump the version here as well?
> 
> Yes, any change to any docker image should bump the version so that we can roll back if any problem occurs.

Makes sense, I noticed all images are pointing to the same version file and given that I'm planning to improve several Dockerfiles in different PRs (I considered better doing this way to facilitate the review). Can I change the version file in those PRs which are ready to be merged and keep them in order? Any preference?

**Comment by andy31415** [comment]
> > > @andy31415 should I need to bump the version here as well?
> > 
> > 
> > Yes, any change to any docker image should bump the version so that we can roll back if any problem occurs.
> 
> Makes sense, I noticed all images are pointing to the same version file and given that I'm planning to improve several Dockerfiles in different PRs (I considered better doing this way to facilitate the review). Can I change the version file in those PRs which are ready to be merged and keep them in order? Any preference?

At some point we tried to have individual versions (i.e. not change 'chip-build' base version when only a sub-image version changed) however quickly ended up making mistakes and having a hard time updating them.

The current rule is that changing in any image changes the global version even if this means that some versions are identical.

**Review by andy31415 — CHANGES_REQUESTED** [review]
Version file needs updating on any docker image change, even if assumed noop

**Comment by electrocucaracha** [comment]
> Version file needs updating on any docker image change, even if assumed noop

I've changed the version file

**Review by jmartinez-silabs — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Pull request merged**
