### PR TITLE
Add docker definition for nRF Connect SDK

### LINKED ISSUE #1528: Add docker for nRF Connect SDK
#### Problem
We need a docker image to check build of the nRF Connect platform in the _Examples_ github workflow (once the platform is added; see #1493).

 #### Proposed Solution
Put a new docker image definition in integrations/docker/images/chip-build-nrfconnect-platform directory.

### PR DESCRIPTION
**Pull request by Damian-Nordic**
#### Problem
We need a docker image to check build of the nRF Connect platform in the _Examples_ github workflow (once the platform is added; see #1493).

 #### Proposed Solution
Put a new docker image definition in integrations/docker/images/chip-build-nrfconnect-platform directory.

fixes #1528

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

**Comment by rwalker-apple** [comment]
could this be folded into the chip-build-nrf-platform image, instead?

**Comment by Damian-Nordic** [comment]
@rwalker-apple Thanks for your comment. I thought that if a docker image is not only meant for CI, but potentially also for users (who usually won't build an application for both nRF5 and nRF Connect at a time), then it's better to have two smaller than one bigger image. What do you think?

**Comment by rwalker-apple** [comment]
> @rwalker-apple Thanks for your comment. I thought that if a docker image is not only meant for CI, but potentially also for users (who usually won't build an application for both nRF5 and nRF Connect at a time), then it's better to have two smaller than one bigger image. What do you think?

I don't have any strong feelings, just noticed that you're replicating much of what the nrf-platform docker image is.

One thought I have is that this may increase the maintenance burden for CHIP's "build for Nordic" environment, as there are would be 2 places the platform and compiler version are maintained.

If tooling for the 2 Nordic targets don't conflict with each other, I'd just tack onto the other image (maybe rename it, as well?)

**Review by BroderickCarlin — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Comment by Damian-Nordic** [comment]
> I don't have any strong feelings, just noticed that you're replicating much of what the nrf-platform docker image is.
> 
> One thought I have is that this may increase the maintenance burden for CHIP's "build for Nordic" environment, as there would be 2 places the platform and compiler version are maintained.
> 
> If tooling for the 2 Nordic targets don't conflict with each other, I'd just tack onto the other image (maybe rename it, as well?)

That's a good point although I would still prefer having separate images for both SDKs not to bloat their sizes (despite of the common pieces most of their components are exclusive). But I guess I can turn the nrf Dockerfile into a multi-stage one on the next update.

**Comment by rwalker-apple** [comment]
> > I don't have any strong feelings, just noticed that you're replicating much of what the nrf-platform docker image is.
> > One thought I have is that this may increase the maintenance burden for CHIP's "build for Nordic" environment, as there would be 2 places the platform and compiler version are maintained.
> > If tooling for the 2 Nordic targets don't conflict with each other, I'd just tack onto the other image (maybe rename it, as well?)
> 
> That's a good point although I would still prefer having separate images for both SDKs not to bloat their sizes (despite of the common pieces most of their components are exclusive). But I guess I can turn the nrf Dockerfile into a multi-stage one on the next update.

great plan.  would you file an issue describing what needs fixing and what approach should be taken to address?

**Comment by Damian-Nordic** [comment]
> great plan. would you file an issue describing what needs fixing and what approach should be taken to address?

sure, done!

**Pull request merged**
