### PR TITLE
Add bootstrap variant that skips CIPD

### PR DESCRIPTION
**Pull request by mohrr**
#### Problem
Update CHIP's bootstrap to allow skipping the CIPD step.

 #### Summary of Changes
* Update Pigweed submodule
* Switch bootstrap to use a config file.
* Create a separate config file for bootstrapping without CIPD and update bootstrap.sh to allow using it.

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]
@mohrr  - please sign the CLA and apply restyle. There is a script `./scripts/helpers/restyle-diff.sh` that can do the restyle locally.

**Review by saurabhst — APPROVED** [review]

**Comment by andy31415** [comment]
@mohrr - the ESP32 build failure may be real. Is it related too new versions of things being checked out?

**Comment by mohrr** [comment]
> @mohrr - the ESP32 build failure may be real. Is it related too new versions of things being checked out?

Someone on the Pigweed team recognizes the issue and is working on it. I'll likely be updating the commit that updates Pigweed but the other two commits should remain the same.

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
@mohrr Build is failing :(

**Review by LuDuda — APPROVED** [review]

**Review by jmartinez-silabs — APPROVED** [review]

**Review by mspang — APPROVED** [review]

**Pull request merged**
