### PR TITLE
Ensure null-term of strings in Linux Conn Mger

### LINKED ISSUE #15847: Linux WiFi driver treating non-null-terminated strings as null-terminated
#### Problem
The Linux wifi driver has code like so:
```
932 memcpy(ssidStr, ssid.data(), ssid.size());
933 memcpy(keyStr, credentials.data(), credentials.size());
934 g_variant_builder_add(&builder, "{sv}", "ssid", g_variant_new_string(ssidStr));
935 g_variant_builder_add(&builder, "{sv}", "psk", g_variant_new_string(keyStr));
```
in src/platform/Linux/ConnectivityManagerImpl.cpp 

If someone passes an SSID of length `kMaxWiFiSSIDLength` this is going to read past end of buffer when calling `g_variant_new_string`...  Similar for the key string.

 #### Proposed Solution
Either use an API that can accept non-null-terminated strings, or ensure that `ssidStr` and `keyStr` have an extra byte at the end and are always null-terminated.

### PR DESCRIPTION
**Pull request by lzgrablic02**
#### Problem
* Fixes #15847.

#### Change overview
Ensures null-termination of SSID and key strings in Linux ConnectivityManagerImpl.

#### Testing
How was this tested? (at least one bullet point required)
* None

### CODE REVIEW

**Review by woody-apple — APPROVED** [review]

**Review by msandstedt — CHANGES_REQUESTED** [review]
This can still break:

```
CHIP_ERROR
ConnectivityManagerImpl::ConnectWiFiNetworkAsync(ByteSpan ssid, ByteSpan credentials,
                                                 NetworkCommissioning::Internal::WirelessDriver::ConnectCallback * apCallback)
{
...
    char ssidStr[kMaxWiFiSSIDLength + 1u] = { 0 }; 
    char keyStr[kMaxWiFiKeyLength + 1u]   = { 0 }; 
...
    memcpy(ssidStr, ssid.data(), ssid.size());
    memcpy(keyStr, credentials.data(), credentials.size());
```

**Comment by lzgrablic02** [comment]
> This can still break:
> 
> ```
> CHIP_ERROR
> ConnectivityManagerImpl::ConnectWiFiNetworkAsync(ByteSpan ssid, ByteSpan credentials,
>                                                  NetworkCommissioning::Internal::WirelessDriver::ConnectCallback * apCallback)
> {
> ...
>     char ssidStr[kMaxWiFiSSIDLength] = { 0 }; 
>     char keyStr[kMaxWiFiKeyLength]   = { 0 }; 
> ...
>     memcpy(ssidStr, ssid.data(), ssid.size());
>     memcpy(keyStr, credentials.data(), credentials.size());
> ```

Sorry @msandstedt I'm not clear on what you mean. The quoted code looks like the old code.

**Comment by msandstedt** [comment]
Apologies.  Updated the comment.

But yes, even with the change, this can break.  We are passing in ByteSpans which can be any length and still blindly copying into the uint8_t arrays.  There's still a very real possibility of ConnectWiFiNetworkAsync writing over the end of `ssidStr` and `keyStr`, and not being null terminated.  This is the problem:

```
memcpy(ssidStr, ssid.data(), ssid.size());
```

Making `ssidStr` 1 byte bigger doesn't fix it.

**Comment by jmeg-sfy** [comment]
> Apologies. Updated the comment.
> 
> But yes, even with the change, this can break. We are passing in ByteSpans which can be any length and still blindly copying into the uint8_t arrays. There's still a very real possibility of ConnectWiFiNetworkAsync writing over the end of `ssidStr` and `keyStr`, and not being null terminated. This is the problem:
> 
> ```
> memcpy(ssidStr, ssid.data(), ssid.size());
> ```
> 
> Making `ssidStr` 1 byte bigger doesn't fix it.

Indeed this is not safe and prone to overflow good catch @msandstedt

**Review by jmeg-sfy — COMMENTED** [review]
please address the memcpy remark

**Comment by lzgrablic02** [comment]
> Apologies. Updated the comment.
> 
> But yes, even with the change, this can break. We are passing in ByteSpans which can be any length and still blindly copying into the uint8_t arrays. There's still a very real possibility of ConnectWiFiNetworkAsync writing over the end of `ssidStr` and `keyStr`, and not being null terminated. This is the problem:
> 
> ```
> memcpy(ssidStr, ssid.data(), ssid.size());
> ```
> 
> Making `ssidStr` 1 byte bigger doesn't fix it.

I see. I had figured the caller would take care of making sure arguments were valid. Taken care of now, thanks for catching.

**Review by msandstedt — APPROVED** [review]

**Pull request merged**
