### PR TITLE
Group key management cluster

### PR DESCRIPTION
**Pull request by rcasallas-silabs**
#### Problem
Group Key Management cluster tests where disabled due to code generation errors.

#### Change overview
* YAML tests fixed and improved.
* The groupKeyMap attribute of the Group Key Management cluster is now writable.

#### Testing
YAML tests completed successfully.

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
fast track: change by a domain owner, up for sufficient time for cross timezone code review.

**Comment by bzbarsky-apple** [comment]
@rcasallas-silabs Wondering why you created a new PR instead of reopening #13140....

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by bzbarsky-apple** [comment]
@rcasallas-silabs The Darwin failures look like real failures.  In particular, `testSendClusterGroupKeyManagementWriteAttributeGroupKeyMapWithValue` is getting back a INVALID_ACTION error.  And `testSendClusterTestGroupKeyManagementCluster_000010_KeySetRead` is failing because NOT_FOUND is not mapped in the Darwin error mapping bits in `src/darwin/Framework/CHIP/CHIPError.mm` and `src/darwin/Framework/CHIPTests/CHIPErrorTestUtils.mm` (seach for where `EMBER_ZCL_STATUS_INVALID_COMMAND` is handled).

If you prefer, I can do a quick PR to fix the `NOT_FOUND` thing, but I'm not sure what's going on with the `groupKeyMap` attribute write.

**Comment by woody-apple** [comment]
@rcasallas-silabs Conflicts here FYI

**Comment by woody-apple** [comment]
Fast tracking, given > 3 days for review.

**Pull request closed without merging**
