### PR TITLE
Initial Outline

### PR DESCRIPTION
**Pull request by woody-apple**
A bare skeleton for to start with, along with:
• Readme
• License
• Code of Conduct
• Style Guide
• Simple test source code
• Build checks out (and doesn’t run yet) on Pull Request and Push
• clang-tidy runs on Pull Requests
• clang-format starting point

Note: Once this account is open, I recommend turning on on these marketplace extensions:
•restyled.io (config file placed here).
• LGTM - https://github.com/marketplace/lgtm - Good security analysis
• Codacy - https://github.com/marketplace/codacy - Good security analysis/code pattern review

### CODE REVIEW

**Review by gerickson — COMMENTED** [review]
Some minor changes to be addressed, mostly around "third_party" and "actions". The rest warrant discussion either pre- or post-commit.

**Review by gerickson — APPROVED** [review]
I think the clang-tidy / pretty / pretty-check discussion worth having, but this is a solid start.

**Review by anush-apple — APPROVED** [review]

**Review by hawk248 — APPROVED** [review]

**Review by chrisdecenzo — APPROVED** [review]
Looks good, thanks

**Review by robszewczyk — APPROVED** [review]

**Comment by arashmok** [comment]
The Matter protocol, as described in the official GitHub repository for Project CHIP (Connected Home over IP), is an open-source connectivity standard that aims to unify smart home devices and improve interoperability across different ecosystems. It focuses on providing a secure and reliable communication framework for IoT devices, enabling them to work seamlessly together regardless of the manufacturer. The protocol is designed to be extensible and supports various networking technologies, including Wi-Fi and Thread.

**Comment by arashmok** [comment]
What is the Matter protocol according to the official documentation?

**Review by Sum1cares — APPROVED** [review]

**Pull request merged**
