### PR TITLE
Add access control server skeleton

### PR DESCRIPTION
**Pull request by mlepage-google**
#### Problem
Access Control Cluster not yet created.

#### Change overview
Define cluster XML, ZAP, etc.
Add empty cluster implementation to all-clusters-app example.
Disabled some tests of the cluster (since its attributes are not implemented).

#### Testing
Built and ran and ensured it's present in chip-all-cluster-app. Ran unit tests.

### CODE REVIEW

**Comment by mlepage-google** [comment]
PR needs to be draft until more tickled issues are fixed in master, and code is regenerated. But once that happens, it will be fine.

**Comment by mlepage-google** [comment]
Needs PR #12300 to build.

**Comment by mlepage-google** [comment]
I believe it's all only failing now because PR #12300 still isn't in, so build fails (which is what that fixes) and it reports uncommitted regen differences (which it won't when that goes in).

**Comment by mlepage-google** [comment]
I've removed the `isNullable="true"` from AccessControl cluster ACL attribute, for now. I tested with my other PR on top, and it still works to read a list of 3 entries. What will likely fail is, with the zap tool, trying to add AccessControl cluster, and then ACL attribute, it will want a **default** because it's not nullable. Probably simplest to do for now, is type any default, then remove it from the generated zap file.

**Review by yunhanw-google — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]

**Pull request merged**
