### PR TITLE
Fix link to `the cirque test guide`

### PR DESCRIPTION
**Pull request by markus-becker-tridonic-com**
#### Problem

Fix link to `the cirque test guide`

#### Change overview

Change link.

#### Testing

Checked the preview of the README.

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

**Comment by woody-apple** [comment]
@markus-becker-tridonic-com 
`/home/runner/work/connectedhomeip/connectedhomeip/docs/README.md:9: error: unexpected token TK_EOF as the argument of ref (warning treated as error, aborting now)
12551
`

Looks like a real failure in your edit

**Comment by markus-becker-tridonic-com** [comment]
> @markus-becker-tridonic-com `/home/runner/work/connectedhomeip/connectedhomeip/docs/README.md:9: error: unexpected token TK_EOF as the argument of ref (warning treated as error, aborting now) 12551 `
> 
> Looks like a real failure in your edit

Similar to https://github.com/project-chip/connectedhomeip/pull/6862. Update of Doxygen in the containers?

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
@markus-becker-tridonic-com - looks like doxygen fails

**Comment by andy31415** [comment]
Our workflow seems to just say: doxygen runs on ubuntu  20.04.

https://github.com/project-chip/connectedhomeip/blob/master/.github/workflows/doxygen.yaml#L31

Do we need to update doxygen? Can't we make it pass with the current version?

**Comment by andy31415** [comment]
Our scripts try to  install doxygen as is. this is probably wasteful (takes time) and installs an old version as well:

https://github.com/project-chip/connectedhomeip/blob/master/scripts/helpers/doxygen.sh#L37

I believe it would be best to create a doxygen dockerhub image and then we have more control.

**Comment by andy31415** [comment]
In 11529 I created a doxygen dockerhub image. Will build it and see about transitioning our workflows to using it.

**Review by jelderton — APPROVED** [review]

**Comment by andy31415** [comment]
Doxygen passes now, however spellcheck  seems broken in ToT :(

**Comment by andy31415** [comment]
#11540 will fix spellcheck

**Comment by andy31415** [comment]
Doxygen change was  revertted because it does not seem to play nice with GH-pages updates. However this PR now will pass ... but unsure what will happen after merging. @woody-apple ?

**Review by jelderton — APPROVED** [review]

**Pull request merged**
