### PR TITLE
Added steps to validate CASE Authentication Tags (CAT)

### PR DESCRIPTION
**Pull request by vijs**
**Problem**
* ACL currently does not validate CASE Authentication Tags (CAT) Access Control Requests (Issue [#10243](https://github.com/project-chip/connectedhomeip/issues/10243)).

**Change overview**
* Added step to validate CASE Authentication Tags.
* Added new test cases for checking valid/non-valid CAT access requests.

Testing
* Added Matter Unit Tests

### CODE REVIEW

**Comment by msandstedt** [comment]
I thought that even with the move from 32-bit tags to the split 16-bit tag ID and 16-bit tag version we still had CAT1 and CAT2 RDNs.

Does this PR correctly support that?

**Review by yunhanw-google — APPROVED** [review]

**Comment by mlepage-google** [comment]
Hi Vijay, just seeing this now (was sick yesterday). PR #11550 is now merged, which does provide a full implementation of Access Control module (storing entries etc.) using full interface (iterating entries etc.). The SubjectDescriptor has changed slightly (since we can put everything into a NodeId), and the test code is entirely rewritten. Also I know Evgeni is working on adding CATs into the session, its test code (including certs), and then to the subject descriptor (e.g. PR #11697). Therefore this will require coordination and rework, my apologies on that. I'll reach out to you on slack.

**Comment by vijs** [comment]
Hi Marc, I started working on https://github.com/project-chip/connectedhomeip/issues/10243 as it wasn't assigned to anyone. Sorry, I didn't know it's actively being worked on. Let us discuss this in Slack and see how to collaborate.

**Comment by vijs** [comment]
Abandoning this PR as Evgeni is working on it.

**Pull request closed without merging**
