### PR TITLE
[Ameba] Update docker image to the latest

### PR DESCRIPTION
**Pull request by pankore**
#### Problem
Update Ameba SDK to the latest

#### Change overview
Update docker file for ameba
Update docker version

#### Testing
Tested compilation

### CODE REVIEW

**Comment by pankore** [comment]
Hi @anush-apple, @austinh0, @balducci-apple, @bzbarsky-apple, @carol-apple, @chrisdecenzo, @chulspro, @Damian-Nordic, @electrocucaracha, @emargolis, @erjiaqing, @franck-apple, @hawk248, @holbrookt, @jelderton, @jepenven-silabs, @jmartinez-silabs, @kghost, @LuDuda, @lzgrablic02, @mlepage-google, @mrjerryjohns, @msandstedt, @mspang, @pan-apple, @sagar-apple, @saurabhst, @selissia, @tcarmelveilleux, @tecimovic, @vivien-apple, @wbschiller and @woody-apple,

Please kindly help to review this PR and leave your valuable suggestions, many thanks!

**Review by electrocucaracha — APPROVED** [review]
/lgtm

The change doesn't affect the [image building process](https://github.com/project-chip/connectedhomeip/runs/4693501713?check_suite_focus=true#step:3:10382)

**Review by andy31415 — APPROVED** [review]

**Pull request merged**
