### PR TITLE
Fix global usage of GetRandU32 (#10506)

### PR DESCRIPTION
**Pull request by tcarmelveilleux**
Cherry-pick PR #10506 into TE6.lts that fixes K32W

### CODE REVIEW

**Comment by woody-apple** [comment]
@tcarmelveilleux Do you mean TE7? Also - not sure what this ESP32 SDK break is?

**Comment by doru91** [comment]
Indeed, the issue on K32W was solved by this PR.

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
@woody-apple ESP32 breakage is that this old branch still uses `:latest` tagging to decide what CI to run:

https://github.com/project-chip/connectedhomeip/blob/test_event_6.lts/.github/workflows/examples-esp32.yaml#L41

this results in the update to the ESP sdk on master to break builds on old branches. In te7 and above we actually fix the CI image so this does not happen anymore, however te6 and before we did not know that and kept updating latest.

**Pull request closed without merging**
