### PR TITLE
[shell] Add commands for resource usage statistics

### PR DESCRIPTION
**Pull request by Damian-Nordic**
1. Add shell commands for printing and resetting the peak resource usage statistics. If the heap usage watermark is supported, the peak heap usage is printed as well.
2. Add `CONFIG_CHIP_STATISTICS` Kconfig to enable system statistics on nRF Connect platform.
3. Replace the current system stat labels with more user-friendly ones so that they can be used in a shell command output. Also, remove two unused statistics.

### CODE REVIEW

**Comment by Damian-Nordic** [comment]
@ATmobica Do you know why Open IoT tests are failing? I updated `SHELL_COMMAND_NAME` variable in your tests but it still does not help and I don't know what I'm missing.

**Comment by ATmobica** [comment]
> @ATmobica Do you know why Open IoT tests are failing? I updated `SHELL_COMMAND_NAME` variable in your tests but it still does not help and I don't know what I'm missing.

Please update the integration tv-app test too. It also uses shell commands.

**Comment by Damian-Nordic** [comment]
> Please update the integration tv-app test too. It also uses shell commands.
I see, so the same test is used for different apps and the shell output depends on the application configuration. So I should enable CHIP statistics for tv-app as well, right?

**Comment by ATmobica** [comment]
> > Please update the integration tv-app test too. It also uses shell commands.
> 
> I see, so the same test is used for different apps and the shell output depends on the application configuration. So I should enable CHIP statistics for tv-app as well, right?

Not exactly. The tv-app has a separate test. And tv-app uses the CHIP shell that's why you should provide the same changes in `src/test_driver/openiotsdk/integration-tests/tv-app/test_app.py` file as for shell example (`src/test_driver/openiotsdk/integration-tests/shell/test_app.py`)

**Comment by Damian-Nordic** [comment]
@ATmobica Yeah, I removed my comment as I realized my mistake. I understand you now :).

**Review by andy31415 — APPROVED** [review]

**Review by LuDuda — APPROVED** [review]

**Pull request merged**
