### PR TITLE
[Telink]: Replaced manual bootloader configuration by conf file

### PR DESCRIPTION
**Pull request by mishadesh**
Replaced manual definition-based overlays by conf file

The previous solution to configure the bootloader for Telink build was just adding the definitions directly to build command.
The new solution replaces the definitions by bootloader.conf file and applies it by overlay.

### CODE REVIEW

**Review by s07641069 — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]

**Comment by mishadesh** [comment]
@bzbarsky-apple 
Could you please move forward the PR and merge, because the tests are very unstable and I am not able to run them again manually.

**Comment by bzbarsky-apple** [comment]
@mishadesh This needs a review from a second reviewer.  Ideally a telink platform owner.... My review was a rubber-stamp so it's not blocked once that telink owner review exists.

**Review by s07641069 — APPROVED** [review]

**Comment by mishadesh** [comment]
> @mishadesh This needs a review from a second reviewer. Ideally a telink platform owner.... My review was a rubber-stamp so it's not blocked once that telink owner review exists.

But our telink platform doesn't have an owner. How can we request a right to become an owner?

**Comment by andy31415** [comment]
> > @mishadesh This needs a review from a second reviewer. Ideally a telink platform owner.... My review was a rubber-stamp so it's not blocked once that telink owner review exists.
> 
> But our telink platform doesn't have an owner. How can we request a right to become an owner?

@s07641069 is a Telink owner I believe

**Comment by bzbarsky-apple** [comment]
> But our telink platform doesn't have an owner.

Sure it does.  It's anyone in whatever set the telink platform maintainers say are the owners.

**Comment by bzbarsky-apple** [comment]
Fast-tracking platform specific change with platform owner review.

**Pull request merged**
