### PR TITLE
Call InitChipStack from the device controller

### PR DESCRIPTION
**Pull request by vivien-apple**
#### Problem

This is an example of how I would change the event loop code from the Darwin framework to ChipDeviceController if #1497 lands. The current code is not ready to be merged yet. It needs some more love since in the current shape it will likely break examples/chip-tool and we need to determine if CHIPDeviceController always expect a device layer or not.

### CODE REVIEW

**Review by gerickson — APPROVED** [review]

**Comment by vivien-apple** [comment]
I have updated the patch. It will likely not compile well on CI yet since it depends on #1531 and #1534 though. Will force push an update once those lands. But the provided patch use the platform event loop for chip-tool and for the iOS app.

**Review by BroderickCarlin — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
@vivien-apple please rebase :)

**Comment by vivien-apple** [comment]
> @vivien-apple please rebase :)

This PR will work once #1534 has landed. Will rebased once I I finished fixing the build issues with #1534

**Comment by vivien-apple** [comment]
I add to fight a bit the old build system and the gn build system to get it to work. Should be green now.

**Comment by woody-apple** [comment]
@vivien-apple can you fix the merge conflicts here please?

@andy31415 @jelderton - can you review please?

**Review by woody-apple — COMMENTED** [review]
* deleted pull approve test

**Review by woody-apple — APPROVED** [review]
* deleted pull approve test

**Review by woody-apple — COMMENTED** [review]
* deleted pull approve test

**Comment by woody-apple** [comment]
@jelderton @robszewczyk @hawk248 ?

**Review by jelderton — APPROVED** [review]

**Pull request merged**
