### PR TITLE
Added fix for WF200 certificate injection

### PR DESCRIPTION
**Pull request by shgutte**
Problem
What is being fixed? Examples:
Commissioning failed due to certificate injection due to the data type of attestation_credentials_base.

Change Overview: 
Changed the data type of the attestation_credentials_base 

Testing
Tested manually by using MG12+WF200

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

**Review by jmartinez-silabs — COMMENTED** [review]
Current ongoing internal discussion if this is right fix and if it is correct for all platforms

**Review by emargolis — APPROVED** [review]

**Review by woody-apple — APPROVED** [review]

**Comment by andy31415** [comment]
@jmartinez-silabs - is this ok or should we place changes-requested on it?

**Comment by jmartinez-silabs** [comment]
I'll put request for changes we need to confirm something before this can be merged.

**Review by jmartinez-silabs — CHANGES_REQUESTED** [review]
need to confirm the use of pointer type and how this is used later on

**Review by jmartinez-silabs — APPROVED** [review]

**Pull request merged**
