### PR TITLE
Disable privileged mode for builds

### PR DESCRIPTION
**Pull request by mspang**
#### Problem
Our main builds are running with unneeded, dangerous permissions.

 #### Summary of Changes
Remove unneeded permissions.

### CODE REVIEW

**Comment by yunhanw-google** [comment]
If disabling priviledge mode, the inet ipv6 test cannot be run in docker, and HAPPY integration test cannot be run in docker.

**Comment by mspang** [comment]
> If disabling priviledge mode, the inet ipv6 test cannot be run in docker, and HAPPY integration test cannot be run in docker.

We don't want compiling the code to require dangerous permissions. I think we should have coverage of that case. Tests that need more can be defined separately.

**Comment by yunhanw-google** [comment]
> If disabling priviledge mode, HAPPY integration test cannot be run in docker.

@erjiaqing your HAPPY PR cannot be merged without priviledged mode in docker? Since ip namespace need priviledge permission in docker, and happy tests would be used for integration test and for code coverage increase later

**Comment by yunhanw-google** [comment]
> > If disabling priviledge mode, the inet ipv6 test cannot be run in docker, and HAPPY integration test cannot be run in docker.
> 
> We don't want compiling the code to require dangerous permissions. I think we should have coverage of that case. Tests that need more can be defined separately.

What is the risk to make docker priviledge mode when compiling code?

**Comment by mspang** [comment]
> > > If disabling priviledge mode, the inet ipv6 test cannot be run in docker, and HAPPY integration test cannot be run in docker.
> > 
> > 
> > We don't want compiling the code to require dangerous permissions. I think we should have coverage of that case. Tests that need more can be defined separately.
> 
> What is the risk to make docker priviledge mode when compiling code?

That we will end up relying on them in a context where it is not appropriate, like building the project. The CI build already runs as root, which is not ideal. Developers won't build as root, it would be better for CI to build as an unprivileged user just as a local developers do.

**Comment by yunhanw-google** [comment]
> > > > If disabling priviledge mode, the inet ipv6 test cannot be run in docker, and HAPPY integration test cannot be run in docker.
> > > 
> > > 
> > > We don't want compiling the code to require dangerous permissions. I think we should have coverage of that case. Tests that need more can be defined separately.
> > 
> > 
> > What is the risk to make docker priviledge mode when compiling code?
> 
> That we will end up relying on them in a context where it is not appropriate, like building the project. The CI build already runs as root, which is not ideal. Developers won't build as root, it would be better for CI to build as an unprivileged user just as a local developers do.

Thanks for the reply.

I guess local developer would mostly run the compilation in host instead of docker, agree that it is better for CI main build as an unpriviledge user.

From the CI experience in weave, we create two jobs, one is for main build for compilation, one is for code coverage build which run compliation + unit tests + happy integration test. Then I propose to have another job in CHIP which run either HAPPY test in priviledge docker or run in host directly (#2688) as local developer would also run HAPPY test directly in host with sudo.

**Review by andy31415 — APPROVED** [review]

**Review by BroderickCarlin — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]

**Pull request merged**
