### PR TITLE
Rename classes in transport layer

### PR DESCRIPTION
**Pull request by kghost**
#### Problem
Class names in transport layer is not proper

#### Change overview
Rename classes in transport 

SecureSession => CryptoContext
PeerConnectionState => SecureSession
PeerConnections => SecureSessionTable
SecureSessionMgr => SessionManager

This PR is automatically generated using following commands:

```
git sed -f g '\<SecureSession\>' CryptoContext
git sed -f g '\<PeerConnectionState\>' SecureSession
git sed -f g '\<PeerConnections\>' SecureSessionTable
git sed -f g '\<connectionState\>' secureSession
git sed -f g '\<GetPeerConnectionState\>' GetSecureSession
git sed -f g SecureSessionMgr SessionManager
git sed -f g secureSessionMgr sessionManager
git sed -f g sessionMgr sessionManager
git sed -f g GetSessionMgr GetSessionManager
git sed -f g mSessionMgr mSessionManager
git sed -f g '\<ssm\>' sessionManager
mv src/transport/SecureSession.h src/transport/CryptoContext.h
mv src/transport/SecureSession.cpp src/transport/CryptoContext.cpp
mv src/transport/PeerConnections.h src/transport/SecureSessionTable.h
mv src/transport/PeerConnectionState.h src/transport/SecureSession.h
sed -i 's/mSecureSession/mCryptoContext/g' src/transport/SecureSession.h
```

*Note*:  git-sed is in git-extras package of debian/ubuntu

#### Testing
Verified using unit-tests

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]
Approving as automated rename change.

**Review by Damian-Nordic — APPROVED** [review]
nit: Imho `SecureSessionKeys` would be a better name than `CryptoContext` as the latter sounds pretty generic, but anyway it's an improvement. Thanks for the cleanup!

**Review by saurabhst — APPROVED** [review]

**Comment by andy31415** [comment]
@kghost - conflicts (large renames are likely to conflict in general :/ unfortunate)

**Review by emargolis — APPROVED** [review]

**Comment by woody-apple** [comment]
I would like to see @pan-apple or @bzbarsky-apple take a look at this before merge, given some semantic renames, but overall looks good.

**Review by pan-apple — APPROVED** [review]

**Comment by woody-apple** [comment]
Thanks!

**Review by msandstedt — APPROVED** [review]

**Review by mspang — APPROVED** [review]

**Pull request merged**
