### PR TITLE
Add Dockerfile for Ameba platform

### PR DESCRIPTION
**Pull request by pankore**
#### Problem
* Add Dockerfile for platform **Ameba**

#### Change overview
* Add Dockerfile for platform Ameba
* Update version to 0.5.16

#### Testing
* Tested with _docker build_

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

**Review by andy31415 — CHANGES_REQUESTED** [review]
Changes requested: I do not understand AMEBA_MATTER environment variable.

It does not seem used #9232 and it references a root path. Unclear what the purpose of it is. Please remove.

**Review by andy31415 — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]
Rubberstamping.

**Review by woody-apple — APPROVED** [review]

**Review by Damian-Nordic — APPROVED** [review]

**Comment by pankore** [comment]
Dear @andy31415 ,
We have finally got the approval from another reviewer. Please help to merge if it is all good.
Many thanks!!

**Review by jmartinez-silabs — APPROVED** [review]

**Comment by pankore** [comment]
Dear @woody-apple @andy31415,
May I have your advice on how to proceed next or who should I ask to merge this PR?
Many thanks!

**Pull request merged**
