### PR TITLE
Disable Thermostat Clusters attribute tests from Darwin

### PR DESCRIPTION
**Pull request by chrisbeach59**
#### Problem
Thermostat Cluster Server implements constraints per the spec.
The automated test generation for the cluster generates write values that are outside constraints
blocks https://github.com/project-chip/connectedhomeip/pull/11058
#### Change overview
What's in this PR
Added excluding of Thermostat Cluster Attribute tests to Darwin zapt template file
#### Testing
Validated that after changes were made and regen:
All ZAP generated files generated successfully
ChipClusterTests.m did not contain any Thermostat Cluster tests

### CODE REVIEW

**Comment by andy31415** [comment]
@chrisbeach59 could we instead modify the tests to write values that are within spec range?

**Comment by chrisbeach59** [comment]
@andy31415  We will need to generate manual test cases. They can not be auto generated.  I have a series of tests that were used to validate the pre-attribute-changed-callback.  Different tests need to be run based on the FeatureMap bits.  The test results.  Right now the scripting engine does not support reading an attribute and using it's value as a condition for other tests.  Also the featuremap remains broken for little endian cpu's.  I have some #defines in the thermostat-server.cpp code to work around this.  (There is a PR in the ZAP project to address this that is still pending)  I am hesitant to add the manual test cases to CI until this is addressed for fear of breaking CI, again.

**Comment by andy31415** [comment]
@vivien-apple FIY.

From my side I am approving based on comments from Chris

**Review by andy31415 — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]

**Review by chrisdecenzo — APPROVED** [review]

**Pull request merged**
