### PR TITLE
[examples] Enable networkcommissioning on all example apps

### PR DESCRIPTION
**Pull request by erjiaqing**
#### Problem
Network Commissioning is not enabled on all example apps.

 #### Summary of Changes
1. Enable network commissioning cluster on all example apps.
2. Update cluster id: 0xaaaa -> 0x0031
3. Small fix on network commissioning implementation

### CODE REVIEW

**Comment by erjiaqing** [comment]
@andy31415 @bzbarsky-apple  @msandstedt @Damian-Nordic @jepenven-silabs PTAL

**Review by msandstedt — APPROVED** [review]

**Review by andy31415 — APPROVED** [review]
Appoving, noting howver that I cannot review a 11K line changed PR and assumed most code is autogenerated. The only changes I saw were:
   - the cluster id change from 0xaaaa to something that looks more spec-approved and that change is reasonable
   - adding network commisioning to gn/cmakelists

**Comment by msandstedt** [comment]
> Appoving, noting howver that I cannot review a 11K line changed PR and assumed most code is autogenerated. The only changes I saw were:
> 
> * the cluster id change from 0xaaaa to something that looks more spec-approved and that change is reasonable
> * adding network commisioning to gn/cmakelists

In other projects, I've seen the pattern where PRs like these are divided into a manual code change commit and an auto-generated code commit.  That makes review a whole lot easier.  To keep the commit history clean, you can still squash on merge.

Just an idea.

**Comment by msandstedt** [comment]
> > Appoving, noting howver that I cannot review a 11K line changed PR and assumed most code is autogenerated. The only changes I saw were:
> > 
> > * the cluster id change from 0xaaaa to something that looks more spec-approved and that change is reasonable
> > * adding network commisioning to gn/cmakelists
> 
> In other projects, I've seen the pattern where PRs like these are divided into a manual code change commit and an auto-generated code commit. That makes review a whole lot easier. To keep the commit history clean, you can still squash on merge.
> 
> Just an idea.

Another possible approach is to integrate auto-generation and re-commit into CI so that developers are only ever reviewing and merging manual changes.  This has an added benefit of ensuring that auto-generated code is always kept in sync.

**Review by mspang — APPROVED** [review]

**Review by bzbarsky-apple — APPROVED** [review]

**Pull request merged**
