### PR TITLE
Refactor SessionHandle

### PR DESCRIPTION
**Pull request by kghost**
#### Problem
Make session easy to use and managable

#### Change overview
* Access session via a `SessionHandle`
  * All session handles become temporary object which can only exist on stack.
  * Introduce a virtual session interface for all types of sessions (secure, group, unauthenticated)
    * Session APIs like `GetSubjectDescriptor`, `GetPeerAddress`, `GetMRPConfig` are virtual now, and their implementations are pushed down.
  * The session object can be converted to actual session class when needed. (not recommaned)
* Manage session life-cycle using `SessionHolder`
  * `SessionHolder` is used to store a session.
  * `SessionHolder` will clear itself when the session is released.
    * The implementation uses a intrusive list to link all holders, and store the linked-list in the session object.
  * `SessionHolderWithDelegate` can be used to receive `OnSessionReleased` event.

#### Testing
This is a refactor. Verified by unit-tests.

**Note**: this PR is pretty big, I have tried to split it into multiple PRs, The final part appears coupling sticky, and it is quite hard to tear it down any further. But fortunately, the changes are pretty straightforward, and couldn't be hard to review.

### CODE REVIEW

**Comment by kghost** [comment]
K32W fails due to this issue https://github.com/project-chip/connectedhomeip/issues/13362

**Review by msandstedt — APPROVED** [review]
Thanks for this.  This is great.

Tested locally, works for me.  Looks correct.

**Review by andy31415 — DISMISSED** [review]
Flash increases are concerning: it seems IntrusiveList pulls in locale stuff according to #13362 according to a sideffect of `<iterator>`.

this needs investigation: do we really have 100K work of new flash code for our embedded platforms (and 60K worth of code for qpg)? I would expect a 'refactor' to move things around and change a bit, but not have such high size impact.

**Comment by kghost** [comment]
@andy31415 This is because I mistakenly enabled `CHIP_CONFIG_ERROR_SOURCE`, I enabled it for debugging and forget to disable it. After disable it in the latest push, everything goes back to normal.

**Comment by andy31415** [comment]
Maybe the bot is wrong:

Tried to compile before and after on my machine, I got:

```
❯ bloaty ./after/chip-qpg6105-lock-example.out -- ./before/chip-qpg6105-lock-example.out
    FILE SIZE        VM SIZE    
 --------------  -------------- 
  +0.1% +1.88Ki  [ = ]       0    .debug_str
  +0.1%    +480  [ = ]       0    .symtab
  +0.1%    +328  [ = ]       0    .debug_frame
  +0.1%    +152  [ = ]       0    .debug_aranges
  +0.1%    +152  [ = ]       0    [Unmapped]
  [ = ]       0  +0.2%     +64    .heap
  [ = ]       0  -0.1%     -64    .bss
  -0.0%    -152  -0.0%    -152    .text
  -0.1%    -340  [ = ]       0    .strtab
  -0.3% -1.38Ki  [ = ]       0    .debug_ranges
  -0.6% -7.96Ki  [ = ]       0    .debug_abbrev
  -0.5% -13.7Ki  [ = ]       0    .debug_line
  -0.6% -17.5Ki  [ = ]       0    .debug_loc
  -3.3%  -954Ki  [ = ]       0    .debug_info
  -2.4%  -992Ki  -0.0%    -152    TOTAL
  ```
  
  Will remove my "changes requested" as I have no proof that size is actually increasing.

**Comment by andy31415** [comment]
> @andy31415 This is because I mistakenly enabled `CHIP_CONFIG_ERROR_SOURCE`, I enabled it for debugging and forget to disable it. After disable it in the latest push, everything goes back to normal.

That would totally explain it. Thank you.

**Review by andy31415 — APPROVED** [review]

**Comment by andy31415** [comment]
@doru91 - I have patched the NXP SDK to remove the 'define global'  as I have not seen its usage and it seems that for matter it is somewhat common to patch the NXP SDK. Please take a look and see if  there is a better approach.

**Comment by doru91** [comment]
> @doru91 - I have patched the NXP SDK to remove the 'define global' as I have not seen its usage and it seems that for matter it is somewhat common to patch the NXP SDK. Please take a look and see if there is a better approach.

@andy31415 the fix is good to me. I also like the way you've chosen to patch only the required lines instead pf copying the entire file (as is done in the existing script file).

**Pull request merged**
