### PR TITLE
DeviceController: refactor pairing

### PR DESCRIPTION
**Pull request by kghost**
#### Summary of Changes

 ##### Remove `RendezvousSession` usage in device contorller
`RendezvousSession` handles SPAKE2 pairing session and network provision, but network provision will be removed from it, so it is only handling SPAKE2 pairing session. In this case, it is better to use `PASESession` directly.

 ##### Move `DeviceCommissioner` functionalities to `Device`
`DeviceCommissioner` is a singleton class handling pairing session, it is basically bind to a device while doing a the pairing procedure, and the execution flow is bouncing between the device and the commissioner. When moving all these code in to the `Device` class, the code become more clear and understandable.

I think the original code is highly inspired by the old device controller, which handles only one device. But the new device controller handles multiple devices, and the device pairing part belongs to a device instead a global controller.

 #### Note

This PR will break network provision and BLE pairing.

Network provision: current implementation doesn't align with the spec, it need to be a cluster instead.
BLE pairing: @erjiaqing will bring a unified transport for both BLE and IP, it will be fix then.

### CODE REVIEW

**Comment by woody-apple** [comment]
@pan-apple ?

**Comment by pan-apple** [comment]
I am a bit confused with the design change this PR is bringing.

1. What's the use of an unpaired `CHIPDevice` object?
2. Once a device has been paired, the pairing session and corresponding information used for pairing process is not really needed. The updated `CHIPDevice` object will carry it now.
3. Overall, I am not sure what problem we are solving by moving `DeviceCommissioner` functionality into `CHIPDevice` object. Maybe there're better ways to solve it.

**Review by woody-apple — CHANGES_REQUESTED** [review]
Requesting changes based on @pan-apple 's feedback

**Comment by kghost** [comment]
> I am a bit confused with the design change this PR is bringing.
> 
> 1. What's the use of an unpaired `CHIPDevice` object?

A device waiting to be pairing, it is just an abstraction.

> 2. Once a device has been paired, the pairing session and corresponding information used for pairing process is not really needed. The updated `CHIPDevice` object will carry it now.

Yes, and the Channel API #4019 will solved the problem. The pairing information will be saved in the channel builder, the throw out once pairing is completed. 

> 3. Overall, I am not sure what problem we are solving by moving `DeviceCommissioner` functionality into `CHIPDevice` object. Maybe there're better ways to solve it.

Yes, the Channel API #4019 is the better way.

Overall, everything suggesting that #4019 is blocking lots of thing, please priorities #4019 first.

**Comment by LuDuda** [comment]
> #### Note
> This PR will break network provision and BLE pairing.
> 
> Network provision: current implementation doesn't align with the spec, it need to be a cluster instead.
> BLE pairing: @erjiaqing will bring a unified transport for both BLE and IP, it will be fix then.

@kghost Thank you for your work! I didn't review the content in the details but would like to express my opinion on the above fragment of PR description.

In my opinion, this is not an acceptable approach, to introduce such a big regression (lost of features) to get a value of better code. As a Thread developer, I wouldn't be able to perform Rendezvous and Thread provisioning at all (if I read the description correctly). All examples will stop working for many people (including CHIP Harness team) and so developers/early adopters would need to do some hacks to test ZCL communication with the Phone. While I agree, the current version of Network Provisioning is not the final one, we should iteratively replace it with the new one without breaking master for a couple of days/weeks.

Could we first introduce the cluster-based Network Provisioning, and (only then/at the same time) start refactoring the code?

**Comment by kghost** [comment]
> Is it possible that we first introduce the cluster-based Network Provisioning, and (only then/at the same time) start refactoring the code?

@erjiaqing is working on that part, it will probably land soon.

**Comment by LuDuda** [comment]
Yes, had a chat on slack with him. Thank you @kghost!

**Comment by kghost** [comment]
Blocked by #3945 #4421

**Pull request closed without merging**
