### PR TITLE
Remove clusters client code from src/app/

### PR DESCRIPTION
**Pull request by vivien-apple**
#### Problem

While looking at a mechanism to replace the `Plugins Callbacks` mechanism with `CHIPCallback` (because of #3782) I noticed that `emberAfClusterInitCallback` was getting called twice for each clusters of the first endpoint in the `all-clusters-app` demo.

This is because our AppBuilder generated configurations file have all clients enabled.

I have regenerated a configuration file with clients disabled and in the process I'm removing all code from `src/app/clusters` that is related to client.

I know there was some discussion about `ias-zone-client`, so it may be a good time to take a decision.

About the 2 others occurrences of client code, aka `groups-client` and `scenes-client` it is not clear to me what is their usage.

Maybe that's just me being too agressive in removing client code here...

I suspect @rwalker-apple and @bzbarsky-apple may have an opinion here.

 #### Summary of Changes
 * Update the `all-clusters-app` gen folder by removing all clients on the first endpoint
 * Delete `src/app/clusters/*-client` folders
 * Remove the `groups-client` and `scenes-client` compilation targets for the `all-clusters-app` applications
 * Remove the code in `src/app/util/process-global-message.cpp` that was referencing `ias-zone-client`

### CODE REVIEW

**Review by andy31415 — APPROVED** [review]

**Review by rwalker-apple — APPROVED** [review]

**Review by bzbarsky-apple — CHANGES_REQUESTED** [review]
We shouldn't remove the actual cluster client implementations, at least for now.  They do contain "business logic" that is necessary to properly implement clients for those clusters.

For the rest... I guess having the same endpoint implement both the client and server side of a cluster is a bit odd.  But we _do_ want to ideally keep testing the client sides of clusters.  I would not worry about it too much it it's a pain, but perhaps we could put all the client sides of clusters on a separate endpoint (endpoint 3, say)?

**Comment by bzbarsky-apple** [comment]
And in particular, it looks like the Silicon Labs code does not really support sanely implementing both the client and server of the same cluster on the same endpoint, though it will let you configure that in the UI.  But doing it on different endpoints should be ok.

**Comment by vivien-apple** [comment]
> We shouldn't remove the actual cluster client implementations, at least for now. They do contain "business logic" that is necessary to properly implement clients for those clusters.
> 
> For the rest... I guess having the same endpoint implement both the client and server side of a cluster is a bit odd. But we _do_ want to ideally keep testing the client sides of clusters. I would not worry about it too much it it's a pain, but perhaps we could put all the client sides of clusters on a separate endpoint (endpoint 3, say)?

Now that I'm thinking a bit more about it I wonder if I should just revisit what I have generated for the `chip-tool` command line tool.

Currently `chip-tool` is sort of doing the job of the client side part of `call-command-handler.cpp`.
One solution could be to get rid of that and focus on generating the various `emberAf{{clusterName}}Cluster{{commandName}}ResponseCallback` only inside chip-tool.

This way `chip-tool` will be a real consumer of the client side of clusters and we will have a separate mechanism for testing the client side bits than hooking everything on the same app.

Any thoughts ?

**Comment by bzbarsky-apple** [comment]
> Any thoughts ?

I absolutely think we should do that; I've just been waiting for us to move to ZAP before doing it....  So yes, if that's viable, we could do that and drop the client-side clusters from all-clusters-app

**Comment by vivien-apple** [comment]
Closing to not pollute the open PRs list since it may takes time to finalise that.

**Pull request closed without merging**
